### ISSUE TITLE
能否做个外置源维护系统 然后app从服务器获取源 获取的过程中走鉴权的方式

### ISSUE THREAD

**Issue by chenxudong2020** [lizongying/my-tv#1]
能否做个外置源维护系统 然后app从服务器获取源 获取的过程中走鉴权的方式 app每次启动获取源
内置源失效了 需要改代码重新编译生成apk 维护不方便

可以参考骆驼的IPTV的项目 我已经把这个后台搞到docker了但是php有些页面打不开
https://github.com/chenxudong2020/docker_builder/tree/main/iptv

**Comment by lizongying** [comment]
如果没有商业化，外部源很难稳定。
这个项目的目标是最终从官方获取源。
尽量精简。

**Comment by chenxudong2020** [comment]
这个项目源是从哪里获取的 外置源更新方便点如果内置源 失效了还需要重新编译apk安装麻烦 至于你说的也是一部分原因



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月15日(周五) 中午1:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lizongying/my-tv] 能否做个外置源维护系统 然后app从服务器获取源 获取的过程中走鉴权的方式 (Issue #1)




 
如果没有商业化，外部源很难稳定。
 这个项目的目标是最终从官方获取源。
 尽量精简。

**Comment by lizongying** [comment]
> 这个项目源是从哪里获取的 外置源更新方便点如果内置源 失效了还需要重新编译apk安装麻烦 至于你说的也是一部分原因
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年12月15日(周五) 中午1:12 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [lizongying/my-tv] 能否做个外置源维护系统 然后app从服务器获取源 获取的过程中走鉴权的方式 (Issue #1) 如果没有商业化，外部源很难稳定。 这个项目的目标是最终从官方获取源。 尽量精简。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可能的情况下，还是走内置，也是一部分人的选择，很多人还是不喜欢折腾。外置的话tvbox已经做的很好了。用的央视源，不得不说，他们的加密做了不少工作。
