### ISSUE TITLE
【点赞捐助】这app的直播切换速度非常快，是使用了什么秘诀吗？

### ISSUE THREAD

**Issue by huifei0129** [lizongying/my-tv#100]
这app的直播切换速度非常快，是使用了什么秘诀吗？

**Comment by zbby1987** [comment]
无他，
唯视频源速度比较快尔

**Comment by kamkdd** [comment]
感觉不单单是直播源的原因，目前切换速度是最快的，不过，还可以优化，换台的时候不要出现黑屏，用当前节目画面替代黑屏，相当于画面暂停了，直到节目加载完成再切换下一个节目

**Comment by postxx** [comment]
是用了央视网的源，有cdn加速。大家偷着用啊别太张扬了。

**Comment by zbby1987** [comment]
> 是用了央视网的源，有cdn加速。大家偷着用啊别太张扬了。

央视网和央视频，是两回事。。。你再仔细看看用的哪个

**Comment by postxx** [comment]
> > 是用了央视网的源，有cdn加速。大家偷着用啊别太张扬了。
> 
> 央视网和央视频，是两回事。。。你再仔细看看用的哪个

哎你非要搞精准打击。。。。

**Comment by zbby1987** [comment]
> > > 是用了央视网的源，有cdn加速。大家偷着用啊别太张扬了。
> > 
> > 
> > 央视网和央视频，是两回事。。。你再仔细看看用的哪个
> 
> 哎你非要搞精准打击。。。。

https://www.123pan.com/s/9sRPjv-2t4Vv.html
正版且永不过期的央视网的，你可以用这个2兆的定制浏览器试试
作为压箱底的备用版本

**Comment by postxx** [comment]
> > > > 是用了央视网的源，有cdn加速。大家偷着用啊别太张扬了。
> > > 
> > > 
> > > 央视网和央视频，是两回事。。。你再仔细看看用的哪个
> > 
> > 
> > 哎你非要搞精准打击。。。。
> 
> https://www.123pan.com/s/9sRPjv-2t4Vv.html 正版且永不过期的央视网的，你可以用这个2兆的定制浏览器试试 作为压箱底的备用版本

好的感谢
