### ISSUE TITLE
怎么打开设置菜单？

### ISSUE THREAD

**Issue by zjqf2021** [lizongying/my-tv#111]
几点反馈：
- 打不开设置菜单
- 画面无法设置比例，显示不全屏
- 选台菜单在操作时自动隐藏。
     - 建议点空白处隐藏，不然没选好就从头开始找了
     - 选台图标建议改小或者直接用按钮/文字更方便

**Comment by lizongying** [comment]
只有电视有设置。
手机就是合适比例，不认为拉伸全屏更合理。
建议滑动的时候点一下，防止自动隐藏。
对于老人来说不一定能看清字
