### ISSUE TITLE
节目播放一段时间后卡住

### ISSUE THREAD

**Issue by ShanshanHY** [lizongying/my-tv#116]
已验证版本 1.4.5 & 1.4.7
验证平台 N1(Android TV 7.1)，K60(Android 14)

使用方正宽带作为网络，播放时间大概在5分钟之后，当前节目便会卡住，重新换台恢复正常(包括1.4.7修复的cctv13)
手机使用流量可正常播放

**Comment by ShanshanHY** [comment]
抓包查看，好像是获取的url中的token(不清楚是什么，暂且称为token)失效导致的

在方正宽带网络环境下，17:10:07获取的包含token的url，17:15:09判定失效，整5分钟

而使用流量环境获取的包含token的url一直都生效

![image](https://github.com/lizongying/my-tv/assets/29966961/c21d963f-e009-4270-8465-ab1a2383b1fd)

![image](https://github.com/lizongying/my-tv/assets/29966961/9249c26a-0916-4f53-a039-f7978c5f8a4c)

**Comment by ccav14** [comment]
> 抓包查看，好像是获取的url中的token(不清楚是什么，暂且称为token)失效导致的
> 
> 在方正宽带网络环境下，17:10:07获取的包含token的url，17:15:09判定失效，整5分钟
> 
> 而使用流量环境获取的包含token的url一直都生效
> 
> ![image](https://private-user-images.githubusercontent.com/29966961/299606534-c21d963f-e009-4270-8465-ab1a2383b1fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODI5OTYsIm5iZiI6MTcwNjE4MjY5NiwicGF0aCI6Ii8yOTk2Njk2MS8yOTk2MDY1MzQtYzIxZDk2M2YtZTAwOS00MjcwLTg0NjUtYWIxYTIzODNiMWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDExMzgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYjAyMTExZmEyNmRiODhhN2RhMWI4ZjlkZDUxMzE1MWYzM2EwMGMzYWM0NzAwMDQxNGM5ODk2YjhlYTBiY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n9hajI4U-tuebrVdjclzat_MwiX5M8NFOIaMS7pUohY)
> 
> ![image](https://private-user-images.githubusercontent.com/29966961/299605796-9249c26a-0916-4f53-a039-f7978c5f8a4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODI5OTYsIm5iZiI6MTcwNjE4MjY5NiwicGF0aCI6Ii8yOTk2Njk2MS8yOTk2MDU3OTYtOTI0OWMyNmEtMDkxNi00ZjUzLWEwMzktZjc5NzhjNWY4YTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDExMzgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YWQ5YzgyZjBmODliZDIyNThlMWU5OTliZmE5MmUyZDc5N2MyZmQ2MjY3MjExYzFjZGU2OGQxOWM0YWZhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cxpk8X1NJJ52dmh-2QsELP0oDl227fuFv60K2mkzdhU)

老哥什么软件分享下呗

**Comment by ShanshanHY** [comment]
> 老哥用 的什么抓包软件分享下呗

[Reqable](https://reqable.com/zh-CN/)

**Comment by ccav14** [comment]
> > 老哥用 的什么抓包软件分享下呗
> 
> [Reqable](https://reqable.com/zh-CN/)

收到谢谢

**Comment by ashsteins** [comment]
cctv6 有点糊

**Comment by lizongying** [comment]
这个先关闭了，不便讨论更多细节。
