### ISSUE TITLE
建议增加自定义直播源

### ISSUE THREAD

**Issue by KevinZheng001** [lizongying/my-tv#117]
现在的直播源是代码中写死的，增加自定义直播源及iptv m3u，增加这一功能后应用的可玩性将进一步得到拓展，强力建议作者能增加这一功能。

**Comment by lizongying** [comment]
已了解需求，现阶段先不上这个功能。因为现有的外部直播源可能无法满足需求，最好新开个APP更侧重自定义功能的实现。

**Comment by honeyshine75** [comment]
建议可以动态拉取源，可以在你的服务端配置之类的
