### ISSUE TITLE
大佬真的太用心了

### ISSUE THREAD

**Issue by AustinFan** [lizongying/my-tv#12]
加上台标看起来美观多了 而且加了一条移动专线
但是还是看一会儿就卡了 期待再优化 
不知道会不会出联通专线

**Comment by lizongying** [comment]
一会就卡的问题已经找到方法解决了，代码中。不会有联通专线，移动专区也是临时方案，不知道稳定性如何。大家可以反馈下，因为不是官方源，如果不能用了就会移除。

**Comment by lizongying** [comment]
@AustinFan 1.2.0卡的问题解决了
