### ISSUE TITLE
自己拉下来代码运行时，提示接口签名失败，这个要怎么处理呢？

### ISSUE THREAD

**Issue by Ahuangshang** [lizongying/my-tv#120]
LiveInfo(code=20301, msg=签名验证失败, data=LiveInfoData(chanll=null, playurl=null, errinfo=null))

**Comment by lizongying** [comment]
安全考虑，暂不讨论

**Comment by Ahuangshang** [comment]
给个思路为什么encrypy（）native方法后ckey为null，就是这个导致的，给个思路可以吧
