### ISSUE TITLE
建议开发者加入app检测更新和自动更新功能

### ISSUE THREAD

**Issue by DomByAngular** [lizongying/my-tv#123]
建议开发者加入app检测更新和自动更新功能，每次手动更新非常麻烦，尤其是对很多老人家庭用户不友好，谢谢

**Comment by Nixontheone** [comment]
我也是认同👍

**Comment by cyxnzb** [comment]
+1，我也是装了给父母用的，但是不能一直都在家里，所以一旦有更新了不在家了估计就更新不了了，就像之前其他的软件有一些源失效了也是，就挺麻烦的，感觉对于他们来说，电视成为了想看又看不了的摆设，也挺无奈

**Comment by gaohanqueyang** [comment]
还是别自动更新了，创维电视第三方应用不让自动更新。

**Comment by lwb1978** [comment]
政策问题，现在国内正规厂家的电视和机顶盒都不能自动安装白名单以外的第三方app，只能各种方法自己更新了。

**Comment by cyxnzb** [comment]
> 政策问题，现在国内正规厂家的电视和机顶盒都不能自动安装白名单以外的第三方app，只能各种方法自己更新了。

我的当贝盒子还可以更新应用啊，提示有更新下载下安装

**Comment by lizongying** [comment]
正在開發
