### ISSUE TITLE
建议作者加入让用户自己导入源功能

### ISSUE THREAD

**Issue by xiananrain** [lizongying/my-tv#124]
内置源有点少，希望作者加入一个让我们自己添加源的模块

**Comment by a776058959** [comment]
其实能添加源的开源软件也有很多了，这个即开即用速度快，我觉得挺好的。
想折腾有很多种其他办法折腾，给家里人用这个就正好

**Comment by ui1840** [comment]
> 其实能添加源的开源软件也有很多了，这个即开即用速度快，我觉得挺好的。 想折腾有很多种其他办法折腾，给家里人用这个就正好

但是好些软件已经好久没更新维护了，使用起来很麻烦，或者就干脆不能使用，比如像IPV6的支持之类的，源类型支持之类的，
而且加了自定义源的功能后，可以减少内置源的压力，而且也可以让这个APP使用寿命更长久，
所以还是期待有个可自定义源的APP，或者干脆就加个空壳也行，不用内置源，

**Comment by maojing0609** [comment]
> > 其实能添加源的开源软件也有很多了，这个即开即用速度快，我觉得挺好的。 想折腾有很多种其他办法折腾，给家里人用这个就正好
> 
> 但是好些软件已经好久没更新维护了，使用起来很麻烦，或者就干脆不能使用，比如像IPV6的支持之类的，源类型支持之类的， 而且加了自定义源的功能后，可以减少内置源的压力，而且也可以让这个APP使用寿命更长久， 所以还是期待有个可自定义源的APP，或者干脆就加个空壳也行，不用内置源，

那你直接用tvbox不就好了吗

**Comment by sz20000** [comment]
自定义导入这个功能没必要。目前主打一个快捷简单，适合家里老人家！功能太多软件会被和谐。

**Comment by flintt** [comment]
我觉得能加自定义的有个好处就是可以在内置源失效时顶上，翻了一下最新版很多台失效了

**Comment by mlzk** [comment]
为了规避法律风险也得做源壳分离吧

**Comment by lizongying** [comment]
#532
