### ISSUE TITLE
请增加一个大湾区卫视

### ISSUE THREAD

**Issue by ghostecoli** [lizongying/my-tv#128]
代家里老父母感谢作者，麻烦作者再增加一个大湾区卫视：https://www.gdtv.cn/tvChannelDetail/51
谢谢

**Comment by ashsteins** [comment]
那其实也可以加广东4k超高清，挺清楚的

**Comment by damon-ho** [comment]
同求，父母需要看广东珠江频道

**Comment by lizongying** [comment]
会考虑

**Comment by w55565** [comment]
差点提issue了，同求。希望开发靓仔可以加该频道
