### ISSUE TITLE
高尔夫网球频道 提示版权问题不让看

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#130]
高尔夫网球频道 提示版权问题不让看

**Comment by ashsteins** [comment]
地方台好像少了吉林卫视、陕西卫视、西藏卫视、内蒙古卫视、宁夏卫视、青海卫视、甘肃卫视、云南卫视、山西卫视。

可以参考灵犀直播的源，那个比较全，谢谢作者

**Comment by Satan-23333** [comment]
cctv10也有这个问题

**Comment by lizongying** [comment]
预期内错误，后期看情况解决。
