### ISSUE TITLE
央视4k好像没到4k分辨率，建议增加其他几个4k频道，如广东4K超高清等，然后cctv16也有4k源

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#131]
现在一种有如下几个4k超高清频道

广东4k超清，南国都市4k，欢笑剧场4k，
![国内4k频道盘点，欢迎补充_看图_台标吧_百度贴吧_5](https://github.com/lizongying/my-tv/assets/157224414/5ecc9d1e-489b-4bc9-b29f-8e4645292ca6)
![国内4k频道盘点，欢迎补充_看图_台标吧_百度贴吧_4](https://github.com/lizongying/my-tv/assets/157224414/686a2982-3982-4545-8546-b35c5305878d)
![国内4k频道盘点，欢迎补充_看图_台标吧_百度贴吧_3](https://github.com/lizongying/my-tv/assets/157224414/0c54853f-161d-4fb7-943c-8beca284a79c)
![国内4k频道盘点，欢迎补充_看图_台标吧_百度贴吧_2](https://github.com/lizongying/my-tv/assets/157224414/b0f8f31f-ff42-47f4-ae8d-78575dd45cb7)
![国内4k频道盘点，欢迎补充_看图_台标吧_百度贴吧_1](https://github.com/lizongying/my-tv/assets/157224414/3b7b8b63-5736-4294-9b64-05ffc57177ad)
![国内4k频道盘点，欢迎补充_看图_台标吧_百度贴吧](https://github.com/lizongying/my-tv/assets/157224414/c73bb4dd-2569-49bf-9fc0-d9ddd7304696)

**Comment by ashsteins** [comment]
还有个 求索记录4k

**Comment by zbby1987** [comment]
你有这几个台的可长期稳定使用的源地址么！？

**Comment by lizongying** [comment]
#557
