### ISSUE TITLE
建议增加中国教育台CETV-1 2 3 4    CHC家庭影院、CHC动作电影、CHC高清电影

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#132]
中国教育电视台综合教育频道（频道呼号：CETV-1，简称：中国教育1台或中国教育1频道），是中国国家级专业的综合教育卫视频道
与CCTV-1享受同等政策支持落地的卫星频道，国家级权威专业的综合教育卫视频道。

**Comment by ashsteins** [comment]
凤凰卫视现在办事处在国内大陆了，理论上没有违禁内容，放心播放

**Comment by lizongying** [comment]
后面看情况。
