### ISSUE TITLE
频道列表建议优化一下

### ISSUE THREAD

**Issue by gonjudaren** [lizongying/my-tv#134]
选频道 只是放大了节目方块 不是特别显著 很容易忽略 不够丝滑   建议加个颜色显示 类似于这种
![OIP-C](https://github.com/lizongying/my-tv/assets/142286774/eefdf8f3-97f5-4a29-b11b-b685143377bb)

**Comment by gonjudaren** [comment]
![OIP-C](https://github.com/lizongying/my-tv/assets/142286774/6af15bee-6f1c-4bc2-b52c-ab3e9e74fcd3)

**Comment by lizongying** [comment]
會優化
