### ISSUE TITLE
1.4.8写的通用，我理解安卓4.4.2的电视盒子可用，实际使用闪退

### ISSUE THREAD

**Issue by bird202301** [lizongying/my-tv#139]
您好，谢谢开发这个软件
1.4.8写的通用，我理解安卓4.4.2的电视盒子可用，实际使用闪退。
我的盒子型号R3300-L
是我的理解有误还是盒子不行，请有空回复
另外大家的使用情况如何呢？

**Comment by donghai-Y** [comment]
首先特别感谢开发者的辛苦付出，我也遇到相同的问题，我的盒子是华为EC6110-M，安卓版本是4.4.4，安装打开后闪退，希望开发者有空做一下适配，再次感谢！

**Comment by lizongying** [comment]
没有相应设备测试，会有设备不兼容情况，暂时无法解决。
