### ISSUE TITLE
索尼电视试了下，CCTV3，6，8都是黑屏，其它CCTV台都能正常播放

### ISSUE THREAD

**Issue by kurumi2024** [lizongying/my-tv#14]
索尼电视试了下，CCTV3，6，8都是黑屏，其它CCTV台都能正常播放。
麻烦确认，谢谢。

**Comment by fhzjgd** [comment]
我也是，应该是连不上直播源，最好能够给出错误提示，两秒无动作的话自动跳转之前的频道。

作者能否做个可定制的？
可定制大栏目，比如可以去掉移动专区。
可定制直播源。

**Comment by lizongying** [comment]
因为368在央视频属于vip频道，所以用的移动源。我这倒是可以播放，既然有同学连不上，说明移动源是对于部分用户是有问题的，后期会移除，实际上目前也是作为备份存在。@kurumi2024 后面我会用一个稳定的源代替，比如央视网，难度比较大，预计一到两周时间。@fhzjgd 可定制后期会加上，目前还是先以播放功能为主要方向。直播源应该不会定制，市面上几乎所有的直播软件都是tvbox套壳，定制功能也比较好。本软件和其他软件的主要区别就是直播源使用内置的官方直播源，应该会比较稳定，而私人维护的源多是转发的方式实现的（不确定），很容易失效，而且找源配置的过程也是比较麻烦。
错误提示得有。

**Comment by lizongying** [comment]
https://www.toutiao.com/w/1787234269397059/?log_from=c60a646f4d5b7_1704440680818
