### ISSUE TITLE
地方台好像少了吉林卫视、陕西卫视、西藏卫视、内蒙古卫视、宁夏卫视、青海卫视、甘肃卫视、云南卫视、山西卫视。

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#140]
地方台好像少了吉林卫视、陕西卫视、西藏卫视、内蒙古卫视、宁夏卫视、青海卫视、甘肃卫视、云南卫视、山西卫视。

**Comment by wqinf** [comment]
支持楼主

**Comment by ashsteins** [comment]
源可以参考 灵犀直播的，他们源挺全的

**Comment by yangjchen** [comment]
补充：天津卫视。家里老人心心念念的《爱情保卫战》

**Comment by vokins** [comment]
吉林卫视、
陕西卫视：http://live.snrtv.com
西藏卫视、
内蒙古卫视、https://www.nmtv.cn/liveTv
宁夏卫视、https://www.nxtv.com.cn/live/
青海卫视、https://www.qhbtv.com/new_index/live/folder2646/
安多卫视（青海卫视藏语）http://www.qhtb.cn/onlin/onlin_tv/
四川康巴卫视 https://www.kangbatv.com/zb_22587/
甘肃卫视、
云南卫视、
山西卫视。

**Comment by yayoiii1** [comment]
云南台：https://www.yntv.cn/live.html

**Comment by ashsteins** [comment]
顶一下

**Comment by lizongying** [comment]
#431
