### ISSUE TITLE
大佬 我提交三个山西源

### ISSUE THREAD

**Issue by missyoubye** [lizongying/my-tv#141]
详见附件。第一个是山西官网源HD。后两个是跟你内置里边一样的源，清晰度SD。
当然大佬看心情加。
[山西卫视.txt](https://github.com/lizongying/my-tv/files/14075415/default.txt)

**Comment by ashsteins** [comment]
地方台好像少了吉林卫视、陕西卫视、西藏卫视、内蒙古卫视、宁夏卫视、青海卫视、甘肃卫视、云南卫视

**Comment by zbby1987** [comment]
能长期稳定么！？

**Comment by missyoubye** [comment]
> 能长期稳定么！？

只是山西台的，就没有一劳永逸的源。反正后俩跟大佬出处的一样，我这失效，大佬的也得失效。

**Comment by liqiangsky** [comment]
> 详见附件。第一个是山西官网源HD。后两个是跟你内置里边一样的源，清晰度SD。 当然大佬看心情加。 [山西卫视.txt](https://github.com/lizongying/my-tv/files/14075415/default.txt)

山西卫视高清的是真少

**Comment by lizongying** [comment]
#431
