### ISSUE TITLE
安卓端节目列表操作不方便，节目列表显示消失太快。

### ISSUE THREAD

**Issue by xiaowang19840839** [lizongying/my-tv#145]

**Comment by zbby1987** [comment]
没这问题啊

**Comment by Hizhangsan** [comment]
是的 ，感谢大佬做出这款软件，能否再优化一下滑动频道时都没选上频道呢，就闪回视频播放了，如果优化一点就完美了，跳出频道时就应该把它定住

**Comment by zbby1987** [comment]
你俩是用手机看的吧。。。

**Comment by HaolinHom** [comment]
可以加上一些运行端的判断逻辑优化一下频道列表展示与消失的逻辑

**Comment by lizongying** [comment]
暂时延长到5秒。@HaolinHom 倒是也可以，不过，加上手机的逻辑就太复杂了，同时手机端也不是主要方向。实际上节目列表是有待优化的，后面再处理了。
