### ISSUE TITLE
问作者：现在这种内置方式，有没有可能源一失效就都不能用了！？？

### ISSUE THREAD

**Issue by zbby1987** [lizongying/my-tv#146]
目前的源，有没有这种隐患！？？
.
感觉还是从官方网页那获取视频源的当时最稳妥长久啊！！！

**Comment by Nixontheone** [comment]
没有一个源都会长久的，如果你有长久的话就用官方网站吧😂

**Comment by l2999019** [comment]
这个源只要加密方式不变 应该不会没有

**Comment by lizongying** [comment]
正如 @Nixontheone 所说，确实无法真正做到长久。但从方式上说，我的电视应该比iptv的方式更稳定一些。
