### ISSUE TITLE
【功能建议】开机自动启动my-tv

### ISSUE THREAD

**Issue by lthero-big** [lizongying/my-tv#147]
感谢作者的软件，my-tv直播源很高清，切换速度快，无广告界面简洁直观！

提个功能建议：

**电视盒子开机后，自动启动my-tv**

**Comment by fengluhome** [comment]
这个功能很实用，祈求大神能解决了一下

**Comment by yanleilei250** [comment]
老人用特别实用，希望作者可以考虑加入此功能，感谢作者此款软件

**Comment by lizongying** [comment]
#89
