### ISSUE TITLE
华为智慧屏现在看不了CCTV

### ISSUE THREAD

**Issue by xjhjinhui** [lizongying/my-tv#15]
感谢大佬无私分享！

PS：昨晚还能看CCTV，今天早上不能看了，卫视频道大部分还可以看。

**Comment by lizongying** [comment]
如果是移动专区，稳定性不做保证，可以试着切到上面的央视。我刚测试都是正常的。
还有就是，电视的系统时间要正常。
如果还有问题，可以和我反馈下。

**Comment by xjhjinhui** [comment]
感谢！
刚刚试了最新版本1.2.0，顶部的央视除了CCTV3、6、8，其他央视都可以看了；
底部的移动专区确实没法看；

**Comment by lizongying** [comment]
https://www.toutiao.com/w/1787234269397059/?log_from=c60a646f4d5b7_1704440680818
