### ISSUE TITLE
CCTV 10 根据版权相关要求，暂无法观看该节目

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#154]
CCTV 10 根据版权相关要求，暂无法观看该节目

**Comment by ashsteins** [comment]
> 过一会儿就正常了

确实，咋回事呢，其他台就没这个问题

**Comment by Cococloud** [comment]
没有拿到节目的网络播放权，央视自己官方源会暂时停止
连1台上午的剧场都会暂停播放的

**Comment by ashsteins** [comment]
> 没有拿到节目的网络播放权，央视自己官方源会暂时停止 连1台上午的剧场都会暂停播放的

原来如此，还有这回事，那iptv会暂停么

**Comment by lizongying** [comment]
后面会处理，暂时关闭问题了
