### ISSUE TITLE
都赶快去扫码打赏！！

### ISSUE THREAD

**Issue by sylarl** [lizongying/my-tv#156]
大家都不希望这玩意消失吧？赶紧扫码打赏支持作者~要不很快就会凉凉了。
电视家会员一年还60呢，不用多少，你扫个5块，一瓶水钱，一瓶水而已。
真心支持，别凉了。

**Comment by billliou** [comment]
已经打赏支持！

**Comment by ybinson** [comment]
已赞, 先试试.

**Comment by ashsteins** [comment]
已支持，希望更多台，补全地方台和CETV

**Comment by lizongying** [comment]
多谢支持，量力而为。
