### ISSUE TITLE
提供几个直播源地址 

### ISSUE THREAD

**Issue by gonjudaren** [lizongying/my-tv#159]
https://www.yibababa.com/vod
https://www.juwanhezi.com/more/live
https://nettvpro.xyz/
http://www.guangbomi.com/

**Comment by gonjudaren** [comment]
https://github.com/joevess/IPTV

**Comment by gonjudaren** [comment]
https://www.ahhhhfs.com/?cat=&s=%E7%9B%B4%E6%92%AD%E6%BA%90

**Comment by jijunhao** [comment]
非常感谢！

**Comment by stone2341** [comment]
非常感谢老哥的帮助！！

**Comment by lishengwei** [comment]
> 在这个直播源我也研究了一下，大部分都是可能是ipv6的，但是我家网络没有ipv6，这很不好办。不知道作者是怎么解决这个问题的。

找宽带运营商给你搞。挺简单的。

**Comment by gonjudaren** [comment]
https://gyssi.link/login.html

**Comment by WFANG12719** [comment]
看了下码，人家从yangshipin.cn来的，绝对不会有问题，也不用担心失效，其它源都保不准。

**Comment by muziling** [comment]
> 看了下码，人家从yangshipin.cn来的，绝对不会有问题，也不用担心失效，其它源都保不准。

好像不是yangshipin，移动的源，但是我不是移动的宽带，不知道为什么用这个也能看。代码里的m3u8链接我放到播放器里是看不了的。
https://github.com/lizongying/my-tv/blob/main/app/src/main/java/com/lizongying/mytv/TVList.kt

**Comment by WFANG12719** [comment]
局域网都是通的，只要不特别封禁，都可以看，区别在于速度，清晰度

William Fang
________________________________

**Comment by gonjudaren** [comment]
https://tvsuper.github.io/%E7%9B%B4%E6%92%AD%E5%88%97%E8%A1%A8.html

**Comment by gonjudaren** [comment]
https://www.freetvtv.com/

**Comment by gonjudaren** [comment]
https://www.iptv345.com/?act=home
