### ISSUE TITLE
大多数海外版的电视或者盒子遥控器都没有菜单键。

### ISSUE THREAD

**Issue by a909301228** [lizongying/my-tv#161]
希望未来如果有功能更新需要用到这个按键，大大能考虑到我们！

**Comment by ashsteins** [comment]
外贸盒子都有菜单键，别骗人

**Comment by fengjiuge1** [comment]
胡说，基本都有

**Comment by pooppiss** [comment]
大部分情况下，长按OK键是可以代替菜单键的。不过还是有个别软件不支持。我的Z9D电视遥控器就没有菜单键。

**Comment by asdwfwqd** [comment]
我有两个盒子
一个是chromecast with google tv，没有菜单键
另一个是nvidia shield tv 2019 pro，有菜单键

**Comment by lizongying** [comment]
1.7.3 遥控器左键进入节目列表，遥控器右键进入菜单
