### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by sunKit-io** [lizongying/my-tv#164]
![WX20240131-214000@2x](https://github.com/lizongying/my-tv/assets/20592158/e6508c42-bbcf-495d-9ae0-d7cd211cd259)
没有编译成功，这个是哪个环境的问题呢

**Comment by sunKit-io** [comment]
@xpadvent 是的，文件是一個空的文件。。。

**Comment by sunKit-io** [comment]
@lizongying 英哥，看下文件是否沒有上傳呢

**Comment by lizongying** [comment]
没有上传
