### ISSUE TITLE
希望加入广东珠江台&南方台

### ISSUE THREAD

**Issue by dfhuang-gd** [lizongying/my-tv#167]
广东省90%老人家就看这两个台。希望能加入，先谢谢大神。速度真的快！

**Comment by ashsteins** [comment]
广东有个4k台也不错

**Comment by ashsteins** [comment]
你这样说 我希望加入 延边卫视 台，延边这边老人90%都看

**Comment by dfhuang-gd** [comment]
> 你这样说 我希望加入 延边卫视 台，延边这边老人90%都看

想找个稳定的app不容易，特别是稳源难

**Comment by ashsteins** [comment]
> > 你这样说 我希望加入 延边卫视 台，延边这边老人90%都看
> 
> 想找个稳定的app不容易，特别是稳源难

看看灵犀直播里的广东地方台有没有 珠江

**Comment by winner106** [comment]
附议

**Comment by vokins** [comment]
https://www.gdtv.cn/tvChannelDetail/44
广东珠江台

https://www.gdtv.cn/tvChannelDetail/15
岭南戏曲

**Comment by sz20000** [comment]
别加了，，增加服务器压力。。。

**Comment by lizongying** [comment]
#431
