### ISSUE TITLE
凤凰卫视和凤凰资讯台

### ISSUE THREAD

**Issue by atlantis-l** [lizongying/my-tv#170]
作者大大你好，App很好用，已赞赏。

坐标广东，家里的地方机顶盒里面有凤凰卫视和资讯台，家里人挺喜欢看这两个台，希望可以加上去。

还有一个广东经济科教频道，抗日神剧🤣。

![image](https://github.com/lizongying/my-tv/assets/40952195/e319a7d8-23b0-4aa4-be21-553478a0cdde)

**Comment by ashsteins** [comment]
凤凰卫视真可以加，现在不算境外电视台了

**Comment by pooppiss** [comment]
这俩确实需求呼声高，但要有稳定的视频源。三天两头不能看也是头疼的。

**Comment by HoodL** [comment]
这个要有源吗？你们谁能搞到凤凰的直播源

**Comment by sz20000** [comment]
期待凤凰卫视资讯台。家里老人家特别喜欢看这个台。

**Comment by midpoint** [comment]
非常好用，如果有自定义频道，可以自己添加一些源就更好了

**Comment by pliskinfree** [comment]
这个app最大的优势就是支持ipv4的访问，有很好的适应性，
而现在比较稳定的卫视高清直播源包括凤凰都是ipv6的地址

**Comment by ProudBenzene** [comment]
求支持！

**Comment by dz515704201** [comment]
求支持

**Comment by zbby1987** [comment]
> https://www.fengshows.com/live
> 
> 可以看凤凰卫视资讯台和凤凰卫视中文台，但这个切换还需要作者看看怎么实现，谢谢

没梯子打不开？？？

**Comment by lizongying** [comment]
#431
