### ISSUE TITLE
数字键换台的问题

### ISSUE THREAD

**Issue by easedicy** [lizongying/my-tv#173]
您好，我发现用遥控按数字键时换到一个频道之后马上换另一个频道要等数字消失不然会跟着之前输的数字，
比如：我输了3跳转到3号频道后数字没有消失时，这时我发现按错了频道，然后我想马上换到6频道输到6就变成36了，大佬可不可以改进一下，十分感谢
(^_^)

**Comment by lizongying** [comment]
1.7.5已处理
