### ISSUE TITLE
“重温经典”电视直播频道今日开播：首播 87 版《红楼梦》、83 版《射雕英雄传》及《黑猫警长》等节目

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#174]
据介绍，“重温经典”频道在国家广播电视总局指导下，由中国广电集团主办，北京歌华有线承办。频道定位为公益性频道，免费向观众提供应看爱看、脍炙人口的经典内容，涵盖经典电视剧、动画片、纪录片等节目类型，旨在打造观众百看不厌、内容经久不衰、老少咸宜的国家级视听经典播出平台。
“重温经典”频道于 1 月 15 日在北京、上海、广东、山东、吉林、贵州、河北等 7 省市上线试播，北京地区频道号为 618。

该频道于 1 月 15 日至月底试播，试播验证结束后，2 月 1 日在全国有线电视网络正式落地开播。频道每日首播 6 小时，重播 2 次，每日播出 18 小时。首播时间为 18:00-24:00，一轮重播时间为次日 06:00-12:00，二轮重播时间为次日 12:00-18:00。

**Comment by ashsteins** [comment]
不错的台

**Comment by lizongying** [comment]
#431
