### ISSUE TITLE
1.5.0 无法安装，1.5.1 可以安装

### ISSUE THREAD

**Issue by vokins** [lizongying/my-tv#178]
您好，在索尼电视 bravia 4k vh21上无法安装

Android TV 操作系统版本 10
内核版本 4.19.75
 
通过系统自带的安装第三方app的“应用助手”，可以识别到，但点击安装后，最后提示“未安装应用”

谢谢

**Comment by sz20000** [comment]
这是你电视机系统问题。

**Comment by vokins** [comment]
抱歉， 是  1.5.0 无法安装。
我又试了，1.5.1 可以安装
https://github.com/lizongying/my-tv/releases/download/v1.5.1/my-tv-v1.5.1.apk
使用正常。谢谢

**Comment by lizongying** [comment]
我先记着了，按理说不会发生，暂时不好确定原因。
