### ISSUE TITLE
下载速度会慢慢递减，每隔一段时间就会卡

### ISSUE THREAD

**Issue by Candiana** [lizongying/my-tv#18]
下载速度会慢慢递减，每隔一段时间就会卡，刷新一下后又可以观看。之前用别的直播源源也会出现这样的状况，所以想请教一下老哥了解这样的原因么。

**Comment by lizongying** [comment]
这个软件应该不会，我看了很长时间都是没问题的。

**Comment by lizongying** [comment]
下载速度是指什么？如果视频正常，就不用关心下载速度

**Comment by Candiana** [comment]
谢谢，安装1.2.0后问题暂未再次出现
下载速度就是播放直播时下载视频片段的速度，会慢慢从几MB掉到几十kb，并且直播会随之卡住。这种现象在这个软件之前的版本上也会发生，切换一下频道就又能看一会儿，直到再次卡住。
