### ISSUE TITLE
可以自定义m3u源吗

### ISSUE THREAD

**Issue by lightpollution** [lizongying/my-tv#186]
自定义的话可以自己维护源，长时间不在家怕失效了

**Comment by midpoint** [comment]
是的，如果可以自定义就更好了

**Comment by lovingzyz** [comment]
你都自定义了，用TVBOX不好嘛

**Comment by Chenshennan** [comment]
虽然看不懂Java,但是从文件里面看来。应该是爬的央视评。改了编译不就解决了么（不是）

**Comment by lhbdhr** [comment]
> 你都自定义了，用TVBOX不好嘛

TVBOX是哪个软件呀？

**Comment by lovingzyz** [comment]
> > 你都自定义了，用TVBOX不好嘛
> 
> TVBOX是哪个软件呀？

兄弟，你都能上github了，TVbox都不知道嘛，随便google一下都找得到哇

**Comment by lhbdhr** [comment]
> > > 你都自定义了，用TVBOX不好嘛
> > 
> > 
> > TVBOX是哪个软件呀？
> 
> 兄弟，你都能上github了，TVbox都不知道嘛，随便google一下都找得到哇

主要看着这个 http://tvbox.clbug.com 网址，不像是官网啊。我还以为我找错了呢。
试了几个源，也没法播啊，不好用。
是需要自己维护一个源吗？

**Comment by lovingzyz** [comment]
> > > > 你都自定义了，用TVBOX不好嘛
> > > 
> > > 
> > > TVBOX是哪个软件呀？
> > 
> > 
> > 兄弟，你都能上github了，TVbox都不知道嘛，随便google一下都找得到哇
> 
> 主要看着这个 http://tvbox.clbug.com 网址，不像是官网啊。我还以为我找错了呢。 试了几个源，也没法播啊，不好用。 是需要自己维护一个源吗？

自己维护也可以，那么多大佬也都有源

**Comment by lizongying** [comment]
#532
