### ISSUE TITLE
天猫魔盒上闪退问题

### ISSUE THREAD

**Issue by yufd1986** [lizongying/my-tv#187]
在天猫魔盒M-30-B上安装完，打开闪退。

**Comment by xiaohang7101** [comment]
在天猫魔盒上安装完，打开闪退。

**Comment by sz20000** [comment]
天猫魔盒这种电子垃圾，赶紧换了吧。

**Comment by lizongying** [comment]
[v1.5.9](https://github.com/lizongying/my-tv/releases/tag/v1.5.9)
