### ISSUE TITLE
额。。回家以后又看不了了

### ISSUE THREAD

**Issue by rjn90815** [lizongying/my-tv#190]
这次是频道全黑，版本1.5.0 1.4.8都不行，网络是上海电信

**Comment by xtianxx** [comment]
我的是前几天看着看着就黑屏了 也没有声音 刚刚装上1.5.0 看看行不行

**Comment by wxjdsj** [comment]
是不是网络的问题，我这没问题024联通

**Comment by xtianxx** [comment]
正常看着看着黑屏 然后我换个台就行了类似刷新下就又正常了 这个现象是最近才出现的刚装上没啥问题
&nbsp;目前我装了下最新的版本就是前两天刚发布的目前没啥问题 网络没啥问题应该
还有我是个小白 没看懂024联通刷意思（真不懂）
最后谢谢大佬回复！
&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月3日(周六) 晚上8:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lizongying/my-tv] 额。。回家以后又看不了了 (Issue #190)




 
是不是网络的问题，我这没问题024联通

**Comment by lizongying** [comment]
如果最新版可以就用最新的吧
