### ISSUE TITLE
大佬我编译了下源码，编译不过，缺少native.c，可以提供吗

### ISSUE THREAD

**Issue by kinghore12030** [lizongying/my-tv#192]
编译报错信息
CMake Error at CMakeLists.txt:17 (add_library):
  Cannot find source file:

    src/main/cpp/native.c

**Comment by baolijin** [comment]
我也遇到同样的问题，应该是hash方案不想开源。我这边去掉直接跑so库，能编译过，也能run，但是Encryptor.hash(data: ByteArray)始终 return null，所以无法播放。 也请大佬一起看一下。

**Comment by kinghore12030** [comment]
你好，我是王金浩，你的邮件已收到，谢谢。

**Comment by baolijin** [comment]
我也遇到同样的问题，应该是hash方案不想开源。我这边去掉直接跑so库，能编译过，也能run，但是Encryptor.hash(data: ByteArray)始终 return null，所以无法播放。 也请大佬一起看一下。

**Comment by sz20000** [comment]
别整了。大佬搞得挺好的。

**Comment by boxvm** [comment]
别人大佬自己开了vip 有些tv 需要vip

**Comment by yayoiii1** [comment]
同问 add_library( # Specifies the name of the library.
            native

            # Sets the library as a shared library.
            SHARED

            # Provides a relative path to your source file(s).
            src/main/cpp/native.c)

**Comment by kinghore12030** [comment]
> 别整了。大佬搞得挺好的。

主要想看看怎么加一下自己的源
