### ISSUE TITLE
【功能建议】安装在电视上，能够在网络抖动后自动连接

### ISSUE THREAD

**Issue by WFANG12719** [lizongying/my-tv#194]
网络总是不能100%全天连接，有时路由器重启，或半夜运营商把ADSL重置换IP地址，画面就卡住不动了，打开电视也就一幅画静止在那里，老年人还以为电视有坏了呢，重新选择一个频道再换回来就可以，其实就是网络断过没有继续接上流视频。

**Comment by zbby1987** [comment]
不管什么原因卡住的，
卡住后，确实应该有一个刷新重连的机制

**Comment by WFANG12719** [comment]
let it be...
