### ISSUE TITLE
提个中肯建议

### ISSUE THREAD

**Issue by sz20000** [lizongying/my-tv#201]
换台时候，选中的图标比例能否相差更大一点，更突出选中图标？选中换个底色也可以。
目前老人换台不太好看选中了哪个图标。

**Comment by Yvonne0827** [comment]
将选中的泰高亮或显示成别的颜色

**Comment by zbby1987** [comment]
确实是不少人提过这个问题了，
老人可能对那个选中状态的图标没那么敏感

**Comment by lizongying** [comment]
是的，应该更醒目一些。后面加入。
