### ISSUE TITLE
天猫魔屏闪退

### ISSUE THREAD

**Issue by cent-USA2025** [lizongying/my-tv#203]
天猫魔屏闪退。
设备型号
MagicProjectorM2X
总容量 11.7G
可用容量 9.1G
总内存 2006M
分辨率  1280*720
屏幕密度 160 dpi 
 cpu 频率
100MHZ/1908MHZ
 cpu 核心数
 cpu 架构 armv7l
 root 否
 mac 地址
系统版本
9.1.0- RS -20221227.1503
内核版本
 Linux 4.9.113

**Comment by RSAMHW** [comment]
+1 我的天猫魔盒 也有问题

**Comment by sz20000** [comment]
天猫魔盒这种爱国设备还是尽快弃用吧。这种软件是不会通过的。

**Comment by emiya01** [comment]
我爸妈的天猫魔盒也有问题，求问有没有解决方法或者能用的app推荐？老人用这些比较麻烦

**Comment by lizongying** [comment]
[v1.5.9](https://github.com/lizongying/my-tv/releases/tag/v1.5.9)
