### ISSUE TITLE
安卓手机换台不是很友好

### ISSUE THREAD

**Issue by MrZbinby** [lizongying/my-tv#206]
安卓手机换台只能上下左右一个一个的换，点击屏幕
出现的频道选择还没选完就消失，点开又弹回原来的位置，好不容易滑回位置又消失，所以希望改善一下，感谢

**Comment by IFengjun** [comment]
这是给电视使用的，手机点击事件和电视遥控事件不一样，所以操作起来不顺手。手机凑合用就行了

**Comment by lizongying** [comment]
有机会再优化了
