### ISSUE TITLE
卡通频道

### ISSUE THREAD

**Issue by yhy-456** [lizongying/my-tv#209]
希望增加一些卡通频道，类似金鹰卡通、炫动卡通、卡酷频道这种~

**Comment by dianliao** [comment]
应该找不到稳定的源

**Comment by HiruOcha** [comment]
希望添加嘉佳卡通

**Comment by jijunhao** [comment]
金鹰卡通,http://dbiptv.sn.chinamobile.com/PLTV/88888890/224/3221225744/index.m3u8
哈哈炫动,http://dbiptv.sn.chinamobile.com/PLTV/88888890/224/3221226213/index.m3u8
优漫卡通,http://dbiptv.sn.chinamobile.com/PLTV/88888890/224/3221225795/index.m3u8
北京卡酷,http://dbiptv.sn.chinamobile.com/PLTV/88888890/224/3221225743/index.m3u8
嘉佳卡通,http://dbiptv.sn.chinamobile.com/PLTV/88888890/224/3221226227/index.m3u8

直播源还是有的，但是老年人一般不看

**Comment by lizongying** [comment]
#431
