### ISSUE TITLE
你好，app做的很好

### ISSUE THREAD

**Issue by lgm0603** [lizongying/my-tv#21]
3.6.9台怎么没有，另外问下你的直播源是移动的，我是电信线路，也可以流畅播放，在用你的app时，如果我用你的直播源，再用其他直播软件怎么不能播放？

**Comment by renjianxiaopihong** [comment]
最新的V1.2.6有3、6、9台啊，我用联通的，也很流畅，感谢

**Comment by lgm0603** [comment]
最新的1.26，3.6.9台我这儿不能播放，不知是什么原因？

**Comment by lgm0603** [comment]
央视的风云音乐后的几个台也不能播放，卫视台怎么不全，我我们甘肃台也没有

**Comment by renjianxiaopihong** [comment]
我刚是在手机上测试的，没发现问题，晚上回去在电视上试试后再来反馈，希望没问题，这个特别适合家里老人，只看1、4、9、10、13这几个台

**Comment by lgm0603** [comment]
以上是在虚拟机上测试的，我安装到电视后，打开app提示   “我的电视"已停止运行

**Comment by renjianxiaopihong** [comment]
在家试了一下，用WiFi确实看不了，应该是只能IPV6观看，希望能后续更新IPV4的源

**Comment by renjianxiaopihong** [comment]
我用的华为智慧屏，安装使用没有问题，就是3、6、8播放不了，应该是IPV6的问题
