### ISSUE TITLE
1.5.3 Android盒子第二次开机打开上一次电视台会黑屏1-2分钟才能看到内容

### ISSUE THREAD

**Issue by lleheaven** [lizongying/my-tv#214]
RT，每次新开机，进入app，就是黑屏，只能放在那里等着，大概1-2分钟后，就突然有视频了，然后切换台也是秒开，就是第一次进去时候黑屏时间有点长，黑屏时候即使切换其他台，也都是黑屏，只能等出图后切换台。希望这个流程可以优化，谢谢！

**Comment by sz20000** [comment]
小米电视一切正常！

**Comment by zbby1987** [comment]
不确定这个黑屏是软件处于怎样的状态中，
如果是在加载视频，那应该是有一个加载中的状态动画。
这里可以把状态的类别完善下，比如:
连接服务器中，
连接服务器成功,loading
等等...这样好让用户自行排查问题。

还有一个方法，就是软件确定黑屏短时间无法解决时，要么自行刷新，要么自动切到下一个频道

**Comment by lizongying** [comment]
我会优化下
