### ISSUE TITLE
自定义直播源

### ISSUE THREAD

**Issue by AidenLee1994** [lizongying/my-tv#216]
可不可以像tivimate那样可以用户提交直播源，还有能不能显示支持的直播源网络，像aptv那样，可以很清楚直播源走的网络类型

**Comment by zengkid** [comment]
> 你下个 aptv 不就行了。这个主打简洁！快速！

### aptv是apple TV啊。

**Comment by zm47726151** [comment]
有好的直播源分享出来吧

**Comment by lizongying** [comment]
#532
