### ISSUE TITLE
小米电视机流畅运行，无广告，建议进一步完善菜单

### ISSUE THREAD

**Issue by dairui2** [lizongying/my-tv#218]
小米电视机已经试用了并跟你点亮Star，整体很好，菜单layout稍有不适，目前是长长的三行，如果要看“新疆卫视”则操作步骤较多，建议改成frame(左侧分组菜单，右侧预览)，如果有可能继续丰富一下视频资源。

**Comment by zbby1987** [comment]
搞个选台无图标的开关比较好。
文字上加个选中的背景色，
多加几行几列，尽量一屏内能显示完。

**Comment by AccountGc** [comment]
> 小米电视机已经试用了并跟你点亮Star，整体很好，菜单layout稍有不适，目前是长长的三行，如果要看“新疆卫视”则操作步骤较多，建议改成frame(左侧分组菜单，右侧预览)，如果有可能继续丰富一下视频资源。

点个start你有啥可炫耀的？

**Comment by Ghost-2022** [comment]
为什么我的小米EA55安装后没有信号

**Comment by Ghost-2022** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by lizongying** [comment]
後面會優化

**Comment by Ghost-2022** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
