### ISSUE TITLE
建议立即下架删除，B站有推广你的软件，已经上热门30万播放了，你多注意

### ISSUE THREAD

**Issue by wow233** [lizongying/my-tv#221]

**Comment by zbby1987** [comment]
我也是这个感觉，如果人在台湾或者大马，倒还好。
如果人在大陆，建议谨慎起来。。。

**Comment by LEONYIP7** [comment]
怪不得今天突然黑了

**Comment by Dicky-pong** [comment]
无语，刚安装，发现黑屏了。。。

**Comment by LEONYIP7** [comment]
删库吧，注意安全。

**Comment by ZGASN** [comment]
B站的那些人。。。真的。。。。这毁了

**Comment by mingtiao30** [comment]
：< 估计是被掐源了

**Comment by ragecaty** [comment]
刚来就黑了

**Comment by ragecaty** [comment]
> 我也是这个感觉，如果人在台湾或者大马，倒还好。 如果人在大陆，建议谨慎起来。。。净网·2024已经启动 ★ ★★ ★★★ 先用我下面发的电视浏览器版本，临时顶一顶吧！ 因为是浏览器，换台肯定没我的电视那么流畅！ 自家安卓设备内置的webview.apk版本相对高的， 推荐用第1个链接，最低支持安卓5， 切台速度相对第2个链接快，安装包2.5兆，下载地址： https://www.123pan.com/s/9sRPjv-xdxVv.html 用电脑浏览器，或者手机浏览器的UA改成PC才能直接下载 . 如果设备相对比较老（最低安卓4.4.2)， 或者系统webview用的老版本的，用下面集成腾讯x5内核的版本！ 集成的x5内核36兆，安装包总体积38兆，下载地址: https://www.123pan.com/s/9sRPjv-pdxVv.html

不错，挺好用的

**Comment by zbby1987** [comment]
> 不错，挺好用的

2.5兆的那个，如果你设备自带的webview相对新的话，切台速度也还可以。
先临时顶顶吧，
浏览器肯定是没有专门的app那么好用的

**Comment by MiniKoro** [comment]
挺无语的

**Comment by alexallen1** [comment]
注意个啥，本身github就是分享兴趣的地方，注册一个github也就10秒钟的事

**Comment by lizongying** [comment]
请更新最新版本

**Comment by ccav14** [comment]
不低调使用以后看什么电视
