### ISSUE TITLE
下载了，安装手机，电视都没有办法播放，怎么回事？

### ISSUE THREAD

**Issue by shunsae** [lizongying/my-tv#222]

**Comment by zbby1987** [comment]
估计是源被掐了
★
★★
★★★
先用我下面发的电视浏览器版本，临时顶一顶吧！
因为是浏览器，换台肯定没我的电视这种专门的直播app好用！
自家安卓设备内置的webview.apk版本相对高的，
推荐用第1个链接，最低支持安卓5，切台速度相对第2个链接快，
安装包仅2.5兆，下载地址：
https://www.123pan.com/s/9sRPjv-xdxVv.html
用电脑浏览器，或者手机浏览器的UA改成PC才能直接下载
★
如果设备相对比较老（最低安卓4.4.2)，
或者系统webview用的老版本的，用下面集成腾讯x5内核的版本！
集成的x5内核36兆，安装包总体积38兆，下载地址:
https://www.123pan.com/s/9sRPjv-pdxVv.html

**Comment by Dandelion-appointment** [comment]
只能看cgtn的纪录片

**Comment by zbby1987** [comment]
> 只能看cgtn的纪录片

用2楼的，都可以看

**Comment by Bilibili331** [comment]
真特么服了B站这些人了

**Comment by lizongying** [comment]
请更新最新版本
