### ISSUE TITLE
什么情况为什么又不能看了？

### ISSUE THREAD

**Issue by Nixontheone** [lizongying/my-tv#224]
本来是用的好好的，又不能看了！

**Comment by zbby1987** [comment]
先用我下面发的电视浏览器版本，临时顶下吧！
因为是浏览器，换台肯定没我的电视这种专门的直播app快！
自家安卓设备内置的webview.apk版本相对高的，
推荐用第1个链接，最低支持安卓5，切台速度相对第2个链接快，
支持手机(手机上长按屏幕换台)，安装包仅2.5兆，下载地址：
https://www.123pan.com/s/9sRPjv-xdxVv.html
用电脑浏览器，或者手机浏览器的UA改成PC才能直接下载

★

如果设备相对比较老（最低安卓4.4.2)，不支持手机操作，
或者系统webview用的老版本的，用下面集成腾讯x5内核的版本！
集成的x5内核36兆，安装包总体积38兆，下载地址:
https://www.123pan.com/s/9sRPjv-pdxVv.html

**Comment by sz20000** [comment]
应该是服务器压力太大了！这个软件造福了全球华人！

**Comment by zbby1987** [comment]
> 应该是服务器压力太大了！这个软件造福了全球华人！

并不是，你应该考虑下，为什么同样是央视频，
二楼链接里的软件却能用，
官方app也能用，只有mytv不能用了？

2.5兆-极速版，安卓9～14设备(tv/盒子‖手机可长按屏幕换台)：
https://www.123pan.com/s/9sRPjv-xdxVv.html

38兆-兼容版，安卓4～8设备(老电视/盒子，不支持手机)：
https://www.123pan.com/s/9sRPjv-pdxVv.html

**Comment by Nixontheone** [comment]
> 先用我下面发的电视浏览器版本，临时顶下吧！ 因为是浏览器，换台肯定没我的电视这种专门的直播app快！ 自家安卓设备内置的webview.apk版本相对高的， 推荐用第1个链接，最低支持安卓5，切台速度相对第2个链接快， 支持手机(手机上长按屏幕换台)，安装包仅2.5兆，下载地址： https://www.123pan.com/s/9sRPjv-xdxVv.html 用电脑浏览器，或者手机浏览器的UA改成PC才能直接下载
> 
> ★
> 
> 如果设备相对比较老（最低安卓4.4.2)，不支持手机操作， 或者系统webview用的老版本的，用下面集成腾讯x5内核的版本！ 集成的x5内核36兆，安装包总体积38兆，下载地址: https://www.123pan.com/s/9sRPjv-pdxVv.html

多谢，感恩🙏 ，有没有好介绍的软件可以看电影和电视剧呢？

**Comment by zbby1987** [comment]
> 多谢，感恩🙏 ，有没有好介绍的软件可以看电影和电视剧呢？

tvbox就不多介绍了，

手机还可以用这个：
https://www.jianpian8.co/

**Comment by lizongying** [comment]
请更新最新版本
