### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by zjy208723** [lizongying/my-tv#226]
今天更新最新版1.5.3，更新后看了一下正常，关了盒子，晚上回家打开就黑屏，所有台都不能看了

**Comment by zbby1987** [comment]
2.5兆--webview极速版，首选推荐！
安卓9～14设备(tv/盒子‖手机可长按屏幕换台)：
https://www.123pan.com/s/9sRPjv-xdxVv.html
★
★★
★★★
38兆--腾讯x5兼容版，
安卓4～8设备(老电视/盒子，不支持手机)：
https://www.123pan.com/s/9sRPjv-pdxVv.html

**Comment by zbby1987** [comment]
> 你也是不嫌累的每个帖子都回复

从小就爱分享

**Comment by lizongying** [comment]
请更新最新版本
