### ISSUE TITLE
大佬，会不会有自动更新的功能呢？

### ISSUE THREAD

**Issue by Nixontheone** [lizongying/my-tv#228]
希望会有自动更新的功能，比较方便大家使用🙏

**Comment by back3333** [comment]
有自动更新死的快

**Comment by zbby1987** [comment]
> 希望会有自动更新的功能，比较方便大家使用🙏

方便顺着服务器抓到他？

**Comment by Nixontheone** [comment]
> > 希望会有自动更新的功能，比较方便大家使用🙏
> 
> 方便顺着服务器抓到他？

不是这样说，我也明白他的无奈，只是建议而已！

**Comment by protectedMan** [comment]
有没有一种可能,就是故意不加自动更新功能?

**Comment by lizongying** [comment]
#123
