### ISSUE TITLE
建议图标上加个版本号

### ISSUE THREAD

**Issue by tommyonsn** [lizongying/my-tv#231]
比如昨天1.5.3，今天用不了了。U盘里有1.5.0（通用版）和1.5.3（安卓5版）。
今天更新了1.5.2（通用版）和1.5.5（安卓5版）。
有四个在安装优盘里，图标上没有版本号分不清四个哪个是哪个。
希望能加个小标识，谢谢

**Comment by RuCu6** [comment]
命名清楚不就可以了吗  为什么要在图标上写版本号  奇葩行为

**Comment by gqzy2013** [comment]
> 命名清楚不就可以了吗 为什么要在图标上写版本号 奇葩行为

确实挺奇葩的 没记错从github直接下载的文件 文件名就带版本号

**Comment by liigo** [comment]
他这个版本号的确很混乱，先发1.5.1，后发1.5.0，这事都干得出。

**Comment by jijunhao** [comment]
双数通用，单数特供

**Comment by tommyonsn** [comment]
> 命名清楚不就可以了吗 为什么要在图标上写版本号 奇葩行为

我的电视安装时看不到文件名，只能看到图标

**Comment by lizongying** [comment]
圖標上區分有點麻煩，建議更改下顯示方式，應該可以看到文件名

**Comment by wzsxyjs** [comment]
求稳定，但很不稳定。希望出一个服务器自己配置的稳定定制版。
