### ISSUE TITLE
建议大佬只维护一个源

### ISSUE THREAD

**Issue by EtAiorsW** [lizongying/my-tv#233]
增加点使用难度，降低风险。已经看到有人做了视频，而且登上了b站热门第一，这种敏感软件本来就不应该广泛传播，而且大佬用爱发电的成果却被别人拿来赚米，多少好的开源软件都被这样给整没了。

**Comment by acliyang** [comment]
一定要保护好自己啊

**Comment by TownMarshal** [comment]
注意注意！

**Comment by shengdao001** [comment]
注意自己啊！

**Comment by tommyonsn** [comment]
就是看到b站才知道的

**Comment by whtk** [comment]
回头被封了去骂b站的

**Comment by billliou** [comment]
今日头条也有不少。

**Comment by ragecaty** [comment]
手动保护

**Comment by CJyoung524** [comment]
希望像作者一样的好人一生平安

**Comment by amorfati94** [comment]
好像今天已经没法用了，打开一直黑屏，不知道是家里电视的问题还是被传太多了。

**Comment by whtk** [comment]
正在用 用的1.55 使用良好

**Comment by gqzy2013** [comment]
> 好像今天已经没法用了，打开一直黑屏，不知道是家里电视的问题还是被传太多了。

最新版已经修复 下今早的最新就好了

**Comment by kamkdd** [comment]
登上了b站热门第一，难道不是好事吗？谁不希望自己的作品发扬光大
