### ISSUE TITLE
CCTV 10 信源无效

### ISSUE THREAD

**Issue by Bent2333E** [lizongying/my-tv#236]
RT，调到10台会显示“应版权方要求，暂停提供直播信号”。

另，昨晚1.4.8版本的10台昙花一现的可以播放，但今天早上1.4.8失效黑屏。

电视盒子版本4.4.2

**Comment by gqzy2013** [comment]
C10应该是直播源的问题 到了指定节目直播源会被掐断 

启动黑屏到Releases下载最新版解决

**Comment by daguGit** [comment]
安卓，1.5.5版本同

**Comment by lizongying** [comment]
正常。後面可能會處理。
