### ISSUE TITLE
天猫魔盒1s+可以正常使用，但画面播放非常卡，可以排除网络的原因。

### ISSUE THREAD

**Issue by huangjua** [lizongying/my-tv#238]
如题，已经找到原因，是设备本身存储内存不足，播放缓存不足导致内容卡顿。从我这个小破设备来看，起码剩余3.5g左右的储存内存才能流畅播放。作者你后续有无对这种老旧小内存的设备优化的打算呢？

**Comment by lizongying** [comment]
沒有。有精力可能會嘗試一下，做不好可能就算了。可能有更重要的工作。
