### ISSUE TITLE
给TV装浏览器软件，直接打开央视频！！！

### ISSUE THREAD

**Issue by nomoneynolife** [lizongying/my-tv#239]
来拿当备用方案，，，

试了下，除了视频有点模糊，，，其他还行。。。

**Comment by ljk99** [comment]
我用浏览器看直播，直接被电视盒子拦截信号

**Comment by nomoneynolife** [comment]
> 截

浏览器可以伪装那个浏览器标识的，貌似是叫UA啥的

**Comment by lizongying** [comment]
也是個方案

**Comment by zbby1987** [comment]
> 浏览器可以伪装那个浏览器标识的，貌似是叫UA啥的

2.5兆-webview极速版_直播浏览器：
https://www.123pan.com/s/9sRPjv-7HxVv.html
安卓5以上才可装，推荐安卓8～14设备用，安卓9最佳！
(tv/盒子专用‖手机也可用：长按屏幕换台)：
开启了无图模式：屏蔽图片加载，切台速度嘎嘎快。

调用的系统内置webview版本太低(≥v66)或功能阉割时，
就无法播放，此时建议用下面集成了x5内核的兼容版。
★
★★
★★★

38兆-腾讯x5内核兼容版_直播浏览器：
https://www.123pan.com/s/9sRPjv-pdxVv.html
安卓4～14设备可安(老电视/盒子推荐，不支持手机操作)：
安卓4～7推荐，但安卓4.4.2只能用这版。
暂未开启图片屏蔽，切台速度相对慢，后续会优化。
