### ISSUE TITLE
经常卡死

### ISSUE THREAD

**Issue by liigo** [lizongying/my-tv#242]
遇到多次了，比较频繁。看着看着CCTV然后莫名其妙卡死了，无法自行恢复。强行退出或换台后还能正常播放，排除网络问题。
我先后试过1.5.1, 1.5.0, 1.5.3（我至今不明白他为何在1.5.1之后又发布一个更小的版本号）。
看升级内容作者是想解决这个问题，但问题一直在。

**Comment by liigo** [comment]
山东电信宽带。我前面已经说明排除了网络问题。

**Comment by ShanshanHY** [comment]
> 山东电信宽带。我前面已经说明排除了网络问题。

好的，感谢
我是想借用你的经验来排查我的网络
