### ISSUE TITLE
只有一个小小的建议。。。

### ISSUE THREAD

**Issue by olprc** [lizongying/my-tv#243]
**昨天油管上无意中看到介绍这个APP的视频，试用了一下，效果非常好，速度也非常快！非常惊喜！结果 。。。晚上就看不了了，就全黑了。我心想，难道是电视检测到我用了某些不被允许的APP，给我阻断了？
刚上来看了眼，原来是有新版本了。我的小建议就是：能不能增加在线升级的功能？或者，有新版本了，客户端给个弹出提示也可以。**

**Comment by whtk** [comment]
我觉得第二个方法靠谱

**Comment by allyn0303** [comment]
不建议，少点人用，这样才安全。多点阻难国内的用户

**Comment by lizongying** [comment]
可以考慮，但暫時沒時間做。最新版提示應該可以。
