### ISSUE TITLE
安卓4电视安装通用版本闪退

### ISSUE THREAD

**Issue by sparkplain** [lizongying/my-tv#244]
从1.5.0以上的通用版本闪退

**Comment by whtk** [comment]
还是换个安卓高点的电视把。。。

**Comment by sparkplain** [comment]
我的电视甚至都不是安卓系统，而是yunos3.3.0，1.4.8及以下的通用版本能用，奈何现在源失效了。

**Comment by whtk** [comment]
> 我的电视甚至都不是安卓系统，而是yunos3.3.0，1.4.8及以下的通用版本能用，奈何现在源失效了。

哈哈 sorry

**Comment by whtk** [comment]
确实没更新前 我家用的也是1.4.8

**Comment by tp1415926535** [comment]
同，安卓4.2.2，Release v1.5.2 启动之后下方显示CCTV1 然后闪退。

**Comment by tp1415926535** [comment]
同，安卓4.2.2，Release v1.5.2 启动之后下方显示CCTV1 然后闪退。

**Comment by tp1415926535** [comment]
> 还是换个安卓高点的电视把。。。

更新电视安卓版本太麻烦了，代价过大

**Comment by xzhan6004** [comment]
爸妈买的电视根本不会看这些，我进系统看都不显示安卓版本只显示电视系统版本，我还是一个个试才试到1.4.2能用，想更新系统太折腾了

**Comment by dxuser114** [comment]
我也是，安卓4.4.2系统，打开也崩溃![IMG_20240206_192814.jpg](https://github.com/lizongying/my-tv/assets/149327737/4549f798-1c83-450b-b665-a303de7eb8a8)

**Comment by qshyw1** [comment]
安卓4.4.2系统 中兴盒子，也闪退

**Comment by tp1415926535** [comment]
安卓4.2.2，Release v1.5.4 依旧显示完CCTV1之后闪退

**Comment by tp1415926535** [comment]
今天测 Release v1.5.8 依旧显示完CCTV1之后闪退

**Comment by lizongying** [comment]
請提供更多信息
