### ISSUE TITLE
这软件真好，能设置开机自启动吗?

### ISSUE THREAD

**Issue by safesword** [lizongying/my-tv#247]
**秒换台，非常神奇。比之前的电视家强不少。
博主，能添加个开机自启动的选项的吗？谢谢。（这个选项对家里老人非常友好）**

**Comment by huanghuashu** [comment]
下载个当贝桌面里面应该可以设置

**Comment by safesword** [comment]
> > **秒换台，非常神奇。比之前的电视家强不少。 博主，能添加个开机自启动的选项的吗？谢谢。（这个选项对家里老人非常友好）**
> 
> 开机自启，现在国产电视系统五花八门，很难

额，我的是TCL老款，支持开机自启动的。我自己搜了一下，可以添加几行代码进去，实现开机自启动，这个操作打算求助同事。

**Comment by lizongying** [comment]
#89
