### ISSUE TITLE
老铁又看不了了全黑屏

### ISSUE THREAD

**Issue by fly8888** [lizongying/my-tv#248]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by ddkk3000** [comment]
是的。是不是服务器关了？

**Comment by wangshibo74** [comment]
不会被封杀了吧

**Comment by wangshibo74** [comment]
似乎已经解决了

**Comment by ddkk3000** [comment]
> 似乎已经解决了

我这还是黑的
