### ISSUE TITLE
能加上香港电视台，tvb那些吗

### ISSUE THREAD

**Issue by SilverHayasaka** [lizongying/my-tv#249]
老广这边看电视一般都看香港台，如果有就更好了

**Comment by sz20000** [comment]
送台电视给你就更好了

**Comment by lizongying** [comment]
会考虑

**Comment by ashsteins** [comment]
> 会考虑

凤凰中文台、凤凰资讯台和香港卫视，凤凰主流这三个台

**Comment by bmw7cc** [comment]
> 会考虑

这APP做的及其简单，仿佛回到了90年代的感觉.。。。哈哈哈

**Comment by lizongying** [comment]
#431

**Comment by lizongying** [comment]
已增加鳳凰衛視[v1.6.1](https://github.com/lizongying/my-tv/releases/tag/v1.6.1)
