### ISSUE TITLE
在16:10比例的平板电脑上屏幕的显示问题

### ISSUE THREAD

**Issue by nicholas0444** [lizongying/my-tv#25]
APP很好用，解决了国外用户无法观看国内CCTV的问题。
在我的安卓平板上遇到一个小问题，因为屏幕是16:10的，但是节目源大多都是16:9的
因此正常情况下屏幕上下会有黑边，但是目前发现1.2.6版本下，视频是平铺状态全屏，也就是说屏幕左右有切割
所以希望作者可以在下一个版本修复这个问题哈，非常感谢！

**Comment by lizongying** [comment]
好问题，没考虑到这个。下一版本，修复这种情况。

**Comment by nicholas0444** [comment]
Thanks a lot, working perfectly now
![Screenshot_20240102-200955](https://github.com/lizongying/my-tv/assets/33141021/d718a798-f5f7-4db8-a958-d6fdd8e6db1b)

**Comment by nicholas0444** [comment]
Nice!
