### ISSUE TITLE
源码无法编译使用

### ISSUE THREAD

**Issue by yuanjianchun** [lizongying/my-tv#250]
单独编译native.c异常，大佬需要怎样才可以搞的

**Comment by gqzy2013** [comment]
之前有人求过了 native.c没上传 大佬不公开

**Comment by baolijin** [comment]
> 之前有人求过了 native.c没上传 大佬不公开

首先是native.c没开源，然后libnative.so也无效。没关系 只要项目还活着，我就满足了

**Comment by lizongying** [comment]
如果大范围传播加密算法的话，估计我的电视真得嘎了。
望大家理解。

**Comment by hongfs** [comment]
> 如果大范围传播加密算法的话，估计我的电视真得嘎了。 望大家理解。

这就很奇怪了呀，你的发行版用 github actions 去编译然后上传发布，我自己 fork 一份然后也是用 github actions 去打包，可以安装，打开后有显示频道 logo，就是没有频道的画面内容。
