### ISSUE TITLE
求大佬出个稳定版，过完年回去谁会弄电视家里人不会,现在安装要adb命令，才能安装

### ISSUE THREAD

**Issue by boy86001** [lizongying/my-tv#251]

**Comment by Guancheng-Li** [comment]
开源的东西，很难稳定的...
- 方案1：过年时pdd买一个9块\月咪咕会员备用，走手机投央视频投屏助手就行（包年大概85），这个是最稳的，技术门槛低。
- 方案2：可以试试Tvimate+IPV6源，这个可能有时候缓冲会卡下，全国已经普及IPV6了，给家人设置好就能用，设置一遍就行，前提有IPV6，接受有时有点缓冲卡下（m3u.ibert.me）。
- 方案3：买地面波接收器，这个看城市信号覆盖和你家房子的位置了；
- 方案4：电视软件，[my-tv](https://github.com/lizongying/my-tv)，[cctv_viewer](https://github.com/Eanya-Tonic/CCTV_Viewer)，小薇电视，电视5.0，还有一些B站搜，不过能用多久看缘分，前两个是最好的

建议弄个外贸盒子或者运营商刷机盒子，就能随意安装了。
国内厂商的盒子基本都是广告播放器，不推荐。
电视建议少折腾，闪存这东西有寿命，盒子坏了买一个还行，电视就算买便宜的换起来也不方便。

**Comment by xzhan6004** [comment]
> 开源的东西，难稳定的...
> 
> * 方案1：过年时pdd买一个9/月咪咕视频会员备用，走手机投央投屏助手就行（包年大概85，比IPTV，X电便宜太多），这是最稳定的块，技术提案低（缺点：还是得学投屏，电视端不能直接用，即使买会员，有些独家版权的电视剧综艺看不了）；
> * 方案2：可以尝试Tvimate+IPV6源（IPTV Pro有些源用不了，Televizo UI我不喜欢，KODI操作也有些复杂），这个可能有时候缓冲会卡下，全国已经普及IPV6了，给家人设置好可以使用，设置一遍就行，前提有IPV6，接受有时候有点缓冲卡下（m3u.ibert.me比较稳，还可以配置docker，直接用也没有问题；小黄鱼也卖有人自己维护的源码）；
> * 方案3：买地面波接收器，这个看城市信号覆盖和你家房子的位置了；
> * 方案4：电视软件，[my-tv](https://github.com/lizongying/my-tv)，[cctv_viewer](https://github.com/Eanya-Tonic/CCTV_Viewer)，小薇电视，电视5.0，还有一些B站搜，不过能用多久看缘分，前两个是最好的；
> * 方案5：回家用IPTV抓包，这个技术发达，而且得有光猫管理员密码，不适合老人用；
> * 方案6：不是办法，电脑访问央视，PotPlayer/VLCPlayer打开IPV6的m3u文件...
> 
> 建议弄个外贸盒子或者运营商刷机盒子接电视，就能方便安装了。 国内厂商的盒子基本都是广告播放器，不推荐。 电视建议少折腾，不然这东西有耗，盒子坏了买一个还行，电视就算买便宜的换起来也相当不方便。
> 
> 我用1+2+4，2&4配好随缘用，教老人用1投屏兜底。 客厅用电视+盒子，卧室客厅闲置的显示器，显示器+盒子+外接小音箱。

感谢作者！cctv_viewer安装上能用了，老人家就是想看看央视播的电视剧昨天my tv不能用急坏了

**Comment by Guancheng-Li** [comment]
> > 开源的东西，难稳定的...
> > 
> > * 方案1：过年时pdd买一个9/月咪咕视频会员备用，走手机投央投屏助手就行（包年大概85，比IPTV，X电便宜太多），这是最稳定的块，技术提案低（缺点：还是得学投屏，电视端不能直接用，即使买会员，有些独家版权的电视剧综艺看不了）；
> > * 方案2：可以尝试Tvimate+IPV6源（IPTV Pro有些源用不了，Televizo UI我不喜欢，KODI操作也有些复杂），这个可能有时候缓冲会卡下，全国已经普及IPV6了，给家人设置好可以使用，设置一遍就行，前提有IPV6，接受有时候有点缓冲卡下（m3u.ibert.me比较稳，还可以配置docker，直接用也没有问题；小黄鱼也卖有人自己维护的源码）；
> > * 方案3：买地面波接收器，这个看城市信号覆盖和你家房子的位置了；
> > * 方案4：电视软件，[my-tv](https://github.com/lizongying/my-tv)，[cctv_viewer](https://github.com/Eanya-Tonic/CCTV_Viewer)，小薇电视，电视5.0，还有一些B站搜，不过能用多久看缘分，前两个是最好的；
> > * 方案5：回家用IPTV抓包，这个技术发达，而且得有光猫管理员密码，不适合老人用；
> > * 方案6：不是办法，电脑访问央视，PotPlayer/VLCPlayer打开IPV6的m3u文件...
> > 
> > 建议弄个外贸盒子或者运营商刷机盒子接电视，就能方便安装了。 国内厂商的盒子基本都是广告播放器，不推荐。 电视建议少折腾，不然这东西有耗，盒子坏了买一个还行，电视就算买便宜的换起来也相当不方便。
> > 我用1+2+4，2&4配好随缘用，教老人用1投屏兜底。 客厅用电视+盒子，卧室客厅闲置的显示器，显示器+盒子+外接小音箱。
> 
> 感谢作者！cctv_viewer安装上能用了，老人家就是想看看央视播的电视剧昨天my tv不能用急坏了

感谢软件作者们吧，我只是把他们的资源整合了一下找个最优解而已。
