### ISSUE TITLE
部分电视无法返回

### ISSUE THREAD

**Issue by ItsBag** [lizongying/my-tv#252]
某品牌电视盒子按返回键后没有反应

**Comment by CJyoung524** [comment]
你得把型号、系统等详细信息给出来，不然你让别人怎么给你解决问题？

**Comment by ItsBag** [comment]
@CJyoung524 谢谢帮忙解决问题
android版本：8.1.0  软件版本：1.5.2
感谢作者制作软件
希望能继续坚持下去
谢谢作者大大已打赏鼓励

**Comment by ItsBag** [comment]
嗯
