### ISSUE TITLE
信号源全部失效了，大家有遇到这问题吗

### ISSUE THREAD

**Issue by aichinuomifan** [lizongying/my-tv#253]

**Comment by wadwqe** [comment]
我也是

**Comment by 402324505** [comment]
哎，刚安装就看得一下，只能看一个国际频道了

**Comment by wadwqe** [comment]
只能等大佬更新了

**Comment by Nixontheone** [comment]
请更新最新版本

**Comment by Neil-2322** [comment]
是不是用的人多了，被举报了？

**Comment by Nixontheone** [comment]
> 是不是用的人多了，被举报了？

别瞎说，请更新最新版本

**Comment by androidjiajia** [comment]
最新版本可以的，刚亲测

**Comment by DarkLeaves** [comment]
给家里电视装的1.4.8的，刚刚只能看那个外语的一个频道。最新版要求安卓版本大于5，我家里这个装不了，咋整呀

**Comment by shengdao001** [comment]
> 给家里电视装的1.4.8的，刚刚只能看那个外语的一个频道。最新版要求安卓版本大于5，我家里这个装不了，咋整呀

安装最新通用版

**Comment by shengdao001** [comment]
> 给家里电视装的1.4.8的，刚刚只能看那个外语的一个频道。最新版要求安卓版本大于5，我家里这个装不了，咋整呀

版本是1.5.2

**Comment by Edwinzzzs2** [comment]
大家都怎么解决的

**Comment by Nixontheone** [comment]
> 大家都怎么解决的

请更新最新版本

**Comment by wadwqe** [comment]
我的小米电视显示检测安装包异常无法安装，可是电视的安装未知应用权限是打开了的，是不兼容吗

**Comment by aichinuomifan** [comment]
亲测更新到1.55版就好了

**Comment by Neil-2322** [comment]
> 只能等大佬更新了

已经更新了

https://lyrics.run/my-tv.html

**Comment by Guancheng-Li** [comment]
两个小米盒子，3s用1.55没问题，4c用1.55有问题，都是android6.0(ATV)

**Comment by AidenLee1994** [comment]
检查一下系统时间是不是对的，没校准前只能看一个频道
