### ISSUE TITLE
电视盒子开机系统时间混乱

### ISSUE THREAD

**Issue by AidenLee1994** [lizongying/my-tv#257]
可以让软件在开启时去更新系统时间么？

下面是用adb设置使用腾讯ntp服务器去解决的，能否让软件自动去执行
adb shell settings put global ntp_server time1.cloud.tencent.com
adb shell settings put global auto_time 1
adb shell settings put global auto_time_zone 1
adb shell am broadcast -a android.intent.action.BOOT_COMPLETED

此外，可以给软件提供开机自启的设置么？

**Comment by lizongying** [comment]
上面的操作，可能没有权限。
最新版本解决了时间问题。
关于开机自启 #89
