### ISSUE TITLE
黑屏问题

### ISSUE THREAD

**Issue by yiqiuery** [lizongying/my-tv#259]
飞利浦电视安卓版本4.3，昨天安装的1.4几来着，昨天晚上正常观看一个小时以后黑屏，今天安装了1.52依旧无法播放

**Comment by 871052165** [comment]
> 我也是一样的

小米电视5S

**Comment by Guancheng-Li** [comment]
小米盒子4c 1.55&1.52同

**Comment by 871052165** [comment]
> 小米盒子4c 1.55&1.52同，android 6.0，伪原生安卓系统（官方系统加google framework和leanback launcher魔改版） 小米盒子3s 1.55没问题，android6.0，纯原生系统

我下载了最新的版本，正常了

**Comment by yuxianggangnoob** [comment]
> > 小米盒子4c 1.55&1.52同，android 6.0，伪原生安卓系统（官方系统加google framework和leanback launcher魔改版） 小米盒子3s 1.55没问题，android6.0，纯原生系统
> 
> 我下载了最新的版本，正常了

我下载的1.5.3,还是黑屏的,你用是啥版本?
