### ISSUE TITLE
凤凰卫视官方直播地址，建议大佬采用。

### ISSUE THREAD

**Issue by sz20000** [lizongying/my-tv#260]
https://www.fengshows.com/hongkongv/

也可以下载  凤凰秀 app  内地可以流畅看直播。

**Comment by sz20000** [comment]
打开网址需要科学。但是下载 app 后不用科学可以流畅播放。打开 app 不用科学。

**Comment by sz20000** [comment]
顶！

**Comment by lizongying** [comment]
会考虑
