### ISSUE TITLE
版本号太乱

### ISSUE THREAD

**Issue by jiutian956** [lizongying/my-tv#261]
版本号能不能按顺序放有时候分不清哪个是高版本哪个是低版本

**Comment by liigo** [comment]
同问，通用版和专版是怎么定义的，我该选哪一个？

**Comment by Dragon-GCS** [comment]
通用就是所有安卓版本都能用，专版就是安卓大于5.0的系统用的。release页面每个版本都有说明，数字越大版本越高

**Comment by Guancheng-Li** [comment]
现在看起来偶数是通用版，奇数是高安卓版本

**Comment by shengdao001** [comment]
通用版是安卓4.2及以上使用的，太低也不行

**Comment by zbby1987** [comment]
确实是乱

**Comment by Guancheng-Li** [comment]
> 确实是乱，
> 
> 应该是
> 
> v1.6.0_api21(安卓5～14)
> 
> v1.6.0_api17(安卓4.2～14)
> 
> 
> 
> 用同一个版本号+差异化的尾标来区分！
> 
> 

Linux的稳定版和测试版了解下：）

**Comment by zbby1987** [comment]
> Linux的稳定版和测试版了解下：）

了解不出来

**Comment by lizongying** [comment]
參考 @Guancheng-Li 

> 现在看起来偶数是通用版，奇数是高安卓版本

實際上功能可能不一樣，單純加後綴可能也不太合適。暫時先這麼輪著更新了。
