### ISSUE TITLE
手机切换频道很麻烦

### ISSUE THREAD

**Issue by ghost** [lizongying/my-tv#263]
1), 手机安装app后,,切换频道界面在左右滑动过程中,容易消失
2), 建议在app界面添加切换频道的按钮,比如音量键是切换频道或者左右滑动是切换频道
3), 可以增加<<chc电影频道>>吗😁

**Comment by zm47726151** [comment]
上下滑很麻烦么？

**Comment by Fengshaoyuan** [comment]
滑动的时候频道号显示异常、没更新 @lizongying 看到相关issue，没开新坑

**Comment by lizongying** [comment]
@ghost 有机会会优化下手机操作，暂时可能没时间。
现阶段上下滑动是切换频道。
