### ISSUE TITLE
#建议增加一个自定义直播源的功能

### ISSUE THREAD

**Issue by muxinmufei** [lizongying/my-tv#265]
可否增加一个自定义直播源的功能，不然一旦直播源没了就完了，只能依赖等着升级更新最新版本了

**Comment by qiuhaotc** [comment]
那你就用kodi + 直播源呗

**Comment by kamkdd** [comment]
> 那你就用kodi + 直播源呗

我非常不明白，这年头还有人推荐kodi 看直播的，首先tvobx、diyp等看直播自定义直播源比kodi 好操作一万倍

**Comment by ashsteins** [comment]
支持

**Comment by zm47726151** [comment]
有好的直播源分享出来嘛！

**Comment by lizongying** [comment]
#532
