### ISSUE TITLE
恭喜登顶GitHub trending榜！

### ISSUE THREAD

**Issue by masterzht** [lizongying/my-tv#266]
软件做的很好，真正的做到了面向用户编程，非常简洁人性化，不然也不会受这么多用户喜爱。提三个建议吧，可以规避些潜在的大陆审查风险。
1.节目源还可以进一步精简
2.不开放自定义源功能
3.不开放回看功能

**Comment by shengdao001** [comment]
恭喜恭喜

**Comment by ashsteins** [comment]
恭喜

**Comment by windboot** [comment]
恭喜登榜

**Comment by h0we** [comment]
恭喜登榜

**Comment by whtk** [comment]
人心所向

**Comment by Josephleo147** [comment]
恭喜恭喜

**Comment by sz20000** [comment]
深圳发来贺电！

**Comment by zbby1987** [comment]
> 1.节目源还可以进一步精简 2.不开放自定义源功能 3.不开放回看功能

你怎么不让他放弃反编译破解高清地址，
只播放免费开放的720p视频呢？

甚至去完善已有的无图视频浏览器，直接播放官网直播网页呢，
这肯定能过审

**Comment by 01super** [comment]
重庆发来贺电！

**Comment by yxhy1010** [comment]
非常棒的软件，一直喜欢！

**Comment by lizongying** [comment]
@masterzht 無論程度如何，已經影響了部分人的利益。剩下的就是時間和大家的訴求了。
已經感覺到自己被推著走了。
1 肯定會加，儘量精簡
2 看情況，至少這個項目不會
3 嘗試抵制，應該不會加入

**Comment by lfm09** [comment]
自定义源功能才是最需要的

**Comment by jackson-xp** [comment]
恭喜！
