### ISSUE TITLE
什么时候可以支持cctv5+ 凤凰卫视这种频道啊

### ISSUE THREAD

**Issue by ctgushiwei** [lizongying/my-tv#268]

**Comment by shengdao001** [comment]
cctv5+不是已经有了吗，凤凰卫视这得看作者用哪个源了，目前这个源还没有

**Comment by Audioboat** [comment]
CCTY5和5+都沒有图像，也没有音频。

**Comment by shengdao001** [comment]
> CCTY5和5+都沒有图像，也没有音频。

那为啥我有啊？

**Comment by AItext1** [comment]
> > CCTY5和5+都沒有图像，也没有音频。
> 
> 那为啥我有啊？

我这也看不了

**Comment by shengdao001** [comment]
> > > CCTY5和5+都有图像，也没有音频。
> > 
> > 
> > 那为什么我有啊？
> 
> 我这也看不了

![Uploading Screenshot_20240206_134515_com.lizongying.mytv.jpg…]()

**Comment by shengdao001** [comment]
![Screenshot_20240206_134515_com lizongying mytv](https://github.com/lizongying/my-tv/assets/92067239/9784a014-1eac-4e6f-affa-5d765a23ee82)

**Comment by shengdao001** [comment]
我这还是能看

**Comment by 15554041980** [comment]
他这个源好像没有ipv4和v6的区别吧，都能用
