### ISSUE TITLE
部分央视能否用IPV4源

### ISSUE THREAD

**Issue by renjianxiaopihong** [lizongying/my-tv#27]
已试用1.2.8，已经是目前最好用的电视应用了，能给央视频拿下属实🐮🍺，但部分央视频道用的IPV6的源看不了，希望有空能替换掉

**Comment by lizongying** [comment]
解决中。

**Comment by Yvonne0827** [comment]
@lizongying 是我目前用过的所有IPTV中换台最快的，最丝滑的，想替你宣传，又怕被端掉，哈哈

**Comment by fhzjgd** [comment]
> 解决中。

央视3，6，8还是不行，电信的网络。

**Comment by chenxudong2020** [comment]
> > 解决中。
> 
> 央视3，6，8还是不行，电信的网络。

我的可以 估计你没ipv6吧

**Comment by lizongying** [comment]
和ipv6没有关系。移动的iptv对于从其他网络访问会有限制，表现就是黑屏、卡等，另外一个问题就是有画面没声音，这是因为部分设备不支持移动iptv的声音格式，表现就是部分设备有声音，部分设备没声音。这个也能解决，但没必要。因为iptv始终对不同网络会有限制，所以即使解决没什么意义。
我已经不用这种方式了，大家可以用最新版本体验下。

**Comment by kyriej** [comment]
没用过央视频，央视频源竟然这么丝滑

**Comment by kyriej** [comment]
大神太牛了，收下他们的膝盖吧
