### ISSUE TITLE
1.4.2安卓4打开黑屏，昨天开始没信号

### ISSUE THREAD

**Issue by xzhan6004** [lizongying/my-tv#270]

**Comment by Orange5722** [comment]
1.5.3在电视上打开也没信号，能正常换台，但是所有频道都是黑屏（捂脸），从源码里找到了直播链接可以直接看，同问以上问题，谢谢大神

**Comment by dyccsxg** [comment]
最新的1.5.5可以正常观看

**Comment by xzhan6004** [comment]
> 最新的1.5.5可以正常观看

1.5.5安不上去，安了闪退

**Comment by Goodboy-dai** [comment]
> 1.5.3在电视上打开也没信号，能正常换台，但是所有频道都是黑屏（捂脸），从源码里找到了直播链接有的可以直接看，电视上就是黑屏。故同问以上问题，谢谢大佬
> 
> 

我是校正电视系统时间解决的，看看你电视时间对不对

**Comment by shengdao001** [comment]
> > 最新的1.5.5可以正常观看
> 
> 1.5.5安不上去，安了闪退

安装通用版1.5.2

**Comment by canterburyell** [comment]
1.58安装后，也是黑屏

**Comment by lizongying** [comment]
最新版
