### ISSUE TITLE
软件外观上可否进行改善？

### ISSUE THREAD

**Issue by Hopelsz** [lizongying/my-tv#271]
软件使用上一切正常，美中不足就是app图标有点难看了，还有电视台列表展示方式不太适应。一切都是个人观点

**Comment by xzhan6004** [comment]
能让软件适配广稳定都是问题，哪来的时间去考虑界面

**Comment by whtk** [comment]
一且要低调。。

**Comment by sephony** [comment]
想要好的界面可以自己提PR，作者精力也有限，能把视频源处理好稳定播放就很不错了

> 软件使用上一切正常，美中不足就是app图标有点难看了，还有电视台列表展示方式不太适应。一切都是个人观点

**Comment by lizongying** [comment]
功能的问题还有很多，暂时先不考虑图标。
