### ISSUE TITLE
黑屏问题 无信号问题

### ISSUE THREAD

**Issue by qjh04** [lizongying/my-tv#272]
大家安装最新版就可以了

**Comment by xzhan6004** [comment]
安卓低版本只能安1.4.2

**Comment by Goodboy-dai** [comment]
我的也是，T95电视盒，看电视过程中直接断电，然后重新打开不管看哪个台都是黑屏

**Comment by Goodboy-dai** [comment]
我之前也是，后来发现自己电视时间不对，校正电视时间后就正常播放了，大家可以看看自己电视时间对不对

**Comment by vanniszsu** [comment]
1.5.1 有同样的问题，且电视时间正确，安卓系统时间都是NTP自动校对的，不可能出现大的偏移

**Comment by shengdao001** [comment]
> 安卓低版本只能安1.4.2

安装最新通用版1..5.2，通用版是支持安卓4.2及以上的

**Comment by xiaoliwe** [comment]
> 我之前也是，后来发现自己电视时间不对，校正电视时间后就正常播放了，大家可以看看自己电视时间对不对

电视时间与本机电脑相差1分钟,会有影响？
