### ISSUE TITLE
native.c文件缺失

### ISSUE THREAD

**Issue by wj071842154** [lizongying/my-tv#278]
native.c文件缺失

**Comment by 2926295173** [comment]
请直接使用 ./gradlew assembleRelease -PIS_SO_BUILD=false

so中涉及加密，不便提供 #34

**Comment by skusdk** [comment]
PIS_SO_BUILD=false
我本地运行
cKey =  encryptor!!.encrypt(cnlid, timeStr, appVer, guid, platform)
signature = getSignature()
一个加密，一个hash都是null，这是为啥

**Comment by EightDoor** [comment]
@skusdk 自己在网站做js逆向吧  不是太难，实测可以成功。native.c缺少3个方法的encrypt（AES加密 关键是key、iv参数）、hash（md5） 可以不播放不需要鉴权的视频。剩下得自己研究下吧
