### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by Kroeseir** [lizongying/my-tv#279]
![Screenshot_2024-02-06-19-03-34-76_cfdca73bf31d290416a54475c98e7f2b](https://github.com/lizongying/my-tv/assets/125105720/706f8baa-1df2-4b19-a666-cbb8757b9435)
只能播放cgtn纪录频道，菜单有当前播放节目名

**Comment by CoderHRXu** [comment]
查看一下电视机的系统时间，时间不对https请求发不通。

**Comment by lizongying** [comment]
在新的版本裡對時間做了處理，有興趣的可以去看一下。
