### ISSUE TITLE
报错“应用未安装”

### ISSUE THREAD

**Issue by sakura-3** [lizongying/my-tv#283]
系统是安卓4.4.3，通过U盘安装v1.5.5，v1.5.2，v1.4.2，点击安装后提示“应用未安装”，但是v1.5.2版本在我的手机（鸿蒙OS 4.14.116）上是可以用的

**Comment by zbby1987** [comment]
文件结尾必须是小写的.apk

**Comment by sakura-3** [comment]
文件名确定和release名一致

**Comment by finviman** [comment]
我是android4.2.2, 也是同样错误
