### ISSUE TITLE
编译错误问题

### ISSUE THREAD

**Issue by nuaa-wwbin** [lizongying/my-tv#288]
你好，我在M2 based macbook pro上编译这个项目APP时，遇到这个错误，能指导我一些怎么解决这个问题吗？

-- The C compiler identification is AppleClang 15.0.0.15000040
-- The CXX compiler identification is AppleClang 15.0.0.15000040
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.5s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
log-lib
    linked by target "nothing" in directory /Users/xxxx/xx/projects/my-tv/app

-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

又或者能给一个解释编译依赖和工具的REAMDE吗？希望能够得到您的帮忙，谢谢

**Comment by nuaa-wwbin** [comment]
非常感谢，这个问题我或许知道什么原因了，原谅我不是一个android开发者，没有这方面的经验，正在使用新的新的自动化编译工具进行编译，如果有遇到问题再来请教 谢谢

**Comment by lizongying** [comment]
暫不支持直接編譯，有一個文件我沒有上傳。
