### ISSUE TITLE
多数频道黑屏

### ISSUE THREAD

**Issue by zjy208723** [lizongying/my-tv#289]
看了一天又黑了，软件太火了，一个版本看不了三天

**Comment by shuohao** [comment]
今天上午看的时候还挺好 刚打开大部分都黑了

**Comment by sbkk000** [comment]
央视的经常黑屏

**Comment by CJyoung524** [comment]
大多数央视频道黑了

**Comment by daguGit** [comment]
很奇怪，好几次都是晚上失效

**Comment by AdeSpike** [comment]
央视多数频道黑屏，只有CCTV6和CCTV11能看，其他全部黑屏。地方台可以看的还比较多，但也有偶尔几个台黑屏。国际频道全部黑屏

**Comment by lizongying** [comment]
我過於自信了，以為很穩定，為了大家使用更流暢，就去掉了備用源（IPTV）。 下次會加入備用源，但是可能一些人會看不了，只能做到這些了。
