### ISSUE TITLE
感谢作者，能否做一下Android4.x版本的兼容

### ISSUE THREAD

**Issue by whitoad** [lizongying/my-tv#29]
从知乎推荐而来。非常感谢作者，质量超高的软件，在同好群里评价极高。不知有没有可能做下安卓低版本的兼容，造福一下低系统版本的用户？群里许多用户有此类诉求。

**Comment by lizongying** [comment]
在安排了，在等安卓4的盒子到位。

**Comment by zbby1987** [comment]
从工具里看，已经支持到安卓4.2了啊！

**Comment by lizongying** [comment]
@zbby1987 所以得看下安卓4闪退的具体原因，一定会解决的。

**Comment by DaGuoZhang** [comment]
照理说anroid 4.3应该支持，安装是可以装上，icon也能看到的，但打开就是闪退，不知道原因。

**Comment by hzjnet** [comment]
确实能安装 使用闪退

**Comment by lizongying** [comment]
不用试了，现在不支持。已在计划中。

**Comment by lizongying** [comment]
请安装[1.4.2](https://github.com/lizongying/my-tv/releases/tag/v1.4.2)

**Comment by hzjnet** [comment]
> 请安装[1.4.2](https://github.com/lizongying/my-tv/releases/tag/v1.4.2)

4.4.2的3798v100能正常播放了
