### ISSUE TITLE
安装首次可以打开有信号，关闭重开后黑屏无信号

### ISSUE THREAD

**Issue by FeyWAnGG** [lizongying/my-tv#291]
安装首次可以打开有信号，关闭重开后黑屏无信号。遇到两次了，第一次安装1.5通用版本时候遇到，后面放着没管了，这次更新了1.54通用版又是，刚安装好后打开没问题，关闭一阵重开就黑屏无信号，和1.5当时情况一致。后面再怎么卸载重装都不行了。

**Comment by ni7ht** [comment]
我也是测试哪个版本播放不卡住的时候，发现现在安装哪个版本都黑屏了……可能是信号源问题

**Comment by FeyWAnGG** [comment]
我从网上搜到了答案，是有些盒子的系统时间有问题，导致刚开机时间错误，只要时间不对，就无法播放，后面有些盒子会自动对时，等时间正常了，就可以正常播放了
