### ISSUE TITLE
央视都没了么？

### ISSUE THREAD

**Issue by forkman24** [lizongying/my-tv#293]
1.5.5版本，打开后没有央视，是我打开方式不对么？

**Comment by AccountGc** [comment]
x现在央视的都没有

**Comment by 89333367** [comment]
使用1.5.4版本，这个版本没问题

**Comment by shengdao001** [comment]
> 1.5.5版本，打开后没有央视，是我打开方式不对么？

使用最新版本，作者已经发布了

**Comment by jeff-sun** [comment]
为啥不搞个应用内升级？

**Comment by alanfans** [comment]
1.5.7好了

**Comment by ccav14** [comment]
> 为啥不搞个应用内升级？

要不阁下赞助一下？

**Comment by forkman24** [comment]
好嘞，下载1.5.4中

**Comment by SuperSkidder** [comment]
> > 为啥不搞个应用内升级？
> 
> 要不阁下赞助一下服务器？

可以用github

**Comment by qiuzhangsaer** [comment]
这是版本获取接口，可以根据created_at获取最新版本，然后下载browser_download_url获取安装包，下的慢前面可以拼个ghproxy的代理，我只能给到这了，术业有专攻，我不是搞安卓的不会整 [https://[api.github.com/repos/lizongying/my-tv/releases](https://api.github.com/repos/lizongying/my-tv/releases)](https://[api.github.com/repos/lizongying/my-tv/releases](https://api.github.com/repos/lizongying/my-tv/releases))

**Comment by lizongying** [comment]
在做在線升級了。
