### ISSUE TITLE
请问怎么看系统版本？

### ISSUE THREAD

**Issue by tommyonsn** [lizongying/my-tv#294]
是“版本”还是“内核版本”啊？
我的索尼电视显示版本是7.0，但是内核版本是3.0
按哪个算呢？

**Comment by Longma-1** [comment]
> 是“版本”还是“内核版本”啊？ 我的索尼电视显示版本是7.0，但是内核版本是3.0 按哪个算呢？

你是说安装这个软件需要看的版本号吗？根据你说的版本7.0，应该就是基于安卓7.0系统，可以安装的。

**Comment by lizongying** [comment]
安卓版本，不清楚的最好查下網絡。
