### ISSUE TITLE
可不可以搞个应用内升级？

### ISSUE THREAD

**Issue by Y-sir** [lizongying/my-tv#295]
可不可以搞个应用内升级？
毕竟在小米盒子里面安装需要提前下载到u盘，挺麻烦的 @lizongying

**Comment by leauny** [comment]
@lylelau 默认用github下载，支持自定义加速链接不就可以了

**Comment by lylelau** [comment]
@leauny 可以，那你来，作者源码不是在拿

**Comment by leauny** [comment]
> @leauny 可以，那你来，作者源码不是在拿

你脾气怎么那么大，我不会才来给点建议，你这种回复对项目没有任何积极作用。别把臭脾气带到这上面。

**Comment by superiorlu** [comment]
可以通过adb远程来安装：
> 前提：电脑和电视连同一个wifi, 需要打开电视的adb调试功能，小米电视在设置 -> 账号与安全 -> ADB调试

1. adb connect 电视ip （ip从网络设置连接的wifi中查看）例如：
```sh
adb connect 192.168.0.4
```
第一次电视会出现一个调试授权弹窗，点击确认即可。

2. 安装apk包:
```sh
adb install  my-tv-v1.5.6.apk
```
等待一会看到 `Success`，就说明升级成功了。
