### ISSUE TITLE
能否添加自动更新

### ISSUE THREAD

**Issue by Mr-tang0** [lizongying/my-tv#297]
每次都只能下载到u盘更新，挺麻烦的

**Comment by LLeavesG** [comment]
支持！

**Comment by hange2011** [comment]
支持+1

**Comment by bxwqsbkl** [comment]
支持9999w+

**Comment by lylelau** [comment]
@bxwqsbkl 精神支持666谁不会？想自动更新你倒是赞赏啊一百不嫌多一块不嫌少，服务器不用钱啊？

**Comment by 70975924** [comment]
不建议，会自动更新只会用的人越来越多，软件没的越来越快，不愿意折腾的不要用，恰好过滤一部分人，能让软件更长久的活下去

**Comment by sunnysu0608** [comment]
> 每次都只能下载到u盘更新，挺麻烦的

说得好

**Comment by qiuzhangsaer** [comment]
这是版本获取接口，可以根据created_at获取最新版本，然后下载browser_download_url获取安装包，下的慢前面可以拼个ghproxy的代理，我只能给到这了，术业有专攻，我不是搞安卓的不会整 https://api.github.com/repos/lizongying/my-tv/releases

**Comment by lizongying** [comment]
@qiuzhangsaer 主要是網路問題，這確實是一個比較好的方式。
在做更新了，請大家先等待下。
