### ISSUE TITLE
建议出一个只能加自定义源的app

### ISSUE THREAD

**Issue by lishengwei** [lizongying/my-tv#298]
看了好多issues，里面好多都是反馈要么打不开，要么想要别的频道，作者能否出一个只能添加自定义源的app呢？也即一个空壳的App，这样精力不用放在处理直播源上。

**Comment by ccav14** [comment]
自定义源我为何不用别的更成熟的app？

**Comment by bxwqsbkl** [comment]
> 自定义源我为何不用别的更成熟的套壳app？

如果你有稳定好用的，可以分享到这里，谢谢大佬

**Comment by ashsteins** [comment]
别推荐diyp了，很垃圾，万年不更新的壳子

**Comment by ashsteins** [comment]
建议推荐tivimate，对m3u很友好

**Comment by lylelau** [comment]
你都说是个壳子，TVbox还两年不更新了呢 @ashsteins

**Comment by lylelau** [comment]
空壳不是一大堆为什么就要揪着这个不放？ @lishengwei

**Comment by ui1840** [comment]
> 空壳不是一大堆为什么就要揪着这个不放？ @lishengwei

内置源和自定义源又不冲突的，你这气急败坏的是啥想法这是，
这几天的多次更新，不就是内置源的问题吗？
如果可以自定义的话，作者不用花费大量无谓的精力去维护内置源，而用户也可以自己找自己可用的稳定源，这完全就是个双赢的结果啊，为啥你会这么的不乐意？
现在的壳最好的就是diyp，可支持低android版本，功能支持也多，但是已经不更新了，
像现在大量的v6源，diyp添加后就不能播放，实在可惜，
综上，以diyp为目标的app，才是作者最佳的目标方向，这样作者的精力可以完全放在功能的开发上，节目源则完全可以让用户自己去自行设置，自行负责源的质量，

**Comment by ashsteins** [comment]
> > 空壳不是一大堆为什么就要揪着这个不放？ @lishengwei
> 
> 内置源和自定义源又不冲突的，你这气急败坏的是啥想法这是， 这几天的多次更新，不就是内置源的问题吗？ 如果可以自定义的话，作者不用花费大量无谓的精力去维护内置源，而用户也可以自己找自己可用的稳定源，这完全就是个双赢的结果啊，为啥你会这么的不乐意？ 现在的壳最好的就是diyp，可支持低android版本，功能支持也多，但是已经不更新了， 像现在大量的v6源，diyp添加后就不能播放，实在可惜， 综上，以diyp为目标的app，才是作者最佳的目标方向，这样作者的精力可以完全放在功能的开发上，节目源则完全可以让用户自己去自行设置，自行负责源的质量，

这人就是个rz，不用管他，他想不明白的

**Comment by maplewang** [comment]
自定义源好处多多，比如美国就有一些大大小小的网络公司，挺多过的电视源就是放不了，自定义源好处就在于可以自行删除添加源，作者也不用为了源发行新版本。

**Comment by AppleMate60pro** [comment]
@ui1840 既然都要用壳自定义源了，为什么还要用这个呢？

**Comment by AppleMate60pro** [comment]
@maplewang 那直接用可自定义源的壳不就行了？又不是没有空壳

**Comment by AppleMate60pro** [comment]
> > 空壳不是一大堆为什么就要揪着这个不放？ @lishengwei
> 
> 内置源和自定义源又不冲突的，你这气急败坏的是啥想法这是， 这几天的多次更新，不就是内置源的问题吗？ 如果可以自定义的话，作者不用花费大量无谓的精力去维护内置源，而用户也可以自己找自己可用的稳定源，这完全就是个双赢的结果啊，为啥你会这么的不乐意？ 现在的壳最好的就是diyp，可支持低android版本，功能支持也多，但是已经不更新了， 像现在大量的v6源，diyp添加后就不能播放，实在可惜， 综上，以diyp为目标的app，才是作者最佳的目标方向，这样作者的精力可以完全放在功能的开发上，节目源则完全可以让用户自己去自行设置，自行负责源的质量，

出这个不就是为了简单看电视吗？你都知道diyp可自定义源，就用不就行了，要功能也还有其他的壳子

**Comment by AppleMate60pro** [comment]
> [ashsteins](/ashsteins)

你本就是个智障，白嫖惯了什么都想往死里薅

**Comment by kennylbj** [comment]
很难想象楼上这种初升东夕存在这个世上的意义是什么

**Comment by AppleMate60pro** [comment]
> 很难想象楼上这种初升东夕存在这个世上的意义是什么

为的就是你看见了还不能怎么样，看你气急败坏的样子就更像是畜生

**Comment by lishengwei** [comment]
本来就是大家讨论讨论，探讨一下需求，无非就是希望项目做的更好，结果issue里变成人身攻击，[AppleMate60pro](https://github.com/AppleMate60pro) 你戾气太重。你这种人的存在，是社区气氛变坏的主要原因。
