### ISSUE TITLE
1.5.7是支持服务器更新channelList吗

### ISSUE THREAD

**Issue by yuanjianchun** [lizongying/my-tv#300]
代码有了，功能是上线了吗

**Comment by tommyonsn** [comment]
> 阁下不赞助一点？

小红书来的？

**Comment by lizongying** [comment]
@lylelau 感謝支持
在這裡也希望大家不要主動提讚賞的問題了，這是自願行為，如果施加言語壓力，我想這就背離了我們的初心。
甚至會影響我的電視的使用感受，不想看到這樣。
