### ISSUE TITLE
我建议软件内部集成一个直播源网址，gitee也可以的

### ISSUE THREAD

**Issue by sunnysu0608** [lizongying/my-tv#305]
这样以后只要软件没问题，只要后台作者一人维护就可以了，我们不用每次都要重新安装

**Comment by CJyoung524** [comment]
不考虑gitee官方会给封吗？gitee不是github

**Comment by SimonFuInSky** [comment]
你放在国内的地址绝对被封的，github大部分地区又访问不了

**Comment by netcccyun** [comment]
github有镜像地址的，国内访问是没问题，没必要用gitee

**Comment by NOTF-API** [comment]
我看了一些源码，并不是简单的直播源，是需要经过一定加解密的，所以直播源不是固定的。所以意义不大，实现难度高。

**Comment by prettyboyweiwei** [comment]
做成有软件更新二话不说直接弹窗提示安装应该对家里人有用吧

**Comment by lalasou** [comment]
目前这个是换台速度最快的app   不知道如果自定义播放源还能不能 这么快 
如果能自定义播放源 还能这么快无敌了


ps（可以后台检测播放源 自动换最快的源）

**Comment by lizongying** [comment]
#532
