### ISSUE TITLE
希望大家能多一份理解，作者大佬很辛苦！

### ISSUE THREAD

**Issue by CJyoung524** [lizongying/my-tv#308]
昨天晚上软件失效，大佬**凌晨三点**还在改代码，提交1.5.7最新版本，真心感谢，为很多普通老百姓谋福利！
大家可以在能力范围之内打赏点钱，你1块我1块钱不多，汇聚在一起就是My-Tv能继续走下去的能量！

随着软件传播的越普遍，可以预料到会有很多issue，还是希望大家多提一些有建设性的issue，有些非代码bug相关的issue提完之后可以自己手动的close掉，避免每次还需要作者去close，影响软件开发的时间精力！还有就是大家提issue的时候，先去看code里作者的ToDo，我看现在提的好几个都是已经在ToDo里面，不需要重复提了！

多一份理解，多一份支持，开源软件开发不易！

**Comment by Damonxy** [comment]
我有点好奇失效的原因是什么，马上过年事情比较多，没时间把代码过一遍，后面有问题大家一起解决就不用自己这么辛苦了。

**Comment by tuobahao** [comment]
建议适当收费。

**Comment by SummerWindL** [comment]
支持建议适当收费

**Comment by alexmao78** [comment]
一旦收费后，网上那些喷子们就又要开始作了

**Comment by ChicFoster** [comment]
可以开一个打赏渠道，毕竟为大家辛苦的

**Comment by CJyoung524** [comment]
> 可以开一个打赏渠道，毕竟为大家辛苦的

https://lyrics.run/my-tv.html 这里就是my-tv的主页，有大佬的收款码

**Comment by lizongying** [comment]
不會收費！
