### ISSUE TITLE
这个是用什么语言写的？

### ISSUE THREAD

**Issue by Y-sir** [lizongying/my-tv#309]
本人是java，发现没见过这种源码文件呢

**Comment by shengdao001** [comment]
C语言

**Comment by hele204** [comment]
kotlin啊

**Comment by Y-sir** [comment]
> kotlin啊

@shengdao001 到底是哪个

**Comment by shengdao001** [comment]
![捕获](https://github.com/lizongying/my-tv/assets/92067239/ea4cbb10-b3ca-4042-8d35-537d08cbe45e)

**Comment by shengdao001** [comment]
> > 科特林啊
> 
![捕获](https://github.com/lizongying/my-tv/assets/92067239/69a7e9ab-e43b-4cd0-be71-9d279ec22281)

> @shengdao001到底是哪个

**Comment by shengdao001** [comment]
> > 科特林啊
> 
> @shengdao001到底是哪个

![捕获](https://github.com/lizongying/my-tv/assets/92067239/f7fab14f-ab1b-4409-a652-9c260af7d47d)

**Comment by shengdao001** [comment]
> > 科特林啊
> 
> @shengdao001到底是哪个

这俩都有，但C语言更多

**Comment by lizongying** [comment]
这个项目才用的kotlin，还是挺好的，感觉比java更易写
