### ISSUE TITLE
关于菜单键调出页面的建议

### ISSUE THREAD

**Issue by johnnyeecker** [lizongying/my-tv#311]
作者你好，这软件很好用。简洁，快捷，清晰。希望持久。
因为是老式遥控器没有菜单键（Sony），导致无法设置那个反转上下方向键的功能。折腾半天用各种app也调不出来那个按菜单键出来的菜单。所以有个小建议，能否按返回键一次时（按两次还是直接退出挺好），可以呼出菜单，然后选择进入设置。
谢谢。

**Comment by Y-sir** [comment]
换遥控器试试呢

**Comment by lizongying** [comment]
能不能把遙控器的圖片發一張？我加到其他按鍵上。現在收藏、幫助、設置、菜單都可以呼出設置。

**Comment by johnnyeecker** [comment]
> 能不能把遙控器的圖片發一張？我加到其他按鍵上。現在收藏、幫助、設置、菜單都可以呼出設置。

作者你好,感谢关注和回复.
![remote controller](https://github.com/lizongying/my-tv/assets/47209206/c0314479-5c4a-4aec-bafa-e93760015269)
根据你的提示,我按了遥控器上的帮助键(这四个键中只有帮主键),但是会退出my tv并调用电视(sony)自己的帮助页面,而不能调出APP内的设置菜单.
谢谢.

**Comment by esme518** [comment]
现在新的Google TV都没有以前安卓TV遥控器的菜单按键了(变为了语音助手按键) 建议增加设置菜单入口
![image](https://github.com/lizongying/my-tv/assets/4252356/57edb35a-7db3-4328-9f13-352910647b31)

**Comment by niko8868** [comment]
同求，原生安卓tv没有菜单键，建议改成长按确认键或者在按确认键后的选单中加入虚拟按键

**Comment by lizongying** [comment]
1.7.3 遥控器左键进入节目列表，遥控器右键进入菜单
