### ISSUE TITLE
快过年了，我感觉加软件在线更新功能是大部分人的刚需

### ISSUE THREAD

**Issue by Y-sir** [lizongying/my-tv#312]
快过年了，我感觉加软件自动更新是大部分人的刚需，因为很多老年人看电视，可以加一个进入软件，检测自动更新的功能，对老年人也很友好的，毕竟卸载安装太费劲了

**Comment by ChicFoster** [comment]
太对了哥

**Comment by CJyoung524** [comment]
我觉得目前光维护更新源就需要很多时间，这个自更新的哪位有能力的自己写一个提PR吧

**Comment by brucelee2009** [comment]
+1, 失效太快了，不能自动更新的话，对老年人使用电视没什么用

**Comment by lylelau** [comment]
@Y-sir 阁下赞助一下肯定上自动更新

**Comment by CJyoung524** [comment]
还有自动更新有一个问题，怎么解决二手贩子倒卖问题？@Y-sir

**Comment by Y-sir** [comment]
> 还有自动更新有一个问题，怎么解决二手贩子倒卖问题？@Y-sir

@CJyoung524 倒卖这个问题，感觉不在正常使用软件体验之内

**Comment by YXCQU** [comment]
过年还更新啥，等着吧，提要求的记得把赞助记录附上

**Comment by ddxwhgithub** [comment]
快过年了，办事前提礼物上门是礼貌吧

**Comment by Longma-1** [comment]
自动更新，大家就基本用不了了。被F的快！！！

**Comment by lizongying** [comment]
在做

**Comment by AppleMate60pro** [comment]
> +1, 失效太快了，不能自动更新的话，对老年人使用电视没什么用

家里有宽带吧有网络吧，直接用iptv不就啥事没用
