### ISSUE TITLE
强烈要求有内置解码器可以切换  我用系统解码器看什么人都是蓝色的 

### ISSUE THREAD

**Issue by SuperBlackWednesday** [lizongying/my-tv#319]
也就是硬解像看鬼片一样  软解看人才正常   可以带个切换解码器功能吗？  好多软件都能切换解码器的

**Comment by zbby1987** [comment]
怎么判断出是调用系统播放器的？
exo或者media3的体积小，
ijk硬解+surface兼容性好，但体积有点大

**Comment by sunnysu0608** [comment]
> 怎么判断出是调用系统播放器的？
> 
> exo或者media3的体积小，但直播很少用它。
> 
> ijk硬解+surface兼容性好，但体积有点大

https://gitee.com/sangni2024/mingge/raw/master/1.txt这个直播源如何？

**Comment by SuperBlackWednesday** [comment]
例如   秒看HD  这个软件  里面有个解码设置   可以设置软解码 或者硬解码  我用硬解码 就是看人像鬼一样    必须要设置成软解码  我用的华为破解盒子  就是安装网线送的那种  硬解码是有问题的  其实好多电视软件都可以设置解码方式 但是他们没这个软件快

**Comment by zbby1987** [comment]
> 例如 秒看HD 这个软件 里面有个解码设置 可以设置软解码 或者硬解码 我用硬解码 就是看人像鬼一样 必须要设置成软解码 我用的华为破解盒子 就是安装网线送的那种 硬解码是有问题的 其实好多电视软件都可以设置解码方式 但是他们没这个软件快

有可能是你刷的系统把解码部分给阉割了，
你还是写出来具体硬件信息吧：
设备型号，
安卓系统版本，
ROM下载地址

**Comment by lizongying** [comment]
感謝建議。確實各種設備的解碼能力不同，軟解應該是最便捷的方式了，會加上。
