### ISSUE TITLE
Android TV OS 11无法使用

### ISSUE THREAD

**Issue by linzha0** [lizongying/my-tv#324]
你好，十分感谢你的开源软件。
我在北美地区，使用了Android TV OS 11, kernel version 4.19.116+, Android TV OS build RTT2.220118.001,
我依次安装了1.5.4~8，有电视列表，但是点进去都是黑屏。
希望能给些建议。感谢

**Comment by zbby1987** [comment]
https://www.123pan.com/s/9sRPjv-7HxVv.html

北美的电视安卓版本这么高么？
可以用这种浏览器从网页上流畅看么？

能看的话给个反馈，谢谢

**Comment by linzha0** [comment]
买的电视预装的就是OS11了，我试了下你给的app。
感谢建议，我试了。央视的基本都能看，画质好像不是很出彩。地方台不能看，显示网络未连接。

**Comment by zbby1987** [comment]
第一个中央一台，和地方台，都用的央视频。

第二个中央一台和后续的中央台都用的央视官网。


看来央视官网的视频线路在海外可用。


但央视频主要是针对国内用户的。

**Comment by xujijie** [comment]
slimbox系统也有这个问题，这个是一个atv系统的改版。

**Comment by zbby1987** [comment]
他主要是在北美的原因，和系统版本的关系不是很大



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月8日(周四) 上午10:30
收件人: ***@***.***&gt;;
***@***.***&gt;;
主题: Re: [lizongying/my-tv] Android TV OS 11无法使用 (Issue #324)




 
slimbox系统也有这个问题，这个是一个atv系统的改版。

**Comment by xujijie** [comment]
slimbox系统也有这个问题，这个是一个atv系统的改版，我是国内用户，网络上应该不存在问题，家里有两个盒子，其中一个可用，slimbox这个盒子就不可用，黑屏




> 他主要是在北美的原因，和系统版本的关系不是很大
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年2月8日(周四) 上午10:30 收件人: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [lizongying/my-tv] Android TV OS 11无法使用 (Issue #324) slimbox系统也有这个问题，这个是一个atv系统的改版。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

**Comment by zbby1987** [comment]
你是用的我发的链接，还是我的电视app？
我们讨论的是链接里的app。
我发的链接里的app没有黑屏这一说，尤其是slimbox这种atv改版，他们集成的webview版本不低，一般不会不能用。



---原始邮件---


 
slimbox系统也有这个问题，这个是一个atv系统的改版，我是国内用户，网络上应该不存在问题，家里有两个盒子，其中一个可用，slimbox这个盒子就不可用，黑屏
  
他主要是在北美的原因，和系统版本的关系不是很大
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年2月8日(周四) 上午10:30 收件人: @.&gt;; @.&gt;; 主题: Re: [lizongying/my-tv] Android TV OS 11无法使用 (Issue #324) slimbox系统也有这个问题，这个是一个atv系统的改版。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;

**Comment by xujijie** [comment]
> 你是用的我发的链接，还是我的电视app？ 我们讨论的是链接里的app。 我发的链接里的app没有黑屏这一说，尤其是slimbox这种atv改版，他们集成的webview版本不低，一般不会不能用。
> […](#)
> ---原始邮件--- slimbox系统也有这个问题，这个是一个atv系统的改版，我是国内用户，网络上应该不存在问题，家里有两个盒子，其中一个可用，slimbox这个盒子就不可用，黑屏 他主要是在北美的原因，和系统版本的关系不是很大 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年2月8日(周四) 上午10:30 收件人: @.&gt;; @.&gt;; 主题: Re: [lizongying/my-tv] Android TV OS 11无法使用 (Issue #324) slimbox系统也有这个问题，这个是一个atv系统的改版。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

抱歉，我说的是我的电视app的问题，没有注意到你后来发了链接。

**Comment by linzha0** [comment]
如果主要原因是我在海外,那就先关闭issue了
