### ISSUE TITLE
看加入了军团卫视，还剩吉林卫视 CETV系列  CHC家庭影院、CHC动作电影、CHC高清电影 这些台

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#326]
看加了军团卫视，还剩吉林卫视 CETV系列  CHC家庭影院、CHC动作电影、CHC高清电影 这些台

**Comment by ashsteins** [comment]
https://github.com/Meroser/IPTV
可以参考meroser 的源，他的源我用很久了，不错

**Comment by ashsteins** [comment]
央视高清/24个频道
CCTV-1 综合、CCTV-2 财经、CCTV-3 综艺、CCTV-4 中文国际、CCTV-5 体育、CCTV-5+ 体育赛事、CCTV-6 电影、CCTV-7 国防军事、CCTV-8 电视剧、CCTV-9 纪录、CCTV-10 科教、CCTV-11 戏曲、CCTV-12 社会与法、CCTV-13 新闻、CCTV-14 少儿、CCTV-15 音乐、CCTV-16 奥林匹克、CCTV-17 农业农村、CCTV-4K 超高清、CCTV-8K 超高清、CETV-1 综合教育、CETV-2 空中课堂、CETV-3 教育服务、CETV-4 职业教育
💿卫视高清/40个频道
高清： 湖南卫视、浙江卫视、东方卫视、北京卫视、江苏 卫视、安徽卫视、重庆卫视、东南卫视、甘肃卫视、广东卫视、广西卫视、贵州卫视、海南卫视、河北卫视、黑龙江卫视、河南卫视、湖北卫视、江西卫视、吉林卫视、辽宁卫视、山东卫视、深圳卫视、四川卫视、天津卫视、云南卫视、新疆卫视、三沙卫视
标清： 青海卫视、陕西卫视、山西卫视、西藏卫视、内蒙古卫视、宁夏卫视、兵团卫视、安多卫视、康巴卫视、大湾区卫视、农林卫视、延边卫视、厦门卫视
🎥数字高清/39个频道
CHC高清电影、CHC家庭影院、CHC动作电影、求索纪录、求索科学、求索动物、求索生活、黑莓电影、黑莓动画、哒啵电竞、哒啵赛事、乐游、纪实人文、纯享4K、风云剧场、风云音乐、第一剧场、女性时尚、 风云足球、兵器科技、怀旧剧场、世界地理、文化精品、央视台球、高尔夫网球、电视指南、都市剧场、金色学堂、哈哈炫动、游戏风云、欢笑剧场、第一财经、武术世界、文物宝库、梨园、天元围棋、弈坛春秋、劲爆体育
📽港澳台国际/18个频道
凤凰中文、凤凰资讯、凤凰香港、翡翠台、明珠台、J2、NHK World、CNA、AlJazeera、Arirang TV、RT News、RT Documentary、CGTN、CGTN Documentary、CGTN Français、CGTN Русский、CGTN Español、CGTN العربية

**Comment by lizongying** [comment]
已增加鳳凰衛視[v1.6.1](https://github.com/lizongying/my-tv/releases/tag/v1.6.1)
