### ISSUE TITLE
新年快乐，作者可不可以在app打开时加入自动筛选视频源正常的频道功能。

### ISSUE THREAD

**Issue by kpqn** [lizongying/my-tv#328]
新年过去马上又是老年人独自在家了。要是打开时app对应的台源失效了，老人可能就不知道该怎么办了，要是能加入自动筛选，把失效的频道去掉，显示能观看的频道这样就算部分源失效也有台可以看对老年人比较友好。

**Comment by lizongying** [comment]
暫時應該不會加入這個功能，一般如果源失效了，可能很大一部分或者全部都會有問題。
