### ISSUE TITLE
希望能自动更新和软件稳定

### ISSUE THREAD

**Issue by moxiaoweng** [lizongying/my-tv#333]
希望能自动更新，毕竟软件主要是父母再用，他们不懂这些，能保持资源正常使用即可

谢谢开发者了

**Comment by ZR010** [comment]
到是希望软件不要频繁更新，希望源能及时更新。在很多电视机上(如tcl)是无法更新非自带应用商店里的软件的。

**Comment by BruceHan98** [comment]
> 到是希望软件不要频繁更新，希望源能及时更新。在很多电视机上(如tcl)是无法更新非自带应用商店里的软件的。

应该说的是希望视频源能自动更新，而不是每次更换视频源都要重装软件

**Comment by lizongying** [comment]
#123
