### ISSUE TITLE
大佬能加点地方台吗？

### ISSUE THREAD

**Issue by wdyxsj** [lizongying/my-tv#335]
大佬软件太及时了，家里老人特别喜欢。这边是辽宁的，大佬有时间能加点辽宁地方台吗？

**Comment by kid88888** [comment]
地方台可以搞一个dtmb天线

**Comment by shengdao001** [comment]
> 大佬软件太及时了，家里老人特别喜欢。这边是辽宁的，大佬有时间能加点辽宁地方台吗？
这个问题别人已经问过了，大佬说以后尽量加上
![捕获](https://github.com/lizongying/my-tv/assets/92067239/66345b66-e81d-4353-95b8-eba378e6b61a)

**Comment by lizongying** [comment]
#431
