### ISSUE TITLE
请问大佬能不能搞一个在线更新的方法，每次黑屏都要重新下载安装包，而且更新频率有点快，太麻烦了

### ISSUE THREAD

**Issue by wuchunlong112** [lizongying/my-tv#336]
请问大佬能不能搞一个在线更新的方法，每次黑屏都要重新下载安装包，而且更新频率有点快，太麻烦了

**Comment by brucelee2009** [comment]
+1, 刚装上2天就不能用了

**Comment by shengdao001** [comment]
> 请问大佬能不能搞一个在线更新的方法，每次黑屏都要重新下载安装包，而且更新频率有点快，太麻烦了



> +1, 刚装上2天就不能用了

大佬不是说了吗，马上应该就有了

**Comment by zbby1987** [comment]
> 请问大佬能不能搞一个在线更新的方法，每次黑屏都要重新下载安装包，而且更新频率有点快，太麻烦了

去看下首页说明里写的to do

**Comment by lizongying** [comment]
#123
