### ISSUE TITLE
大佬，你赞赏码被封了

### ISSUE THREAD

**Issue by wildwinld** [lizongying/my-tv#337]
赏赞失败，提示账户异常，可通过支付微信公众号查看详情

**Comment by bazhijing** [comment]
一样，捐钱的时候提示不能给

**Comment by lizongying** [comment]
是被限制了。
微信这几天抽风，说是疑似赌博，限制部分交易。
无语了，这也太看不起赌博的人了。
已经申请了解禁。
感谢大家的热情，这两天打赏很多，很感激大家。
