### ISSUE TITLE
大佬能否出个电脑版的

### ISSUE THREAD

**Issue by wangtieying** [lizongying/my-tv#339]
电脑想看电视费点劲

**Comment by maopashui** [comment]
ipv6直播源随便播

**Comment by wangtieying** [comment]
> ipv6直播源随便播

但是感觉大佬这个真的是清晰，其他的直播源要不卡要不画质不好

**Comment by panweidesign** [comment]
电脑那么多软件 你要求有点多生怕大佬闲着

**Comment by Get4u** [comment]
我用BlueStacks 5安卓模拟器在电脑上看，挺好用
![未标题-1](https://github.com/lizongying/my-tv/assets/104744541/ee73b5af-1f36-4430-82fa-78ac8cd26cec)
![未标题-2](https://github.com/lizongying/my-tv/assets/104744541/2a91c7d9-f70b-4311-960a-6c41a1b04c9f)

**Comment by soberGou** [comment]
电脑支持安装安卓应用，https://www.zeppos.tech/t/topic/314

**Comment by lizongying** [comment]
暫無計劃
