### ISSUE TITLE
这个项目在编译的时候少一个  native 文件

### ISSUE THREAD

**Issue by aalj** [lizongying/my-tv#34]
如题。 该项目在编译的时候提示缺少文件， 这个文件能否上传一下呢   

src/main/cpp/native.c

**Comment by lizongying** [comment]
因为涉及到部分加密，不太好直接提供。你可以直接修改代码，把这部分的逻辑去掉。

**Comment by Ahuangshang** [comment]
我修改了这部分代码，但是请求接口提示签名失败

**Comment by aalj** [comment]
我也没解决，   如果有好的解决办法能分享一下吧 ， 万分感激 @Ahuangshang
