### ISSUE TITLE
在线更新😊

### ISSUE THREAD

**Issue by Master-Panda** [lizongying/my-tv#343]
在线更新确实很重要，如果让家里人自己手动更新，那太复杂了，在线更新就好很多了

**Comment by PANGPANGDigital** [comment]
同意，希望有一个在线更新功能，然后加一个App的图标icon就好了！

**Comment by shengdao001** [comment]
大佬已经说了，应该马上就有了
![捕获](https://github.com/lizongying/my-tv/assets/92067239/1a334ce1-4917-4708-ad8c-ea11a1635e13)

**Comment by lizongying** [comment]
#123
