### ISSUE TITLE
视频源是不是以中国大陆为主，台湾、北美是不是访问不到

### ISSUE THREAD

**Issue by soberGou** [lizongying/my-tv#344]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

咨询

**Comment by soberGou** [comment]
台湾的朋友安装后黑屏

**Comment by lizongying** [comment]
@soberGou 最新版本嗎？從之前的反饋來看，海外用戶體育台看不了，其他頻道應該是可以的。
另外，即使可以看，因為海外不一定有CDN分發，播放流暢度估計好不到哪去。

**Comment by soberGou** [comment]
@lizongying 感谢回复，如果不是网络问题，可能和安卓系统有关，问朋友了，还没回复我

**Comment by AItext1** [comment]
加拿大可以访问，而且很流畅。

**Comment by luwei15** [comment]
> @soberGou 最新版本嗎？從之前的反饋來看，海外用戶體育台看不了，其他頻道應該是可以的。 另外，即使可以看，因為海外不一定有CDN分發，播放流暢度估計好不到哪去。

美国。。一直更新一直追。。就没有能看过一次。。手机 机顶盒 电视 加window 11全试过去了

**Comment by youcannotseemeagain** [comment]
从代码看，电视台信源来自央视频，开发者似乎还冲了个vip贡献给大家用
