### ISSUE TITLE
[BUG] Fake-IP模式下所有频道都看不了

### ISSUE THREAD

**Issue by WFANG12719** [lizongying/my-tv#345]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

网络环境是代理的fake ip模式，所有频道都黑屏，没有任何图像、声音，也没有任何错误信息。

### 预期行为

全黑屏、无声，看不了，希望能在代理的fake ip环境里使用。

### 实际行为

app无法工作

### 复现步骤

在fake ip模式下，在安卓7的环境上装上最新版软件，不能使用，黑屏，无声，没有报错信息

### UI / OS

安卓7电视盒子，当贝桌面

### Android 版本

7

### 额外信息

fake IP的文档：【RFC】https://www.rfc-editor.org/rfc/rfc3089
代理环境的fake IP: https://blog.skk.moe/post/what-happend-to-dns-in-proxy/

**Comment by Amamiya23** [comment]
应该和fakeip 无关，你更新最新版1.58试试。我也开了openclash的fakeip增强模式，正常观看

**Comment by wayne0926** [comment]
我也是fakeip，也能正常观看

**Comment by WFANG12719** [comment]
假期仔细看了下码，是腾讯和阿里的公共DNS总是把dbiptv.sn.chinamobile.com解析到不可用的CDN节点了。将这个域名配置为用运营商的DNS解析就可以。确实与fake IP无关。
