### ISSUE TITLE
[BUG] 求助，cctv1-cctv4k，除了cctv6以外，全部黑屏，8k往后和地方台都正常

### ISSUE THREAD

**Issue by wangyips** [lizongying/my-tv#346]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

那天安装好后看了一会cctv1.几分钟后就突然黑屏了，往后到cctv4k都黑屏，从cctv8k开始和地方台都正常，这是咋回事？

### 预期行为

？

### 实际行为

？

### UI / OS

google TV

### Android 版本

12

**Comment by siteoj** [comment]
dd+1，而且6台有水印且画质模糊，希望修复，明天可以用来看春晚

**Comment by Coldprince98** [comment]
> 俺也一样

更新到1.5.8可以解决

**Comment by dajiagehaha** [comment]
俺也一样

**Comment by wgl1999** [comment]
俺也一样

**Comment by lizongying** [comment]
請試試最新版
