### ISSUE TITLE
[BUG] CCTV兵器科技频道音量比其他频道音量高很多

### ISSUE THREAD

**Issue by dairui2** [lizongying/my-tv#348]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

从其他频道切换到CCTV兵器科技频道，操作遥控器无论是下键到此频道，还是上键到此频道，音量都突然增大约两倍(音量的数值没变)，越过此频道后(切换到其他频道)，音量自动减小到正常。

### 预期行为

切换频道时，音量保持与电视机预设音量一致

### 实际行为

音量都突然增大约两倍(音量的数值没变)

### 复现步骤

step1，观看CCTV兵器科技频道之外的任意频道
step2，切换到CCTV兵器科技频道

### UI / OS

XIAOMI

### Android 版本

6.0

**Comment by lizongying** [comment]
最新版優化了，但我的電視已經暫時停止更新，有相關需求可以嘗試下 [我的電視·〇](https://github.com/lizongying/my-tv-0)
