### ISSUE TITLE
水一帖,作者及用户们过年好!

### ISSUE THREAD

**Issue by johnnyeecker** [lizongying/my-tv#350]
估计是作者担心耽误大家过年看电视,前几天改的很拼.感谢.
希望这个app能持久,不掺杂广告,不被盯上,就大家闷头享用:)
祝大家过年好!
![720](https://github.com/lizongying/my-tv/assets/47209206/c9f745e0-a863-4f57-8df1-9223029ed877)

**Comment by Lemonlee8** [comment]
1.5.8, 昨天还能看大部分cctv呢，今天打开，全黑屏了。。。。

**Comment by wuzhxyl** [comment]
好的啊， 就是过年别再更新了不能用..

**Comment by Lemonlee8** [comment]
刚试了一下，手机和平板可以用，盒子黑屏了，可能我盒子有问题。

**Comment by lizongying** [comment]
新春快樂
