### ISSUE TITLE
CCTV6突然就看不了了

### ISSUE THREAD

**Issue by darling02w** [lizongying/my-tv#355]
CCTV6突然就看不了了

**Comment by FrankCui-FengqiaoCui** [comment]
在我的TCL电视上似乎CCTV6黑屏，或者声音也没有，然后整个卡住:)

**Comment by CrazyZard** [comment]
me too 是不是源有问题

**Comment by darling02w** [comment]
我试了好几个版本都是黑屏

**Comment by haithink** [comment]
我下载了[Release v1.8.6](https://gitee.com/lizongying/my-tv/releases/tag/v1.8.6)，直接就没有CCTV6
