### ISSUE TITLE
[FR] 求作者增加阻止屏保的功能，看几分钟会自动屏保

### ISSUE THREAD

**Issue by zealorca** [lizongying/my-tv#357]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

[BUG] 求作者增加阻止屏保的功能，看几分钟会自动屏保

### 解决方案

[BUG] 求作者增加阻止屏保的功能，看几分钟会自动屏保

### 额外信息

[BUG] 求作者增加阻止屏保的功能，看几分钟会自动屏保

**Comment by helloworld10010** [comment]
没听说过播放着东西还屏保的。。  看一下你电视设置

**Comment by fengjiuge1** [comment]
没听说过播放着东西还屏保的。。 看一下你电视设置

**Comment by lizongying** [comment]
現在播放應該不會出現屏保，測試的一些設備還未出現此現象，後面看看還有沒有其他設備出現此問題
