### ISSUE TITLE
[BUG] 正在播放的节目显示错误。

### ISSUE THREAD

**Issue by B1-ling** [lizongying/my-tv#358]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

正在播放的节目显示为空。

### 预期行为

正常情况下打开软件，画面偏下方会出现带有台标和正在播放节目的名称，

### 实际行为

打开软件后，画面偏下方只会出现台标，正在播放的节目为空。
![Uploading 20240209184339.jpg…]()

### 复现步骤

打开软件的2秒内。

### UI / OS

康佳

### Android 版本

安卓5以上

**Comment by lizongying** [comment]
最新版本1.6.0已修復。建議大家使用官方渠道觀看。
