### ISSUE TITLE
[BUG] 中国电信的宽带，全部都不能播放了

### ISSUE THREAD

**Issue by JJ-Jiajia** [lizongying/my-tv#359]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

中国电信的宽带，全部都不能播放了

### 预期行为

打开可以正常播放

### 实际行为

全部都不能播放了

### 复现步骤

打开应用，结果不能观看

### UI / OS

sony x90k

### Android 版本

12

**Comment by mdjhacker** [comment]
yiyangde

**Comment by daguGit** [comment]
呵呵哒，放弃了

**Comment by aivandeGZ** [comment]
+1

**Comment by misaka36** [comment]
+1

**Comment by whtk** [comment]
我家一样。。这时候搞事情。。。太缺德了 ，作者加油

**Comment by SoonerMinde** [comment]
还准备看春晚呢😂

**Comment by ygxbnet** [comment]
+1

**Comment by JHL1127skr** [comment]
一样

**Comment by blankmagic** [comment]
春晚没得看了

**Comment by moyichao** [comment]
睇下睇下就没了

**Comment by ygxbnet** [comment]
春晚~~~~！

**Comment by x0829** [comment]
+1

**Comment by zhjsws** [comment]
我也是

**Comment by daguGit** [comment]
切央视频秒投屏了，无缝衔接。及时做好plan B

**Comment by Yuhao-Luo** [comment]
移动+1

**Comment by whtk** [comment]
央视频 不用投屏 直接直播  投屏有延迟

**Comment by wingjson** [comment]
广电司马玩意

**Comment by klren0312** [comment]
> 央视频 不用投屏 直接直播 投屏有延迟

央视频好卡5555

**Comment by lizongying** [comment]
最新版本1.6.0已修復。建議大家使用官方渠道觀看。
