### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by piaoxue1** [lizongying/my-tv#360]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

全部已经不能看了

### 预期行为

能看

### 实际行为

不能看

### 复现步骤

任何都是黑屏

### UI / OS

TCL

### Android 版本

9

**Comment by zxczhai** [comment]
同样的,全部黑屏了

**Comment by darling02w** [comment]
我试了好几个版本都是黑屏

**Comment by dimonwei** [comment]
啊啊啊，好着急

**Comment by fpd3210** [comment]
一样的

**Comment by fpd3210** [comment]
没有新的通道？

**Comment by misaka36** [comment]
+1

**Comment by Zhao-YB** [comment]
插眼

**Comment by gudukuaile** [comment]
> 各位可以先用tvbox，源地址填饭太硬的，http://饭太硬.top/tv  暂时还能看

电视不支持ipv6的不能用

**Comment by lizongying** [comment]
最新版本1.6.0已修復
