### ISSUE TITLE
[BUG]V1.5.8版本，创维电视，安装App之后，打开App后黑屏，按确定键可以显示电视台列表。

### ISSUE THREAD

**Issue by rbyyy** [lizongying/my-tv#361]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

V1.5.8版本，创维电视，安装App之后，打开App后黑屏，按确定键可以显示电视台列表。

### 预期行为

正常播放电视台节目

### 实际行为

黑屏，没有播放电视台节目

### UI / OS

创维Android OS

### Android 版本

9

**Comment by cethink** [comment]
一样黑屏，无法播放

**Comment by cll543721618** [comment]
被封了，这个好像是用得央视频得流

**Comment by lizongying** [comment]
最新版本1.6.0已修復
