### ISSUE TITLE
[FR] 大家不要反馈用不了了，都一样的问题，我给大家备用的看春晚（我不是作者😂）

### ISSUE THREAD

**Issue by rianlu** [lizongying/my-tv#362]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

临时应付一下

### 解决方案

补充：评论区反馈可以直接下载央视频也能用（可直接安装到电视或者手机投屏）

我给大家分享两个电视软件

123网盘
https://www.123pan.com/s/cAXQjv-Xp6N3.html提取码:7XUe

蓝奏云
https://wwi.lanzoup.com/b01es4lhg
密码:e7up
手机下载如果提示需要会员，把浏览器切换为电脑模式就可以了
![WechatIMG134](https://github.com/lizongying/my-tv/assets/42767582/cc7bdd4a-8b8a-4048-85db-512d9fb68f67)
![WechatIMG135](https://github.com/lizongying/my-tv/assets/42767582/b458378e-4d1f-4280-afe6-3d4ca48967c7)

**Comment by whtk** [comment]
是不是你黑的？

**Comment by bombermanll** [comment]
感谢

**Comment by whtk** [comment]
电视里安装央视频可以直接 看央视直播 不需要投屏

**Comment by bruceyang233** [comment]
我就知道中国人最会损中国人(与作者没关系，源应该是被封了)，我提前准备了一个群晖直播助手和这个mytv，这个坏了，自建的也能找源看

**Comment by rianlu** [comment]
> 是不是你黑的？

草过分了，我也是发现看不了，才上来看看啥情况

**Comment by Diskland** [comment]
哈哈哈  感谢有你

**Comment by rianlu** [comment]
> 我就知道中国人最会损中国人(与作者没关系，源应该是被封了)，我提前准备了一个群晖直播助手和这个mytv，这个坏了，自建的也能找源看

就很奇怪，白天还好好的，突然就不行了，应该是热度太高了被搞了

**Comment by zh-plus** [comment]
其实直接手机下载央视频APP，投屏就行了

**Comment by jerryyjf** [comment]
感谢作者

**Comment by alsojin0806** [comment]
估计限制流量了

**Comment by 1584598022** [comment]
非会员无法下载

**Comment by rianlu** [comment]
> 非会员无法下载

浏览器切换为电脑模式就行了

**Comment by Abbccco** [comment]
感谢作者

**Comment by lichanglei** [comment]
直接 央视频TV版  免费的

**Comment by dmhmb0908** [comment]
这个需要办理蓝奏云会员才能下载啊

**Comment by joy525525525** [comment]
> 这个需要办理蓝奏云会员才能下载啊

浏览器切换成电脑版就能下载了

**Comment by rianlu** [comment]
> 这个需要办理蓝奏云会员才能下载啊

不需要的，手机浏览器切换为电脑模式就可以了

**Comment by JUN-DANG-Y-Q** [comment]
感谢！

**Comment by sweetgressz** [comment]
幸好我还留了一手😊

**Comment by whtk** [comment]
sorry 我道歉。我是被气晕了

**Comment by rianlu** [comment]
> sorry 我道歉。我是被气晕了

哈哈哈我也很气，莫名其妙就不行了，我还以为作者又更新了😂

**Comment by whtk** [comment]
哎。。。这tmd

**Comment by sweetgressz** [comment]
I'm devastated. 我还以为是我网络出问题了🥲

**Comment by caiVei** [comment]
新年快乐！

**Comment by soaringambition** [comment]
都不好用啊

**Comment by rianlu** [comment]
> 都不好用啊

那你试试央视频

**Comment by Colinhongle** [comment]
感谢大兄弟

**Comment by rianlu** [comment]
> 鸿蒙电视一直弹窗重新安装是什么情况

这个我也不清楚，你要不试试央视频TV版

**Comment by majestichou** [comment]
突然就挂了，以为电视坏了呢

**Comment by dmhmb0908** [comment]
感谢

**Comment by leaveinsummer** [comment]
感谢，用上了

**Comment by ssmalltone123** [comment]
我切换电脑版也不行，无法下载

**Comment by rianlu** [comment]
> 我切换电脑版也不行，无法下载

我传了另一个网盘，你试试这个
https://www.123pan.com/s/cAXQjv-Xp6N3.html提取码:7XUe

**Comment by zbby1987** [comment]
楼主的没这个方便
https://www.123pan.com/s/9sRPjv-A9xVv.html

**Comment by daymissed** [comment]
差点去换台电视！

**Comment by lizongying** [comment]
最新版本1.6.0已修復。建議大家使用官方渠道觀看。
