### ISSUE TITLE
[BUG] 春晚期间 401 Unauthorized

### ISSUE THREAD

**Issue by YSIOne** [lizongying/my-tv#363]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

约7:30能进入观看，8点左右黑屏，抓包显示 401 Unauthorized

### 预期行为

none

### 实际行为

黑屏

### UI / OS

XIAOMI

### Android 版本

9

**Comment by lizongying** [comment]
最新版本1.6.0已修復
