### ISSUE TITLE
[FR] 央视频直播链接

### ISSUE THREAD

**Issue by muzihuaner** [lizongying/my-tv#364]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

直播链接。 https://www.yangshipin.cn/#/tv/home?pid=600001859

### 解决方案

直播链接。 https://www.yangshipin.cn/#/tv/home?pid=600001859

### 额外信息

直播链接。 https://www.yangshipin.cn/#/tv/home?pid=600001859

**Comment by dyingway** [comment]
谢谢：）也就给老人看个春节晚会，这个就够了。

**Comment by zbby1987** [comment]
早就猜到，
央视频会掐着春晚的点儿来给你黑屏的！
.
先用这个链接里的看吧。。。
https://www.123pan.com/s/9sRPjv-A9xVv.html
