### ISSUE TITLE
[FR] 请问native.c在哪里

### ISSUE THREAD

**Issue by liulixiang1988** [lizongying/my-tv#365]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

想学习一下，但是cmakelist.txt中有个native.c，请问这个会开源吗 https://github.com/lizongying/my-tv/blob/main/app/CMakeLists.txt#L24

### 解决方案

no

### 额外信息

no

**Comment by CJyoung524** [comment]
close掉吧，不会开源的
