### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Lao-Wang233** [lizongying/my-tv#366]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

无法观看，全部黑屏

### 预期行为

更换多个版本仍然黑屏

### 实际行为

所有频道都看不了

### UI / OS

三星

### Android 版本

10

**Comment by zbby1987** [comment]
早就猜到，
央视频会掐着春晚的点儿来给你黑屏的！
.
先用这个链接里的看吧。。。
https://www.123pan.com/s/9sRPjv-A9xVv.html

**Comment by lizongying** [comment]
最新版本1.6.0已修復。建議大家使用官方渠道觀看。
