### ISSUE TITLE
[BUG] 村晚相声没听完，挂了？

### ISSUE THREAD

**Issue by shawnmage** [lizongying/my-tv#367]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

挂了挂了挂了

### 预期行为

挂了挂了挂了

### 实际行为

挂了挂了挂了

### UI / OS

当贝盒子

### Android 版本

12

**Comment by faintout** [comment]
挂了

**Comment by zkmnnssm** [comment]
我感觉会发生这种事情，没想到真发生了，现在换到ipad直播投屏了

**Comment by hupengchn** [comment]
挂了，转央视频TV版看春晚了。。。

**Comment by xiaochenthu** [comment]
It really failed

**Comment by hupengchn** [comment]
邮件已收到，谢谢。
祝事事顺心。
（该邮件来自自动回复）

**Comment by luobei555** [comment]
真挂了，央视频投屏了[哭]

**Comment by zbby1987** [comment]
早就猜到，
央视频会掐着春晚的点儿来给你黑屏的！
.
先用这个链接里的看吧。。。
https://www.123pan.com/s/9sRPjv-A9xVv.html

**Comment by lizongying** [comment]
最新版本1.6.0已修復。建議大家使用官方渠道觀看。
