### ISSUE TITLE
挂了，可以先转央视频TV版看

### ISSUE THREAD

**Issue by xiaochenthu** [lizongying/my-tv#369]

**Comment by danche354** [comment]
确实挂了😂

**Comment by lisi0** [comment]
> 央视频TV太卡了太卡了

可以试试降低清晰度

**Comment by garywill** [comment]
你们说的央视频TV，和应用宝搜到的“央视频”是同一个吗？那个没有TV

**Comment by zbby1987** [comment]
> 你们说的央视频TV，和应用宝搜到的“央视频”是同一个吗？那个没有TV

不是同一个，应用宝里的是手机版，电视安不了
.
早就猜到，
央视频会掐着春晚的点儿来给你黑屏的！
.
先用这个链接里的看吧。。。
https://www.123pan.com/s/9sRPjv-A9xVv.html

**Comment by whtk** [comment]
我海信电视里直接下。。的央视频

**Comment by lizongying** [comment]
最新版本1.6.0已修復。建議大家使用官方渠道觀看。
