### ISSUE TITLE
6的源好像不是太清晰，3和9的源都挺高清的

### ISSUE THREAD

**Issue by biubingo** [lizongying/my-tv#37]
![Screenshot_2024-01-06-22-56-37-470_com lizongying mytv](https://github.com/lizongying/my-tv/assets/155462148/b99afc2a-e48a-4485-8d5f-5fdc0fa7f851)
![Screenshot_2024-01-06-22-57-07-189_com lizongying mytv](https://github.com/lizongying/my-tv/assets/155462148/2dd1e11a-61d8-4483-8ee8-ca065b93e105)
![Screenshot_2024-01-06-22-57-27-393_com lizongying mytv](https://github.com/lizongying/my-tv/assets/155462148/e1f09d27-74d8-4940-ad01-028f36567b3e)

**Comment by lizongying** [comment]
暂时无解
