### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by zjy208723** [lizongying/my-tv#370]
看一天就黑屏，更新1.5.8还是黑屏

**Comment by Larkelmes** [comment]
同，就是春晚开始后不就黑了

**Comment by lucking** [comment]
难受啊

**Comment by zbby1987** [comment]
早就猜到，
央视频会掐着春晚的点儿来给你黑屏的！
.
先用这个链接里的看吧。。。
https://www.123pan.com/s/9sRPjv-A9xVv.html

**Comment by lizongying** [comment]
最新版本1.6.0已修復。建議大家使用官方渠道觀看。
