### ISSUE TITLE
[BUG] 关键时候条链子(⋟﹏⋞)

### ISSUE THREAD

**Issue by wpsdoo** [lizongying/my-tv#371]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

黑屏

### 预期行为

春晚看不了

### 实际行为

挂逼了

### UI / OS

xiaomi

### Android 版本

12

**Comment by prettyboyweiwei** [comment]
+1

**Comment by lucking** [comment]
我屮艸芔茻，难受，被封了吧

**Comment by Colinhongle** [comment]
没事，投屏也能看，主要是平时，给爸妈看的怕他们不会弄

**Comment by 21learnMore** [comment]
啊啊啊啊啊一样

**Comment by yxhy1010** [comment]
一个都不能看了

**Comment by lucking** [comment]
老年人不会弄啊

**Comment by MultiWolf** [comment]
同样，所有频道都寄了QAQ

**Comment by troublewind** [comment]
猜到会这样了，春晚是看电视的高峰期，流量这么大大概率会挂

**Comment by zbby1987** [comment]
早就猜到，
央视频会掐着春晚的点儿来给你黑屏的！
.
先用这个链接里的看吧。。。
https://www.123pan.com/s/9sRPjv-A9xVv.html

**Comment by bigdataOrfrontEnd** [comment]
哎，利益当先啊

**Comment by rkonfj** [comment]
春晚版权问题。估计明天就恢复了，哈哈
