### ISSUE TITLE
黑屏了

### ISSUE THREAD

**Issue by tianshaboy88** [lizongying/my-tv#372]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

又黑屏了

### 预期行为

又黑屏了

### 实际行为

又黑屏了

### UI / OS

tcl

### Android 版本

11

**Comment by barbiel1106** [comment]
黑屏了😂，索尼9000h，下午看着好好的，快到点了黑屏了

**Comment by HurleyF** [comment]
一样挂了…

**Comment by douyaolai** [comment]
春晚看到 岳云鹏小品的时候挂掉黑屏了

**Comment by zbby1987** [comment]
确实是！
央视频是掐着春晚的点儿来给你黑屏的！
.
先用这个链接里的看吧。。。
https://www.123pan.com/s/9sRPjv-A9xVv.html

**Comment by vcetor** [comment]
> 黑屏了😂，索尼9000h，下午看着好好的，快到点了黑屏了



> 黑屏了😂，索尼9000h，下午看着好好的，快到点了黑屏了

同型号 我也是

**Comment by barbiel1106** [comment]
央视频app可以直接看春晚直播，将就用用

**Comment by barbiel1106** [comment]
> > 黑屏了😂，索尼9000h，下午看着好好的，快到点了黑屏了
> 
> > 黑屏了😂，索尼9000h，下午看着好好的，快到点了黑屏了
> 
> 同型号 我也是

央视频app可以直接看春晚直播，将就用用

**Comment by zbby1987** [comment]
> 央视频app可以直接看春晚直播，将就用用

手机版？大家都是电视上看的

**Comment by lixiaolong0588** [comment]
这个开源项目得罪太多人利益了，一个人搞不容易

**Comment by lfm09** [comment]
> 这个开源项目得罪太多人利益了，一个人搞不容易

自定义源功能很有必要

**Comment by soberGou** [comment]
手机打开黑屏了，投影仪到现在是好的，具体原因是啥，给很多人推荐了，看春晚时黑屏了
![image](https://github.com/lizongying/my-tv/assets/50661423/ed1700d5-be2e-496a-8041-c6ccc5ef0091)

**Comment by lizongying** [comment]
最新版本1.6.0已修復
