### ISSUE TITLE
大家可以去腾讯视频看，有4K直播线路，不卡，不要会员。

### ISSUE THREAD

**Issue by jervy** [lizongying/my-tv#374]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

大家可以去腾讯视频看，有4K直播线路，不卡，不要会员。

### 预期行为

.

### 实际行为

.

### UI / OS

.

### Android 版本

.

**Comment by cornradio** [comment]
https://tv.cctv.com/live/cctv1/

**Comment by cornradio** [comment]
但是，很烂很难看...

**Comment by lizongying** [comment]
最新版本1.6.0已修復。還是建議大家選擇官方渠道。

**Comment by frisklee251** [comment]
春晚直播TCL电视首页banner就有，好像用的就是腾讯视频的源

**Comment by frisklee251** [comment]
春晚直播TCL电视首页banner就有，好像用的就是腾讯视频的源
