### ISSUE TITLE
看春晚呢 

### ISSUE THREAD

**Issue by 907597029** [lizongying/my-tv#375]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

黑屏了 一个台都没了 看到除夕夜十点半的时候忽然黑屏了

### 预期行为

看春晚呢 黑屏了 除夕夜十点半黑屏了

### 实际行为

看春晚呢 黑屏了 除夕十点半黑屏了

### UI / OS

小米 s pro

### Android 版本

12

**Comment by DaiyuChen** [comment]
作者刚刚发了一个版本修复了

**Comment by baibaiwow** [comment]
新发了个releases您是完全没有看到吗
