### ISSUE TITLE
老大真牛逼，大三十想大家所想

### ISSUE THREAD

**Issue by adandm** [lizongying/my-tv#378]
谢谢

**Comment by longzai0803** [comment]
谢谢大佬，新年快乐！

**Comment by yxhy1010** [comment]
同感，真心感谢作者！

**Comment by fxmdegh** [comment]
好人一生平安

**Comment by lovethanatos** [comment]
谢谢，十分感谢。

**Comment by shengdao001** [comment]
感谢大佬

**Comment by danche354** [comment]
感谢大佬

**Comment by nezhastudio** [comment]
守护年三十的大神

**Comment by Diskland** [comment]
感恩！！！

**Comment by shit6** [comment]
感谢

**Comment by Larkelmes** [comment]
牛逼牛逼

**Comment by ni7ht** [comment]
英雄！

**Comment by whtk** [comment]
感谢！

**Comment by rockiecxh** [comment]
感恩！！！

**Comment by lllxh** [comment]
大佬新年快乐

**Comment by ygxbnet** [comment]
谢谢大佬，祝大佬新年快乐

**Comment by lizongying** [comment]
有時也會想這個項目的意義。這種方式，大家是否真的喜歡？還是我們的初衷嗎？交點錢、看看廣告、購購物，可能看電視更簡單些，也不用一直去更新吧？
我自己來說，本身就有移動和聯通的IPTV，一直用的也只是DTMB。
是不是只是我們自己在孤獨狂歡？看了很多網上用戶的評論真的有點懷疑了。

**Comment by tianshaboy88** [comment]
感恩大佬

**Comment by chenbokaix250** [comment]
被迫除夕加班 牛逼牛逼

**Comment by troublewind** [comment]
> 有時也會想這個項目的意義。這種方式，大家是否真的喜歡？還是我們的初衷嗎？交點錢、看看廣告、購購物，可能看電視更簡單些，也不用一直去更新吧？ 我自己來說，本身就有移動和聯通的IPTV，一直用的也只是DTMB。 是不是只是我們自己在孤獨狂歡？看了很多網上用戶的評論真的有點懷疑了。

意义非凡！这是我们无声的抵抗，一年也就这会儿流量大，大佬辛苦！

**Comment by prettyboyweiwei** [comment]
大佬牛逼，感谢，新年快乐🎉

**Comment by zs123zs** [comment]
感谢大佬，大佬新年快乐

**Comment by xmzgtx** [comment]
> 有時也會想這個項目的意義。這種方式，大家是否真的喜歡？還是我們的初衷嗎？交點錢、看看廣告、購購物，可能看電視更簡單些，也不用一直去更新吧？ 我自己來說，本身就有移動和聯通的IPTV，一直用的也只是DTMB。 是不是只是我們自己在孤獨狂歡？看了很多網上用戶的評論真的有點懷疑了。

事情做到问心无愧即可，这个项目主要用户并不懂技术也不理解你做这件事情的动机。我觉得重点不是用户，而是自己。

**Comment by xmzgtx** [comment]
对了，收款码被支付宝阻止了

**Comment by lfm09** [comment]
> 有時也會想這個項目的意義。這種方式，大家是否真的喜歡？還是我們的初衷嗎？交點錢、看看廣告、購購物，可能看電視更簡單些，也不用一直去更新吧？ 我自己來說，本身就有移動和聯通的IPTV，一直用的也只是DTMB。 是不是只是我們自己在孤獨狂歡？看了很多網上用戶的評論真的有點懷疑了。

感谢大佬！增加自定义源功能很有必要

**Comment by yxhy1010** [comment]
@lizongying 您是一位君子，感恩作者的辛勤付出。

**Comment by NicholasGGW** [comment]
谢谢大佬！

**Comment by sionsama** [comment]
> 有時也會想這個項目的意義。這種方式，大家是否真的喜歡？還是我們的初衷嗎？交點錢、看看廣告、購購物，可能看電視更簡單些，也不用一直去更新吧？ 我自己來說，本身就有移動和聯通的IPTV，一直用的也只是DTMB。 是不是只是我們自己在孤獨狂歡？看了很多網上用戶的評論真的有點懷疑了。

**Comment by xiaobaicai2019** [comment]
感谢！另外，收款码失效了，导致我无法赞助

**Comment by ltycn** [comment]
> 有時也會想這個項目的意義。這種方式，大家是否真的喜歡？還是我們的初衷嗎？交點錢、看看廣告、購購物，可能看電視更簡單些，也不用一直去更新吧？
> 我自己來說，本身就有移動和聯通的IPTV，一直用的也只是DTMB。
> 是不是只是我們自己在孤獨狂歡？看了很多網上用戶的評論真的有點懷疑了。

谢谢大佬，爸妈在家不会捣鼓电视，买了基本就当摆设。这个项目让电视又用起来，正好赶上春晚，一家人能边看春晚边吃年夜饭（虽然很难看）起码不孤单！再次感谢![image](https://github.com/lizongying/my-tv/assets/140243957/226aa0da-6fe8-4706-89e0-6a3775e54fe9)

**Comment by AWEI-netizen** [comment]
感谢大佬！新年大吉！
