### ISSUE TITLE
1.5.8又恢复了。。。

### ISSUE THREAD

**Issue by TakcC** [lizongying/my-tv#379]
过12点，1.5.8又能看了，真的是😂😂😂

**Comment by wpsdoo** [comment]
你们这些人，大年三十都不让作者休息。哈哈。大佬牛逼啊。半夜给修复了。㊗️新年万事如意🎆。大家快给作者发红包咯

**Comment by myvmiao** [comment]
1.58没恢复，还得更新到1.6才行

**Comment by jackson-xp** [comment]
恢复了 好棒！！！

**Comment by 4t8dd** [comment]
不同版本持续出现不能观看的现象是什么原因呢？

**Comment by fengjiuge1** [comment]
> 1.58没恢复，还得更新到1.6才行

恢复了，昨晚好多软件都不行了，最后用ipv6直播源播放的

**Comment by Amamiya23** [comment]
我昨晚紧急用油管看的，央视频电视上超级卡。1080p都卡，油管4k却无压力

**Comment by yxhy1010** [comment]
@4t8dd 网路原因，昨天电信卡死吗，春节没办法

**Comment by BiuZero** [comment]
> 我昨晚紧急用油管看的，央视频电视上超级卡。1080p都卡，油管4k却无压力

我昨天发现这个软件用不了后来用优酷卡死，央视频一直流畅，可能和地区也有关吧

**Comment by lizongying** [comment]
是恢复了，具体就不解释了
