### ISSUE TITLE
[FR] 更新地址走代理ghproxy

### ISSUE THREAD

**Issue by ruiwangye** [lizongying/my-tv#380]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

大部份目标用户可能都无法直接访问github，检查更新地址能不能考虑加个代理如（https://mirror.ghproxy.com/），让这部分用户也能自动更新

**Comment by kzeng** [comment]
为这个提议点赞！大陆很多用户访问 GitHub 是困难的，升级的源可考虑托管到别的地方。再次感谢@lizongying 大神的无私付出！🙏

**Comment by xz-dev** [comment]
ghproxy 的可用地址一直在变，实际用 ghproxy 就跟打地鼠一样玄学

**Comment by lizongying** [comment]
現在更新尚未使用github地址。
