### ISSUE TITLE
[BUG] 这玩意慎用，会有远程入侵，被控制

### ISSUE THREAD

**Issue by fsty521e79** [lizongying/my-tv#381]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

 这玩意慎用，会有远程入侵，被控制，遥控乱按，然后关机，

### 预期行为

 这玩意慎用，会有远程入侵，被控制，遥控乱按，然后关机，

### 实际行为

 这玩意慎用，会有远程入侵，被控制，遥控乱按，然后关机，

### UI / OS

安卓9

### Android 版本

9

**Comment by Mashirl** [comment]
这玩意是开放源代码的，构建全是GitHub actions通过在仓库公开的源代码编译的，空口无凭不要乱说，有问题也是别的软件有问题

**Comment by Earplug** [comment]
没想到还能在github上看到这种发言，你好歹自己看看代码呢？

**Comment by ccav14** [comment]
是你遥控器被控制了

**Comment by XuBoZhangQvQ** [comment]
哈哈哈哈哈哈，源码都在这里呢，你自己看看代码，实在不得行自己编译一下，看看有没有远程地址，上传信息\控制

**Comment by dustxdustx** [comment]
别人入侵你电视做啥？让你只能看春晚？

**Comment by NikolaCavendish** [comment]
你这应该是隔壁用的遥控器信号频率和你的差不多，他们按的时候控制到你的电视了

**Comment by wabzsy** [comment]
前来见证物种多样性

**Comment by sionsama** [comment]
抽象

**Comment by mrkaixuan** [comment]
大哥开源呢,不如咱研究明白再发言

**Comment by QiKe-007** [comment]
咋就说好歹抓包一下，放个图，排除一下其他因素，别张口就来对吧，要用严谨性，不要张口就来，要是你开发这项目，别人这样讲，你会咋想

**Comment by whtk** [comment]
这里都有点技术。。。不是国内贴吧。。

**Comment by CESAEREE** [comment]
66666 
前来见证物种多样性，太抽象了

**Comment by MicrosoftWindows10** [comment]
很符合我对dinner five的想象，大过年的让大家都来骂你，你是最🤣👉💩的

**Comment by Xuan-Haoyu** [comment]
很有可能是你家小孩通过局域网控制电视了（比如小米电视可以用米家控制） 也有可能是你遥控器快没电了

**Comment by awmc233** [comment]
搞不好是个50w呢

**Comment by Mybctd** [comment]
hh
