### ISSUE TITLE
[BUG] 看着看着突然闪退 然后再次打开也闪退什么情况

### ISSUE THREAD

**Issue by yuluoqingcheng** [lizongying/my-tv#382]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

看着看着突然闪退 然后再次打开也闪退什么情况

### 预期行为

打开以后闪退 直接回到主菜单

### 实际行为

直接闪退

### 复现步骤

1.打开APP
2.直接闪退
（网络正常）

### UI / OS

小米电商盒子

### Android 版本

12

### 额外信息

无

**Comment by yuantao313** [comment]
可能已经被注意到了。小米电视卸载后电视端重新安装报“存在违规功能，禁止安装”

**Comment by lizongying** [comment]
服務器帶寬打滿了，已升級。重新使用打開軟件即可。

**Comment by yuluoqingcheng** [comment]
感谢作者回复 谢谢修复
