### ISSUE TITLE
[BUG] 手机安装1.5.8，1.60闪退

### ISSUE THREAD

**Issue by daguGit** [lizongying/my-tv#383]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

在手机鸿蒙系统4.0.0.122中，闪退。
昨天之前安装哪个版本均可观看。系统没有更新，但手机有重启，但是今天下午再打开闪退，1.5.8 1.6.0闪退。
重启手机或重新安装后暂没有解决。

### 预期行为

不知

### 实际行为

闪退

### UI / OS

华为mate40E 

### Android 版本

鸿蒙4.0.0.122

**Comment by barbiel1106** [comment]
同闪退，电视端app，1.5.8、1.5.6、1.6.0，都试过，都闪退，测试时间2024年2月10日15时

**Comment by babyhz** [comment]
n1盒子也闪退

**Comment by daguGit** [comment]
已有多人反馈此问题，issue关闭
