### ISSUE TITLE
1.6.0突然闪退，报空指针异常

### ISSUE THREAD

**Issue by randeexiong** [lizongying/my-tv#384]
![IMG_20240210_150218.jpg](https://github.com/lizongying/my-tv/assets/10184937/9ceae949-1f96-4879-af56-7632caf4bcf4)

**Comment by sannire** [comment]
+1

**Comment by whtk** [comment]
明显服务器问题，没有返回token

**Comment by lizongying** [comment]
服務器帶寬打滿了，已升級。重新使用打開軟件即可。
