### ISSUE TITLE
[BUG] 在腾讯极光盒子上闪退

### ISSUE THREAD

**Issue by zs123zs** [lizongying/my-tv#386]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

今天安装的1.6 版本app用了半天后，进去之后，闪退出来

### 预期行为

none

### 实际行为

none

### UI / OS

腾讯极光盒子6SE

### Android 版本

10

**Comment by lizongying** [comment]
服務器帶寬打滿了，已升級。重新使用打開軟件即可。
