### ISSUE TITLE
[BUG] 当贝盒子闪退/无法打开

### ISSUE THREAD

**Issue by AjiuQUQ** [lizongying/my-tv#387]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

软件无法打开，尝试重启电视盒后进入软件出现频道图标后闪退（无画面），之后也无法再打开软件。

### 预期行为

启动app

### 实际行为

app无法正常启动

### 复现步骤

尝试打开app，无法打开，无任何提示

### UI / OS

当贝盒子，当贝桌面

### Android 版本

安卓7

**Comment by AjiuQUQ** [comment]
1.6/1.5.8及多版本尝试均无法启动

**Comment by XuBoZhangQvQ** [comment]
我看好多人反馈这个问题，我是华为电视，今天上午，还能正常打开，刚刚打开也是闪退

**Comment by lizongying** [comment]
服務器帶寬打滿了，已升級。重新使用打開軟件即可。
