### ISSUE TITLE
[BUG] 小米盒子3s 1.5.7以及最新版本闪退问题

### ISSUE THREAD

**Issue by Anmizi** [lizongying/my-tv#388]
### 检查清单

- [ ] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

1.5.7版本之前播放正常，今天播放一段时间后闪退无法进入，更新最新版本闪退问题依旧存在

### 预期行为

正常进入应用

### 实际行为

发生闪退

### 复现步骤

暂无

### UI / OS

小米盒子3s

### Android 版本

6.0.1

### 额外信息

无

**Comment by zbby1987** [comment]
安卓9的小米电视没这个问题

**Comment by wylfannystore** [comment]
闪退+1

**Comment by soberGou** [comment]
闪退+1

**Comment by ptknh** [comment]
还没试用小米盒子，tcl电视打开闪退

**Comment by lizongying** [comment]
服務器帶寬打滿了，已升級。重新使用打開軟件即可。

**Comment by lfm09** [comment]
估计是服务器的原因，现在又正常了，只是cctv5无法播放，提示因版权问题。建议加上自定义源功能，这样即使服务器有问题也能播放。
