### ISSUE TITLE
[BUG] 小米电视2 安卓4.4.4使用V1.6.0闪退

### ISSUE THREAD

**Issue by HyperQi** [lizongying/my-tv#389]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

小米电视2 安卓4.4.4使用V1.6.0闪退

### 预期行为

小米电视2 安卓4.4.4使用V1.6.0闪退

### 实际行为

小米电视2 安卓4.4.4使用V1.6.0闪退

### UI / OS

XIAOMI

### Android 版本

4.4.4

### 额外信息

小米电视2 安卓4.4.4使用V1.6.0闪退

**Comment by cq123456a** [comment]
闪退+1

**Comment by shanei5107** [comment]
闪退+1

**Comment by zbby1987** [comment]
安卓9的小米电视没这个问题

**Comment by lizongying** [comment]
服務器帶寬打滿了，已升級。重新使用打開軟件即可。

**Comment by spyyt** [comment]
小米电视2不是4.3系统吗，你怎么升级的4.4？
