### ISSUE TITLE
优化应用图标

### ISSUE THREAD

**Issue by yaoyuan2326** [lizongying/my-tv#39]
![IMG_7037](https://github.com/lizongying/my-tv/assets/155813208/d430423b-572b-41a3-88c0-fcc2b973e984)app图标横版拉伸看着有点不美观，可能设计成像影视仓一样的好看些的图标。

**Comment by lizongying** [comment]
多谢反馈，后续版本处理。

**Comment by zbby1987** [comment]
你这是缺一个横版的长方形图标，方形图标的汉字被强拉成长方形才不好看
