### ISSUE TITLE
开始闪退了[BUG] 

### ISSUE THREAD

**Issue by lsk5201** [lizongying/my-tv#391]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

/

### 预期行为

/

### 实际行为

崩溃了

### UI / OS

格力G7

### Android 版本

12

**Comment by jackson-xp** [comment]
+1

**Comment by sinbadr** [comment]
+1

**Comment by awmc233** [comment]
+1
os原生安卓TV10

**Comment by xiaolanglu** [comment]
+1

**Comment by jvuixcqm** [comment]
+1

**Comment by awmc233** [comment]
我把gitee上面所有历史版本都试了一遍，在原生AndroidTV 10上面都闪退

**Comment by awmc233** [comment]
我当时正在和家里老人看电视，然后突然一下电视直接回了桌面，之后就都打不开了，打开就闪退，有时还能显示出来一下CCTV1，有时是直接点了没反应

**Comment by sweetgressz** [comment]
+1

**Comment by cal-a737** [comment]
下载试用了以下，小米电视，闪退

**Comment by Wheat976** [comment]
雷鸟，闪退+1

**Comment by Grey132** [comment]
雷鸟闪退➕1

**Comment by sionsama** [comment]
TCL闪退

**Comment by DevilFu** [comment]
索尼A90J +1

**Comment by lexikeqi** [comment]
+1

**Comment by mickey0110** [comment]
+1

**Comment by awmc233** [comment]
已经修好了，原生安卓0电视系统能正常播放
