### ISSUE TITLE
1.4.8-1.6.0全部都是闪退，可以安装，系统7.1.2

### ISSUE THREAD

**Issue by ccvina** [lizongying/my-tv#392]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

闪退

### 预期行为

闪退

### 实际行为

闪退

### UI / OS

斐讯盒子

### Android 版本

7.1.2

**Comment by jerry-shao** [comment]
好像从大佬的API拿token的时候报NPE.

<img width="1512" alt="image" src="https://github.com/lizongying/my-tv/assets/7830699/f26b5459-6352-4c5e-a0d1-9155de59551c">

**Comment by Germxu** [comment]
同样问题，同样版本，昨天晚上还在用 1.5.7 正常看春晚，现在打卡闪退最近版本都闪退

**Comment by whtk** [comment]
应该是服务器出问题了

**Comment by blankmagic** [comment]
海信闪退

**Comment by QiKe-007** [comment]
> API拿token的时候报NPE.

是的，昨晚春晚之前正常打开，一直到春晚开始可以看的，但手机端就看不了，用了最新1.6.0才能看

**Comment by QiKe-007** [comment]
无网络环境打开，app不会闪退，但联网切频道，就直接闪退，就是上面大佬所讲的，当代码试图在一个空对象上调用方法或访问属性时，会抛出NullPointerException，在Android上发生NPE并且没有被正确捕获和处理，就会导致应用崩溃闪退

**Comment by ocyisheng** [comment]
。。。

**Comment by qgmzfj** [comment]
+1

**Comment by lizongying** [comment]
服務器帶寬打滿了，已升級。重新使用打開軟件即可。
