### ISSUE TITLE
[BUG] 从1.4.2到1.6.0全部闪退

### ISSUE THREAD

**Issue by 8u8m** [lizongying/my-tv#393]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

平板、电视、手机以及电脑模拟器上
均是闪退

### 预期行为

闪退

### 实际行为

闪退

### UI / OS

TCL电视、笔记本、华为手机、安卓平板

### Android 版本

4、10、鸿蒙

### 额外信息

平板、电视、手机以及电脑模拟器上
均是闪退

**Comment by gaboolic** [comment]
+1

**Comment by qgmzfj** [comment]
+1

**Comment by wucd18** [comment]
+1

**Comment by qgmzfj** [comment]
+1

**Comment by mozhumao** [comment]
1.6.0我闪退

**Comment by mickey0110** [comment]
+1

**Comment by LittlePenhu** [comment]
经过测试，连接网络的情况下闪退，断开网络不闪退

**Comment by wangtieying** [comment]
+1

**Comment by TianyaImpression** [comment]
1.60，小米电视，闪退，从昨天开始的

**Comment by Fireworks-agamer** [comment]
好像可以用了

**Comment by Flavored4179** [comment]
+1 sony电视

**Comment by wylapp** [comment]
+1

**Comment by Xuan-Haoyu** [comment]
昨天下午出现闪退bug 今天快中午（11点吧）好了  下午六点又不行了

**Comment by csmSimona** [comment]
今天下午开始 v1.5.4、v1.6.0 都闪退

**Comment by lizongying** [comment]
服務器帶寬打滿了，已升級。重新使用打開軟件即可。
