### ISSUE TITLE
[BUG] V1.6 cctv5 看不了，切换的时候下面有短时提示小字说应版权方要求不能播放

### ISSUE THREAD

**Issue by zazitufu** [lizongying/my-tv#395]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

V1.6 

cctv5 看不了，切换的时候下面有短暂提示小字，大意是说应版权方要求不能播放

cctv5+ 能看

### 预期行为

CCTV所有频道都能看

### 实际行为

cctv5不能观看，其他正常

呃，我走过去查看电视机的安卓版本的时候，再试了cctv5，又能看了，这看上去好像是部分体育赛事可能不能看。因为我比较少看cctv5，主要是家人看，所以我不太确定原因。

### UI / OS

创维

### Android 版本

7

**Comment by soberGou** [comment]
现在好了，再试一下

**Comment by flytkgl** [comment]
大概是有体育赛事的时候就看不了

**Comment by homerhan** [comment]
我的cctv5显示有版权不让放，cctv5+直接点了无任何反应。。

**Comment by lizongying** [comment]
視頻源問題
