### ISSUE TITLE
[BUG] 当贝F3投影仪今天下午开始所有my tv版本均无法打开使用，此前一切正常

### ISSUE THREAD

**Issue by svanlo1314** [lizongying/my-tv#397]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

当贝F3投影仪今天下午开始所有my tv版本均无法打开使用，此前一切正常。
具体表现为软件无法打开，遥控器点击了没有任何反应，也没有任何提示。

### 预期行为

软件无法使用

### 实际行为

软件无法使用

### UI / OS

Dangbei

### Android 版本

6.0

**Comment by lshkai** [comment]
我家的小米盒子也是。。。全部都不能打开了，临时又用了灵犀直播。。。。

**Comment by svanlo1314** [comment]
我把投影仪拔掉插头断电重启后，又能正常使用了。

**Comment by lizongying** [comment]
@svanlo1314 算是bug，已修復
