### ISSUE TITLE
[BUG] 怀疑是节目源会封锁应用？

### ISSUE THREAD

**Issue by xnklerEd** [lizongying/my-tv#398]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

我客厅和卧室各有一台电视，一台小米投影仪，一台飞利浦电视，安装的mytv都是最新版，客厅全天使用，安装后很快在今天下午失效，卧室昨天安装了最新版后一直没打开过，下午上来看到很多人反馈最新版已经闪退失效，晚上无意中打开卧室上的mytv，居然可以正常使用，正常使用中，也许退出后重新进入就再也不行了？

### 预期行为

我客厅和卧室各有一台电视，一台小米投影仪，一台飞利浦电视，安装的mytv都是最新版，客厅全天使用，安装后很快在今天下午失效，卧室昨天安装了最新版后一直没打开过，下午上来看到很多人反馈最新版已经闪退失效，晚上无意中打开卧室上的mytv，居然可以正常使用，正常使用中，也许退出后重新进入就再也不行了？

### 实际行为

我客厅和卧室各有一台电视，一台小米投影仪，一台飞利浦电视，安装的mytv都是最新版，客厅全天使用，安装后很快在今天下午失效，卧室昨天安装了最新版后一直没打开过，下午上来看到很多人反馈最新版已经闪退失效，晚上无意中打开卧室上的mytv，居然可以正常使用，正常使用中，也许退出后重新进入就再也不行了？

### UI / OS

Xiaomi

### Android 版本

12

**Comment by xnklerEd** [comment]
补一张在正常使用的图片，上面有日期时间![IMG_20240210_200548](https://github.com/lizongying/my-tv/assets/4424407/d40377a1-25ac-4a0f-ac3b-667eecd7ef78)

**Comment by h7g6b2v8cv** [comment]
The server automatically blocks when it detects an illegal IP connection.There is no solution to this problem at present.

**Comment by dartagnanli** [comment]
雷鸟电视，[v1.5.8](https://github.com/lizongying/my-tv/releases/tag/v1.5.8) 版本安装使用第二天闪退

**Comment by xnklerEd** [comment]
> The server automatically blocks when it detects an illegal IP connection.There is no solution to this problem at present.

yes maybe, but my issue is two devices under the same  router, one was crashed but  another works  well

**Comment by h7g6b2v8cv** [comment]
> > 服务器检测到非法IP连接时会自动阻塞。目前还没有解决这个问题的方法。
> 
> 是的，也许，但我的问题是同一路由器下的两个设备，一个崩溃了，但另一个运行良好

The server's judgment of illegal connection is not only IP or device feature code, but also a waiting time from obtaining these feature values to blocking the devices with these feature values, so two devices under the same router may not be blocked at the same time.

**Comment by lizongying** [comment]
just a bug
