### ISSUE TITLE
[FR] 选台界面优化，希望可以延长自动消失时间，可以自定义图标大小

### ISSUE THREAD

**Issue by ddwty** [lizongying/my-tv#399]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

希望可以增加设置，能够延长选台界面的自动消失时间。现在家里老人在用这个软件，遥控器手速跟不上，还没等选到想看的频道时，选台界面就自动消失了。
希望可以自定义增大选台界面的电视频道的图标大小，不然老人有的字看不清

**Comment by deanlau1988** [comment]
我也准备说这个的，哈哈哈

**Comment by qgmzfj** [comment]
+1

**Comment by zhj250566372** [comment]
非常感谢作者,但是建议藏好点,小心律师函,如果在国外当我没说

**Comment by mencall** [comment]
确实，我也想说这个。
这个软件小巧简洁，界面直观，不过图标字样在普通电视或小电视上有点小了（本人近视），另外选中操作也不是很明显，感觉可以优化下。
用另外一个app，源失效时候老自动切台都没法操作，这个倒是没有吧，不过换台时间停留也同样短了点。
之前几次黑屏跳出，也不清楚怎么回事（然后现在又好使了），是否做个什么错误提示比较好？

**Comment by qgmzfj** [comment]
+1

> 确实，我也想说这个。 这个软件小巧简洁，界面直观，不过图标字样在普通电视或小电视上有点小了（本人近视），另外选中操作也不是很明显，感觉可以优化下。 用另外一个app，源失效时候老自动切台都没法操作，这个倒是没有吧，不过换台时间停留也同样短了点。 之前几次黑屏跳出，也不清楚怎么回事（然后现在又好使了），是否做个什么错误提示比较好？

错误提示见到过，例如版权问题，后应该是修复了5台问题消失了，不过这种提示速度很快就会消失，并且字有点小

现在还在看电视的人群相对比较简单，老人+孩子居多，建议作者能加大图标，加大提示，加多停留时间，或者提供一个选项，例如加大图标有大中小，文字有大中小，停留时长可以自定义秒数，现实生活中大杯中杯小杯的事还是很常见的，感谢作者为此付出，新年快乐~

**Comment by lizongying** [comment]
最新版本已经做了优化
