### ISSUE TITLE
无法安装，海信电视安卓9系统 提示“安装包无效”，用当贝市场打开安装包提示“应用未安装”

### ISSUE THREAD

**Issue by AustinFan** [lizongying/my-tv#4]

**Comment by AustinFan** [comment]
好用了，需要先把之前的版本卸载

**Comment by lizongying** [comment]
后面的更新会更丝滑些。
之前手动版本v0.x.x，会更新失败（由于安卓默认版本1.0.0），需要卸载更新。
现在已经把版本改到了1.0.0以上，并使用了自动构建。

**Comment by lizongying** [comment]
安卓4的确实有问题。但安卓9似乎大家没有这方面的反馈，如果还是不行，再重起问题吧。
