### ISSUE TITLE
[BUG] 软件升级问题。

### ISSUE THREAD

**Issue by happymy** [lizongying/my-tv#401]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

1.57、1.58、1.60等软件安装包，版本号不同，但是显示版本相同。导致必须先卸载才能安装。
由于众所周知的原因，在线升级。建议使用https://mirror.ghproxy.com/ 代理github raw。

### 预期行为

软件安装为升级。
可在线升级。

### 实际行为

高版本软件安装为重装。
在线升级无法访问github。

### UI / OS

realme

### Android 版本

12

### 额外信息

感谢作者，清晰度真的好高。

**Comment by lizongying** [comment]
在線升級開發尚未完成
