### ISSUE TITLE
[FR] 关于存储在Github的远程资源访问

### ISSUE THREAD

**Issue by fanmingming** [lizongying/my-tv#403]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

实现在中国大陆范围内可以正常获取到Github内的资源。

### 解决方案

通过jsdelivr请求gh的json内容会返回Failed。
@LeGend-wLw my-tv-json-utils仓库内的资源可部署到Cloudflare的Workers & Pages中，以解决内地无法访问的问题。

**Comment by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [comment]
建议用GitHub代理：https://gh-proxy.com/
