### ISSUE TITLE
服务器带宽跑满，为啥会导致软件闪退！？

### ISSUE THREAD

**Issue by zbby1987** [lizongying/my-tv#405]
撑死也只该是黑屏啊

**Comment by whtk** [comment]
请求token，得不到回应，代码里处理token的代码，报异常，到不了显示界面

**Comment by zbby1987** [comment]
应该把所有的错误类型，长时间显示在软件界面，
并且不要像token弹窗提示语那样，自己几秒后就消失



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月11日(周日) 中午12:04
收件人: ***@***.***&gt;;
主题: Re: [lizongying/my-tv] 服务器带宽跑满，为啥会导致软件闪退！？ (Issue #405)




 
请求token，得不到回应，代码里处理token的代码，报异常，到不了显示界面

**Comment by whtk** [comment]
我记得有个帖子贴了 调试软件的情况。你可以自己调试，不然看了异常也没啥用
