### ISSUE TITLE
 src/main/cpp/native.c 文件缺失，大佬能补一下？[BUG] 

### ISSUE THREAD

**Issue by 97Mozart** [lizongying/my-tv#407]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

 src/main/cpp/native.c 文件缺失，大佬能补一下，自启动闪退

### 预期行为

 src/main/cpp/native.c 文件缺失，大佬能补一下，自启动闪退

### 实际行为

 src/main/cpp/native.c 文件缺失，大佬能补一下

### UI / OS

XIAOMI

### Android 版本

13

**Comment by dorisoy** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的 bug report。
> * [x]  我正在使用本软件的最新版本。
> 
> ### my-ty 版本
> 最新稳定版
> 
> ### Bug 描述
> src/main/cpp/native.c 文件缺失，大佬能补一下，自启动闪退
> 
> ### 预期行为
> src/main/cpp/native.c 文件缺失，大佬能补一下，自启动闪退
> 
> ### 实际行为
> src/main/cpp/native.c 文件缺失，大佬能补一下
> 
> ### 复现步骤
> _No response_
> 
> ### UI / OS
> XIAOMI
> 
> ### Android 版本
> 13
> 
> ### 额外信息
> _No response_

![Uploading 微信图片_20240229172459.png…]()
