### ISSUE TITLE
中央2，中央6，中央8无法观看[BUG] 

### ISSUE THREAD

**Issue by awmc233** [lizongying/my-tv#409]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

中央3  6 8 无法观看，问题出现时我正在观看中央8的电视剧，然后突然卡住了，换到另外一个台以后再换就回不去了，具体是按了频道号码，下方也出现了对应频道的名称以及预告，但是画面还是切换之前的频道。（目前已知中央3，6，8不能看了）

### 预期行为

正常播放

### 实际行为

无法切换频道

### 复现步骤

打开软件以后切到中央1，之后打开主菜单（或者按3号台）就可以复现问题

### UI / OS

Android原生

### Android 版本

9

**Comment by jackson-xp** [comment]
+1

**Comment by chenhaoo2020** [comment]
+1

**Comment by panyuming111** [comment]
+1

**Comment by whtk** [comment]
中央三我家看不了 5也不行

**Comment by awmc233** [comment]
我家5还可以，风云的那些没试

**Comment by lizongying** [comment]
已處理
