### ISSUE TITLE
这些不是长效源

### ISSUE THREAD

**Issue by dghgw2022** [lizongying/my-tv#410]
放一定时间后就不能播放了，这些不是长效源

**Comment by dotaqi** [comment]
现在哪有长效源啊，只有不断更新

**Comment by Obizuh** [comment]
免费的就别太挑了，要么就换个空壳软件，自己往里面添加源，要么就花点钱找别人维护的稳定源，或者开个iptv，绝对长效

**Comment by iteratorlee** [comment]
> 免费的就别太挑了，要么就换个空壳软件，自己往里面添加源，要么就花点钱找别人维护的稳定源，或者开个iptv，绝对长效

求问哪里可以找到稳定维护的收费源？

**Comment by huanyusb** [comment]
> > 免费的就别太挑了，要么就换个空壳软件，自己往里面添加源，要么就花点钱找别人维护的稳定源，或者开个iptv，绝对长效
> 
> 求问哪里可以找到稳定维护的收费源？

宽带运营商

**Comment by lizongying** [comment]
#684
