### ISSUE TITLE
[FR] 换台的时候能不能别黑屏 晚上关灯的时候 狗眼闪瞎

### ISSUE THREAD

**Issue by xxlxmd** [lizongying/my-tv#411]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

 换台的时候能不能别黑屏 晚上关灯的时候 狗眼闪瞎

### 解决方案

保留一下之前内容截图或者 切换成功后在平滑切换

### 额外信息

感谢

**Comment by fengjiuge1** [comment]
+1

**Comment by milimilimm** [comment]
毛病真多

**Comment by xxlxmd** [comment]
> 毛病真多

不是毛病 是用了 投影仪 晚上观看的时候 每次换台 房间全黑...然后 房间全亮 然后 房间全黑 房间全亮.... 小is而已

**Comment by sz20000** [comment]
你网络足够快就没事

**Comment by mlzk** [comment]
应该是客户机的问题，小米电视 300m 电信宽带 秒开都是

**Comment by tangdw1028** [comment]
我提过类似问题（https://github.com/lizongying/my-tv/issues/196），被一堆无脑战士一顿喷

**Comment by lizongying** [comment]
最新版已修復，但現在已無法觀看了。可以嘗試下 [我的電視·〇](https://github.com/lizongying/my-tv-0)
