### ISSUE TITLE
[BUG] 中央3无法使用

### ISSUE THREAD

**Issue by PDSB001** [lizongying/my-tv#413]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

换台到中央三时画面停留在上个台的画面,如视频

https://github.com/lizongying/my-tv/assets/132314585/040333b5-b37d-4893-9f96-bc4252020338

### 预期行为

画面切换至CCTV3

### 实际行为

画面停留在原来的频道

### 复现步骤

1.打开mytv
2换台至CCTV3
3. bug复现

### UI / OS

小米

### Android 版本

6.0.1

### 额外信息

我尝试升级和降级mytv,同时升级系统到最新，小米盒子3s，网络环境为大连联通300M宽带，数小时前CCTV3仍可用

**Comment by lizongying** [comment]
已處理
