### ISSUE TITLE
[FR] 希望增加多些频道，像广东珠江等频道没有，最好就可以添加自定义源功能

### ISSUE THREAD

**Issue by MANTOUYAI** [lizongying/my-tv#415]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

可以看更多的频道，以及以后涉及到版权问题时，有自定义源功能时，再由各位大神上传一些源时可以规避一些风险。

### 额外信息

开源大佬幸苦了

**Comment by CJyoung524** [comment]
添加自定义源功能简单，问题是怎么把获取稳定的网页源吧？

**Comment by shengdao001** [comment]
> 添加自定义源功能简单，问题是怎么把获取稳定的网页源吧？

雀食

**Comment by lovingzyz** [comment]
兄弟，你都自定义源了，那么多空壳盒子随便配置啊，这个就简单就好了，适合不折腾的，折腾的有大把的app用

**Comment by maplewang** [comment]
支持自定义源，这样新源会越来越多

**Comment by lizongying** [comment]
#532
