### ISSUE TITLE
添加DLNA投屏的功能[FR] 

### ISSUE THREAD

**Issue by Obizuh** [lizongying/my-tv#416]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

添加这个功能了可以用手机打开app，然后投屏到电脑，电视等局域网其他设备，比较方便快捷，适合短时使用

**Comment by CJyoung524** [comment]
伪需求，本身就是电视应用不需要加

**Comment by ChambersXDU** [comment]
Nonsense

**Comment by lizongying** [comment]
现阶段可能非必要，暂时就不加了。
