### ISSUE TITLE
[BUG] 安卓4.0通过U盘安装时报解析包时错误

### ISSUE THREAD

**Issue by SanLiu1432** [lizongying/my-tv#417]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

[BUG] 安卓4.0.4通过U盘安装时报解析包时出现问题

### 预期行为

[BUG] 安卓4.0.4通过U盘安装时报解析包时出现问题

### 实际行为

[BUG] 安卓4.0.4通过U盘安装时报解析包时出现问题

### 复现步骤

[BUG] 安卓4.0.4通过U盘安装时报解析包时出现问题

### UI / OS

海信

### Android 版本

4.0.4

### 额外信息

release从1.2到1.6安装包都试了一遍,难顶

**Comment by qgmzfj** [comment]
检察一下机器是不是空间满了
或者重新下载一次安装包

**Comment by Leon-2021** [comment]
https://github.com/lizongying/my-tv/issues/208
