### ISSUE TITLE
[BUG] 上下换台经常弹出设置对话框

### ISSUE THREAD

**Issue by xianyunyh** [lizongying/my-tv#418]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

使用上下切换频道的时，设置对话框会偶尔主动弹出，影响体验。

### 预期行为

不频繁弹出设置对话框

### 实际行为

频繁弹出设置对话框

### UI / OS

乐视

### Android 版本

7

**Comment by lizongying** [comment]
#705
