### ISSUE TITLE
[BUG] 天猫智慧屏闪退

### ISSUE THREAD

**Issue by aeoluszzff** [lizongying/my-tv#419]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

启动应用时闪退

### 预期行为

能正常启动

### 实际行为

crashed

### 复现步骤

1. 启动app
2. 闪退

### UI / OS

天猫智慧盒

### Android 版本

9

**Comment by lizongying** [comment]
可以試試1.5.9

**Comment by lizongying** [comment]
[v1.5.9](https://github.com/lizongying/my-tv/releases/tag/v1.5.9)
