### ISSUE TITLE
海外5看不了

### ISSUE THREAD

**Issue by huangzf128** [lizongying/my-tv#42]
日本。
是地区限制吗？

**Comment by lizongying** [comment]
可以试着切换一下，看看是否还能不能看？

**Comment by huangzf128** [comment]
不行哎，除了5和5+，其他的都能看，效果也都很好。
我用的是Chromecast with google TV。
显示4的状态，按下一台没有反应，仍然播放4的内容，再按一下还是一样。然后再按就跳到6了。

**Comment by lizongying** [comment]
@huangzf128 有判断ip的可能性，现阶段就不处理了。请持续关注，方案是有的，但暂时不会上线，如果受影响的人不多的话，望理解。先关闭问题了。
