### ISSUE TITLE
大佬，接受广告赞助吗？

### ISSUE THREAD

**Issue by 8689586** [lizongying/my-tv#420]
只在GitHub上面放条广告，类型机场

**Comment by xujiaxin1017** [comment]
滚

**Comment by asuka555888** [comment]
> 滚
> 

哈哈哈

**Comment by 8689586** [comment]
大过年的你妈是不是死了

**Comment by 8689586** [comment]
> 滚
> 
> 

小畜生你妈是不是死了，问你这个傻逼了吗？小畜生快点回话🐶

**Comment by mzh2077** [comment]
> 小畜生你妈是不是死了，问你这个傻逼了吗？小畜生快点回话🐶

>别败坏社区风气，文明讨论，不想讲话可以不讲

**Comment by mzh2077** [comment]
> 小畜生你妈是不是死了，问你这个傻逼了吗？小畜生快点回话🐶

>别败坏社区风气，文明讨论，不想讲话可以不讲

**Comment by 8689586** [comment]
> 如果你眼睛不好就把嘴闭上，谁先骂的你看不见？
> 
> > 小畜生你妈是不是死了，问你这个傻逼了吗？小畜生快点回话🐶
> 
> 
> 
> >别败坏社区风气，文明讨论，不想讲话可以不讲

**Comment by mzh2077** [comment]
> > 如果你眼睛不好就把嘴闭上，谁先骂的你看不见？
> > > 小畜生你妈是不是死了，问你这个傻逼了吗？小畜生快点回话🐶
> > 
> > 
> > > 别败坏社区风气，文明讨论，不想讲话可以不讲

人家说一个字滚，你就开始对别人父母攻击，很难想象这是一个卖机场的人说出的话，你多大了，是上小学的话那就不计较了

**Comment by 8689586** [comment]
我知道，你妈死的早，你不知道你亲爹是谁的小杂种眼瞎，我就不跟你计较了，大过年的自己出来找骂，是不是啊，小杂种快点回话

Ifm ***@***.***> 于2024年2月17日周六 17:51写道：

**Comment by 8689586** [comment]
> > > 如果你眼睛不好就把嘴闭上，谁先骂的你看不见？
> 
> > > > 小畜生你妈是不是死了，问你这个傻逼了吗？小畜生快点回话🐶
> 
> > > 
> 
> > > 
> 
> > > > 别败坏社区风气，文明讨论，不想讲话可以不讲
> 
> 
> 
> 人家说一个字滚，你就开始对别人父母攻击，很难想象这是一个卖机场的人说出的话，你多大了，是上小学的话那就不计较了

我知道你从小父母双亡，没家教，我也不跟你计较，大过年的不要出来找骂。就算你没家教，你小学老师也告诉过你，滚 是什么性质的词语

**Comment by lizongying** [comment]
感謝關注，暫時不加廣告。

**Comment by mzh2077** [comment]
> > > > 如果你眼睛不好就把嘴闭上，谁先骂的你看不见？
> > 
> > 
> > > > > 小畜生你妈是不是死了，问你这个傻逼了吗？小畜生快点回话🐶
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 别败坏社区风气，文明讨论，不想讲话可以不讲
> > 
> > 
> > 人家说一个字滚，你就开始对别人父母攻击，很难想象这是一个卖机场的人说出的话，你多大了，是上小学的话那就不计较了
> 
> 我知道你从小父母双亡，没家教，我也不跟你计较，大过年的不要出来找骂。就算你没家教，你小学老师也告诉过你，滚 是什么性质的词语

很难想象这是一个成年人说出的话，也不知道你以前父母是如何教你的，我没骂你一句，你就开始人身攻击，注意：这是github，你想找人吵架可以去微博，谢谢

**Comment by 8689586** [comment]
> 很难想象这是一个成年人说出的话，也不知道你以前父母是如何教你的，我没骂你一句，你就开始人身攻击，注意：这是github，你想找人吵架可以去微博，谢谢

就喜欢你看不惯我又干不掉我的样子。
没有对你人身攻击哦，因为没把你当人看。

现实中你跟别人说滚，你看看别人会不会把你牙打掉💩

**Comment by mzh2077** [comment]
> > 很难想象这是一个成年人说出的话，也不知道你以前父母是如何教你的，我没骂你一句，你就开始人身攻击，注意：这是github，你想找人吵架可以去微博，谢谢
> 
> 就喜欢你看不惯我又干不掉我的样子。 没有对你人身攻击哦，因为没把你当人看。
> 
> 现实中你跟别人说滚，你看看别人会不会把你牙打掉💩
github还是有你这种人啊，和微博小鬼没区别了，这个话题关闭了，小鬼就不要老是聊了，好好学习，以后说不定机场被搞了还能搞点正经事干🙏

**Comment by 8689586** [comment]
> > > 很难想象这是一个成年人说出的话，也不知道你以前父母是如何教你的，我没骂你一句，你就开始人身攻击，注意：这是github，你想找人吵架可以去微博，谢谢
> 
> > 
> 
> > 就喜欢你看不惯我又干不掉我的样子。 没有对你人身攻击哦，因为没把你当人看。
> 
> > 
> 
> > 现实中你跟别人说滚，你看看别人会不会把你牙打掉💩
> 
> github还是有你这种人啊，和微博小鬼没区别了，这个话题关闭了，小鬼就不要老是聊了，好好学习，以后说不定机场被搞了还能搞点正经事干🙏
> 
> 大过年的，你这小畜生不是自己出来找骂么😏
小畜生快点回话
