### ISSUE TITLE
希望添加设置开机启动

### ISSUE THREAD

**Issue by leastfrog** [lizongying/my-tv#421]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

    添加开机启动，这样电视开机就能直接打开my-tv看电视。如果总是手动打开，对于老人看电视还是有点麻烦。
    另外希望在线更新尽快推出。每次手动更新，还是不太方便。

**Comment by habacat** [comment]
早就有人提过了，不符合
![image](https://github.com/lizongying/my-tv/assets/41714213/fbc0e34d-54ea-4567-9215-468ded8166e1)

**Comment by xiaoWangSec** [comment]
#400  下个版本应该就有开机自启了, 已经有代码提交了

**Comment by MemoryCollection** [comment]
在线更新我可以提供服务器,阿里云的ecs

**Comment by lizongying** [comment]
最新新版本雖然加了此功能，自測是不生效的，估計大多數設備還是不支持的。
