### ISSUE TITLE
地方卫视能否增加山西卫视等地方卫视频道

### ISSUE THREAD

**Issue by ssyxg23** [lizongying/my-tv#422]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

地方卫视能否增加山西卫视等地方卫视频道

### 解决方案

地方卫视能否增加山西卫视等地方卫视频道

### 额外信息

地方卫视能否增加山西卫视等地方卫视频道

**Comment by lizongying** [comment]
#431
