### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by nulijiazaizhong** [lizongying/my-tv#423]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

江苏地区存在链接不稳定情况，时好时坏

### 预期行为

江苏地区存在链接不稳定情况，时好时坏

### 实际行为

江苏地区存在链接不稳定情况，时好时坏

### 复现步骤

江苏地区存在链接不稳定情况，时好时坏

过段时间再进就可以了

### UI / OS

乐视

### Android 版本

8.0

### 额外信息

江苏地区存在链接不稳定情况，时好时坏

**Comment by lizongying** [comment]
這個問題不太好定位，後面看看是否有同類問題吧
