### ISSUE TITLE
老大，能改个漂亮点的logo吗？[FR] 

### ISSUE THREAD

**Issue by tallguess** [lizongying/my-tv#429]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

美化一下logo会很好

**Comment by sz20000** [comment]
现在的 logo 很好了！不用改！

**Comment by lifeve** [comment]
自己改吧，一步到位。

**Comment by lizongying** [comment]
好看似乎意義不太大，還是感謝建議。
