### ISSUE TITLE
图标能美化下么？

### ISSUE THREAD

**Issue by aston314** [lizongying/my-tv#43]
现在的不是很好看
[
![8FB5DCB2-C776-4A93-9B9C-54351908D168](https://github.com/lizongying/my-tv/assets/2224932/7ab3c0c1-2d05-4c19-a72e-7cfb7e9752c7)
](url)

**Comment by lizongying** [comment]
@aston314  从我的角度看，这几个icon里，我的电视还行。还是十分感谢。

**Comment by Yongqi-Liang** [comment]
给你做了一个，可以考虑用下（MIUI风格），512*512白色背景
@lizongying 
![new_ic_launcher-playstore](https://github.com/lizongying/my-tv/assets/48613878/7cf3bf30-0db6-4bc7-9b58-4be7ab22f988)

**Comment by lizongying** [comment]
@Yongqi-Liang 挺好看的，收藏了。暂时先不动了。
