### ISSUE TITLE
建议修改为更为直观的名称以便老人能够轻易识别

### ISSUE THREAD

**Issue by dachandler7** [lizongying/my-tv#434]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

感谢大佬，已支持！
我是用来给家里的电视用的，目前遇到的问题是，目前的软件名称不是特别直观，老人不能轻易的找到。
如果能够优化一下名称让它再直观一些就好了，例如“电视直播”、“看电视”之类的。
当然这只是个小小的请求，目前的版本已经非常满意了！

**Comment by lizongying** [comment]
感謝建議，暫時名稱先不動了。本身能活下去就不錯了。
