### ISSUE TITLE
[FR] 

### ISSUE THREAD

**Issue by SMGDHHYF** [lizongying/my-tv#435]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

希望能够增加地方频道

### 额外信息

家里有一些老人经常看那些地方频道，例如说广东珠江，大湾区卫视，所以希望作者能够尽快跟进

**Comment by lizongying** [comment]
#557
