### ISSUE TITLE
[FR] 软件很好用

### ISSUE THREAD

**Issue by Hi-360** [lizongying/my-tv#439]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

继续保持  感谢作者的辛苦开发

### 解决方案

继续保持  感谢作者的辛苦开发

### 额外信息

继续保持  感谢作者的辛苦开发

**Comment by lizongying** [comment]
感謝支持
