### ISSUE TITLE
[FR] 是否可以做到软件热更新呢？

### ISSUE THREAD

**Issue by xy-blog** [lizongying/my-tv#445]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

软件热更新，不用每次都在github下载后再安装到电视。

### 解决方案

是否存在这样的可能性：关键的源相关数据放在云服务器，更新时可以直接更新源相关的数据，这样云服务器那边只要提供几个接口就可以，APP只需要在打开时获取一下接口数据，这样可以尽可能减少对云服务器配置的依赖。

### 额外信息

这可能需要作者大大评估一下软件使用量、技术实现细节和投入成本问题，可以跟大家讨论一下热更新的可能性，感谢！

**Comment by ashsteins** [comment]
建议可以导入自定义源 方便源失效时候自己维护

**Comment by xy-blog** [comment]
> 接口配置作为一个json或者xml等格式的文件放在仓库里，软件打开时自动从GitHub仓库获取，连云服务器都省了

国内网络不好访问github，还得是国内的云服务器比较好

**Comment by lizongying** [comment]
無法做到
