### ISSUE TITLE
[FR] 日本电视台的源可以参考这个，已测试大部分都能播放

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#446]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

解决日本电视台的观看问题

### 解决方案

引入
https://iptvcat.com/japan__2

### 额外信息

已测试大部分都能播放

**Comment by ashsteins** [comment]
其中NHK 等电视台还是不错的，既然有CGTN系列外语台，可以加在那个分类那边，反正阿拉伯语台看的人还没看日语的多，哈哈

**Comment by jackson-xp** [comment]
这个可以 不过审查风险增加不少

**Comment by ashsteins** [comment]
> 这个可以 不过审查风险增加不少

现在就有阿拉伯台，基本没人看，如果说境外的话，还可以加台湾台呢，毕竟我国不可分割的一部分

**Comment by sz20000** [comment]
求泰国台

**Comment by lizongying** [comment]
可以关注下这个新项目，会支持自定义源 #532
