### ISSUE TITLE
[FR 建议增加TvOS，MacOS，PadOS和phoneOS版

### ISSUE THREAD

**Issue by Miaohouli** [lizongying/my-tv#447]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

增加用户群体

**Comment by ashsteins** [comment]
不支持，支持安卓出个适配手机竖屏的版本

**Comment by Amamiya23** [comment]
别乱提建议，你说的这些到处都是iptv源，以手机和桌面系统的自由度你自己随便找个专业播放器都能看。你这样辛苦开发者并且封的也很快

**Comment by lizongying** [comment]
#461
