### ISSUE TITLE
[FR] 备用源可参考 Meroser's IPTV的源，已测试可看，很多台

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#448]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

备用源可参考 Meroser's IPTV的源，已测试可看
https://github.com/Meroser/IPTV

### 解决方案

代码地址：https://github.com/Meroser/IPTV

**Comment by ashsteins** [comment]
顶起来

**Comment by lizongying** [comment]
可以关注下这个新项目，会支持自定义源 #532
