### ISSUE TITLE
[BUG] 安卓4, 1.6.0版本用不了了

### ISSUE THREAD

**Issue by GTian28** [lizongying/my-tv#449]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

安卓4, 1.6.0版本用不了了

### 预期行为

正常播放

### 实际行为

黑屏不显示画面

### UI / OS

酷开系统

### Android 版本

4

**Comment by DevilFu** [comment]
+1

**Comment by GTian28** [comment]
今天又能用啦
