### ISSUE TITLE
[FR] 想增加一些以前电视家上面的固定的电视剧频道

### ISSUE THREAD

**Issue by 7tinghua** [lizongying/my-tv#450]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

丰富电视内容

### 解决方案

我老家的人用了这个非常好。但是之前习惯在电视家看那些电视剧，就是固定一个频道专门播某一个特定的电视剧的频道，像雍正王朝、大染坊之类的。我想学习一下代码，但是基础很差。可不可以告诉我，怎么样单独添加一个电视剧的大类，然后里面是各个电视剧的子频道。信号源我去搜。但是我不知道改怎么去修改代码，希望大神们可以指点一下，你们指点一下，可能会给我节省很多很多看代码的时间。感谢！！

**Comment by ashsteins** [comment]
我当时就提出 导入自定义源功能，总有人唱反调，有这个功能我就可以加一些自己喜欢的源了
总有人说 什么APP 什么壳子自己加，废话，那些我当然知道，我只是希望我的电视更完美而已，这样我就可以删了那些壳子

**Comment by lfm09** [comment]
> 我当时就提出 导入自定义源功能，总有人唱反调，有这个功能我就可以加一些自己喜欢的源了 总有人说 什么APP 什么壳子自己加，废话，那些我当然知道，我只是希望我的电视更完美而已，这样我就可以删了那些壳子

赞同

**Comment by ashsteins** [comment]
另外 电视剧之类的  灵犀直播 比较全，老大可以参考一下

**Comment by Ahuangshang** [comment]
有源吗？我改写了一版，可以自己添加源，有兴趣可以下载玩玩

**Comment by ashsteins** [comment]
> 有源吗？我改写了一版，可以自己添加源，有兴趣可以下载玩玩

哪能下载你的改版，我去试试

**Comment by 7tinghua** [comment]
> 有源吗？我改写了一版，可以自己添加源，有兴趣可以下载玩玩

可以就拿这个项目的源码去改呀，我看了一下，config.json里面存了所有频道的信号源，但是还要改一些前端页面的代码，添加一个大类和一些子频道之类的。

**Comment by 7tinghua** [comment]
> 有源吗？我改写了一版，可以自己添加源，有兴趣可以下载玩玩

请问哪里可以下载您的改版呢？我想试试，感谢分享，我去了你的页面没有看到相关的项目

**Comment by Ahuangshang** [comment]
等我晚上给大家一个下载链接，后台管理网站为http://imengu.cn:8082，测试账号：Test,密码：123@qwer,里面的源大家不要乱改哦，如果有能用的源，新增就可以了，版本下载链接：http://imengu.cn:8081/Ahuangshang/apk/lttv.apk.(暂时还是404，晚上8点后可以正常下载)

**Comment by 7tinghua** [comment]
@Ahuangshang 感谢！！这个太牛了！！！ 后台貌似看不到新增源的按钮，我这边就看到三个，修改，删除，和导出。 另外这个是热更新的吗？是不是后台新增了信号源之后，当app启动后就可以自动更新频道了呢？

**Comment by Ahuangshang** [comment]
不好意思，忘了给权限了，现在进去就有了，安装后不能直接观看，需要我这边授权才能观看，我看到有一台设备了，已经授权了.
如果要添加自己的源，请选择其他源，选择央视频是播放不了的，只有选择其他源才能正常观看，保存后，打开APP就可以看到了

**Comment by sz20000** [comment]
帮我授权一下啊ac94a

**Comment by sz20000** [comment]
> 不好意思，忘了给权限了，现在进去就有了，安装后不能直接观看，需要我这边授权才能观看，我看到有一台设备了，已经授权了.
> 
> 如果要添加自己的源，请选择其他源，选择央视频是播放不了的，只有选择其他源才能正常观看，保存后，打开APP就可以看到了

求授权![image](https://github.com/lizongying/my-tv/assets/4333756/dd5e9c57-6c7e-4d21-9e12-0c2dc8d68711)

**Comment by Ahuangshang** [comment]
已授权

**Comment by Ahuangshang** [comment]
大家有源的去添加其他源类型吧，添加了就可以看了

**Comment by Ahuangshang** [comment]
![qrcode_for_gh_d4f98e4045d9_258](https://github.com/lizongying/my-tv/assets/15123689/ed2f7f31-6047-4932-bd24-e772ecde6522)
关注公众号，发送授权，授权更快捷，欢迎大家关注！

**Comment by Ahuangshang** [comment]
打算出个版本，可以自己添加源，本地直接播放，这样用起来会更方便点，就是换设备就要重新导入

**Comment by Ahuangshang** [comment]
重温经典是哪位大神添加的源，又遇到同样的问题了，有画面没声音，这个问题还比较棘手，这是播放源视频编码问题，播放器暂时还不支持这个解码，我要重新编译播放器

**Comment by lfm09** [comment]
> 打算出个版本，可以自己添加源，本地直接播放，这样用起来会更方便点，就是换设备就要重新导入

能否出一个启动时不需要连接远程服务器、不需要授权，可以本地直接添加节目源的版本？谢谢

**Comment by Ahuangshang** [comment]
可以考虑，就是每次要手动添加，换设备就要添加

**Comment by huiwin** [comment]
> 我当时就提出 导入自定义源功能，总有人唱反调，有这个功能我就可以加一些自己喜欢的源了 总有人说 什么APP 什么壳子自己加，废话，那些我当然知道，我只是希望我的电视更完美而已，这样我就可以删了那些壳子

这个还是比较好的、赞同

**Comment by Ahuangshang** [comment]
纠结好久，项目已开源，有兴趣的可以去看看，地址：https://gitee.com/huangshang/lttv

**Comment by lfm09** [comment]
> 可以考虑，就是每次要手动添加，换设备就要添加

这个很正常呀，空壳版都是这样的

**Comment by lizongying** [comment]
#532
