### ISSUE TITLE
[FR] 卫视不全，能否增加个吉林卫视

### ISSUE THREAD

**Issue by limin-tang** [lizongying/my-tv#453]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

卫视不全，能否增加个吉林卫视

**Comment by wxjdsj** [comment]
吉林卫视它也不是省级卫视啊

**Comment by huanyusb** [comment]
> 吉林卫视它也不是省级卫视啊

吉林卫视是省级卫视

**Comment by ashsteins** [comment]
除了吉林，还有不少卫视没有呢，对比灵犀直播 参考下

**Comment by lizongying** [comment]
#557
