### ISSUE TITLE
[BUG] 长虹电视：根据现有法律，无法安装。

### ISSUE THREAD

**Issue by noviceZ** [lizongying/my-tv#456]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

长虹电视，通过手机app推送mytv(1.5.9/1.6.0)到电视上安装，报错提示，根据现有法律不支持安装，要怎么解决。

### 预期行为

完成安装

### 实际行为

报错提示，根据现有法律不支持安装。

### 复现步骤

1.电视上打开“八爪鱼遥控”
2.手机上打开“八爪鱼遥控”
3.在同一网络下连接上，推送mytv，安装进度条完成后报错。

### UI / OS

长虹

### Android 版本

电视版本不确定

### 额外信息

没有使用额外电视盒子，使用的是电视内置的。

**Comment by ashsteins** [comment]
长虹现在不允许外部安装，建议买个盒子

**Comment by noviceZ** [comment]
> 长虹现在不允许外部安装，建议买个盒子

之前电视本身应用商店没有的应用，用这种方法是可以安装的。
比如电视本身没有当贝市场，用这种方法能安装，mytv之前不知道没试过。出了那个政策之后安的mytv

**Comment by jackson-xp** [comment]
应该是八爪鱼把数据上报了呗 换个方式装

**Comment by noviceZ** [comment]
> 应该是八爪鱼把数据上报了呗 换个方式装

我回去试试别的

**Comment by Ahuangshang** [comment]
这个需要使用adb命令安装了

**Comment by noviceZ** [comment]
> 这个需要使用adb命令安装了

怎么操作

**Comment by ashsteins** [comment]
买个盒子吧，不贵，国内电视系统很多限制

**Comment by liuchuancong** [comment]
adb wifi

**Comment by sinfeilong** [comment]
系统降级就可以安装了

**Comment by zjy208723** [comment]
只要是安卓系统的电视或者盒子都能安装，不管啥牌子的电视出现的提示只是为了不让你按装第三方软件，让你用自带的收费软件，为了赚你们的服务费，大家自己百度自己品牌电视安装apk方法，

**Comment by noviceZ** [comment]
貌似就是电视本身系统的原因，最简单方法外接盒子，还有一些贴吧上的方法不知道行不行
