### ISSUE TITLE
[FR] 增加pc版本

### ISSUE THREAD

**Issue by KangLin** [lizongying/my-tv#459]
增加Windows 和 Ubuntu版本

**Comment by Amamiya23** [comment]
pc一堆iptv源，自己找去吧

**Comment by Obizuh** [comment]
VLC多好用，配上ipv6源，很少会失效。要么就用适用于win11的安卓系统，里面安上电视应用也可以用

**Comment by KangLin** [comment]
@Obizuh 哪里有源？

**Comment by Obizuh** [comment]
> @Obizuh 哪里有源？

https://github.com/Meroser/IPTV

**Comment by KangLin** [comment]
@Obizuh 
看了，但没成功。你能详细说下如何用 vlc 播放？

**Comment by lizongying** [comment]
#461
