### ISSUE TITLE
请问native.c 可以放出来吗？万分感谢！

### ISSUE THREAD

**Issue by 1993571506** [lizongying/my-tv#46]
请问native.c 可以放出来吗？万分感谢

**Comment by lizongying** [comment]
这个项目涉及的加密挺多的，大部分都已经公开了，只有少量加密在native.c。为了让项目能维持一段时间，也为了大家的安全，就不放源码了，对于有些同学，补上应该不是问题，毕竟完全公开不合适。望理解。

**Comment by 1993571506** [comment]
我想自己打包一个独特的版本给家里老人用，不知道是不是我自己打包的原因，libnative.so始终无法调用生成ckey
