### ISSUE TITLE
源码编译运行 发现加密和hash 返回的值都是null  导致签名失败[BUG] 

### ISSUE THREAD

**Issue by skusdk** [lizongying/my-tv#465]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新 CI 版

### Bug 描述

PIS_SO_BUILD=false
我本地编译运行
cKey = encryptor!!.encrypt(cnlid, timeStr, appVer, guid, platform)
signature = getSignature()
一个加密，一个hash都是null，这是为啥

cmake {
                arguments "-DIS_SO_BUILD=${project.hasProperty('IS_SO_BUILD') ? project.IS_SO_BUILD : false}"

                abiFilters "armeabi-v7a", "arm64-v8a"
            }
            
这里我改成了false

### 预期行为

正常应该返回对应的签名值

### 实际行为

签名失败

### UI / OS

XIAOMI

### Android 版本

11

**Comment by xiaoWangSec** [comment]
涉及加密, 部分代码未上传, #34  #278

**Comment by kennyworld** [comment]
我改成IS_SO_BUILD = false时，编译的apk打开闪退。但是 IS_SO_BUILD = true时 需要 src/main/cpp/native.c   文件，源码里没有。

**Comment by xiaoWangSec** [comment]
> 我改成IS_SO_BUILD = false时，编译的apk打开闪退。但是 IS_SO_BUILD = true时 需要 src/main/cpp/native.c 文件，源码里没有。

我也是这样。理论上讲没有native.c可以直接使用编译好的libnative.so进行外部方法调用，但是会闪退。
我无法连接logcat查看错误日志

**Comment by skusdk** [comment]
> 我改成IS_SO_BUILD = false时，编译的apk打开闪退。但是 IS_SO_BUILD = true时 需要 src/main/cpp/native.c 文件，源码里没有。

打开闪退，是你apk没有签名导致的，用证书签名就可以了。

现在的问题是编译运行都正常，就是签名数据有问题，调用那个签名函数返回null，不知道为啥，照道理应该是没有问题的，因为github Action 编译出来的都能正常用

**Comment by kennyworld** [comment]
> > 我改成IS_SO_BUILD = false时，编译的apk打开闪退。但是 IS_SO_BUILD = true时 需要 src/main/cpp/native.c 文件，源码里没有。
> 
> 打开闪退，是你apk没有签名导致的，用证书签名就可以了。
> 
> 现在的问题是编译运行都正常，就是签名数据有问题，调用那个签名函数返回null，不知道为啥，照道理应该是没有问题的，因为github Action 编译出来的都能正常用

生成的是签名apk。你在实机上正常打开没问题？

**Comment by skusdk** [comment]
> > > 我改成IS_SO_BUILD = false时，编译的apk打开闪退。但是 IS_SO_BUILD = true时 需要 src/main/cpp/native.c 文件，源码里没有。
> > 
> > 
> > 打开闪退，是你apk没有签名导致的，用证书签名就可以了。
> > 现在的问题是编译运行都正常，就是签名数据有问题，调用那个签名函数返回null，不知道为啥，照道理应该是没有问题的，因为github Action 编译出来的都能正常用
> 
> 生成的是签名apk。你在实机上正常打开没问题？

源码里面都没有证书，你咋签名的，命令编译出来的是没有签名的。

我现在运行都正常，就是签名有问题， 返回null，数据验签不通过

**Comment by kennyworld** [comment]
> > > > 我改成IS_SO_BUILD = false时，编译的apk打开闪退。但是 IS_SO_BUILD = true时 需要 src/main/cpp/native.c 文件，源码里没有。
> > > 
> > > 
> > > 打开闪退，是你apk没有签名导致的，用证书签名就可以了。
> > > 现在的问题是编译运行都正常，就是签名数据有问题，调用那个签名函数返回null，不知道为啥，照道理应该是没有问题的，因为github Action 编译出来的都能正常用
> > 
> > 
> > 生成的是签名apk。你在实机上正常打开没问题？
> 
> 源码里面都没有证书，你咋签名的，命令编译出来的是没有签名的。
> 
> 我现在运行都正常，就是签名有问题， 返回null，数据验签不通过

我又试了下，是versionCode为null 造成的闪退，改掉后能正常打开。但是频道都看不了，不知道是不是你说的签名问题。

**Comment by lizongying** [comment]
@skusdk 有驗證。不太方便大範圍傳播，望理解。除了不能播放，其他操作應該可以。
