### ISSUE TITLE
[FR] 新版本1.60 与 1.59 今天首次安装后可以使用，下午开始不能使用烦请更新~

### ISSUE THREAD

**Issue by goodmen001** [lizongying/my-tv#467]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

新版本1.60 与 1.59 今天首次安装后可以使用，下午开始不能使用烦请更新~

### 解决方案

新版本1.60 与 1.59 今天首次安装后可以使用，下午开始不能使用烦请更新~

**Comment by goodmen001** [comment]
补充，安装手机系统为华为鸿 ，卸载后，重新安装1.59 ，只能显示一个频道，换台数字可以跳动，但是内容不变，只有一个台。

**Comment by yxhy1010** [comment]
我这里一切正常，版本1.60的。

**Comment by sz20000** [comment]
不支持鸿蒙

**Comment by lizongying** [comment]
使用最新版本
