### ISSUE TITLE
没有我最爱我珠江卫视[FR] 

### ISSUE THREAD

**Issue by Senagee** [lizongying/my-tv#469]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

增加珠江卫视

### 解决方案

 。

### 额外信息

。

**Comment by ccav14** [comment]
珠江卫视是什么鬼

**Comment by ashsteins** [comment]
没有我最爱的延边卫视，我也会说

**Comment by ashsteins** [comment]
没有我最爱的厦门卫视，我继续说

**Comment by ashsteins** [comment]
粤语区需要，那其他方言区也需要，来呗。晋方言、吴方言、闽方言、客家方言、粤方言、湘方言、赣方言、徽方言

**Comment by oneisall8955** [comment]
广东的珠江台，很经典

**Comment by ashsteins** [comment]
延边卫视，很经典

**Comment by Scott0902** [comment]
荔枝网是广东台的官方电视源，包括珠江频道、广东卫视、大湾区卫视、广东民生、广东少儿等，清晰度只有540，采用wasm加密m3u8链接，但这个不是静态链接，网站采用ws协议动态更新，使得播放链接每隔十分钟不等就会失效。

**Comment by lizongying** [comment]
#557
