### ISSUE TITLE
[FR] 建议增加延边卫视频道，中国唯一一家朝鲜语卫星电视媒体，了解朝韩文化

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#472]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

延边卫视（现国家广电总局备案全称：吉林广播电视台延边卫视频道 ，中国唯一一家朝鲜语卫星电视媒体。2006年8月10日正式上星播出。覆盖范围包括中国境内的东北三省、山东半岛、京、津等部分朝鲜族聚居地区，以及朝鲜半岛、日本、俄罗斯远东地区。现节目全天播出时长约为20小时，朝汉语比例约为1:1。延边卫视已在全国25个地区、100多个县（市）级的电视网络实现了落地播出，收视覆盖人口突破了一亿。

### 解决方案

主要是朝鲜族相关，也是说汉语和韩语对半开

### 额外信息

延边卫视是国内第一家自治州上星的电视台，对外宣传延边，让国人了解延边，亲近延边有着独特的现实意义。

**Comment by lizongying** [comment]
#557
