### ISSUE TITLE
[FR]  建议增加厦门卫视，闽台文化为特色的专业卫星频道，经常介绍台湾相关

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#473]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

厦门卫视（Xiamen Star TV）是厦门广播电视集团旗下的卫星电视频道，于2005年2月1日正式开播。这是中国大陆地区第一个以闽台文化为特色的卫星频道，节目以普通话、闽南话双语播出，以传递两岸资讯，推动两岸交流，弘扬闽南文化，传播华夏文明为宗旨，全天24小时播出。
2013年6月起，厦门卫视落地北京、上海、福建等全国九省市， 
并通过长城平台，实现对亚洲、欧洲、美国、加拿大、拉丁美洲、澳大利亚、新西兰等国家及台湾地区的覆盖。2015年3月30日起，厦门卫视实现高清播出，启用“蓝底白鹭”版台标。
![厦门卫视的搜索结果_百度图片搜索](https://github.com/lizongying/my-tv/assets/157224414/204451a6-6b0c-42d1-802b-605c938e315b)

### 解决方案

厦门卫视以厦门腔闽南语节目为主，以娱乐、文化、艺术和新闻资讯为主要内容。全天播出19个小时，每天首播6小时自制节目，其中闽南语节目占播出总量的2/3，全天候滚动播出字幕新闻。2013年3月末，为了增强在中国国内的覆盖，厦门卫视与东南卫视捆绑使用中星6B卫星、开始以普通话广播，而在亚太5号卫星上的厦门卫视则继续以厦门腔闽南语节目为主。2014年2月11日起，厦门卫视高清版在厦门市内测试播出，标清版也开始过渡16:9压缩播出。

### 额外信息

对岸就是此岸，厦门卫视率先提出“两岸共同新闻”的理念，推出两岸传媒界内容共享、平台互动的《两岸新新闻》。节目以“离台湾最近的大陆视角、厦门视角”观察两岸，像关心家人一样关切两岸，速评两岸，深读中国。

厦门卫视主要介绍台湾相关，推荐引入

**Comment by lizongying** [comment]
#557
