### ISSUE TITLE
[FR] 建议增加三沙卫视，主要报道南海局势相关，能让家里人了解中国南海的新闻

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#475]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

三沙卫视是于2013年2月获国家广电总局批准的电视台，于2013年9月3日开播 2018年6月27日，三沙卫视将播出画面由4:3改为16:9。
三沙卫视是一个综合性的电视频道，全天24小时播出，将重点反映海南省特别是三沙市的经济社会发展、资源开发利用、海底考古发现和南海海洋资源保护等方面的状况。
满足三沙市居民及驻岛官兵的生产、生活以及文化娱乐等方面需求，促进与南海周边国家和地区的文化交流和民间交流。

### 解决方案

了解南海局势推荐该频道。

### 额外信息

有很大的政治作用，让青少年了解南海是中国的一部分

**Comment by helloworld10010** [comment]
神tm政治作用，操的心不少

**Comment by sz20000** [comment]
支持

**Comment by AItext1** [comment]
这么关心南海怎么不去办个电信的IPTV，这点钱都舍不得花吗？

**Comment by ashsteins** [comment]
> 这么关心南海怎么不去办个电信的IPTV，这点钱都舍不得花吗？

留着给你烧纸的钱

**Comment by lizongying** [comment]
哎，要是官方這麼跟我說得有多好！
