### ISSUE TITLE
建议代码不开源

### ISSUE THREAD

**Issue by HuShanquan3** [lizongying/my-tv#476]
代码开源有几个问题:
1.抓取你的直播源成本就降低了，任何人都用直播源就泛滥了，到时候必然会卡顿，或者失效几率增大，找源容易，但稳定的太少。
2.央视频逆向接口如果被其他人大量使用官方修复会更频繁，其二央视频盗源可能引来不必要的麻烦。
综上:建议代码不开源，apk最好加固防止逆向，只发布apk更新即可或者参考tvbox以热更新插件方式更新更方便。

**Comment by sjk7524068** [comment]
@ashsteins 这个可行，将源和应用做一个切割，避免被审查

**Comment by 1309276666** [comment]
v1.6.2这个版本在天猫盒子上还是闪退。我试过1.4.2到最新的都是在闪退。下个版本能否给解决！

**Comment by zbby1987** [comment]
> v1.6.2这个版本在天猫盒子上还是闪退。我试过1.4.2到最新的都是在闪退。下个版本能否给解决！

1.5.9没修复？

**Comment by 1309276666** [comment]
没有我已经安装了。1.5.9的版本了也是闪退！还请重新验证一下谢谢！




万维网络
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lizongying/my-tv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月22日(星期四) 下午5:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lizongying/my-tv] 建议代码不开源 (Issue #476)





  
v1.6.2这个版本在天猫盒子上还是闪退。我试过1.4.2到最新的都是在闪退。下个版本能否给解决！
  
1.5.9没修复？

**Comment by helloworld10010** [comment]
> 代码开源有几个问题: 1.抓取你的直播源成本就降低了，任何人都用直播源就泛滥了，到时候必然会卡顿，或者失效几率增大，找源容易，但稳定的太少。 2.央视频逆向接口如果被其他人大量使用官方修复会更频繁，其二央视频盗源可能引来不必要的麻烦。 综上:建议代码不开源，apk最好加固防止逆向，只发布apk更新即可或者参考tvbox以热更新插件方式更新更方便。

玩的就是独乐乐不如众乐乐，你当人家黑奴呢天天给你维护

**Comment by zbby1987** [comment]
确实是，干脆就给你楼主一个人维护，这样速度最快，最安全。


也不想想github是干啥的地方，为啥发在这儿





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月23日(周五) 晚上6:02
收件人: ***@***.***&gt;;
***@***.***&gt;;
主题: Re: [lizongying/my-tv] 建议代码不开源 (Issue #476)




  
代码开源有几个问题: 1.抓取你的直播源成本就降低了，任何人都用直播源就泛滥了，到时候必然会卡顿，或者失效几率增大，找源容易，但稳定的太少。 2.央视频逆向接口如果被其他人大量使用官方修复会更频繁，其二央视频盗源可能引来不必要的麻烦。 综上:建议代码不开源，apk最好加固防止逆向，只发布apk更新即可或者参考tvbox以热更新插件方式更新更方便。
  
玩的就是独乐乐不如众乐乐，你当人家黑奴呢天天给你维护

**Comment by dfhuang-gd** [comment]
不开源？这个平台的意义是什么？

**Comment by fanmingming** [comment]
只要能播放就能抓到源，没有所谓的闭源就抓不到源的说法。

**Comment by zbby1987** [comment]
确实是



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月27日(周二) 中午11:46
收件人: ***@***.***&gt;;
***@***.***&gt;;
主题: Re: [lizongying/my-tv] 建议代码不开源 (Issue #476)




 
只要能播放就能抓到源，没有所谓的闭源就抓不到源的说法。

**Comment by AppleMate60pro** [comment]
可能他以为加密了就抓不到了吧

**Comment by AppleMate60pro** [comment]
> @ashsteins 这个可行，将源和应用做一个切割，避免被审查

你也是个麻瓜，作者在更新着源你还不感激，到时真要成壳一样自定义源，要你们到处找源天天更新源，你们又在叽叽哇哇

**Comment by zbby1987** [comment]
确实是，
这软件最最核心的价值其实在于源本身，
软件虽然也很好，但毕竟市面上已经有了太多现成的壳。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月27日(周二) 下午2:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [lizongying/my-tv] 建议代码不开源 (Issue #476)




  
@ashsteins 这个可行，将源和应用做一个切割，避免被审查
  
你也是个麻瓜，作者在更新着源你还不感激，到时真要成壳一样自定义源，要你们到处找源天天更新源，你们又在叽叽哇哇

**Comment by ashsteins** [comment]
> > @ashsteins 这个可行，将源和应用做一个切割，避免被审查
> 
> 你也是个麻瓜，作者在更新着源你还不感激，到时真要成壳一样自定义源，要你们到处找源天天更新源，你们又在叽叽哇哇

你就是沙比

**Comment by AppleMate60pro** [comment]
@zbby1987这个优点就是秒开台秒换台，源最核心。倘若可以稳定一个版本，看不了可以后台更新源就好了，不用再下载app重新安装，其他功能并不需要，主要就是看电视，简单方便。你们是否知道秒看tv，就类似这样，看不了了后台更新源即可

**Comment by lizongying** [comment]
感謝建議。開源確實會有這些問題，就這樣吧，都這樣了。
