### ISSUE TITLE
[FR] 目前需要增加的补全的卫视频道汇总。

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#478]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

CETV-1 综合教育、CETV-2 空中课堂、CETV-3 教育服务、CETV-4 职业教育

高清： 湖南卫视、浙江卫视、东方卫视、北京卫视、江苏 卫视、安徽卫视、重庆卫视、东南卫视、甘肃卫视、广东卫视、广西卫视、贵州卫视、海南卫视、河北卫视、黑龙江卫视、河南卫视、湖北卫视、江西卫视、吉林卫视、辽宁卫视、山东卫视、深圳卫视、四川卫视、天津卫视、云南卫视、新疆卫视、三沙卫视
标清： 青海卫视、陕西卫视、山西卫视、西藏卫视、内蒙古卫视、宁夏卫视、兵团卫视、安多卫视、康巴卫视、大湾区卫视、农林卫视、延边卫视、厦门卫视

数字高清/38个频道
CHC高清电影、CHC家庭影院、CHC动作电影、求索纪录、求索科学、求索动物、求索生活、黑莓电影、黑莓动画、哒啵电竞、哒啵赛事、乐游、纪实人文、纯享4K、风云剧场、风云音乐、第一剧场、女性时尚、 风云足球、兵器科技、怀旧剧场、世界地理、文化精品、央视台球、高尔夫网球、电视指南、都市剧场、金色学堂、哈哈炫动、游戏风云、欢笑剧场、第一财经、武术世界、文物宝库、梨园、天元围棋、弈坛春秋、劲爆体育

国际时事/15个频道
凤凰中文、凤凰资讯、凤凰香港、NHK World、CNA、AlJazeera、Arirang TV、RT News、RT Documentary、CGTN、CGTN Documentary、CGTN Français、CGTN Русский、CGTN Español、CGTN العربية

### 解决方案

大佬可以对比一下 目前少哪些频道，主要少吉林卫视、三沙卫视、延边卫视、厦门卫视等。

**Comment by SMGDHHYF** [comment]
能不能新增地方频道

**Comment by ccav14** [comment]
有源吗，就算有能做到秒开吗

**Comment by sz20000** [comment]
> 能不能新增地方频道

能不能买套别墅给你？

**Comment by lizongying** [comment]
已增加鳳凰衛視[v1.6.1](https://github.com/lizongying/my-tv/releases/tag/v1.6.1)
