### ISSUE TITLE
请问现在支持在线更新了吗

### ISSUE THREAD

**Issue by qinys36** [lizongying/my-tv#479]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

请问现在支持在线更新了吗

**Comment by fy403** [comment]
首先得感谢作者提供这样优秀的软件，对于一些机器上安装mytv看电视是非常方便的；
但有时候需要隔几天就需要手动升级一下，这对于IT人是一件普通的事情，但对于一些不懂技术的父辈们，就显得很困难。
我目前是自己写一个apk去检测是否需要更新，然后下载并更新。
### 原理大致如下
```shell
tag=$(curl -Ls  -H "Accept: application/vnd.github+json" \
 -H "X-GitHub-Api-Version: 2022-11-28" \
 https://api.github.com/repos/lizongying/my-tv/releases/latest \
 | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
wget --content-disposition -O my-tv.apk https://github.com/lizongying/my-tv/releases/download/${tag}/my-tv-${tag}.apk
#curl -L -o my-tv.apk -k -A "curl/7.81.0" -H "Accept: */*" "https://github.com/lizongying/my-tv/releases/download/${tag}/my-tv-${tag}.apk"'
```
即先获取github的最新release版本，然后使用可重定向的下载工具下载即可。
[编写apk的参考blog：[自动版本升级](https://blog.csdn.net/ahuyangdong/article/details/119456466#:~:text=1%20App%E7%AB%AF%E5%90%91%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%8F%91%E9%80%81%E7%BD%91%E7%BB%9C%E8%AF%B7%E6%B1%82%EF%BC%8C%E8%8E%B7%E5%8F%96App%E7%9A%84%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%AC%E5%8F%B7%E4%BF%A1%E6%81%AF%EF%BC%8C%E8%BF%9B%E8%A1%8C%E6%AF%94%E8%BE%83%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%9C%8D%E5%8A%A1%E7%AB%AF%E8%BF%94%E5%9B%9E%E7%9A%84%E7%89%88%E6%9C%AC%E5%8F%B7%E5%A4%A7%E4%BA%8E%E5%BD%93%E5%89%8DApp%E7%9A%84%E7%89%88%E6%9C%AC%E5%8F%B7%EF%BC%8C%E5%88%99%E5%BC%80%E5%90%AF%E7%AC%AC%E4%BA%8C%E6%AD%A5%EF%BC%8C%E4%B8%8B%E8%BD%BD%E6%96%B0%E7%89%88%E6%9C%ACApp%EF%BC%9B%202,%E6%9C%89%E6%96%B0%E7%89%88%E6%9C%ACApp%E6%97%B6%EF%BC%8C%E5%BC%80%E5%90%AF%E4%B8%8B%E8%BD%BD%EF%BC%8C%E5%B9%B6%E5%9C%A8%E7%95%8C%E9%9D%A2%E4%B8%8A%E7%BB%99%E5%87%BA%E4%B8%8B%E8%BD%BD%E8%BF%9B%E5%BA%A6%E6%8F%90%E7%A4%BA%EF%BC%8C%E5%A2%9E%E5%8A%A0%E4%BA%A4%E4%BA%92%E6%80%A7%EF%BC%9B%203%20%E5%9C%A8%E4%B8%8B%E8%BD%BD%E8%BE%BE%E5%88%B0100%25%E7%9A%84%E8%BF%9B%E5%BA%A6%E6%97%B6%EF%BC%8C%E9%80%9A%E8%BF%87%E4%BB%A3%E7%A0%81%E6%89%93%E5%BC%80apk%E5%AE%9E%E7%8E%B0%E5%AE%89%E8%A3%85%E3%80%82)

**Comment by fy403** [comment]
[app-debug.zip](https://github.com/lizongying/my-tv/files/14382182/app-debug.zip)
可以试试这个apk的手动升级，api接口用的是gitee的，对国内的下载友好些

**Comment by sz20000** [comment]
做个成品给大家下载啊

**Comment by fy403** [comment]
> 做个成品给大家下载啊

好家伙，你但凡下载一下app-debug.zip文件都知道发的apk就是做好的关于mytv的

**Comment by qinys36** [comment]
感谢感谢。。我去试试

**Comment by xuzhen9876543** [comment]
> > 做个成品给大家下载啊
> 
> 好家伙，你但凡下载一下app-debug.zip文件都知道发的apk就是做好的关于mytv的

应用是非正式发布版本，当前设备不支持安装
鸿蒙4.0

**Comment by fy403** [comment]
> > > 做个成品给大家下载啊
> > 
> > 
> > 好家伙，你但凡下载一下app-debug.zip文件都知道发的apk就是做好的关于mytv的
> 
> 应用是非正式发布版本，当前设备不支持安装 鸿蒙4.0

主要我不是搞安卓开发的，能力有限，这个功能还是希望作者支持

**Comment by sz20000** [comment]
> > 做个成品给大家下载啊
> 
> 
> 
> 好家伙，你但凡下载一下app-debug.zip文件都知道发的apk就是做好的关于mytv的

感谢大佬！

**Comment by eric1ee** [comment]
应用程序安装失败
![83819f9dd88c0acf13c466ba8906562](https://github.com/lizongying/my-tv/assets/23067121/d6eefcb7-8adc-4fa9-9277-9ee51f0dcb2c)

**Comment by sz20000** [comment]
小米电视安装失败

**Comment by ni7ht** [comment]
> [app-debug.zip](https://github.com/lizongying/my-tv/files/14382182/app-debug.zip) 可以试试这个apk的手动升级，api接口用的是gitee的，对国内的下载友好些

兄弟，斐讯N1安卓7安装失败，这个有版本要求吗？

**Comment by fy403** [comment]
我的是安卓tv10可以

> 斐讯N1安卓7

![image](https://github.com/lizongying/my-tv/assets/51740518/54cf6853-278e-4746-9f3a-d8974640aeb8)
目前在安卓10tv上可以运行，其它平台还没有调试

**Comment by fy403** [comment]
> 应用程序安装失败 ![83819f9dd88c0acf13c466ba8906562](https://private-user-images.githubusercontent.com/23067121/307631711-d6eefcb7-8adc-4fa9-9277-9ee51f0dcb2c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTUzOTksIm5iZiI6MTcwODkxNTA5OSwicGF0aCI6Ii8yMzA2NzEyMS8zMDc2MzE3MTEtZDZlZWZjYjctOGFkYy00ZmE5LTkyNzctOWVlNTFmMGRjYjJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAyMzgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNTgyMGViMzE5MzQ4Y2ZhMzhkNWZmMzIyYTZkNDA1ODU1NGVjZjQ2ZjEyMTBhY2JkOTg0NGI4YzhkNDU1NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dI71yM43Mm61X530kCIOORAOynQ2C6OZRB_tNHVMzcg)



> > [app-debug.zip](https://github.com/lizongying/my-tv/files/14382182/app-debug.zip) 可以试试这个apk的手动升级，api接口用的是gitee的，对国内的下载友好些
> 
> 兄弟，斐讯N1安卓7安装失败，这个有版本要求吗？报错跟上面兄弟的截图一样



> 小米电视安装失败

这是修改的源码地址[mytv-manual-update](https://github.com/fy403/mytv-manual-update.git)，可自行适配一下

**Comment by webcrawler** [comment]
@fy403 666

**Comment by sz20000** [comment]
> 自行

apk下载地址呢？

**Comment by kukudemajia** [comment]
这个功能真的非常有必要，希望能够内置。

**Comment by lizongying** [comment]
#575
