### ISSUE TITLE
有在线升级的计划吗？

### ISSUE THREAD

**Issue by caoenergy** [lizongying/my-tv#48]
大佬有在线升级的计划吗？如果有的话能不能考虑在gitee发版，这样在电视上升级网络相对容易一点

**Comment by zbby1987** [comment]
你觉得这种软件能在gitee发么？牢底坐穿？

**Comment by caoenergy** [comment]
好吧，大佬太肝了发版非常勤，所以想问有没有在线升级的计划，非常感谢大佬！

**Comment by ccav14** [comment]
这升级得也太频繁了吧

**Comment by zanzhz1101** [comment]
ota需要服务器或者对象存储，成本过高了，权限也不一定有，使用隐式Intent来启动系统默认的浏览器下载apk倒是没啥问题

**Comment by lizongying** [comment]
暂无计划
