### ISSUE TITLE
[FR] 可否增加软解/硬解的开关？

### ISSUE THREAD

**Issue by Scott0902** [lizongying/my-tv#481]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

部分电视盒子使用硬件解码的话，会强力降噪、涂抹和锐化，画质会变得像水彩画、油画一般，只要切换为软解，画质就正常了。

### 解决方案

目前My-tv默认使用硬解，希望大佬能像其他软件一样可以增加硬解/软解的开关。谢谢！

**Comment by AppleMate60pro** [comment]
@Scott0902 换个盒子吧，换个好点的盒子起码看别的能带得起4K

**Comment by Scott0902** [comment]
> @Scott0902 换个盒子吧，换个好点的盒子起码看别的能带得起4K

我有两个盒子：
（1）RK3328（1+8G）
（2）S905X3（4+32G）
两个盒子都能硬解4K以及H265，后者的配置虽然高一点，但硬解会强力降噪和锐化，画质油画化。前者的配置更旧，但硬解和软解的画质都不错。

**Comment by lizongying** [comment]
後面會加入軟解
