### ISSUE TITLE
[BUG] 旧版本无数据

### ISSUE THREAD

**Issue by xiaohange** [lizongying/my-tv#482]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

过年的时候安装的通用版本 my-tv-v1.5.3.apk，没几天就请求不到数据了，难道每次都要重新安装新版本吗？不能做在线更新？

### 预期行为

过年的时候安装的通用版本 my-tv-v1.5.3.apk，没几天就请求不到数据了，难道每次都要重新安装新版本吗？不能做在线更新？

### 实际行为

过年的时候安装的通用版本 my-tv-v1.5.3.apk，没几天就请求不到数据了，难道每次都要重新安装新版本吗？不能做在线更新？

### 复现步骤

过年的时候安装的通用版本 my-tv-v1.5.3.apk，没几天就请求不到数据了，难道每次都要重新安装新版本吗？不能做在线更新？

### UI / OS

海信

### Android 版本

12

### 额外信息

过年的时候安装的通用版本 my-tv-v1.5.3.apk，没几天就请求不到数据了，难道每次都要重新安装新版本吗？不能做在线更新？

**Comment by AppleMate60pro** [comment]
@xiaohange 手动升级1.6.0吧旧版本都看不了了

**Comment by xiaohange** [comment]
> @xiaohange 手动升级1.6.0吧旧版本都看不了了

好吧
