### ISSUE TITLE
能否添加安徽广播电视的频道

### ISSUE THREAD

**Issue by YRK-Max** [lizongying/my-tv#485]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

能否添加安徽广播电视的频道，比如安徽经济生活频道

**Comment by ashsteins** [comment]
能否添加 辽宁地方频道，如辽宁体育

**Comment by lizongying** [comment]
#557
