### ISSUE TITLE
[FR] 什么时候可以支持广东珠江台

### ISSUE THREAD

**Issue by BiapGit** [lizongying/my-tv#486]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

 什么时候可以支持广东珠江台

### 解决方案

 什么时候可以支持广东珠江台

### 额外信息

 什么时候可以支持广东珠江台

**Comment by ashsteins** [comment]
什么时候可以支持延边卫视

**Comment by BiapGit** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ashsteins** [comment]
什么时候可以支持厦门卫视，我也会说

**Comment by ieiian** [comment]
希望可以支持南方卫视（大湾区卫视），老人家喜欢看个

**Comment by ashsteins** [comment]
希望可以支持延边卫视，朝鲜族同胞需要看这个

**Comment by Scott0902** [comment]
荔枝网是广东台的官方电视源，包括珠江频道、广东卫视、大湾区卫视、广东民生、广东少儿等，清晰度只有540，采用wasm加密m3u8链接，但这个不是静态链接，网站采用ws协议动态更新，使得播放链接每隔十分钟不等就会失效。

**Comment by lizongying** [comment]
#557

**Comment by BiapGit** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
