### ISSUE TITLE
建议额外做一个【独立的空壳直播app+直播源的模式】的版本

### ISSUE THREAD

**Issue by zbby1987** [lizongying/my-tv#49]
参考派大星直播app，完美兼容安卓4 ，可开机自启动。
下载链接：https://share.feijipan.com/s/91Uk5k0e
.
独立直播壳app优势：
1，源地址出问题，如某个台时效了，只改(在线源地址/特定格式或加密的本地源地址文件)即可，不用重新发软件版本。
2，降低开发者相关法律风险。
3，可自定义一个直播源文件格式，同时兼容现有直播源文件格式。
4，源地址可默认预置进app，也可有用户自行填写，灵活度高。
.
缺点：
对动手能力差的中老年用户不友好，
他们大概率不会自己填写源地址

**Comment by lizongying** [comment]
会考虑，很大可能会这么做。
