### ISSUE TITLE
CCTV5没有版权[FR] 

### ISSUE THREAD

**Issue by Feeccm** [lizongying/my-tv#490]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

恢复版权

**Comment by Audioboat** [comment]
I am in Melbourne Australia, no CCTV5 or CCTV5+ can be viewed.

**Comment by sz20000** [comment]
小米电视cctv5 一切正常

**Comment by homerhan** [comment]
人在新西兰，用的amazon fire tv电视棒，cctv5 cctv5+也是无法观看，别的都没问题

**Comment by Audioboat** [comment]
但我用爱一帆或晨星电视就沒有问题。

**Comment by nomoneynolife** [comment]
> 人在日本，cctv5 cctv5+也是无法观看

巴嘎巴嘎

**Comment by lizongying** [comment]
#395
