### ISSUE TITLE
[BUG] 1.6.1版本增加的凤凰卫视不能正常播放。。。

### ISSUE THREAD

**Issue by drw2005** [lizongying/my-tv#491]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

凤凰卫视切换不出来，无法播放。
其他台都正常！

### 预期行为

正常播放凤凰卫视

### 实际行为

无法播放。

### UI / OS

小米电视

### Android 版本

6

**Comment by sz20000** [comment]
小米电视，一切正常！凤凰三个台。全部秒播！完美！

**Comment by ashsteins** [comment]
一切正常！凤凰三个台，就是清晰度不高

**Comment by drw2005** [comment]
找到原因了，连接手机热点，用流量能正常播放。
这样看来是家里的路由器拦截了凤凰三个台，正在找原因。

**Comment by wind-3364** [comment]
小米电视一切正常，不要开梯子。

**Comment by drw2005** [comment]
> 小米电视一切正常，不要开梯子。

开了也没事，上次更换了下规则，现在已经正常了。
