### ISSUE TITLE
港澳台终于有了！建议新增合法的娱乐台。香港面包台

### ISSUE THREAD

**Issue by sz20000** [lizongying/my-tv#492]
直播信号来自官网
http://www.breadradioonline.com

**Comment by sz20000** [comment]
香港卫视，官网直播

http://www.hkstv.tv/?mod=index&do=live&tpl=phone

**Comment by zbby1987** [comment]
> 香港卫视，官网直播
> 
> http://www.hkstv.tv/?mod=index&do=live&tpl=phone

打不开，提示什么异常行为

**Comment by lizongying** [comment]
对网络有要求

**Comment by ashsteins** [comment]
> 对网络有要求

https://iptvcat.com/s/%E9%9D%A2%E5%8C%85   面包台的源
