### ISSUE TITLE
凤凰三个台的高清版。官方app源

### ISSUE THREAD

**Issue by sz20000** [lizongying/my-tv#493]
下载凤凰秀App，h可登录一下就有高清信号！希望老大采用！![image](https://github.com/lizongying/my-tv/assets/4333756/a207da48-ddb8-411d-b268-fbe2a0f19f34)![image](https://github.com/lizongying/my-tv/assets/4333756/d8b20680-cb59-433d-b941-2c97aa8d131b

凤凰秀app安卓苹果客户端都有！都是秒播！

**Comment by ashsteins** [comment]
支持高清源

**Comment by ashsteins** [comment]
#EXTINF:-1 tvg-id="D01" tvg-name="凤凰中文" tvg-logo="https://cdn.jsdelivr.net/gh/wanglindl/TVlogo@main/img/Phoenix1.png" group-title="国际时事",凤凰中文
http://[2409:8087:2001:20:2800:0:df6e:eb22]:80/ott.mobaibox.com/PLTV/3/224/3221228527/1.m3u8
#EXTINF:-1 tvg-id="D02" tvg-name="凤凰资讯" tvg-logo="https://cdn.jsdelivr.net/gh/wanglindl/TVlogo@main/img/Phoenix2.png" group-title="国际时事",凤凰资讯
http://[2409:8087:2001:20:2800:0:df6e:eb19]:80/ott.mobaibox.com/PLTV/3/224/3221228524/1.m3u8
#EXTINF:-1 tvg-id="D03" tvg-name="凤凰香港" tvg-logo="https://cdn.jsdelivr.net/gh/wanglindl/TVlogo@main/img/Phoenix3.png" group-title="国际时事",凤凰香港
http://[2409:8087:2001:20:2800:0:df6e:eb22]:80/ott.mobaibox.com/PLTV/1/224/3221228530/1.m3u8

**Comment by Yvonne0827** [comment]
@ashsteins 你这是IPV6地址啊，跟大佬的IPV4不匹配吧

**Comment by ashsteins** [comment]
> @ashsteins 你这是IPV6地址啊，跟大佬的IPV4不匹配吧

大佬也是v6转v4技术的

**Comment by ashsteins** [comment]
支持高清源，目前有点糊

**Comment by lizongying** [comment]
最新版已有
