### ISSUE TITLE
大佬辛苦了，版本号为啥是乱七八糟的？

### ISSUE THREAD

**Issue by wzy2008a** [lizongying/my-tv#494]
版本号为啥不能一次性整正确呢，这么好的App版本号和自动更新搞好些就完美了

**Comment by shuohao** [comment]
确实，1.6.2检查更新提示最新版是1.6.0

**Comment by gouhuzi** [comment]
版本尾数单数为安卓5.0以上专用版本，版本尾数双数为通用版本，看更新日志就清楚了，先更新的通用版本，后更新的专用版本，所以你觉得有点乱

**Comment by luomoxu** [comment]
建议在文件名上做区分 或者直接分出两个不同的系列号 这种单双数的版本规则靠猜也太奇怪了

**Comment by lizongying** [comment]
#607
