### ISSUE TITLE
[BUG] 开机自启不起作用

### ISSUE THREAD

**Issue by ZZtimegoesby** [lizongying/my-tv#495]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

小米电视，软件1.6.2版本，开机自启功能已开启，但是经过测试并不起作用

### 预期行为

可以开机自启

### 实际行为

开机自启不起作用

### UI / OS

小米电视

### Android 版本

MIUI tv 1.3.125

**Comment by ChambersXDU** [comment]
这个是小米电视系统的锅，不对系统进行专门改动的情况下第三方软件自启动都是无效的

**Comment by ZZtimegoesby** [comment]
> 这是小米电视系统的锅，专门系统进行专门的情况下第三方软件自启动都是无效的

好吧，但我记着之前的电视家之类的三方软件都是能开机自启的

**Comment by makailin** [comment]
> 这个是小米电视系统的锅，不对系统进行专门改动的情况下第三方软件自启动都是无效的

小米电视很多软件都可以开机自启。

**Comment by WFANG12719** [comment]
斐讯N1电视盒子P230，开机自启也不work哦。
