### ISSUE TITLE
[FR] IPV4的源 老大可以参考灵犀直播的源，他们有些台还挺全的，补充完整地方台。

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#499]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

山西卫视、厦门卫视、三沙卫视、内蒙古卫视等都有。

### 解决方案

参考灵犀直播的源，都是v4的源。

**Comment by ashsteins** [comment]
有人说为啥那你不用灵犀直播，我说我当然用，但是咱是希望我的电视更上一层楼，补全最后的短板。
台多台全，就可以卸载灵犀直播了，毕竟它还有广告

**Comment by 1021683053** [comment]
还有个问题，一旦做大，肯定会被针对。所以，别想这么多，有的看稳定就不错了

**Comment by liangzhaoliang95** [comment]
别了，灵犀那个糊的一比，现在都是高清源，我宁愿不看，也不想这么好的软件引入模糊的源

**Comment by ashsteins** [comment]
> 别了，灵犀那个糊的一比，现在都是高清源，我宁愿不看，也不想这么好的软件引入模糊的源

补充完整频道，现在本身这软件也有一堆模糊源

**Comment by lizongying** [comment]
#532

**Comment by zouya1990** [comment]
谁有灵犀直播的源？能分享下吗？
