### ISSUE TITLE
[BUG] 我的SKYWORTH电视无法正常运行

### ISSUE THREAD

**Issue by RoundedKnot4342** [lizongying/my-tv#502]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

使用的版本为1.6.1，启动软件会一直黑屏，无论换哪个都是一样

### 预期行为

显示出直播

### 实际行为

保持黑屏

### 复现步骤

1.启动该软件
2.黑屏

### UI / OS

SKYWORTH

### Android 版本

Android 5.1.1

**Comment by kinsum666** [comment]
我也出现这种情况，降级到其它版本也都不行，更新到1.62版本也无法播放，重置系统也都无效，不知道是什么原因。安卓9

**Comment by ashsteins** [comment]
换智能安卓盒子
