### ISSUE TITLE
推荐更新的版本有问题

### ISSUE THREAD

**Issue by ydyydsediz** [lizongying/my-tv#503]
github推荐的是1.6.1，进入发布后发现下面有个1.6.2，但是还是头铁选了1.6.1，结果安装到盒子之后打开就黑屏，随后下载1.6.2就正常了，进入软件，检测更新，结果推荐更新变成了1.6.0

**Comment by sz20000** [comment]
自动更新里面 1.60 能更新成功吗？小米电视点更新后闪退

**Comment by ydyydsediz** [comment]
不能，我直接u盘装1.6.2了

TOMATO ***@***.***>于2024年3月1日 周五23:15写道：

**Comment by fanqiangboy** [comment]
还是1.6.1版用着舒服

**Comment by lizongying** [comment]
[1.6.7](https://github.com/lizongying/my-tv/releases/v1.6.7)已支持自动更新
