### ISSUE TITLE
CCTV16源暂停直播，请及时更换源。

### ISSUE THREAD

**Issue by xljl169** [lizongying/my-tv#504]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

CCTV16源无法直播。

### 预期行为

更新CCTV16源后，可以直播。

### 实际行为

CCTV16源无法直播。

### UI / OS

当贝B3 Pro

### Android 版本

9

**Comment by JackShell2020** [comment]
能不能把 源做成外挂的，启动的时候从网上拉下来，如果某个源不能用了，或者要增加新的，直接改外挂的文件就行了。

不知道这种方案可行吗

**Comment by ihumbert** [comment]
> 能不能把 源做成外挂的，启动的时候从网上拉下来，如果某个源不能用了，或者要增加新的，直接改外挂的文件就行了。
> 
> 
> 
> 不知道这种方案可行吗

diyp是你想要的。你去用那个吧

**Comment by lizongying** [comment]
暫時可用
