### ISSUE TITLE
[FR] 重温经典频道  信号源分享，老大可以参考一下

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#507]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

#EXTINF:-1 tvg-id="cwjd" tvg-name="重温经典" tvg-logo="https://cdn.jsdelivr.net/gh/Meroser/IPTV@main/TVlogo/cwjd.png" group-title="数字高清",重温经典
http://43.141.130.70/zycfcdn.gdwlcloud.com/PLTV/88888888/224/3221225563/index.m3u8

**Comment by sz20000** [comment]
支持

**Comment by IPR001** [comment]
地址怎么导入进软件？

**Comment by TANGMOQI** [comment]
请问怎么用呢

**Comment by lizongying** [comment]
#532
