### ISSUE TITLE
[FR]麻烦提供一下软路由可用的分流规则

### ISSUE THREAD

**Issue by makailin** [lizongying/my-tv#508]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

软路由/软件防火墙开启passwall以及powerDNS等软件后会出现无法播放的情况。希望可以提供域名以及分流规则来兼容诸多软件。

### 额外信息

顺带一提，建议收录一些高清源，目前内置源在大屏电视中有些模糊。

**Comment by makailin** [comment]
添加sn.chinamobile.com，yangshipin.cn后依然启动黑屏，再添加jsdelivr.net后依然偶尔打开软件后黑屏是还有什么前置检测地址吗？

**Comment by drw2005** [comment]
关注一下，集思广益。

**Comment by AppleMate60pro** [comment]
> ### 检查清单
> * [x] 之前没有人提交过类似或相同的功能请求。
> * [x] 这个建议不会背离 my-tv 的初衷。
> 
> ### 改进目的
> 软路由/软件防火墙开启passwall以及powerDNS等软件后会出现无法播放的情况。希望可以提供域名以及分流规则来兼容诸多软件。
> 
> ### 解决方案
> _没有回应_
> 
> ### 额外信息
> 顺带一提，建议收录一些高清源，目前内置源在大屏电视中有些模糊。

不会吧MYTV现在的源还模糊？你是没看过咪咕源的画质吧

**Comment by lizongying** [comment]
隨時更新，無法固定

**Comment by zazitufu** [comment]
我感觉这类直播TV软件，是无法使用软路由上，通过规则分流来跑的。因为它的源不是固定的。

除非作者把更新的源都DDNS到他自己的某个域名上，然后客户端通过域名来访问，这样就可以设置这部分域名直连。

当下只有两种解决方式
1、安卓电视机上装mytv（直连主路由），然后看奈菲的盒子之类的设备连接到旁路软路由。
2、安卓电视/盒子（直连主路由），然后安装nekobox for Android，然后在里面设置开机自启动，并且按应用分流。这样就能让mytv这个app 全部直连。
