### ISSUE TITLE
无法看到频道列表

### ISSUE THREAD

**Issue by LivSolstice** [lizongying/my-tv#51]
电视遥控器几个键都试了，不出现频道列表😭
上下键换台倒是很轻松，秒换

**Comment by lizongying** [comment]
之前有过这种情况，我后面会找找发生的原因。

**Comment by LivSolstice** [comment]
> 之前有过这种情况，我后面会找找发生的原因。

谢谢作者大大

**Comment by yes-github** [comment]
> 之前有过这种情况，我后面会找找发生的原因。

https://dev.mi.com/docs/gameentry/TV&%E7%9B%92%E5%AD%90%E6%B8%B8%E6%88%8F%E6%8E%A5%E5%85%A5%E6%96%87%E6%A1%A3/TV&%E7%9B%92%E5%AD%90%E9%81%A5%E6%8E%A7%E5%99%A8%E9%94%AE%E5%80%BC%E5%AE%9A%E4%B9%89/

确定键（OK/Center）：

  键值：KeyEvent.KEYCODE_DPAD_CENTER 或 KeyEvent.KEYCODE_ENTER
  说明：两个键值都要支持，以满足未来系统需求。

加上KeyEvent.KEYCODE_ENTER试试？

**Comment by lizongying** [comment]
感谢 @yes-github 提示，见1.4.1

**Comment by LivSolstice** [comment]
新版本果然解决了，完美。感谢 @lizongying  @yes-github 两位！
