### ISSUE TITLE
[FR] 能否增加上海欢笑剧场4k频道和都市频道

### ISSUE THREAD

**Issue by ghost** [lizongying/my-tv#510]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [x] 这个建议不会背离 my-tv 的初衷。

### 改进目的

4k频道较少且这两个频道不间断放一些很好的电视剧和电影真的很不错

### 额外信息

这两个频道真的会给大家带来欢乐，和中央电视台电视剧频道很契合

**Comment by Gubsv** [comment]
而且欢笑剧场是全国唯一一个黄金时段会播放韩剧日剧的频道

**Comment by ashsteins** [comment]
支持

**Comment by ashsteins** [comment]
要这些频道真的没什么用 不看放那里占内存，你以为嘴巴动动就好了，这些东西放进去还要写几百行代码

**Comment by fengluhome** [comment]
支持

**Comment by kinsum666** [comment]
> 而且欢笑剧场是全国唯一一个黄金时段会播放韩剧日剧的频道

韩剧日剧现在还有几个人看？都什么年代了还哈日哈韩？

**Comment by lizongying** [comment]
#557
