### ISSUE TITLE
能否增加求索纪录频道，

### ISSUE THREAD

**Issue by luyisuifeng** [lizongying/my-tv#511]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

这个频道真的很多不错的纪录片，增长见闻不错，强烈推荐

**Comment by sz20000** [comment]
支持增加！

**Comment by sz20000** [comment]
求索全系列都建议增加

**Comment by ashsteins** [comment]
Gubsv 曾说 不看放那里占内存，你以为嘴巴动动就好了，这些东西放进去还要写几百行代码

**Comment by kinsum666** [comment]
建议可以自己增加频道，这样方便各众用户，毕竟每个人的需求不一样

**Comment by lizongying** [comment]
#557
