### ISSUE TITLE
请问有直播源的地址吗？

### ISSUE THREAD

**Issue by fkueyadk** [lizongying/my-tv#513]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

在安卓很流畅，但是苹果手机用不了，想获得直播源，谢谢

**Comment by zbby1987** [comment]
直播源隔几天就失效换了，不然何必改成在线换源的版本呢

**Comment by AppleMate60pro** [comment]
我有而且是后台更新的，但我不给你

**Comment by ashsteins** [comment]
Gubsv知道，但他不会告诉你

**Comment by WendelYu** [comment]
看下这个项目，我的苹果手机就是用的这个源
https://github.com/BurningC4/Chinese-IPTV

**Comment by lizongying** [comment]
#684

**Comment by fkueyadk** [comment]
> 看下这个项目，我的苹果手机就是用的这个源 https://github.com/BurningC4/Chinese-IPTV

谢谢
