### ISSUE TITLE
[FR] 国际频道分类 增加新频道推荐，已找到源，老大可以参考

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#514]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

主要是NHK WORLD  CNA等频道。

### 解决方案

#EXTINF:-1 tvg-id="NHK" tvg-name="NHK World" tvg-logo="https://cdn.jsdelivr.net/gh/wanglindl/TVlogo@main/img/NHKWorld.png" group-title="国际时事",NHK World
https://nhkwlive-xjp.akamaized.net/hls/live/2003458/nhkwlive-xjp-en/index_1M.m3u8
#EXTINF:-1 tvg-id="CNA" tvg-name="CNA" tvg-logo="https://cdn.jsdelivr.net/gh/wanglindl/TVlogo@main/img/ChannelAsia.png" group-title="国际时事",CNA
https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5.m3u8
#EXTINF:-1 tvg-id="AlJaz" tvg-name="AlJazeera" tvg-logo="https://cdn.jsdelivr.net/gh/wanglindl/TVlogo@main/img/AlJazeera.png" group-title="国际时事",AlJazeera
http://live-hls-web-aje.getaj.net/AJE/01.m3u8
#EXTINF:-1 tvg-id="Arirang" tvg-name="Arirang TV" tvg-logo="https://cdn.jsdelivr.net/gh/Meroser/IPTV@main/TVlogo/Arirang_TV.png" group-title="国际时事",Arirang TV
https://amdlive-ch01-ctnd-com.akamaized.net/arirang_1ch/smil:arirang_1ch.smil/chunklist_b3256000_sleng.m3u8
#EXTINF:-1 tvg-id="RT01" tvg-name="RT News" tvg-logo="https://cdn.jsdelivr.net/gh/Meroser/IPTV@main/TVlogo/RT_News.png" group-title="国际时事",RT News
https://rt-glb.rttv.com/dvr/rtnews/playlist_4500Kb.m3u8
#EXTINF:-1 tvg-id="RT02" tvg-name="RT Español" tvg-logo="https://cdn.jsdelivr.net/gh/Meroser/IPTV@main/TVlogo/RT_News.png" group-title="国际时事",RT Español
https://rt-esp.rttv.com/dvr/rtesp/playlist_4500Kb.m3u8
#EXTINF:-1 tvg-id="RT03" tvg-name="RT Français" tvg-logo="https://cdn.jsdelivr.net/gh/Meroser/IPTV@main/TVlogo/RT_News.png" group-title="国际时事",RT Français
https://rt-fra.rttv.com/dvr/rtfrance/playlist_4500Kb.m3u8
#EXTINF:-1 tvg-id="RT04" tvg-name="RT Arabic" tvg-logo="https://cdn.jsdelivr.net/gh/Meroser/IPTV@main/TVlogo/RT_News.png" group-title="国际时事",RT Arabic
https://rt-arb.rttv.com/dvr/rtarab/playlist_4500Kb.m3u8
#EXTINF:-1 tvg-id="RT05" tvg-name="RT DE" tvg-logo="https://cdn.jsdelivr.net/gh/Meroser/IPTV@main/TVlogo/RT_DE.png" group-title="国际时事",RT DE
https://rt-ger.rttv.com/dvr/rtdeutsch/playlist_4500Kb.m3u8
#EXTINF:-1 tvg-id="RT06" tvg-name="RT Documentary" tvg-logo="https://cdn.jsdelivr.net/gh/Meroser/IPTV@main/TVlogo/RT_Doc.png" group-title="国际时事",RT Documentary
https://rt-rtd.rttv.com/live/rtdoc/playlist_4500Kb.m3u8
#EXTINF:-1 tvg-id="RT07" tvg-name="RT Doc-Русский tvg-logo="https://cdn.jsdelivr.net/gh/Meroser/IPTV@main/TVlogo/RT_Doc.png" group-title="国际时事",RT Doc-Русский
https://hls.rt.com/hls/rtdru360.m3u8

### 额外信息

#EXTINF:-1 tvg-id="cwjd" tvg-name="重温经典" tvg-logo="https://cdn.jsdelivr.net/gh/Meroser/IPTV@main/TVlogo/cwjd.png" group-title="数字高清",重温经典
http://43.141.130.70/zycfcdn.gdwlcloud.com/PLTV/88888888/224/3221225563/index.m3u8

**Comment by Gubsv** [comment]
要这些频道真的没什么用

**Comment by ashsteins** [comment]
> 要这些频道真的没什么用

你可以不看

**Comment by Gubsv** [comment]
不看放那里占内存，你以为嘴巴动动就好了，这些东西放进去还要写几百行代码

**Comment by ashsteins** [comment]
> 不看放那里占内存，你以为嘴巴动动就好了，这些东西放进去还要写几百行代码

你可以卸载，就不占内存了

**Comment by Gubsv** [comment]
我把你给卸载了吧！哪都有你sb

**Comment by ashsteins** [comment]
> 我把你给卸载了吧！哪都有你sb

急了？沙比

**Comment by Ahuangshang** [comment]
改版请使用，授权请关注公众号
![qrcode_for_gh_d4f98e4045d9_258](https://github.com/lizongying/my-tv/assets/15123689/cd6ee2ef-ed2e-4631-894a-8a10147ac7ea)

链接：https://pan.quark.cn/s/b33da8f4c680

**Comment by lizongying** [comment]
#532
