### ISSUE TITLE
别上港澳台哦，这个传播是非法的[FR] 

### ISSUE THREAD

**Issue by sfjdldldksks** [lizongying/my-tv#516]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

建议多上点地方台

**Comment by sz20000** [comment]
狗屁！

**Comment by yxhy1010** [comment]
非什么法？你脑袋是不是别驴踢了？

**Comment by yxhy1010** [comment]
非什么法了？你脑袋是不是被驴踢了？

**Comment by ashsteins** [comment]
沙比

**Comment by wind-3364** [comment]
你可以不传播吖，自己玩玩就行了。建议上点台湾电视台。让我们不用翻墙，也能看看台湾新闻。

**Comment by drw2005** [comment]
> 你可以不传播吖，自己玩玩就行了。建议上点台湾电视台。让我们不用翻墙，也能看看台湾新闻。

这个建议好。

**Comment by Gubsv** [comment]
> 沙比

哪都有你

**Comment by ashsteins** [comment]
> 哪都有你

急了这是

**Comment by UncleTonymmp** [comment]
非法？？ 我家广电电视好多港澳台可以看

**Comment by LarryBrin** [comment]
确实很蠢

**Comment by ashsteins** [comment]
广东地区很多港澳台的台都可以看，楼主纯纯蠢货

**Comment by ashsteins** [comment]
我朋友广东的，他们家就可以看凤凰台 翡翠台 澳门卫视

**Comment by lizongying** [comment]
感谢建议
