### ISSUE TITLE
⬆★★★★★★★★★★★添加太原四套直播源★★★★★★★★★★★⬆

### ISSUE THREAD

**Issue by yamat000** [lizongying/my-tv#518]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [x] 这个建议不会背离 my-tv 的初衷。

### 改进目的

网上的所有盒子一般地方台都有, 都有了, 但是唯独没有太原的.....,
我看网上有相关的直播源是可以看的吧.................., 比如这个可以在线看的 
+ http://tv.cutv.com/index.html   
+ http://tv.haoqu99.com/3/shan-xi/

em, 希望多加几个直播源.

### 解决方案

添加下太原四套 相关直播源

### 额外信息

非常感谢,哈哈

**Comment by ashsteins** [comment]
Gubsv 有太原台，但他会举报你

**Comment by ashsteins** [comment]
Gubsv 曾说 不看放那里占内存，你以为嘴巴动动就好了，这些东西放进去还要写几百行代码

**Comment by yamat000** [comment]
哈哈哈, 啊,这,道理还是有的.
话说之前有个app 火星海外版的, 
那个里面有,包括全国的 还有,各种小地区的都能看,还有更小的县区的也能看到,
太原一开始也有,结果一更新再也搜不到了,从新安装也不行,其他地县都能正常看,,,,,这就, 简直不能吐槽了.

**Comment by yamat000** [comment]
Gubsv是啥，火星app 一开始有,后来已更新就没了😂



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月02日 15:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lizongying/my-tv] 添加太原四套直播源 (Issue #518) |

Gubsv 有太原台，但他会举报你
