### ISSUE TITLE
断流呀

### ISSUE THREAD

**Issue by lingchvip** [lizongying/my-tv#52]
cctv1直播断流了，播一会就卡住，得重新点开。

**Comment by lizongying** [comment]
后面会关注

**Comment by zbby1987** [comment]
> cctv1直播断流了，播一会就卡住，得重新点开。

你是什么设备？安卓几？
是不是运行内存太小了！？

**Comment by lingchvip** [comment]
> > cctv1直播断流了，播一会就卡住，得重新点开。
> 
> 你是什么设备？安卓几？
> 是不是运行内存太小了！？

魔百盒vm311-1a，2+16 9.0版本，昨天装到1.3.9版本，断流有改善，播一个半小时后停过一次。

**Comment by lingchvip** [comment]
> 后面会关注

大佬威武

**Comment by 643270075** [comment]
> 后面会关注

大佬，1.4.2也会断流，CCTV5看一会卡住不动，没有自动刷新的功能，需要切换台才能正常

**Comment by DomByAngular** [comment]
有断流的现象

**Comment by lizongying** [comment]
最新版
