### ISSUE TITLE
能否增加电视家那样的换台菜单，现在换台方式对于电视端很不友好[FR] 

### ISSUE THREAD

**Issue by tallguess** [lizongying/my-tv#522]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

提高可用性
![Screenshot_2024-03-04-16-34-19-504_org mozilla firefox-edit](https://github.com/lizongying/my-tv/assets/70436397/4df39c60-e7fd-460c-953a-85b90744c848)

**Comment by Ahuangshang** [comment]
改版请使用，授权请关注公众号
![qrcode_for_gh_d4f98e4045d9_258](https://github.com/lizongying/my-tv/assets/15123689/cd6ee2ef-ed2e-4631-894a-8a10147ac7ea)

链接：https://pan.quark.cn/s/b33da8f4c680

**Comment by lynlxx** [comment]
感觉没必要，毕竟现在的电视台也不算多，以后电视台多了倒是可以考虑其他形式
