### ISSUE TITLE
[BUG] 斐讯N1盒子不能自启

### ISSUE THREAD

**Issue by WFANG12719** [lizongying/my-tv#524]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

斐讯N1盒子，[Phicomm] Phicomm p230 (Android 7.1.2)
机器重新启动时App不能随系统启动，需要手工点击启动
帮助家里排除问题时用远程控制盒子，可以看到整个播放界面，但鼠标无法进入设置界面，只能按esc推出，用鼠标点击打开App。

### 预期行为

能随安卓系统启动而自动启动，并进入上次记忆的频道。
用鼠标操作（在电视上或通过电脑远程桌面）可以操作设置界面。

### 实际行为

不能自启
鼠标不能操作设置界面     ----> 1.7.3键盘可以操作设置界面了，按左箭头键右箭头键可以分别进入设置和频道列表

### UI / OS

斐讯N1

### Android 版本

7.1.2

**Comment by WFANG12719** [comment]
升级到1.7.3，键盘可以操作了，可以算是workaround了。
斐讯电视盒子APP还是不能自启，这个不知能否解决？持续关注。。。

**Comment by WFANG12719** [comment]
1.7.3键盘可以操作设置界面了，按左箭头键右箭头键可以分别进入设置和频道列表

**Comment by WFANG12719** [comment]
有以下频道足矣：CCTV 2, 9, 13, 4K, 8K和凤凰资讯

**Comment by lizongying** [comment]
部分設備無法自啟的問題無法解決。雙擊進入設置

**Comment by WFANG12719** [comment]
> 部分設備無法自啟的問題無法解決。雙擊進入設置

OK, then I have a workaround: put the following command in system rc.local to start it manually:

     `am start -W -n com.lizongying.mytv/com.lizongying.mytv.MainActivity`

Anyway, thanks for your continuous efforts to improve this APP.

**Comment by WFANG12719** [comment]
@lizongying 一个参考：之前在同一个设备上(斐讯N1）安装有“云海电视”，这个APP可以自启，没有问题，可否参考这个APP的设计？
云海电视已经停止服务了，不知道他们开源了代码没有？或者可以反编译来学习一下。

**Comment by lizongying** [comment]
> @lizongying 一个参考：之前在同一个设备上(斐讯N1）安装有“云海电视”，这个APP可以自启，没有问题，可否参考这个APP的设计？ 云海电视已经停止服务了，不知道他们开源了代码没有？或者可以反编译来学习一下。

你用的我的電視是最新版嗎？開啟開機啟動了嗎？你確認云海电视可以在同一設備可以開機啟動嗎？

**Comment by WFANG12719** [comment]
> > @lizongying 一个参考：之前在同一个设备上(斐讯N1）安装有“云海电视”，这个APP可以自启，没有问题，可否参考这个APP的设计？ 云海电视已经停止服务了，不知道他们开源了代码没有？或者可以反编译来学习一下。
> 
> 你用的我的電視是最新版嗎？開啟開機啟動了嗎？你確認云海电视可以在同一設備可以開機啟動嗎？

是的，最新版。
是的，在APP里开启了开机启动。
是的，云海电视在同一设备可以自动开机启动。
