### ISSUE TITLE
[FR] 如何设置开机不自动启动？

### ISSUE THREAD

**Issue by hong19860320** [lizongying/my-tv#528]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

希望开机快速进入 android launcher

### 解决方案

增加偏好设置

### 额外信息

没有

**Comment by qpdbzzz** [comment]
这个不是能开关的吗？

**Comment by lizongying** [comment]
新版本默认关闭，也可以设置
