### ISSUE TITLE
v1.6.1，中央三无法播放

### ISSUE THREAD

**Issue by PHCSJC** [lizongying/my-tv#529]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

中央三无法播放

### 预期行为

正常播放

### 实际行为

无法播放

### UI / OS

安卓

### Android 版本

14

**Comment by klakekent** [comment]
我也遇到了 昨天还是好的 估计源失效了

**Comment by qiji2024** [comment]
cctv6,cctv8失效了

**Comment by ashsteins** [comment]
先用灵犀直播 顶一顶

**Comment by ccav14** [comment]
https://www.yangshipin.cn/#/tv/home
这个3个本来是要vip的，估计破戒失效了吧

**Comment by lizongying** [comment]
已恢复
