### ISSUE TITLE
1.6.1版本，央视3，6，8都失效了

### ISSUE THREAD

**Issue by tianshaboy88** [lizongying/my-tv#530]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

央视3，6，8都失效了

### 预期行为

央视3，6，8都失效了

### 实际行为

央视3，6，8都失效了

### UI / OS

TCL

### Android 版本

11

**Comment by ashsteins** [comment]
先用灵犀直播 顶一顶
