### ISSUE TITLE
希望可以自定义源[FR] 

### ISSUE THREAD

**Issue by bobpang2020** [lizongying/my-tv#532]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

因为源太容易失效了，而且相同的一个源，用的人数暴增就非常容易卡顿。

### 解决方案

希望可以把源做成一个单独的文本如json格式，然后程序每次启动或更新源后，重新读json文件更新。然后再创建一个公共的源库，大家可以选择，也可以用自己的。系统框架基本上完美了，又不是商用的，美工OK了

**Comment by lizongying** [comment]
在准备新开一个项目，支持自定义源的https://github.com/lizongying/my-tv-0 现在开发中。本项目暂时就不支持自定义源了。
