### ISSUE TITLE
[BUG] 手机上看点击打开频道列表后，划着划着就退出频道列表

### ISSUE THREAD

**Issue by shuohao** [lizongying/my-tv#534]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

手机上看点击打开频道列表后，划着划着就退出频道列表，滑的动作可能也就两三秒

### 预期行为

停留在频道列表页面

### 实际行为

退出频道列表

### UI / OS

xiaomi 12pro hyper os

### Android 版本

12

**Comment by lfm09** [comment]
确实有这个问题，很不方便

**Comment by shunlongyang** [comment]
同样有这个问题，希望大佬能够解决

**Comment by lizongying** [comment]
最新版本，已經解決了
