### ISSUE TITLE
[BUG] 切换到凤凰卫视后画面卡住，其他频道也无法播放

### ISSUE THREAD

**Issue by 5ephie** [lizongying/my-tv#538]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

切换到新加的三个凤凰台后画面卡住，并且切到其他频道无法正常播放，需要重启盒子才能恢复

https://github.com/lizongying/my-tv/assets/80619139/31767acc-742f-4705-ab1c-0e6474b7ea88

### 预期行为

正常播放

### 实际行为

所有频道都无法播放

### 复现步骤

先切到凤凰卫视，再切换到其他频道

### UI / OS

小米盒子3增强版

### Android 版本

5.1

### 额外信息

版本1.6.1

**Comment by sz20000** [comment]
小米电视3 一切正常！凤凰系列为高清！换台图标排列为满屏全铺！大赞！

**Comment by 5ephie** [comment]
1.6.3 已解决
