### ISSUE TITLE
大赞！1.64

### ISSUE THREAD

**Issue by sz20000** [lizongying/my-tv#539]
换台图标全屏显示非常好！选中还有图标高亮！非常高级！凤凰卫视系列比以前清晰一点！但是流畅度不如上个版本。
期待完整的祖国省级卫视台。陕西，山西，吉林，三沙卫视。。也期待求索系列。更期待在线更新！

目前 1.64 在线更新还是显示 1.60

![image](https://github.com/lizongying/my-tv/assets/4333756/6482eabe-6b00-47ad-ab37-96282d467735)

**Comment by yxhy1010** [comment]
谢谢大佬的无私奉献！！顶
