### ISSUE TITLE
[BUG] 软件版本相同。

### ISSUE THREAD

**Issue by happymy** [lizongying/my-tv#542]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

每个apk安装包的版本都是相同的。无法升级安装，只能卸载后重新安装。

### 预期行为

none

### 实际行为

none

### UI / OS

realme 

### Android 版本

12

**Comment by lizongying** [comment]
应该不是的

**Comment by happymy** [comment]
我用两部手机和电视。测试了一下。
用的都是通用版本。高版本安装没有提示升级。识别为同一个版本。只能卸载老版本后安装新版本。
确实很奇怪。

**Comment by lizongying** [comment]
@happymy 你长按图标，查看下详细信息就知道了

**Comment by sz20000** [comment]
版本号不一样。但是跨版本安装确实需要卸载原先的再安装。不可以覆盖更新。

**Comment by sz20000** [comment]
新版凤凰卫视压缩好厉害，估计是针对移动设备优化的节目源，不过 98寸电视看着不卡，够用了！

**Comment by happymy** [comment]
> 版本号不一样。但是跨版本安装确实需要卸载原先的再安装。不可以覆盖更新。

我特别测试了一下，用的都是有通用标记的版本。

**Comment by happymy** [comment]
> @happymy 你长按图标，查看下详细信息就知道了

已经确认versionCode相同。建议改进版本管理。 十分感谢开发者，这是我用过的最好的iptv软件。

Package name
com.lizongying.mytv
versionCode
1
versionName
1.6.2
Supported ABIs
armeabi-v7a, arm64-v8a
Native libraries
libnative.so, libnothing.so
Minimal supported Android version
Jelly Bean (4.2.x) - API level 17
Target SDK
Android 13 (Tiramisu)Android 14 (Upside Down Cake)Android 15 (Vanilla Ice Cream)Android 16 (Vanilla Ice Cream) - API level 33


---------------------------------------------------------------------------
Package name
com.lizongying.mytv
versionCode
1
versionName
1.6.4
Supported ABIs
armeabi-v7a, arm64-v8a
Native libraries
libnative.so, libnothing.so
Minimal supported Android version
Jelly Bean (4.2.x) - API level 17
Target SDK
Android 13 (Tiramisu)Android 14 (Upside Down Cake)Android 15 (Vanilla Ice Cream)Android 16 (Vanilla Ice Cream) - API level 33

**Comment by sz20000** [comment]
支持精细化完善！

**Comment by sz20000** [comment]
覆盖安装检测的是versionCode

**Comment by lizongying** [comment]
@happymy versionCode确实是相同的，在最新版已经修复，后面的应该可以覆盖安装了。
