### ISSUE TITLE
[FR]  希望可以提升稳定性

### ISSUE THREAD

**Issue by 91hm** [lizongying/my-tv#543]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

希望可以提升稳定性
过年 不在家 父母要看一下春晚 结果看不了  就是这个软件  我希望 gitee 或者其它网站 有个视频源 如果 失效了 也能软件获取到最新的 保证软件正常使用

### 解决方案

gitee创建个仓库 可以正常访问

**Comment by twenty2811** [comment]
https://gitee.com/lizongying/my-tv，这个不是作者的gitee仓库吗？
