### ISSUE TITLE
[BUG] 1.63版本 CETV1 频道图标未显示

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#547]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

专用版

### Bug 描述

[BUG] 1.63版本 CETV1 频道图标未显示

### 预期行为

[BUG] 1.63版本 CETV1 频道图标未显示

### 实际行为

[BUG] 1.63版本 CETV1 频道图标未显示

### UI / OS

Mumu模拟器

### Android 版本

12

**Comment by sz20000** [comment]
![image](https://github.com/lizongying/my-tv/assets/4333756/3dbac522-6ce3-4352-80dd-e09516b87c5f)


情况属实！

**Comment by lizongying** [comment]
新版本已有
