### ISSUE TITLE
[FR] 增加 欧洲华文电视台

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#552]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

欧洲华文电视台是一个专注于华语文化全球传播的24小时全频道媒体，传播方式包括卫星电视、有线电视、手机电视和全球视频分发平台，覆盖亚洲、欧洲、北美、东南亚，落地欧洲，是进入西方主流社会最具规模的关于中国文化的电视播出媒体。
![欧洲华文电视台图片_百度百科](https://github.com/lizongying/my-tv/assets/157224414/95262f1c-ef0c-4a66-803c-374cc24bf4d2)

### 解决方案

欧洲华文电视台是一个服务公众的新媒体平台，也是中国内地在欧洲展示旅游资源、经济信息及消费热点的窗口。它向欧洲全面介绍中国内地的自然风光、人文景观、时尚消费及各省市的经济发展和投资信息。其形式以高质量、多样化的信息专栏、专题片、文艺片、综述座谈、旅游、经贸、活动报道、新闻杂志类、谈话类节目等为主。

**Comment by ashsteins** [comment]
http://europachinatv.com/index.php/lists/29.html

**Comment by lizongying** [comment]
#532
