### ISSUE TITLE
[FR] 目前4K 8K频道汇总如图，希望能补充完整然后分类为 超高清频道

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#553]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

![中国4k频道数量全球第八【高清频道吧】_百度贴吧](https://github.com/lizongying/my-tv/assets/157224414/aebd67ab-2d46-417a-bb06-16bfaf6aab09)

**Comment by sz20000** [comment]
意义不大！1080P高清就够了

**Comment by lizongying** [comment]
#893
