### ISSUE TITLE
[BUG] 自动更新有点问题，版本越更越小？

### ISSUE THREAD

**Issue by 89333367** [lizongying/my-tv#556]
### 检查清单

- [ ] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

从1.6.4更新到1.6.0？好像是不太对
![image](https://github.com/lizongying/my-tv/assets/20157752/d20bcad4-0ac8-48b3-99eb-a4f6dec7998d)

### 预期行为

应该是比1.6.4大的版本才更新吧？

### 实际行为

1.6.4 =》1.6.0
我没有点击更新，不过这个提示应该肯定是不对

### UI / OS

荣耀智慧屏X1，4G内存，65英寸2022款

### Android 版本

好像是10？

**Comment by happymy** [comment]
https://github.com/lizongying/my-tv/issues/542
版本管理的问题。

**Comment by kiben2010** [comment]
我这里也出现同样的问题

**Comment by yzp531** [comment]
是的，版本号好像有问题，手动更新也一样，会提示安装了高版本

**Comment by lizongying** [comment]
#575
