### ISSUE TITLE
珠江频道

### ISSUE THREAD

**Issue by Shimmer2** [lizongying/my-tv#557]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

请问可以增加珠江频道吗？谢谢

**Comment by ashsteins** [comment]
延边卫视先加就加粤语

**Comment by mars456852** [comment]
荔枝网https://www.gdtv.cn/上就有珠江台，如果能爬下来就完美了

**Comment by lizongying** [comment]
暫時不考慮地方頻道，衛視後期會儘量補全
