### ISSUE TITLE
[FR] 山西卫视、宁夏卫视、吉林卫视直播源分享

### ISSUE THREAD

**Issue by YaChengMu** [lizongying/my-tv#559]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

http://220.194.178.58:8888/newlive/live/hls/42/live.m3u8 山西卫视（高清）
http://118.81.242.246:9999/tsfile/live/0118_1.m3u8 山西卫视（高清）

https://hls.ningxiahuangheyun.com/live/nxws1M.flv 宁夏卫视（高清）

http://58.254.14.59:808/hls/43/index.m3u8 吉林卫视（高清）

**Comment by ashsteins** [comment]
支持补充地方卫视

**Comment by ashsteins** [comment]
三沙卫视和延边卫视有么

**Comment by ctgushiwei** [comment]
要ipv4的源才可以

**Comment by lizongying** [comment]
#557
