### ISSUE TITLE
[FR] fanmingming源分享

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#564]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

https://github.com/fanmingming/live/blob/main/tv/m3u/ipv6.m3u

**Comment by sz20000** [comment]
这都是ipv6 的。不是所有人都有ipv6。但是所有人都有ipv4。

**Comment by ashurajo** [comment]
> 这都是ipv6 的。不是所有人都有ipv6。但是所有人都有ipv4。

说得好，手动点赞，不知道什么心理阴暗的还给你点了2个踩，哈哈。

**Comment by lizongying** [comment]
#532
