### ISSUE TITLE
[BUG] 最新1.6.6通用版4.4.2盒子上闪退。。。

### ISSUE THREAD

**Issue by drw2005** [lizongying/my-tv#565]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

安装正常，打开换台时直接退出。

退回到1.6.4正常了（但是三个凤凰台仍然不能看）。

### 预期行为

正常观看。

### 实际行为

打开后换台闪退

### UI / OS

电视盒子

### Android 版本

4.4.2

**Comment by ashsteins** [comment]
早日换安卓9的盒子解决一切问题

**Comment by xjz5959** [comment]
更新盒子吧 。

**Comment by kongguojun** [comment]
我的电视  一直都不支持4.4.2   但是支持4.4.4

**Comment by sunnysu0608** [comment]
> 我的电视 一直都不支持4.4.2 但是支持4.4.4

升级原生安卓就可以

**Comment by lizongying** [comment]
1.6.8已修复两个问题

**Comment by kongguojun** [comment]
这意思是1.68可以用安卓4.4.2了？

**Comment by drw2005** [comment]
> 1.6.8已修复两个问题

实测已经修复，不再闪退，包括凤凰卫视全部正常了。
