### ISSUE TITLE
能否添加一些潮汕地区的频道？

### ISSUE THREAD

**Issue by qpdbzzz** [lizongying/my-tv#566]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

能给听不懂普通话的老年人观看

### 解决方案

添加汕头经济，潮州综合，潮州公共，揭阳公共，揭阳综合其中几个就行

**Comment by sz20000** [comment]
这种小地方频道没有稳定又快速的节目源。

**Comment by angiie** [comment]
挺好奇啥原理的，清晰度非常高

**Comment by lizongying** [comment]
#557
