### ISSUE TITLE
[FR] 建议增加台湾地区频道 比较喜欢壹新闻

### ISSUE THREAD

**Issue by piggy9527** [lizongying/my-tv#568]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

方便看电视

**Comment by ashsteins** [comment]
建议增加延边地区频道，比较喜欢延边卫视

**Comment by lizongying** [comment]
#557
