### ISSUE TITLE
[BUG]版本更新异常 

### ISSUE THREAD

**Issue by chenzhuo0602** [lizongying/my-tv#570]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

专用版

### Bug 描述

我目前安装了v1.6.3版本，检查更新提示更新到1.6.0版本。

### 预期行为

无

### 实际行为

无

### 复现步骤

无

### UI / OS

dbboxH3

### Android 版本

11

### 额外信息

无

**Comment by kilvn** [comment]
附议

**Comment by kiben2010** [comment]
附议

**Comment by lizongying** [comment]
[1.6.7](https://github.com/lizongying/my-tv/releases/v1.6.7)已支持自动更新
