### ISSUE TITLE
1.6.6[BUG]

### ISSUE THREAD

**Issue by naonoo** [lizongying/my-tv#572]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

央5、央16奥林、央5+跳空，

### 预期行为

顺序加减频道

### 实际行为

转到央5及央16央5+三个频道无反应

### UI / OS

sony电视

### Android 版本

10

**Comment by wlhacker** [comment]
大佬能不能加一点类似宝贝回家，失踪人口之类的频道，好人一生平安！

**Comment by lizongying** [comment]
可能頻道暫時不可用
