### ISSUE TITLE
[BUG] 所有中央台的节目经常无法打开

### ISSUE THREAD

**Issue by minglei84** [lizongying/my-tv#573]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

经常发现中央电视台的所有节目无法打开，曾尝试安装最新版，之后正常了一次；
之后所有中央电视台的节目均无法打开。

### 预期行为

期望所有中央台的节目能正常播放

### 实际行为

切换到中央台之后，黑屏无声音，但底部频道处能看到节目名称。

### UI / OS

CHUANGWEI

### Android 版本

12

**Comment by lizongying** [comment]
请升到最新版本
