### ISSUE TITLE
[BUG] 部分cctv频道无法播放，如cctv3 6 8

### ISSUE THREAD

**Issue by wind-3364** [lizongying/my-tv#576]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

其他频道可以正常播放 无卡顿 ，个别央视频道直接不显示。如cctv3 6 8 风云 地理等

### 预期行为

正常播放

### 实际行为

黑屏 切换到该台 无反应

### UI / OS

小米ea系列

### Android 版本

5以上

**Comment by sln162** [comment]
同，无法播放

**Comment by 402324505** [comment]
同，无法播放

**Comment by Aeternum-G** [comment]
同

**Comment by zkun1970** [comment]
同无法播放

**Comment by sln162** [comment]
可以看了，是修复了吗

**Comment by lizongying** [comment]
升到最新版本
