### ISSUE TITLE
海外用户，无法打开CCTV5, CCTV5+,CCTV16奥林匹克和CCTV风云足球频道 

### ISSUE THREAD

**Issue by michaeltao263** [lizongying/my-tv#577]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

坐标美东，在Shield TV安装最新1.6.8版本，以下频道无法打开
CCTV5, CCTV5+,CCTV16奥林匹克和CCTV风云足球频道 

### 预期行为

怀疑是IP地理位置限制

### 实际行为

体育频道无法打开

### UI / OS

TCL

### Android 版本

9.1.1

**Comment by wallinwind** [comment]
这个是节目源的限制，作者也无能为力

**Comment by derekling** [comment]
体育海外没有版权 你自己搭 VPN 回国模式看吧

**Comment by michaeltao263** [comment]
明白，xx回覆。



Send from iOS outlook
________________________________

**Comment by lizongying** [comment]
#395 後面我看看能不能換源解決
