### ISSUE TITLE
[FR] 新频道建议

### ISSUE THREAD

**Issue by bymjsss** [lizongying/my-tv#579]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

请求加入内蒙古卫视、以及各省动漫频道、例如 北京卡酷，金鹰卡通等

**Comment by ashsteins** [comment]
还有 吉林卫视等，目前还不全

**Comment by Tshor** [comment]
安多卫视！！！ 还有康巴卫视、西藏卫视

**Comment by lizongying** [comment]
#557
