### ISSUE TITLE
请求开发IOS版和Apple TV版

### ISSUE THREAD

**Issue by openviso** [lizongying/my-tv#581]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

安卓版的体验非常极致，啥时候发布IOS版、Apple TV版？

### 解决方案

无

### 额外信息

无

**Comment by Developer-echo** [comment]
不太可能，app store开发者账户一年都要不少钱呢

**Comment by liyangzbx** [comment]
不付费订阅，就基本不可能开通ios版本。一付费订阅，项目就得gg

**Comment by gsons** [comment]
> 不付费订阅，就基本不可能开通ios版本。一付费订阅，项目就得gg

ios版本 可以用巨魔的 或者TF版本 又或者越狱

**Comment by lizongying** [comment]
#461
