### ISSUE TITLE
1.68功能测试漏洞

### ISSUE THREAD

**Issue by 402324505** [lizongying/my-tv#582]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

央视3.、6、8、风云等系列后面频道还是无法观看，而且频道切换顺畅度明显下降了好多，尤其地方台切换要来回切换才能正常播放

### 预期行为

望能继续优化

### 实际行为

如题

### UI / OS

安卓盒子

### Android 版本

4.2以上

**Comment by 402324505** [comment]
是安卓4.4以上的

**Comment by lizongying** [comment]
请升级到最新版本
