### ISSUE TITLE
列表页面自动消失

### ISSUE THREAD

**Issue by pyccl** [lizongying/my-tv#587]
点开列表页面时候，要看某个台演的什么节目，但是时间一长（此段时间一直在滑动列表），在滑动时候会出现列表消失的情况，1.70好像消失的时间又长一点了。还有一个，1.70说是可以切换列表样式，也没有找到切换的按钮什么的。😂😂😂

**Comment by lizongying** [comment]
请在电视上使用，电视上有设置页
