### ISSUE TITLE
[BUG] 1.7.2版本 安卓4.4低版本，央视3、6、8无法播放，三个凤凰音画不同步，且卡帧。

### ISSUE THREAD

**Issue by TisonTian** [lizongying/my-tv#589]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

1.7.2版本 安卓4.4低版本，央视3、6、8无法播放

### 预期行为

1.7.2版本 安卓4.4低版本，央视3、6、8可播放

### 实际行为

1.7.2版本 安卓4.4低版本，央视3、6、8无法播放

### UI / OS

Hisense

### Android 版本

4.4

**Comment by TisonTian** [comment]
三个凤凰卫偶尔音画不同步。画面卡帧数，声音一样卡。

**Comment by lizongying** [comment]
#720
