### ISSUE TITLE
可以像央视浏览器那样，用浏览器+油猴脚本，从中央电视台官网播放数据么？

### ISSUE THREAD

**Issue by zbby1987** [lizongying/my-tv#59]
参考项目地址  https://github.com/Eanya-Tonic/CCTV_Viewer
央视官网的节目带着加密，嗅探出视频地址后用外部解码器播放就乱码。
只能用浏览器直接播放，
但流畅度是真的不错。
这个项目目前也不支持安卓4，没法开机启动。

**Comment by lizongying** [comment]
不错的项目。没太明白需求，我能做什么工作？

**Comment by zbby1987** [comment]
> 不错的项目。没太明白需求，我能做什么工作？

整一个比他更好的央视浏览器
