### ISSUE TITLE
模拟器中运行的时候，台标和右上角的数字角标不会自动消失[BUG] 

### ISSUE THREAD

**Issue by abchwabc** [lizongying/my-tv#590]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

在模拟器中运行的时候，电视中间的台标和右上角的数字角标不会自动消失

### 预期行为

模拟器中切换电视台后，可以像电视一样，台标和右上角数据角标可以自动消失。

### 实际行为

![iShot_2024-03-16_17 09 01](https://github.com/lizongying/my-tv/assets/44790500/3963c757-88e1-4d90-bf9c-ad9f79cd9dd7)

### UI / OS

Mac OS M2，mumu模拟器

### Android 版本

12

**Comment by lizongying** [comment]
我在AS模拟器上测试没问题的。暂无其他设备反馈，你可以试试最新版
