### ISSUE TITLE
[BUG] CCTV6、第一剧场、风云剧场之后一直到电视指南这些节目等等一系列无法播放。

### ISSUE THREAD

**Issue by zhaishang** [lizongying/my-tv#591]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

CCTV6、第一剧场、风云剧场之后一直到电视指南这些节目等等一系列无法播放。

### 预期行为

无法播放

### 实际行为

无法播放

### UI / OS

安卓

### Android 版本

4.4

**Comment by lizongying** [comment]
網絡問題

**Comment by zhaishang** [comment]
不是网络问题，以前可以播放
