### ISSUE TITLE
[FR] 请求在安卓手机端增加设置开关

### ISSUE THREAD

**Issue by EncreVille** [lizongying/my-tv#597]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

我经常在平板上使用mytv，但一直没有找到打开设置界面的入口，没有办法调整列表样式和在线更新。或许可以设置一个区域点击打开？

**Comment by ashsteins** [comment]
同意

**Comment by ccav14** [comment]
如果你的平板有安卓传统3键的话可以长按菜单键调出设置

**Comment by lizongying** [comment]
[1.6.7](https://github.com/lizongying/my-tv/releases/v1.6.7)已支持双击打开设置
