### ISSUE TITLE
[FR] 希望可以增加更多的港台的电视频道

### ISSUE THREAD

**Issue by Apollo-yeah** [lizongying/my-tv#598]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

希望可以增加更多的港台的电视频道，如TVB无线、Viutu、中天新闻东森新闻等

**Comment by gsons** [comment]
东森新闻不可能 国内不允许

**Comment by Apollo-yeah** [comment]
> 东森新闻不可能 国内不允许

星火海外版好像是有，不需要科学上网也能连，就是稳定的流可能不好找

**Comment by pooppiss** [comment]
可别增加这些港澳台，太太平平的看看电视就好。敏感的台只会给作者带来麻烦~

**Comment by lizongying** [comment]
#557
