### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Su-YunLong** [lizongying/my-tv#599]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

安卓4.4.2，首次安装可以正常使用（不包括不能播放中央3-6-8风云剧场等），重启后再次进入，黑屏。然后偶尔可用，大多数黑屏。频道列表可调用，菜单可调用，但是所有频道黑屏。此问题不单单是1.72纯在，1.60、1.62、1.64、1.68 均存在。

### 预期行为

给出BUG 信息，是软件运行故障黑屏，还是无法连接到播放源黑屏。

### 实际行为

现在智能卸载重装，首次可用。

### 复现步骤

首次安装，关机重启，偶尔可用，大多数黑屏。

### UI / OS

创维、中兴、海信都纯在此问题

### Android 版本

4.4.2

### 额外信息

非常感谢您的开发和开源，为此付出的努力合心血，特此感谢！

**Comment by Su-YunLong** [comment]
首次安装正常使用，关机重启后，偶尔可用，大多数黑屏

**Comment by gsons** [comment]
> 首次安装正常使用，关机重启后，偶尔可用，大多数黑屏

是网络问题 或者是频道地址不可用了

**Comment by Su-YunLong** [comment]
Thank you for you Email.I will reply to you as soon as possible.( *^_^* )您的邮件我已收到，会尽快给您回复。谢谢!!

**Comment by lizongying** [comment]
#656
