### ISSUE TITLE
1.0.9 黑屏

### ISSUE THREAD

**Issue by AustinFan** [lizongying/my-tv#6]
打开是黑屏 -.-！

**Comment by tom96202** [comment]
1.1.0也是黑屏

**Comment by lizongying** [comment]
官方源的问题算是解决了，自测效果不错。建议升级到1.1.1。打开黑屏的原因可能是之前官方源还有些其他的加密，我这表现就是部分会卡，不过现在应该可以了。

**Comment by chenxudong2020** [comment]
为啥我还是黑屏 电脑雷电模拟器 手机都是黑屏 最新1.1.1

**Comment by chenxudong2020** [comment]
![image](https://github.com/lizongying/my-tv/assets/61214170/028e76a6-9374-47fe-abf6-ab0a0de64614)

**Comment by lizongying** [comment]
请更新到1.1.6以上
#9
