### ISSUE TITLE
[FR]爬加一下荔枝网的节目列表

### ISSUE THREAD

**Issue by mars456852** [lizongying/my-tv#600]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

增加荔枝网的节目频道，这个是固定的，广东地区基本所有常用的台荔枝网都有，但是他只有网页，没有app，电脑观看起来比较麻烦，网址https://www.gdtv.cn/

### 解决方案

如果能爬出来加上荔枝台的节目，广大广东观众不胜感激

**Comment by zhblmy** [comment]
还有明珠台，提前感谢！

**Comment by ashsteins** [comment]
理论上每个省都有类似这种官网，广东做的比较规整

**Comment by chenmto** [comment]
潮汕地区有稳定源吗

**Comment by Apollo-yeah** [comment]
有app，触电新闻

**Comment by maopashui** [comment]
> ### 检查清单
> 
> - [X] 之前没有人提交过类似或相同的功能请求。
> - [X] 这个建议不会背离 my-tv 的初衷。
> 
> ### 改进目的
> 
> 增加荔枝网的节目频道，这个是固定的，广东地区基本所有常用的台荔枝网都有，但是他只有网页，没有app，电脑观看起来比较麻烦，网址https://www.gdtv.cn/
> 
> ### 解决方案
> 
> 如果能爬出来加上荔枝台的节目，广大广东观众不胜感激
> 
> ### 额外信息
> 
> _No response_

荔枝网逆向比较复杂 要是有现成的代码作者应该会加

**Comment by lizongying** [comment]
#557
