### ISSUE TITLE
[FR] 请问可以加一些少儿频道嘛？

### ISSUE THREAD

**Issue by tikko-now** [lizongying/my-tv#602]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

想看一些例如少儿频道和金鹰卡通之类的频道

**Comment by ashsteins** [comment]
同意

**Comment by ashsteins** [comment]
目前是灵犀直播作为补充使用，就是广告有点多

**Comment by lizongying** [comment]
#557
