### ISSUE TITLE
这个要怎么下载？

### ISSUE THREAD

**Issue by xivi1839** [lizongying/my-tv#606]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

如内容。

### 解决方案

这个要怎么下载？是有两个版本吗，看到版本号都不同，有什么区别呢，要不然能不能v1改一下，
tv版应该下载哪个呢，求问，因为真看不懂

### 额外信息

如内容。

**Comment by charleyyy** [comment]
bytheway 你是认真的吗？
https://github.com/lizongying/my-tv/releases/

**Comment by Contralitary** [comment]
这能开一个issue太荒谬了。你这种类型的人适合在自媒体公众号那些地方当伸手党，不适合来GitHub。

**Comment by xivi1839** [comment]
大佬，别生气，小白是真心不懂，所以想发帖子请教的，没有恶意为难你，希望不要生气。

我还是看版本号下载Release v1.7.2就好了，谢谢大佬解答

**Comment by lizongying** [comment]
#607
