### ISSUE TITLE
[FR] 版本号有点看不懂，希望能更明确的区分

### ISSUE THREAD

**Issue by Crazyboyjw** [lizongying/my-tv#607]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

现在的版本号应该是奇偶数来区分的，但是小版本号放在大版本号前面实在是有些奇怪，下载的时候很容易让人分不清到底要下载哪一个

### 解决方案

明确区分两个类型，各自用各自的版本号

**Comment by syq6688** [comment]
单数是安卓5及以上专用，双数是支持高低版本安卓系统

**Comment by Su-YunLong** [comment]
看数字，单号安卓5 以上系统，双数安卓版本通用。

**Comment by amorous-monk** [comment]
同样有这困惑，版本号似乎不应该是这样命名。

**Comment by Fliny** [comment]
比如1.7.2更新了什么内容，后面又更新了1.6.7，那么前者更新的功能在后者里有吗，有些搞不懂

**Comment by hange2011** [comment]
不复杂，你是安卓5以上设备就一直更新单数的版本不用理双数的版本

**Comment by pooppiss** [comment]
为啥不统一成一个通用版本就好~通用版本不就是支持全版本的么~5以上的版本具体有啥不一样咧

**Comment by lizongying** [comment]
> 同样有这困惑，版本号似乎不应该是这样命名。

屬於特殊情況，就簡單處理了
1. 分成兩個項目不合適，區別不大
2. v1、v2這種方式，這種命名比較常見，也比較合理，但也無法體現並行關係。
3. a1、b1這種方式，這種也可以，但版本號的區間也必須分開
4. 單雙的方式，對於不熟悉的人確實不好區分，但從時間上看，總體是遞增的，而且如果後面合併的話，也比較容易。

實際上，當時想的沒這麼多，臨時就這麼定了，後面也就沒改。
