### ISSUE TITLE
[FR] 建议把频道的作为配置，不用每次更新频道去更新APP。同时增加升级功能。

### ISSUE THREAD

**Issue by weishd** [lizongying/my-tv#608]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

建议把频道的作为配置，不用每次更新频道去更新APP。同时增加升级功能。

### 解决方案

建议把频道的作为配置，不用每次更新频道去更新APP。同时增加升级功能。

### 额外信息

建议把频道的作为配置，不用每次更新频道去更新APP。同时增加升级功能。

**Comment by AppleMate60pro** [comment]
只要解决了更新频道就得下载更新APP这一点，升级功能真的没必要，别的功能更不需要，本来就是简单看电视央视卫视

**Comment by lizongying** [comment]
此項目無法進通過配置就能更新頻道
