### ISSUE TITLE
海信R43PRO型号装入最近my-tv版本运行半分钟出现画面短暂卡顿，然后一直是画音不同步

### ISSUE THREAD

**Issue by taddyboy** [lizongying/my-tv#609]
### 检查清单

- [x] 之前没有人提交过类似或相同的 bug report。
- [x] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

海信R43PRO型号装入最近my-tv版本运行半分钟出现画面短暂卡顿，然后一直是画音不同步，声音一直滞后几秒钟左右

### 预期行为

尽快解决

### 实际行为

尽快解决

### 复现步骤

发现很长时间了

### UI / OS

海信

### Android 版本

5

### 额外信息

望尽快解决

**Comment by taddyboy** [comment]
尽快更正

**Comment by taddyboy** [comment]
尽快更新

**Comment by lizongying** [comment]
可以試試最新版
