### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by WaitIU** [lizongying/my-tv#611]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

装上后闪退，黑屏无法观看，无法打开

### 预期行为

修复闪退

### 实际行为

打开后闪退、黑屏

### UI / OS

中国移动盒子(新魔百和M302A)

### Android 版本

4.4.2

### 额外信息

![14b81cfeeca9890944c8798ef2608d2](https://github.com/lizongying/my-tv/assets/95266274/d7080984-090a-4bf7-8948-3126ec2ef95a)

**Comment by WaitIU** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的 bug report。
> * [x]  我正在使用本软件的最新版本。
> 
> ### my-ty 版本
> 通用版
> 
> ### Bug 描述
> 装上后闪退，黑屏无法观看，无法打开
> 
> ### 预期行为
> 修复闪退
> 
> ### 实际行为
> 打开后闪退、黑屏
> 
> ### 复现步骤
> _No response_
> 
> ### UI / OS
> 中国移动盒子(新魔百和M302A)
> 
> ### Android 版本
> 4.4.2
> 
> ### 额外信息
> 
![14b81cfeeca9890944c8798ef2608d2](https://github.com/lizongying/my-tv/assets/95266274/9e66bf96-2fa0-4d58-91b5-f1de83921143)
jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzkzOTUsIm5iZiI6MTcxMDkzOTA5NSwicGF0aCI6Ii85NTI2NjI3NC8zMTQ1MDQwNTItZDcwODA5ODQtMDkwYS00YmY3LTg5NDgtMzEyNmVjMmVmOTVhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDEyNTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODNiNzg2OTJiODY2MTJmNzY4MmUyYTZmNjIxNDA5NDRjZTU2ZTk3MjMyNmFhM2Q4NjY3OGIwYWE5MDJhNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lgai7Bf7wDrzag0PncDCwmCUTEycnE_b_Lo3sWTMbhQ)

**Comment by WaitIU** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的 bug report。
> * [x]  我正在使用本软件的最新版本。
> 
> ### my-ty 版本
> 通用版
> 
> ### Bug 描述
> 装上后闪退，黑屏无法观看，无法打开
> 
> ### 预期行为
> 修复闪退
> 
> ### 实际行为
> 打开后闪退、黑屏
> 
> ### 复现步骤
> _No response_
> 
> ### UI / OS
> 中国移动盒子(新魔百和M302A)
> 
> ### Android 版本
> 4.4.2
> 
> ### 额外信息
> 
![14b81cfeeca9890944c8798ef2608d2](https://github.com/lizongying/my-tv/assets/95266274/f41d440a-68a7-4f20-ae89-7cfa1aa406c1)

**Comment by WaitIU** [comment]
![14b81cfeeca9890944c8798ef2608d2](https://github.com/lizongying/my-tv/assets/95266274/cc55127e-9c44-4b5e-8a37-6e3bba250d43)

**Comment by lizongying** [comment]
已知，暫時沒設備測試。
