### ISSUE TITLE
[FR] 希望辽宁、山东、河北、安徽、天津台增强画质

### ISSUE THREAD

**Issue by taddyboy** [lizongying/my-tv#612]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

改成高清画质

**Comment by ashsteins** [comment]
同意 ，目前感觉不到720p

**Comment by ashsteins** [comment]
本质原因是央视频那边的源不清晰，因为央视频也没有山西卫视等，所以这边也没跟进

**Comment by taddyboy** [comment]
大佬，没有别的办法吗？

**Comment by ashsteins** [comment]
央视影音里面台比较全，还有香港台

**Comment by lizongying** [comment]
儘量
