### ISSUE TITLE
[FR] 央视影音里面有HKS香港台还有山西卫视等缺少的台，可以看看他的源

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#614]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

央视影音里面有HKS香港台还有山西卫视等缺少的台，可以看看他的源

### 解决方案

央视影音里面有HKS香港台还有山西卫视等缺少的台，可以看看他的源

**Comment by ashsteins** [comment]
顶一下

**Comment by lizongying** [comment]
#557
