### ISSUE TITLE
[FR] 是否可以增加gitee的更新通道

### ISSUE THREAD

**Issue by pooppiss** [lizongying/my-tv#615]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

访问github不用加速器会访问不了，无法更新。

### 解决方案

是否有可能有gitee自动更新的通道

### 额外信息

无

**Comment by lizongying** [comment]
不是github
