### ISSUE TITLE
等一个TVB翡翠台[FR] 

### ISSUE THREAD

**Issue by sevenill2626** [lizongying/my-tv#617]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

等一个TVB翡翠台

**Comment by MatinxHT** [comment]
其实..引入海外电视台的资源可能会加速这个项目的灭亡...

**Comment by ashsteins** [comment]
央视影音有HKS香港台，说明官方承认是海内

**Comment by lizongying** [comment]
#557
