### ISSUE TITLE
[FR] 为APP设计了一款logo

### ISSUE THREAD

**Issue by bymjsss** [lizongying/my-tv#619]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

现在的logo过于单调，所以闲来无事做了一个，非专业。
![my-tv](https://github.com/lizongying/my-tv/assets/57902552/3c85f136-2539-474f-af19-4a9fc0bd45f0)

**Comment by pooppiss** [comment]
看着像哔哩哔哩~

**Comment by bymjsss** [comment]
![mytv](https://github.com/lizongying/my-tv/assets/57902552/ba4ce817-77a8-4ced-bd80-934062dbd332)

**Comment by tsukitsukitori** [comment]
还需要一个长方形LOGO，适配当贝桌面那种。

**Comment by qianjingyinzhang** [comment]
觉得没必要搞得花里胡哨，简单明了，四个大字就很不错啦。初衷都是为了方便开电视，特别是家里不懂智能电视机的爸妈或者爷爷奶奶辈分的人使用。

**Comment by Buidmeow** [comment]
应该再来一个纯英文的MY-TV

**Comment by bjfengzq** [comment]
> 觉得没必要搞得花里胡哨，简单明了，四个大字就很不错啦。初衷都是为了方便开电视，特别是家里不懂智能电视机的爸妈或者爷爷奶奶辈分的人使用。

同意，我自己其实很少看电视节目主要还是家里老人用，所以简单直观就好了。

**Comment by ycgeyks** [comment]
我能说这两logo还不如现在的这个么....

**Comment by pyccl** [comment]
这不就是B站么？😁😁😁

**Comment by sz20000** [comment]
的确啊，还不如现在的

**Comment by bymjsss** [comment]
> 我能说这个标志还不如现在的这个……

可以，人各有爱，你们有自己的发言权。

**Comment by lizongying** [comment]
感謝支持，暫時先功能，後面再考慮換標
