### ISSUE TITLE
建议的建议：知道大家会喷，还是要讲

### ISSUE THREAD

**Issue by UnVzaGFu** [lizongying/my-tv#621]
建议大家除了bug反馈之外，不要在那提任何功能需求了，什么增加这台那台的源，增加这个功能那个功能，你们为何不直接去用tvbox或者那些多如牛毛的tvbox套壳版直播app呢，那里花里胡哨的，台也多，你们提的这功能那功能那里都有，去那不好么，my-tv就是以简洁干净速度快而闻名，我觉得作者的想法非常好，目前除了修复bug之外没必要添加任何多余的功能了，当然作者自己有想法还是支持的，就说这么多吧，好了，大家快来喷

**Comment by pooppiss** [comment]
英雄所见略同

**Comment by bjfengzq** [comment]
简单就好。

**Comment by AppleMate60pro** [comment]
本来就是为了简单看电视，就是有那么些傻逼要求人家加这些加那些，真把作者当黑奴。不要钱还要求人家，赞赏不见赞赏一块钱

**Comment by Apollo-yeah** [comment]
我觉得也还好吧。提issue是用户的权利，做不做也是作者的选择，也没说一提issue作者就要给你做出来，作者也是选他自己感兴趣的才会去做，双向奔赴而已，也没你说的那么夸张啦。

**Comment by Apollo-yeah** [comment]
有大家当产品经理和QA测试，得到新的需求和应用测试总好过自己一个人孤零零写着一大堆代码和做出产品没人欣赏，当然这也只是我个人看法。

**Comment by Su-YunLong** [comment]
my-tv就是以简洁干净速度快而闻名，纯看电视。原生态。支持，目前工程够用，修复BUG 比增加功能更有意义。做精不做杂！

**Comment by wangyupo** [comment]
同意，顶

**Comment by lijiaoyang** [comment]
支持

**Comment by lfm09** [comment]
现在的版本在app稳定性和频道稳定性上都还不够，个人认为最重要的就是提高稳定性、可用性

**Comment by WendelYu** [comment]
是的爱折腾的有大把的东西自己折腾就好，这个稳定好用就行

**Comment by xjz5959** [comment]
不需要喷    萝卜白菜   各有所爱

**Comment by lizongying** [comment]
問題不大，在這些需求裡，還是有些很好的建議的，不合理的略過就好了，還能承受。另外，也確實自己能力有限，和大家的期望還有差距。
再次感謝你的支持。

**Comment by xjz5959** [comment]
简单  简约  简爱
