### ISSUE TITLE
[FR] 建议添加ipv6 源

### ISSUE THREAD

**Issue by wujingke** [lizongying/my-tv#623]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

https://github.com/drangjchen/IPTV    可以加入ipv6的源    基本上都能秒开

### 解决方案

ipv6的源比较稳定

**Comment by ycgeyks** [comment]
如果 自定义源 功能实现的话,这个应该也ok了

**Comment by lizongying** [comment]
#684
