### ISSUE TITLE
通用版检测更新时，显示更新失败

### ISSUE THREAD

**Issue by asd519627326** [lizongying/my-tv#625]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

通用版检测更新时，显示更新失败，这个跟网络有关吗？

### 预期行为

可以正常更新，并且如果有更新，则打开软件自动提示

### 实际行为

显示更新失败

### UI / OS

暴风TV

### Android 版本

4.4

**Comment by lizongying** [comment]
可能網絡原因，換個時間試試
