### ISSUE TITLE
希望增加游戏风云上海新闻综合和上海都市

### ISSUE THREAD

**Issue by yanshixin3** [lizongying/my-tv#626]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

希望增加游戏风云上海新闻综合和上海都市

### 解决方案

希望增加游戏风云上海新闻综合和上海都市

### 额外信息

希望增加游戏风云上海新闻综合和上海都市

**Comment by sunnysu0608** [comment]
我的客户端🈶

**Comment by ashsteins** [comment]
灵犀直播有

**Comment by lizongying** [comment]
#557
