### ISSUE TITLE
[BUG]  通用版 无法观看 cctv6 cctv8等付费频道 ，安卓5以上那个版本就可以观看

### ISSUE THREAD

**Issue by lovetingyuan** [lizongying/my-tv#627]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

[BUG]  通用版 无法观看 cctv6 cctv8等付费频道 ，表现为切换到频道并没有反应，但是安卓5以上那个版本就可以观看

### 预期行为

列出的频道都可以观看

### 实际行为

切换了没反应 

### 复现步骤

直接切换到cctv6 

### UI / OS

康佳

### Android 版本

5

**Comment by sunnysu0608** [comment]
那你直接安装1.6.7版本就可以了，真笨

**Comment by vanniszsu** [comment]
> 那你直接安装1.6.7版本就可以了，真笨

中国互联网果然就是这样，一旦人多了，社区氛围就开始变差

**Comment by sunnysu0608** [comment]
> > 那你直接安装1.6.7版本就可以了，真笨
> 
> 中国互联网果然就是这样，一旦人多了，社区氛围就开始变差

哈哈

**Comment by lizongying** [comment]
#656
