### ISSUE TITLE
设置键[FR] 

### ISSUE THREAD

**Issue by sijidou** [lizongying/my-tv#630]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

在选台界面添加设置按钮，Android TV版本比较新的话，是没有设置键的。手机上双击很ok，但电视遥控没办法这样操作。

**Comment by lizongying** [comment]
1.7.3将左键打开播放列表，右键打开设置菜单
