### ISSUE TITLE
建议作者开发iOS版本

### ISSUE THREAD

**Issue by mytstar** [lizongying/my-tv#633]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

作者有没有兴趣搞个iOS和Mac版本，市场也很需要啊

**Comment by ashsteins** [comment]
不重要

**Comment by Contralitary** [comment]
建议你直接帮作者从头写代码，再帮作者交App Store开发者账号费用。市场也很需要啊

**Comment by Developer-echo** [comment]
#581 已经PASS了，就这样就中。

**Comment by OneLove520** [comment]
ios还是用aptv添加M3U订阅链接看电视吧。也挺稳定的

**Comment by leonardo110** [comment]
> 如果出了iOS版，我愿意付费购买APP，挺期待的

那不如直接用广电的机顶盒呢

**Comment by lizongying** [comment]
#461
