### ISSUE TITLE
[FR] 关于自定义源的功能建议

### ISSUE THREAD

**Issue by KazeLiu** [lizongying/my-tv#634]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

频道源失效的时候，就需要更新APP，但是我家人不会更新，我这边就看到了在todo内有个自定义源的想法，我就想提一个实现的方法。但是由于我不是安卓工程师，我只能提出我的想法，没法给出实现代码。

### 解决方案

我的想法是在类型里面增加自定义类，然后读取文件，可以读取电脑文件，也可以读取链接的文件，文件必须符合m3u文件规范。
每次打开程序的时候，读取一次m3u文件然后放到自定义源内。
然后建议添加收藏按钮，可以将收藏的电视放在列表最上面。

**Comment by ashsteins** [comment]
同意

**Comment by sunnysu0608** [comment]
> 同意

你同意有个屁用

**Comment by ashsteins** [comment]
> > 同意
> 
> 你同意有个屁用

沙比

**Comment by zzhmax** [comment]
且建议在现有电视台的情况下，额外再多一类自定义台。那这个东西就是神器了。

**Comment by AppleMate60pro** [comment]
你觉得自定义的台跟内置源可以共存？ @zzhmax

**Comment by AppleMate60pro** [comment]
@KazeLiu 麻烦你去作者主页看看，人家已经出了自定义源的版本，别老是在这里逼逼这个

**Comment by Hi-my-friends** [comment]
支持自定义源，建议使用DIYP或者派大星。作者的APP有自己的发展路线，估计是不想混合使用。

**Comment by laymanal** [comment]
作者本来就有自定义源的版本
[my-tv-0](https://github.com/lizongying/my-tv-0)

**Comment by younglYN** [comment]
> 作者本来就有自定义源的版本 [my-tv-0](https://github.com/lizongying/my-tv-0)

这个版本不太好用，界面优化和加载速度都没有原始版本的好用

**Comment by lizongying** [comment]
现在的我的电视所采用的源和通常的自定义源区别较大，如果要兼容两种方式也较为复杂，可能在使用上也会出现各种问题。
所以，建议使用[my-tv-0](https://github.com/lizongying/my-tv-0)
至于自定义源的速度慢等问题，这确实没有办法。播放速度取决于视频源的质量。
既然已经使用自定义源了，应该是对视频源有所了解的。
