### ISSUE TITLE
最新版去掉了凤凰系列和国际频道？

### ISSUE THREAD

**Issue by sz20000** [lizongying/my-tv#635]
我觉得凤凰系列不应该去掉啊。大多数人就是为了看凤凰资讯台。

**Comment by sunnysu0608** [comment]
> 我觉得凤凰系列不应该去掉啊。大多数人就是为了看凤凰资讯台。

因为不安全

**Comment by sz20000** [comment]
cgtv属于央视。凤凰系列也归新华社管。其实都是体制内的台。

**Comment by ashsteins** [comment]
> cgtv属于央视。凤凰系列也归新华社管。其实都是体制内的台。

没错，另外央视影音APP里面有HKS香港台，也是合法的体制内台
