### ISSUE TITLE
[FR] 不建议去除凤凰卫视，央视影音APP里面都有 HKS香港卫视，说明合法合规

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#636]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

不建议去除凤凰卫视，央视影音里面都有 HKS香港卫视，说明合法合规

**Comment by drw2005** [comment]
也觉得不应该去除，很多人喜欢凤凰卫视。

**Comment by yxhy1010** [comment]
这几个香港的频道真心不错，又没违法，都是正规的频道，为什么要去掉？不理解

**Comment by lizongying** [comment]
還會回來的。只是一個國內專版。
