### ISSUE TITLE
在电信网络（光猫）下不能正常看频道

### ISSUE THREAD

**Issue by kevinjian4212** [lizongying/my-tv#637]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

软件在电信网络下无法看频道（只要经过光猫出去的都不行），但是在电信卡用数据流量时可以看
在移动网络下都可以正常观看
是被墙了吗?之前用路由翻墙可以看。但是最近不行了，现在还能看凤凰三个台，别的都黑屏没信号
如何解决呀？

**Comment by lizongying** [comment]
我的电视与网络无关

**Comment by kevinjian4212** [comment]
你好，感谢你的回复！我确实出现了这样的情况，听别人说有的地方管的严就看不了，但是上个星期有一天也确实可以看，其余时间都不能看。感觉你的软件非常好用，但是我不会解决这个问题。
我出现的情况：
科学上网可以看，移动网络下可以看，电信网络用数据流量可以看，唯一不行的是经过光猫的都不行（路由wifi什么都不行）
光猫是拨号上网的，网络也是正常可以用的
当然你的软件是没有问题的，可能是我的网络不行吧，再次感谢你的无私奉献



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月3日(周三) 上午9:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lizongying/my-tv] 在电信网络（光猫）下不能正常看频道 (Issue #637)




 
我的电视与网络无关

**Comment by lizongying** [comment]
@kevinjian4212 如果是國內網絡，應該是不區分網絡的。也有可能是服務器的問題，恰好當時服務有問題，可以使用1.7.3和1.7.6無服務器版本
