### ISSUE TITLE
峰米T1电视，Android 9系统上无法切换频道

### ISSUE THREAD

**Issue by qixin1991** [lizongying/my-tv#638]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

峰米T1激光电视，安装了MyTV **1.6.6**、**1.6.9**以及**1.7.2** 三个版本都试过了，只有**CCTV1**可以正常播放，其他的频道切换有提示，但是始终停留在CCTV1上。

### 预期行为

可以正常切换播放的频道。

### 实际行为

只能观看CCTV1，切换频道无效

### UI / OS

峰米T1激光电视

### Android 版本

9

**Comment by JinLong369** [comment]
相同BUG。

**长虹 55Q3T**，**安卓 5.1.1**。之前使用 **my-tv 1.6.0** 是开机黑屏，但一般退出重进再换换台差不多能正常播放。

但今天升级到 **1.6.9** 后，首先是各种黑屏，退出重进得有个几遍吧，换换台能看了。但过一会儿，再换台，光右上角的数字和下方的频道信息变，画面还是之前频道的画面。又是各种换台，然后偶尔能正常换过去......

大佬，辛苦修复下，家里老人看电视就靠这个呢🤝

**Comment by lizongying** [comment]
重啟下軟件，大部分頻道可看
