### ISSUE TITLE
海信电视安装错误退出

### ISSUE THREAD

**Issue by eosps** [lizongying/my-tv#64]
海信电视 安卓4.4.2.软件安装成功。启动运行黑屏然后退出，提示  很抱歉，“我的电视”已停止运行。
软件版本1.4.0

**Comment by TLWAJ** [comment]
我家海信电视也差不多，安装成功，但是打开之后黑屏一段时间直接退出了，进不去软件，1.4.0和1.3.9都试过不好用了emmm

**Comment by zbby1987** [comment]
安卓4暂时不支持

**Comment by lizongying** [comment]
请安装1.4.2 [](https://github.com/lizongying/my-tv/releases/tag/v1.4.2)

**Comment by TLWAJ** [comment]
> 请安装1.4.2

已安装，成功运行，大佬太牛了
