### ISSUE TITLE
央视部分频道无法观看

### ISSUE THREAD

**Issue by Xiaomansnail** [lizongying/my-tv#640]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

央视只有1、4、13可以看，地方频道打开需要看脸😱😱

### 预期行为

央视只有1、4、13可以看，地方频道打开需要看脸😱😱

### 实际行为

央视只有1、4、13可以看，地方频道打开需要看脸😱😱

### UI / OS

三星note20U，荣耀

### Android 版本

手机12，电视不清楚

**Comment by starkong2022** [comment]
怎么感觉版本更新后，可看的越来越少了啊

**Comment by liuhualu1225** [comment]
是的，我也是这个bug地方台也看不了

**Comment by kiben2010** [comment]
我这里也一样

**Comment by OyutianO** [comment]
我也一样

**Comment by kkk25641463** [comment]
换哪个app啊

**Comment by lizongying** [comment]
重啟下軟件，大部分頻道可看

**Comment by joedai007** [comment]
> 重啟下軟件，大部分頻道可看

肯定都启动无数遍了才提交问题的
