### ISSUE TITLE
[BUG] 突然不能看了，除中央1台以外的所有频道

### ISSUE THREAD

**Issue by ffxxdjfcdjd** [lizongying/my-tv#641]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

专用版

### Bug 描述

刚才电视端打开黑屏无数据，上下切换频道也只有下面的频标没图像，选中央一台能看，打开手机端也一样，回退版本后打开直接秒退，装回最新版依旧秒退。

### 预期行为

不会是开发者本人停止运作了吧，本人小白一个

### 实际行为

不知道能不能修复好，最好用的软件

### UI / OS

创维

### Android 版本

12

**Comment by sunchengweiqq** [comment]
我也是类似的问题 用的最新版apk   只有央1 央4 央13能看

**Comment by loong-hy** [comment]
我也遇到了这个问题，在荣耀智慧屏上。

**Comment by wqx1970** [comment]
我也是只有中央电视台13的能看，其他都看不了。

**Comment by dabdida** [comment]
安卓4，通用版也一样，更新版本也不行，估计是源的问题。家里老人不会用tvbox之类，就会用这个，看作者最近能不能修复吧

**Comment by imaginekk** [comment]
很多都不能看了因该是电视源的问题

**Comment by yhl668** [comment]
感觉越升级越不对了

**Comment by lizongying** [comment]
#656
