### ISSUE TITLE
无法在我的电视上使用这个app

### ISSUE THREAD

**Issue by Ghost-M16A2** [lizongying/my-tv#642]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

版本1.6.9，手机和电脑模拟器上使用均正常，但是无法在电视上使用，进入就会立刻闪退

### 预期行为

正常使用

### 实际行为

闪退

### 复现步骤

在海信vidaa-d1电视上使用，进入就会立刻闪退

### UI / OS

海信vidaa-d1

### Android 版本

4.4.2

**Comment by youngdrak** [comment]
1.69你还在安卓4上用，作者上面都写了哪个版本用哪个系统，你的安卓4只能用尾数为双数的版本号
