### ISSUE TITLE
旧版本部分频道无法查看，最新版本黑屏进不去

### ISSUE THREAD

**Issue by wujinliang1** [lizongying/my-tv#644]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

旧版本部分频道无法查看，最新版本黑屏进不去

### 预期行为

旧版本部分频道无法查看，最新版本黑屏进不去

### 实际行为

旧版本部分频道无法查看，最新版本黑屏进不去

### UI / OS

安卓

### Android 版本

12

**Comment by kkk25641463** [comment]
一样

**Comment by jackyHuangH** [comment]
应该是源挂了的，看作者能不能修复吧

**Comment by kkk25641463** [comment]
源没挂，我把代码里的源粘贴出来可以用

**Comment by lizongying** [comment]
#656
