### ISSUE TITLE
[FR] 建议新增节相同目源的不同分辨率的选项

### ISSUE THREAD

**Issue by dairui2** [lizongying/my-tv#645]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

使用手机卡流量看电视节目时，节省网络流量

**Comment by whhxmwhh** [comment]
很想看香港无线新闻台。

**Comment by lizongying** [comment]
目前，如果不是重度使用，基本大家是流量过剩。
建议还是wifi环境观看，长时间流量观看也不太合理。
这个功能会考虑，但应该近期不会上。
