### ISSUE TITLE
重大BUG 闪退，无法使用。版本失效

### ISSUE THREAD

**Issue by Su-YunLong** [lizongying/my-tv#646]
1.62版，闪退黑屏，在海信IP903H 、创维E900、中兴B860-2.1均闪退黑屏！之前因为1.72不能正常播放部分频道，所以一直在用稳定的1.62.但是昨天开始1.62开始闪退！安装1.72正常进入，卸载安装1.62 仍然闪退！

**Comment by CzyYYDS** [comment]
好像已经修复更新了

**Comment by Su-YunLong** [comment]
关键是 1.62的央视 368都可以正常观看，现在新版本的看不了 ，旧版本的又开始闪退了~~~

**Comment by lizongying** [comment]
368不再維護，如遇閃退、無法播放等問題，可以升級到1.7.3或1.7.6
