### ISSUE TITLE
[BUG] 很多电视频道都换不了应该是电视源出问题了希望尽快修复

### ISSUE THREAD

**Issue by imaginekk** [lizongying/my-tv#647]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

[BUG] 很多电视频道都换不了应该是电视源出问题了希望尽快修复

### 预期行为

换频道

### 实际行为

没换或者黑屏

### 复现步骤

换台

### UI / OS

华为智慧屏

### Android 版本

鸿蒙

### 额外信息

无

**Comment by CzyYYDS** [comment]
好像已经修复更新了

**Comment by iseku** [comment]
1.7.4修复了，但还是有问题，有些频道不稳定，需要反复切换多次才能打开

**Comment by imaginekk** [comment]
> 1.7.4修复了，但还是有问题，有些频道不稳定，需要反复切换多次才能打开

是的bug有点多

**Comment by lizongying** [comment]
#656
