### ISSUE TITLE
[BUG] 通用版1.74，回归的凤凰香港3个台依旧无法收看。

### ISSUE THREAD

**Issue by yxhy1010** [lizongying/my-tv#648]
### 检查清单

- [ ] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

通用版1.74，回归的凤凰香港3个台依旧无法收看。

### 预期行为

感觉没有以前1.64的那么牛

### 实际行为

切换有卡顿

### 复现步骤

有些台有严重延迟黑屏现象，直接是跳不出来的，要回按以后才有信号。

### UI / OS

海信

### Android 版本

5.0

**Comment by drw2005** [comment]
我的4.4.2盒子上可以正常播放

**Comment by siul2018** [comment]
你的系统安卓5.0为什么不用5.0的版本呢 通用版是给安卓5.0以下的

**Comment by zequanmaoyi12** [comment]
清空下数据，重新启动。就可以看到了。

**Comment by grasscase** [comment]
很奇怪，电视无法播放这几个台，同样，用手机连接和电视一样的电信wifi无法播放，但是用中国移动的数据流量，就可以播放。然后切换为电信的信号，这几个台就无法播放。之前用电信wifi都可以，现在我要用移动流量才可以播放。

**Comment by lizongying** [comment]
建議升級到1.7.6試試
