### ISSUE TITLE
新版换台有停止不动，切换不了 

### ISSUE THREAD

**Issue by yishan2019** [lizongying/my-tv#650]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

1.74 新版换台有停止不动，切换不了 

### 预期行为

1.74 新版换台有停止不动，切换不了 

### 实际行为

1.74 新版换台有停止不动，切换不了 

### 复现步骤

1.74 新版换台有停止不动，切换不了 

### UI / OS

MAX96

### Android 版本

12

### 额外信息

1.74 新版换台有停止不动，切换不了

**Comment by Alpsky2023** [comment]
+1

**Comment by NI-Enrique** [comment]
+1

**Comment by sunnysu0608** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的 bug report。
> * [x]  我正在使用本软件的最新版本。
> 
> ### my-ty 版本
> 通用版
> 
> ### Bug 描述
> 1.74 新版换台有停止不动，切换不了
> 
> ### 预期行为
> 1.74 新版换台有停止不动，切换不了
> 
> ### 实际行为
> 1.74 新版换台有停止不动，切换不了
> 
> ### 复现步骤
> 1.74 新版换台有停止不动，切换不了
> 
> ### UI / OS
> MAX96
> 
> ### Android 版本
> 12
> 
> ### 额外信息
> 1.74 新版换台有停止不动，切换不了

就你屁事多

**Comment by quango-web** [comment]
好像都是cctv的好几个源出问题，比如央视台球，新安装软件可以看，退出来软件再回去就黑屏，掉黑洞里的感觉

**Comment by xinpenghan** [comment]
家里小米电视安装，也是这个问题，切换台，就是黑屏

**Comment by mangwei** [comment]
我从172好像就一直如此，再也没有162当时刚安装后丝滑换台感觉了

**Comment by geyaowei** [comment]
+1

**Comment by lizongying** [comment]
#656
