### ISSUE TITLE
[FR] 做好目前频道即可，清晰稳定最重要的，别的可有可无

### ISSUE THREAD

**Issue by df12345l** [lizongying/my-tv#651]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

人们的要求其实是  ——  有的看就行，就这一个要求。

丰富性不重要，因为要论丰富，有大把的方式去实现，

**Comment by lizongying** [comment]
尽量
