### ISSUE TITLE
建议做两个版本，一个是频道不变，只做稳定性，不升级

### ISSUE THREAD

**Issue by df12345l** [lizongying/my-tv#652]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

另一个可根据网民提议更改

**Comment by Su-YunLong** [comment]
顶你  稳定高于一切，习主席一再强调，要维稳，维稳啊！

**Comment by lizongying** [comment]
受限于服务器，可能比较困难。
