### ISSUE TITLE
1.7.4   刚试了，早上换台没问题，晚上问题严重

### ISSUE THREAD

**Issue by df12345l** [lizongying/my-tv#656]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

除了启动黑屏，没有问题了，或者，不要再升级了

**Comment by whtk** [comment]
这是为啥 难道是服务器的问题？

**Comment by df12345l** [comment]
> 这是为啥 难道是服务器的问题？

慢慢换没问题

**Comment by myworksfun** [comment]
1.74 凤凰几个都无法播放，大家是不是这样的？

**Comment by grasscase** [comment]
> 1.74 凤凰几个都无法播放，大家是不是这样的？

用电信网络无法播放，但我用移动数据流量3个台都可以。

**Comment by quango-web** [comment]
安装环境：google tv，安卓12系统
软件顽疾，新安装则全部台正常，退出并关闭进程后再进去就有很多央视台黑屏（比如央视台球），但是进入软件设置清理数据缓存后重新进入又可正常播放了，不过这种操作是个死循环

**Comment by dwbii** [comment]
> 安装环境：google tv，安卓12系统 软件顽疾，新安装则全部台正常，退出并关闭进程后再进去就有很多央视台黑屏（比如央视台球），但是进入软件设置清理数据缓存后重新进入又可正常播放了，不过这种操作是个死循环

同样问题，我从3月18日到现在的软件都试过，都有这问题

**Comment by lfm09** [comment]
感觉这类问题一直不断啊，太影响使用了，希望能尽早解决、稳定下来

**Comment by myworksfun** [comment]
> > 1.74 凤凰几个都无法播放，大家是不是这样的？
> 
> 用电信网络无法播放，但我用移动数据流量3个台都可以。

测试了一下，电信网确认无法播放，一直显示“黑屏”，用联通的网是可以播放的，所以这个与App无关。😂

**Comment by lizongying** [comment]
服務器問題。
在1.7.6不用連接服務器了，去掉了部分無法觀看的收費頻道，部分頻道的清晰度會下降。
用戶量太大，帶寬不足，特別是晚上高峰期。
服務器確實無法持續，建議使用無服務器版本，如1.7.6。

**Comment by lizongying** [comment]
服務器問題。
在1.7.6不用連接服務器了，去掉了部分無法觀看的收費頻道，部分頻道的清晰度會下降。
用戶量太大，帶寬不足，特別是晚上高峰期。
服務器確實無法持續，建議使用無服務器版本，如1.7.6。

**Comment by df12345l** [comment]
嗯，这个版本问题少了很多，就是一台清晰度差一点&nbsp;


平安
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月2日(星期二) 晚上11:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lizongying/my-tv] 1.7.4   刚试了，早上换台没问题，晚上问题严重 (Issue #656)














 
服務器問題。
 在1.7.6不用連接服務器了，去掉了部分無法觀看的收費頻道，部分頻道的清晰度會下降。
 用戶量太大，帶寬不足，特別是晚上高峰期。
 服務器確實無法持續，建議使用無服務器版本，如1.7.6。
