### ISSUE TITLE
[FR] 谢谢作者！能否增加上海的地方台，链接已添加

### ISSUE THREAD

**Issue by cfotpo** [lizongying/my-tv#657]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

https://live.kankanews.com/ 这个是web页面，源地址目测是动态生成的，不知如何添加进app内

**Comment by ashsteins** [comment]
支持

**Comment by AppleMate60pro** [comment]
不重要

**Comment by uzjihc** [comment]
能把那些非数字系列的中央台给干掉，或者是放到最后面国外那些频道前面最好，上海地方台除了上海人谁看呀

**Comment by ni7ht** [comment]
这个需求推荐用tv端浏览器解决就好了。

**Comment by lizongying** [comment]
#557
