### ISSUE TITLE
大佬太强了！能否增加一些香港频道信号源呢，比如凤凰中文和凤凰资讯这种~

### ISSUE THREAD

**Issue by TLWAJ** [lizongying/my-tv#66]

**Comment by postxx** [comment]
最好别加，只要符合基本需求就行了，稳定才是最好的。

**Comment by TLWAJ** [comment]
> 最好别加，只要符合基本需求就行了，稳定才是最好的。

呃，加上也不会影响稳定吧emmm，毕竟大家天南海北的观看电视的需求也不同，只是衷心希望这个软件能做的更好才提出的建议

**Comment by lizongying** [comment]
已增加鳳凰衛視[v1.6.1](https://github.com/lizongying/my-tv/releases/tag/v1.6.1)
