### ISSUE TITLE
解决没有菜单键的遥控器问题

### ISSUE THREAD

**Issue by i2play** [lizongying/my-tv#660]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

小米盒子国际版，没有菜单键，能否加入按左或右键进入菜单功能，现有的左右键和上下键一样都是换台。

**Comment by lizongying** [comment]
1.7.3將右鍵進入菜單
