### ISSUE TITLE
[FR] 建议增加CHC的3个电影频道为谢......

### ISSUE THREAD

**Issue by yxhy1010** [lizongying/my-tv#661]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

**建议设三个CHC电影轮播频道，高清电影\家庭影院\动作电影，可否增加点娱乐性呢？**

**Comment by UAS0100** [comment]
干嘛不内置m3u直播源呢，每次增加减少修改频道都要升级APP挺麻烦的

**Comment by lizongying** [comment]
> 干嘛不内置m3u直播源呢，每次增加减少修改频道都要升级APP挺麻烦的

可以使用 [我的電視·〇](https://github.com/lizongying/my-tv-0)

**Comment by lizongying** [comment]
#557
