### ISSUE TITLE
[BUG] 最新版本(v1.7.4)的频道切换不稳定，40%概率切换失败，切换失败的具体表现为点击无反应

### ISSUE THREAD

**Issue by cyk0602** [lizongying/my-tv#663]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

最新版本(v1.7.4)的频道切换不太稳定，40%概率切换失败，切换失败的具体表现为点击无反应

### 预期行为

稳定切换到对应频道

### 实际行为

点击切换频道无反应

### 复现步骤

测试设备：华为手机、小米电视
设备版本：Android10
测试视频：↓↓↓<video src="https://github.com/lizongying/my-tv/assets/87061073/a9c44179-03df-428f-84c0-507ad1a636bb"></video>

### UI / OS

XIAOMI

### Android 版本

10

**Comment by ashsteins** [comment]
一样

**Comment by Mluocheng** [comment]
40%

**Comment by 438602062** [comment]
一样

**Comment by quango-web** [comment]
问题基本集中在CCTV的体育类或高清台，但CCTV1却很稳定

**Comment by rwwang50** [comment]
一样

**Comment by myworksfun** [comment]
I encountered the same problem. +1 😄

**Comment by cliff19721108** [comment]
凤凰卫视突然没了

**Comment by zimmer-python** [comment]
感谢反馈！

**Comment by lizongying** [comment]
#656
