### ISSUE TITLE
问个关于中央368的问题[FR] 

### ISSUE THREAD

**Issue by whtk** [lizongying/my-tv#664]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

为啥这几个台不行，是不是信号问题

**Comment by drw2005** [comment]
也很好奇，这三个台有啥不同吗？
去掉后切换又快起来了。

**Comment by CarefulHuo** [comment]
我每次切换到这三个台总是GG，然后会影响到其他的中央台

**Comment by yxhy1010** [comment]
估计是不是程序有什么冲突？我是这样操作的，如：切到CCTV3黑屏是，立马退出整个程序，然后再进去，因为上次卡在CCTV3了，进去以后稍微停顿一下，CCTV3就出来了，其他不能跳出来的频道，依次这样操作能暂时解决这个BUG，也是没有办法的办法，你们可以试试，跟电视品牌没任何关系，是软件的问题，目前也只能如此。我是用通用版1.74......

**Comment by AppleMate60pro** [comment]
> 也很好奇，这三个台有啥不同吗？ 去掉后切换又快起来了。

央视频368是会员频道

**Comment by AppleMate60pro** [comment]
@drw2005 因为在央视频需要会员才能看368台

**Comment by drw2005** [comment]
> @drw2005 因为在央视频需要会员才能看368台

印象中之前是正常的啊，为什么呢。

**Comment by wujingke** [comment]
ipv6  源  就没这个问题

**Comment by AppleMate60pro** [comment]
> > > 也很好奇，这三个台有啥不同吗？ 去掉后切换又快起来了。
> > 
> > 
> > 央视频368是会员频道
> 
> > @drw2005 因为在央视频需要会员才能看368台
> 
> 之前为啥能正常观看呢？

因为作者之前经常频繁在维护呗，你真人家黑奴啊

**Comment by AppleMate60pro** [comment]
> ipv6 源 就没这个问题

你确定久了没有问题？只不过用的时间长一点，不像IPV4的源频繁变

**Comment by javadodobird** [comment]
3、6、8、风云是央视加密收VIP费的，作者不断去破密服务器最后会承受不了的（中国有14亿人僧多服务器少），还很可能会被请去和有关部门聊天，最后可能大家连其它免费的都会失去沒的看了，作者能做到现在这样就已经很大胆很好了，感谢作者。

**Comment by AppleMate60pro** [comment]
> 3、6、8、风云是央视加密收VIP费的，作者不断去破密服务器最后会承受不了的（中国有14亿人僧多服务器少），还很可能会被请去和有关部门聊天，最后可能大家连其它免费的都会失去沒的看了，作者能做到现在这样就已经很大胆很好了，感谢作者。
很多人不知道的，也不看看代码

**Comment by AppleMate60pro** [comment]
> 估计是不是程序有什么冲突？我是这样操作的，如：切到CCTV3黑屏是，立马退出整个程序，然后再进去，因为上次卡在CCTV3了，进去以后稍微停顿一下，CCTV3就出来了，其他不能跳出来的频道，依次这样操作能暂时解决这个BUG，也是没有办法的办法，你们可以试试，跟电视品牌没任何关系，是软件的问题，目前也只能如此。我是用通用版1.74......

368偶尔看不了，请看下面的回答你会知道答案

**Comment by wujingke** [comment]
ipv6  和移动  联通 都是免费的    为啥要费力去破解
