### ISSUE TITLE
[BUG] 安装了最新版，再安装旧版的时候，会提示安装文件损坏

### ISSUE THREAD

**Issue by GoTop** [lizongying/my-tv#665]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

不管是通用版还是专用版，安装了最新版，再安装旧版的时候，会提示安装文件损坏

### 预期行为

旧版的my-tv能正常安装

### 实际行为

再安装旧版的时候，会提示安装文件损坏

### UI / OS

Shield TV 国内版

### Android 版本

7

**Comment by yxhy1010** [comment]
@GoTop 用电视自带的清理工具彻底清除一下缓存，重新安装一下试试。

**Comment by zxhans** [comment]
为啥版本号要变成 1.7.3呢？

**Comment by imaginekk** [comment]
> 为啥版本号要变成 1.7.3呢？

我也好奇这个版本号

**Comment by lovelyelfpop** [comment]
@imaginekk @zxhans  my-tv 分2个版本：**通用版**（支持比较旧的电视的安卓版本比如4.x），和  **安卓5及以上专用**
2者的版本号是各自递增的，可能会出现交叉现象，一会前者版本号高，一会后者版本号高。

**Comment by GoTop** [comment]
> 1、apk是不能降级覆盖安装的，装了高版本号后不能再装低版本号，除非先卸载掉已安装的高版本的app。 2、如果电视安卓版本比较老（比如安卓4.x），是不能安装 **安卓5及以上专用** 这个版本的。尝试安装时系统会提示安装包已损坏，或提示无法解析

我用的是2017版的神盾TV，应该是安卓5以上的系统

我都是将旧版的卸载之后，再安装新版的，而且两个版本我都尝试这安装，可是都会提示：“安装文档损坏”

我再试试吧

**Comment by lizongying** [comment]
安卓設備一般都不會允許安裝舊版，必須先刪除舊版本。
