### ISSUE TITLE
[FR] 希望可以增加河南电视台都市频道吗？非常感谢[FR] 

### ISSUE THREAD

**Issue by AvatarGuo** [lizongying/my-tv#666]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

家里人比较喜欢看民生频道，非常感谢，不知道自己怎么加频道，有群或者有加频道的帮助文档自行添加也行，非常感谢

**Comment by imaginekk** [comment]
地方台因为没有稳定的电视源，每隔一段时间，源就会失效到时候就又看不了多半是不会加的

**Comment by lizongying** [comment]
#557
