### ISSUE TITLE
只有香港台可以看，其他的都看不了[BUG] 

### ISSUE THREAD

**Issue by wanminny** [lizongying/my-tv#667]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

在 LAEC 电视 上安装了1.7.4 刚开始cctv都有台，下午的时候突然没有了cctv；都不能看，然后卸载安装，重置还是没有成功；只能看香港的三个台，其他都是黑屏;

### 预期行为

在 LAEC 电视 上安装了1.7.4 刚开始cctv都有台，下午的时候突然没有了cctv；都不能看，然后卸载安装，重置还是没有成功；只能看香港的三个台，其他都是黑屏;

### 实际行为

在 LAEC 电视 上安装了1.7.4 刚开始cctv都有台，下午的时候突然没有了cctv；都不能看，然后卸载安装，重置还是没有成功；只能看香港的三个台，其他都是黑屏;

### UI / OS

LAEC

### Android 版本

5

**Comment by wanminny** [comment]
几个小时后面又好了，不太稳定~~

**Comment by lizongying** [comment]
升級到最新版吧
