### ISSUE TITLE
[FR] 希望恢复cctv3 cctv6 cctv8 尤其是中央6台电影频道。

### ISSUE THREAD

**Issue by wind-3364** [lizongying/my-tv#670]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

【希望恢复cctv3 cctv6 cctv8 】尤其是中央6台电影频道。老人喜欢😍其他的没有这个频道重要。

### 解决方案

谢谢作者

### 额外信息

作者谢谢啦

**Comment by WFANG12719** [comment]
这三个频道的mustToken = true

**Comment by wujingke** [comment]
用ipv6源吧

**Comment by mtdxc** [comment]
> 用ipv6源吧

怎么弄么？

**Comment by yxhy1010** [comment]
现在连风云足球都没了，少了太多频道，没以前那么稳定

**Comment by psumycom** [comment]
> 现在连风云足球都没了，少了太多频道，没以前那么稳定

要求不要那么高，免费的软件能看现有的这些已经非常满足了，如果有稳定的源肯定会添加进去的，不用提作者也会加上，没有稳定的源加上过不了几天又失效了意义不大，相信作者比我们明白的很。

**Comment by freedy82** [comment]
純碎問一下
https://tv.cctv.com/live/cctv6/
https://tv.cctv.com/live/cctv8/
是用特殊方式播放嗎?
不可以拿來用吧?

**Comment by javadodobird** [comment]
3、6、8、风云是央视加密收VIP费的，作者不断去破密服务器最后会承受不了的（中国有14亿人僧多服务器少），还很可能会被请去和有关部门聊天，最后可能大家连其它免费的都会失去沒的看了，作者能做到现在这样就已经很大胆很好了，感谢作者。
