### ISSUE TITLE
既然有些台没有视频，建议主页就干脆别放台标[BUG] 

### ISSUE THREAD

**Issue by wwjj999** [lizongying/my-tv#671]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

既然有些台没有视频，建议主页就干脆别放台标，免得大家误会，切换频道时也经常不知道自己切换成功没有。

### 预期行为

常态

### 实际行为

常态

### 复现步骤

每次

### UI / OS

xiaomi box

### Android 版本

android tv 9

**Comment by ashsteins** [comment]
?

**Comment by lizongying** [comment]
暫無好的處理辦法
