### ISSUE TITLE
[BUG] 自动更新不可用

### ISSUE THREAD

**Issue by OopsAngela** [lizongying/my-tv#672]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

专用版

### Bug 描述

自动更新功能一直不可用，点击确定更新但是无反应

### 预期行为

应该更新到新版本

### 实际行为

没有任何反馈。

### 复现步骤

点击检查更新，确定更新

### UI / OS

TCL Q10H

### Android 版本

11

**Comment by Fliny** [comment]
同上。我的极光盒子也是一样，点了啥反应都没

**Comment by falltree** [comment]
自从有了自动更新功能，好像是1.69？
我尝试自动更新就没有成功过，尝试过能看到新的版本，但点击更新无反应；要么是根本不显示云端最新的版本号
(注：非网络问题，全部设备可以访问外网)

**Comment by pangpanglong123** [comment]
和其他软件的自动更新完全不一样，魔百盒上点击后显示有新版本但没有进一步反应，模拟器上显示有文件下载但不能安装，

**Comment by huifei0129** [comment]
> 自从有了自动更新功能，好像是1.69？ 我尝试自动更新就没有成功过，尝试过能看到新的版本，但点击更新无反应；要么是根本不显示云端最新的版本号 (注：非网络问题，全部设备可以访问外网)

请教如何设置“全部设备可以访问外网”？谢谢

**Comment by lizongying** [comment]
#772
