### ISSUE TITLE
[FR] 希望能增加内蒙古卫视，谢谢。

### ISSUE THREAD

**Issue by cliff19721108** [lizongying/my-tv#674]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

了解内蒙古地区的风土人情和发展。

**Comment by javadodobird** [comment]
内蒙古卫视沒有信号加不了的。

**Comment by cliff19721108** [comment]
好的，目前加不了，还是要说声谢谢！

**Comment by lizongying** [comment]
#557
