### ISSUE TITLE
华为智慧屏 鸿蒙系统兼容 [FR] 

### ISSUE THREAD

**Issue by Mluocheng** [lizongying/my-tv#676]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

鸿蒙系统兼容

### 额外信息

华为智慧屏 hege-550 , 才发现是鸿蒙系统， 自动更新检查闪退， cctv6 看不了等情况。 可以修修吗？

**Comment by Mluocheng** [comment]
> 不愧是增智慧屏，建议自己写

叫你写了吗？？？

**Comment by Developer-echo** [comment]
跟这没关系，我一台华为65，一台tcl更新检测都闪退的。可能是 response stream 流处理问题，和系统没关系。

**Comment by 9dark9** [comment]
鸿蒙啊，自己写吧，没必要浪费精力兼容，反正那玩意不是一直吹说不是安卓

**Comment by myworksfun** [comment]
The experience and execution efficiency of HarmonyOS's App programming are indeed not very good.😂

**Comment by 18690819111** [comment]
鸿蒙去找鸿蒙的 app，这里是安卓

**Comment by lizongying** [comment]
自動更新開發測試中
