### ISSUE TITLE
[FR] 省级下面的地方台都没有么？比如湖南都市频道之类的。

### ISSUE THREAD

**Issue by kimcaiyuan** [lizongying/my-tv#680]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

[FR] 省级下面的地方台都没有么？比如湖南都市频道之类的。

**Comment by javadodobird** [comment]
市，县地方台请用其他软件看吧，
这个软件有央视(非vip台），省卫视，CGTN已经很足夠很好了，感谢作者。

**Comment by lizongying** [comment]
#557
