### ISSUE TITLE
垃圾地方台加这么多干什么，看这些提的要求真的难蚌。

### ISSUE THREAD

**Issue by tty008** [lizongying/my-tv#682]
垃圾卫视地方台加这么多干什么，看这些提的要求真的难蚌。基本没人看的还要求人加进来。

**Comment by taddyboy** [comment]
台不在多，精品就可以，但是软件一直解决不了央视368还有风云、怀旧，第一剧场正常收看，是个遗憾

**Comment by makailin** [comment]
你不看就等于垃圾是吧？废话占用lssues的属实沾点。

**Comment by ashsteins** [comment]
你不看就等于垃圾是吧？废话占用lssues的属实沾点。.

**Comment by javadodobird** [comment]
市，县地方台请用其他软件看吧，
这个软件有央视(非vip台），省卫视，CGTN已经很足夠很好了，感谢作者，
甚至有那3个凤凰台(个人感觉)我都觉得有冒险有风险了。

**Comment by lizongying** [comment]
#557
