### ISSUE TITLE
[FR] 分享凤凰卫视源

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#683]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

#EXTINF:-1 tvg-id="凤凰中文" tvg-name="凤凰中文" tvg-logo="https://live.fanmingming.com/tv/凤凰卫视中文台.png" group-title="卫视频道",凤凰中文
http://play-flive.ifeng.com/live/06OLEGEGM4G.m3u8
#EXTINF:-1 tvg-id="凤凰资讯" tvg-name="凤凰资讯" tvg-logo="https://live.fanmingming.com/tv/凤凰卫视资讯台.png" group-title="卫视频道",凤凰资讯
http://play-flive.ifeng.com/live/06OLEEWQKN4.m3u8
http://113.64.145.91:8081/hls/36/index.m3u8
#EXTINF:-1 tvg-id="凤凰香港" tvg-name="凤凰香港" tvg-logo="https://live.fanmingming.com/tv/凤凰卫视香港台.png" group-title="卫视频道",凤凰香港
http://113.64.145.91:8081/hls/38/index.m3u8

**Comment by AppleMate60pro** [comment]
不重要

**Comment by think2011** [comment]
<img width="990" alt="image" src="https://github.com/lizongying/my-tv/assets/3961388/ae8e874d-dc76-415a-8328-ac0092c2f94f">
最新的版本gnag'hao刚好就缺了这3个图标

**Comment by lizongying** [comment]
#684
