### ISSUE TITLE
请尽快恢复央视3、6、后面的一些频道，不然这个软件已经没有什么意义了。

### ISSUE THREAD

**Issue by yxhy1010** [lizongying/my-tv#685]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

请尽快恢复央视3、6、8、第一剧场、兵器科技、风云足球、风云剧场、风云音乐、怀旧剧场、世界地理等节目，不然这个软件真的没办法看了，也只能放弃了。

**Comment by taddyboy** [comment]
同感

**Comment by huanyusb** [comment]
我建议提类似要求的时候，先扫一下项目主页上的赞赏码。

**Comment by ashsteins** [comment]
可以先用灵犀直播

**Comment by javadodobird** [comment]
3、6、8、风云是央视加密收VIP费的，作者不断去破密服务器最后会承受不了的（），

**Comment by javadodobird** [comment]
> 能不能有一种方法，作者缴纳VIP费用，方便大家稳定收视，软件用户如需观看这些收费电视，向作者通过某种途径分摊VIP费用

不可能的，变相挣国家政府的钱，更加罪加一等。

**Comment by taddyboy** [comment]
灵犀直播也是一个挺好的直播软件，节目多，广，就是频道切换速度不能和我的电视相比，原来打开软件还可以直接进入到上次退出时的频道，很不错，可惜现在购物台多了，清晰度也没有我的电视质量好，但是他可以和我的电视互补，弥补我的电视节目短板

**Comment by yxhy1010** [comment]
> 我建议提类似要求的时候，先扫一下项目主页上的赞赏码。

好像就你知道似的，我又没瞎。。。。

**Comment by DaiyuChen** [comment]
> 能不能有一种方法，作者缴纳VIP费用，方便大家稳定收视，软件用户如需观看这些收费电视，向作者通过某种途径分摊VIP费用

你是想把别人送进去吧

**Comment by lizongying** [comment]
抱怨無助於解決問題。“儘快”、“不然”，這樣的字眼，讓人很不舒服。
用戶不多的時候，在我可以承受的成本下維護以上頻道。
而當大量用戶湧入，成本激增，作為一個免費軟件肯定是承受不了的。
另外，比如用戶容量是十萬，多一個人，可能就導致所有人都用不了，讓誰看不讓誰看？
這種方式也是不可持續的，越是頻道多越好，用戶就越多，負載越大，最終服務不可用。
既然選擇了免費，就不會加入購物台、廣告，
既然選擇了開源，就不會在軟件裡加入木馬病毒！
可以選擇不用這個軟件，這是您的自由！
