### ISSUE TITLE
[BUG]  CCTV10 无法播放

### ISSUE THREAD

**Issue by Jaydar** [lizongying/my-tv#686]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

因版权问题暂停直播信号源

### 预期行为

因版权问题暂停直播信号源

### 实际行为

因版权问题暂停直播信号源

### UI / OS

XIAOMI

### Android 版本

10

**Comment by javadodobird** [comment]
因版权问题暂停直播信号源，
过了版权问题节目的时间（通常1个小时），CCTV10就会恢复正常了，放不了就放不了，
既然这些版权方这么小气，就留着让他们自己当宝贝一样藏着掖着吧，咱们不看就是了。

**Comment by AppleMate60pro** [comment]
> 因版权问题暂停直播信号源， 过了版权问题节目的时间（通常1个小时），CCTV10就会恢复正常了，放不了就放不了， 既然这些版权方这么小气，就留着让他们自己当宝贝一样藏着掖着吧，咱们不看就是了。
他们不知道的，看不了的肯定是央视频APP那放节目是版权或者需要VIP，说以368经常黑屏，作者用的好像是央视频APP的源

**Comment by Dofox001** [comment]
[lyrics.run/my-tv.html](https://lyrics.run/my-tv.html)这个下载新版本的网址是不是挂了，登录不进去了

**Comment by lizongying** [comment]
已知
