### ISSUE TITLE
[BUG] 经常播着播着卡住不动,需要重新切换一下台才能看

### ISSUE THREAD

**Issue by constar11** [lizongying/my-tv#687]
### 检查清单

- [x] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

专用版

### Bug 描述

经常播着播着卡住不动,需要重新切换一下台才能看

### 预期行为

正常播放

### 实际行为

卡住

### UI / OS

小米

### Android 版本

9

**Comment by cliff19721108** [comment]
最近开始播放时有卡顿现象，望提高观感体验。

**Comment by zxhans** [comment]
可能是被限制了这个渠道了，session会掉线

**Comment by kiben2010** [comment]
我这里也出现这个问题

**Comment by javadodobird** [comment]
这个软件越来越多人知道越来越多人用，
但是服务器容量线路容量不可能不断提升，
有卡顿现象是正常现象。

**Comment by imxintian** [comment]
确实有这个问题

**Comment by bluoy** [comment]
这俩天也遇到了这个

**Comment by dgshilong** [comment]
5分钟断流一下

**Comment by lizongying** [comment]
大家可以試試1.7.8
