### ISSUE TITLE
作者可以指点下如何修改内置节目源吗

### ISSUE THREAD

**Issue by maciakng** [lizongying/my-tv#689]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

此播放器性能不错，家里老人不会自己装软件，自己又不在家，想要通过修改内置节目源，这样可以使用自己的源便于维护

**Comment by lizongying** [comment]
可以使用 我的電視·〇
