### ISSUE TITLE
频道列表里的中央电视台可以尝试搞成两行

### ISSUE THREAD

**Issue by zbby1987** [lizongying/my-tv#69]
不然按到中央13要按15下方向键，操作效率有点低！

**Comment by Hannah-my** [comment]
直接按数字15，就跳转到中央13了

**Comment by zbby1987** [comment]
> 直接按数字15，就跳转到中央13了

多数智能电视的遥控是没有数字键的！
只有iptv送的盒子遥控才常见到数字遥控！

**Comment by lizongying** [comment]
可以考虑，等频道稳定后，再确定一行多少。先一行用着。
