### ISSUE TITLE
能不能在分辨率上适配一下手机？

### ISSUE THREAD

**Issue by 743859910** [lizongying/my-tv#691]
![Screenshot_2024-04-18-17-23-53-021_com.lizongying.mytv.jpg](https://github.com/lizongying/my-tv/assets/84552324/21746f3a-d0d2-4236-b2cd-4d9ef7eb4ea6)

**Comment by lizongying** [comment]
沒太明白。在1.7.5，時間放到了視頻區域。

**Comment by lizongying** [comment]
> > 沒太明白。在1.7.5，時間放到了視頻區域。
> 
> 这个议题的图片没显示吧，就是我手机上也安装了，但是手机上的横屏模式下，两边都有好大的黑边

正常。视频的比例和手机的比例不一致。
