### ISSUE TITLE
[BUG]1.78不能运行 

### ISSUE THREAD

**Issue by zhaishang** [lizongying/my-tv#693]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

无法运行，闪退

### 预期行为

无法运行，闪退

### 实际行为

无法运行，闪退

### UI / OS

华为悦盒

### Android 版本

4.4.4

**Comment by drw2005** [comment]
+1

安卓4.4.2盒子，之前的1.7.6通用版运行正常。

**Comment by zbby1987** [comment]
> 安卓4.4.2盒子，之前的1.7.6通用版运行正常。

你的442能安装，但运行不了？

**Comment by hellwerwolf** [comment]
是的，我也闪退。422能安装，但没法用，上版本能用但断流

**Comment by zbby1987** [comment]
其实以安卓4.1为基点做软件，其他安卓版本都不会出问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月19日(周五) 中午12:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [lizongying/my-tv] [BUG]1.78不能运行  (Issue #693)




 
是的，我也闪退。422能安装，但没法用，上版本能用但断流

**Comment by ymypm** [comment]
1.78我安装上去，也是一直闪退

**Comment by ZacksEternal** [comment]
+1  4.4.2闪退

**Comment by lizongying** [comment]
用1.8.0

**Comment by lss182650** [comment]
1.8安卓4.4.4闪退
