### ISSUE TITLE
[ Notification: ] 新版1.7.8 凤凰的频道有时会走海外策略,珍惜流量

### ISSUE THREAD

**Issue by WFANG12719** [lizongying/my-tv#694]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

新版1.7.8 凤凰的三个频道有时会走海外CDN，目前观察到可以把下面的域名走直连，实测并不影响观看。
DOMAIN-SUFFIX,fengshows.com,DIRECT

### 预期行为

凤凰的三个频道直连观看，实测并不影响，走的ALI云香港节点。
阿里云的AS#45102，有很多IP地址段是境外的。45102是国内CNNIC颁发的AS号，但公告了很多境外的地址。

### 实际行为

如果不控制，观看凤凰的三个频道时，流量可能会走海外策略。

### 复现步骤

观看任何一个凤凰频道，查看流量怎样走？

### UI / OS

N1电视盒子

### Android 版本

7

### 额外信息

流量且用且珍惜

**Comment by lizongying** [comment]
描述的不是很清楚。我的理解是你用了代理，代理可能會走海外線路。
也就是，用了代理，可以把fengshows.com設為直連，減少流量套餐浪費。
需要的同學，可以參考下。

不屬於軟件問題，問題就關了。
