### ISSUE TITLE
[FR] 缺一个直播视频の分辨率的显示，尤其是可以自己加源的○版

### ISSUE THREAD

**Issue by zbby1987** [lizongying/my-tv#695]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

看不到直播视频分辨率，无法判断清晰度。
尤其是可以

### 解决方案

换台时，能否在底部的长方形台标弹框里展示一下直播视频的分辨率？
或者在屏幕右上角跟着选台数字一起显示。

**Comment by lizongying** [comment]
意義不大
