### ISSUE TITLE
希望回归台球频道[FR] 

### ISSUE THREAD

**Issue by QUINEWCUIH** [lizongying/my-tv#698]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

嗯……

**Comment by SmerckZak** [comment]
风云频道都一起吧。。。风云足球台球网球都不错的

**Comment by javadodobird** [comment]
个人意见，
如果不断去破央视vip频道让大家免费看，
惹恼了既得利益者,有关人士,有关部门，
到最后这软件被迫玩完了，
就连央视其他免费频道都保不住大家都沒得看，
又回到了2023年电视家玩完时的状态。

**Comment by uxgnod** [comment]
话说央视 vip 的这些频道有啥正规渠道看吗？感觉正常宽带送的电视啥的都看不了。

**Comment by lizongying** [comment]
#893
