### ISSUE TITLE
昨晚不管是1.7.6还是1.8.0打开一片黑，可以调台，但是没有任何画面和声音[BUG] 

### ISSUE THREAD

**Issue by laoyidianyu** [lizongying/my-tv#699]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

1.7.6和1.8.0打开黑屏

### 预期行为

希望快速改进。

### 实际行为

黑屏

### UI / OS

芒果机顶盒

### Android 版本

8

**Comment by Miroxyz** [comment]
tcl 电视机 1.8.0 有同样的问题

**Comment by kiben2010** [comment]
有同样问题

**Comment by DRZ-hang** [comment]
同样的问题

**Comment by pendar-lion** [comment]
同样问题

**Comment by blackuuz** [comment]
同样问题

**Comment by blackuuz** [comment]
同样问题

**Comment by kenzo-tm** [comment]
同样的问题

**Comment by ashsteins** [comment]
一样的问题，已使用灵犀直播代替

**Comment by laoyidianyu** [comment]
> 同样的问题，已使用灵犀直播代替

有不有灵犀直播链接，我原来的不得行了。

**Comment by DRZ-hang** [comment]
> 一样的问题，已使用灵犀直播代替

求分享，谢谢

**Comment by lizongying** [comment]
#703
