### ISSUE TITLE
建议做成这样简单的界面

### ISSUE THREAD

**Issue by tom96202** [lizongying/my-tv#7]
![Screenshot_20231215-202230_友窝YWP](https://github.com/lizongying/my-tv/assets/110156279/4691d05f-3b14-4131-b6a7-66294742761d)
![Screenshot_20231215-202257_友窝YWP](https://github.com/lizongying/my-tv/assets/110156279/17243626-7edb-41c8-8c36-d0b2fcc44be6)
![Screenshot_20231215-202340_友窝YWP](https://github.com/lizongying/my-tv/assets/110156279/5105d822-f2a0-4d5f-ad97-9e0306edc1ed)

![Screenshot_20231215-202415_友窝YWP](https://github.com/lizongying/my-tv/assets/110156279/4e855ff8-ebce-44a0-bf35-eabd40e1d566)
![Screenshot_20231215-202425_友窝YWP](https://github.com/lizongying/my-tv/assets/110156279/0f8ec827-3070-41f3-bdb9-e93f7dadaac5)

**Comment by tom96202** [comment]
节目表是在网页管理页面设置的。非常自由灵活

**Comment by lizongying** [comment]
首先，这个软件的目标是电视。网页的话，不如直接用央视频等客户端。
越简单越好，家人会用才是好用。
电视频道也是以央视为主，看电影等需求，完全可以去腾讯爱奇艺，应该不是电视直播该走的方向。
说下界面，市面上的直播软件多是某box的基础上改的，不过确实不错，比mytv更简洁。
现在的界面也是有预留，后面会显示截图，甚至视频预览，还有节目单。如果用的人多的话，这些都会上。

**Comment by chenxudong2020** [comment]
能适配下手机吗 方便测试

**Comment by lizongying** [comment]
> 能适配下手机吗 方便测试

手机可以操作了

**Comment by chenxudong2020** [comment]
可以 等下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月25日(周一) 晚上7:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lizongying/my-tv] 建议做成这样简单的界面 (Issue #7)




  
能适配下手机吗 方便测试
  
手机可以操作了

**Comment by chenxudong2020** [comment]
> > 能适配下手机吗 方便测试
> 
> 手机可以操作了

有问题  就是选台之后 播放界面越来越小

**Comment by chenxudong2020** [comment]
![88bf1a9330252ad110897c3ef396764](https://github.com/lizongying/my-tv/assets/61214170/c65ca7ac-0611-44c1-bb4e-584b1ba4f7b8)

**Comment by chenxudong2020** [comment]
> ![Screenshot_20231215-202230_友窝YWP](https://private-user-images.githubusercontent.com/110156279/290848191-4691d05f-3b14-4131-b6a7-66294742761d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDYwMzYsIm5iZiI6MTcwMzUwNTczNiwicGF0aCI6Ii8xMTAxNTYyNzkvMjkwODQ4MTkxLTQ2OTFkMDVmLTNiMTQtNDEzMS1iNmE3LTY2Mjk0NzQyNzYxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQxMjAyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjhlMjRhNmVlNmZlZTMzNDZmN2JmMjBkNGY5YTlmNTlkZDY3MjllOGNkOWIyNWUyNWYzOWMwODg5NTdjYzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5UHhMJdTd0D9tmsGbP3HcnqH1-_Utpmcbs8aDJeOrII) ![Screenshot_20231215-202257_友窝YWP](https://private-user-images.githubusercontent.com/110156279/290848254-17243626-7edb-41c8-8c36-d0b2fcc44be6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDYwMzYsIm5iZiI6MTcwMzUwNTczNiwicGF0aCI6Ii8xMTAxNTYyNzkvMjkwODQ4MjU0LTE3MjQzNjI2LTdlZGItNDFjOC04YzM2LWQwYjJmY2M0NGJlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQxMjAyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjIzMjc4ZDhiOGE5MTU3NGJiZjg1MDI1MjAxZDdlZGJlZmE1Y2E0ZDIwZmIzYjJlMDZiZDcyZjkzOWIxYjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hfeJtxdiyzaLIqVrv7YKSXxmHwklwO50LMruh0Vo67Q) ![Screenshot_20231215-202340_友窝YWP](https://private-user-images.githubusercontent.com/110156279/290848284-5105d822-f2a0-4d5f-ad97-9e0306edc1ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDYwMzYsIm5iZiI6MTcwMzUwNTczNiwicGF0aCI6Ii8xMTAxNTYyNzkvMjkwODQ4Mjg0LTUxMDVkODIyLWYyYTAtNGQ1Zi1hZDk3LTllMDMwNmVkYzFlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQxMjAyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDkzNGM0MTdkM2YzZDA2Y2ZmZjg1NWZhZGZjNDljZDgzYjY2OTI2MGE1MTE3MjI0NGNlMzIxMmNlZDc2NGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s6636XkXsCbhXF557o2PmQYRgsIUUFCIFCZHVpGe0yw)
> 
> ![Screenshot_20231215-202415_友窝YWP](https://private-user-images.githubusercontent.com/110156279/290848304-4e855ff8-ebce-44a0-bf35-eabd40e1d566.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDYwMzYsIm5iZiI6MTcwMzUwNTczNiwicGF0aCI6Ii8xMTAxNTYyNzkvMjkwODQ4MzA0LTRlODU1ZmY4LWViY2UtNDRhMC1iZjM1LWVhYmQ0MGUxZDU2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQxMjAyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmYwMjk3MTEyODE1YWQ3MWMyYzhkNjAyNGY4NDQ0YjBjZGY0MzhmYzA1M2VjYzk0YzIxMjI2ZTE3NDllNGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sokWOgC6DhmHVQ0uN9esvf_-ehaioOEetM1VdAf24n8) ![Screenshot_20231215-202425_友窝YWP](https://private-user-images.githubusercontent.com/110156279/290848330-0f8ec827-3070-41f3-bdb9-e93f7dadaac5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDYwMzYsIm5iZiI6MTcwMzUwNTczNiwicGF0aCI6Ii8xMTAxNTYyNzkvMjkwODQ4MzMwLTBmOGVjODI3LTMwNzAtNDFmMy1iZGI5LWU5M2Y3ZGFkYWFjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQxMjAyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmM5MmZhMTQ4MTgzZWE5YzcyZTQ3NWNkYzEzMzZkZTkyMzk3NGVlN2JmNTY1OGJkNjIyNzgxMTgxMmI2N2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v92DBrDkiZRjOmYZERyAheDMDTOJOHEo1_bpGptF6m8)

这是啥播放器
