### ISSUE TITLE
[FR] 各个频道可以增加不同清晰度的选择，我抓包了YSP的ios数据 贴在下面 可以参考

### ISSUE THREAD

**Issue by xiaomibaba2022** [lizongying/my-tv#700]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [x] 这个建议不会背离 my-tv 的初衷。

### 改进目的

增加不同清晰度选择，给用户提供更高清晰度。

### 解决方案

TV(
                    0,
                    "CCTV1 综合 1080P",
                    "CCTV1",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/d57905b93540bd15f0c48230dbbbff7ee0d645ff539e38866e2d15c8b9f7dfcd.png?imageMogr2/format/webp",
                    "600001859",
                    "2022576803",
                    ProgramType.Y_PROTO,
                    false,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV1 综合 HDR",
                    "CCTV1",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/d57905b93540bd15f0c48230dbbbff7ee0d645ff539e38866e2d15c8b9f7dfcd.png?imageMogr2/format/webp",
                    "600001859",
                    "2022576826",
                    ProgramType.Y_PROTO,
                    false,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV2 财经 1080P",
                    "CCTV2",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/20115388de0207131af17eac86c33049b95d69eaff064e55653a1b941810a006.png?imageMogr2/format/webp",
                    "600001800",
                    "2022576703",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV2 财经 HDR",
                    "CCTV2",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/20115388de0207131af17eac86c33049b95d69eaff064e55653a1b941810a006.png?imageMogr2/format/webp",
                    "600001800",
                    "2022576726",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV3 综艺 1080P",
                    "CCTV3",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/7b7a65c712450da3deb6ca66fbacf4f9aee00d3f20bd80eafb5ada01ec63eb3a.png?imageMogr2/format/webp",
                    "600001801",
                    "2022576503",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV3 综艺 HDR",
                    "CCTV3",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/7b7a65c712450da3deb6ca66fbacf4f9aee00d3f20bd80eafb5ada01ec63eb3a.png?imageMogr2/format/webp",
                    "600001801",
                    "2022576526",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV4 中文国际 1080P",
                    "CCTV4",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/f357e58fdbcc076a3d65e1f958c942b2e14f14342c60736ceed98b092d35356a.png?imageMogr2/format/webp",
                    "600001814",
                    "2022576603",
                    ProgramType.Y_PROTO,
                    false,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV4 中文国际 HDR",
                    "CCTV4",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/f357e58fdbcc076a3d65e1f958c942b2e14f14342c60736ceed98b092d35356a.png?imageMogr2/format/webp",
                    "600001814",
                    "2022576626",
                    ProgramType.Y_PROTO,
                    false,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV5 体育 1080P",
                    "CCTV5",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/0a6a7138952675983a3d854df7688557b286d59aa06166edae51506f9204d655.png?imageMogr2/format/webp",
                    "600001818",
                    "2022576403",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV5 体育 HDR",
                    "CCTV5",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/0a6a7138952675983a3d854df7688557b286d59aa06166edae51506f9204d655.png?imageMogr2/format/webp",
                    "600001818",
                    "2022576404",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV5+ 体育赛事 1080P",
                    "CCTV5+",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/649ad76a90bfef55b05db9fe52e006487280f619089099d5dc971e387fc6eff0.png?imageMogr2/format/webp",
                    "600001817",
                    "2022576303",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV5+ 体育赛事 HDR",
                    "CCTV5+",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/649ad76a90bfef55b05db9fe52e006487280f619089099d5dc971e387fc6eff0.png?imageMogr2/format/webp",
                    "600001817",
                    "2022576304",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV6 电影 1080P",
                    "CCTV6",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/741515efda91f03f455df8a7da4ee11fa9329139c276435cf0a9e2af398d5bf2.png?imageMogr2/format/webp",
                    "600108442",
                    "2013693903",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = true
                ),
                TV(
                    0,
                    "CCTV6 电影 HDR",
                    "CCTV6",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/741515efda91f03f455df8a7da4ee11fa9329139c276435cf0a9e2af398d5bf2.png?imageMogr2/format/webp",
                    "600108442",
                    "2013693926",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = true
                ),
                TV(
                    0,
                    "CCTV7 国防军事 1080P",
                    "CCTV7",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/b29af94e295ebdf646cefb68122c429b9cd921f498ca20d2d8070252536f9ff9.png?imageMogr2/format/webp",
                    "600004092",
                    "2022576203",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV7 国防军事 HDR",
                    "CCTV7",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/b29af94e295ebdf646cefb68122c429b9cd921f498ca20d2d8070252536f9ff9.png?imageMogr2/format/webp",
                    "600004092",
                    "2022576226",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV8 电视剧 1080P",
                    "CCTV8",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/ad51de94426a0ba039e6dd6a8534ea98ecc813a6176bde87b4f18cc34d6d7590.png?imageMogr2/format/webp",
                    "600001803",
                    "2022576103",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = true
                ),
                TV(
                    0,
                    "CCTV8 电视剧 HDR",
                    "CCTV8",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/ad51de94426a0ba039e6dd6a8534ea98ecc813a6176bde87b4f18cc34d6d7590.png?imageMogr2/format/webp",
                    "600001803",
                    "2022576126",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = true
                ),
                TV(
                    0,
                    "CCTV9 纪录 1080P",
                    "CCTV9",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/2ed1b4deeca179d5db806bb941790f82eb92a1b7299c1c38fe027f95a5caee5e.png?imageMogr2/format/webp",
                    "600004078",
                    "2022576003",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),

                TV(
                    0,
                    "CCTV9 纪录 HDR",
                    "CCTV9",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/2ed1b4deeca179d5db806bb941790f82eb92a1b7299c1c38fe027f95a5caee5e.png?imageMogr2/format/webp",
                    "600004078",
                    "2022576026",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV9 纪录 HDR",
                    "CCTV9",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/2ed1b4deeca179d5db806bb941790f82eb92a1b7299c1c38fe027f95a5caee5e.png?imageMogr2/format/webp",
                    "600004078",
                    "2022576026",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),

                TV(
                    0,
                    "CCTV10 科教",
                    "CCTV10",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/aa6157ec65188cd41826e5a2f088c3d6d153205f5f6428258d12c59999e221aa.png?imageMogr2/format/webp",
                    "600001805",
                    "2022573003",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV10 科教 HDR",
                    "CCTV10",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/aa6157ec65188cd41826e5a2f088c3d6d153205f5f6428258d12c59999e221aa.png?imageMogr2/format/webp",
                    "600001805",
                    "2022573026",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV11 戏曲",
                    "CCTV11",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/ed12ed7c7a1034dae4350011fe039284c5d5a836506b28c9e32e3c75299625c0.png?imageMogr2/format/webp",
                    "600001806",
                    "2022575903",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV11 戏曲",
                    "CCTV11",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/ed12ed7c7a1034dae4350011fe039284c5d5a836506b28c9e32e3c75299625c0.png?imageMogr2/format/webp",
                    "600001806",
                    "2022575926",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV12 社会与法",
                    "CCTV12",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/484083cffaa40df7e659565e8cb4d1cc740158a185512114167aa21fa0c59240.png?imageMogr2/format/webp",
                    "600001807",
                    "2022575803",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV12 社会与法 HDR",
                    "CCTV12",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/484083cffaa40df7e659565e8cb4d1cc740158a185512114167aa21fa0c59240.png?imageMogr2/format/webp",
                    "600001807",
                    "2022575826",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV13 新闻",
                    "CCTV13",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/266da7b43c03e2312186b4a999e0f060e8f15b10d2cc2c9aa32171819254cf1a.png?imageMogr2/format/webp",
                    "600001811",
                    "2022575703",
                    ProgramType.Y_PROTO,
                    false,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV13 新闻 HDR",
                    "CCTV13",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/266da7b43c03e2312186b4a999e0f060e8f15b10d2cc2c9aa32171819254cf1a.png?imageMogr2/format/webp",
                    "600001811",
                    "2022575726",
                    ProgramType.Y_PROTO,
                    false,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV14 少儿",
                    "CCTV14",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/af6b603896938dc346fbb16abfc63c12cba54b0ec9d18770a15d347d115f12d5.png?imageMogr2/format/webp",
                    "600001809",
                    "2022575603",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV14 少儿 HDR",
                    "CCTV14",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/af6b603896938dc346fbb16abfc63c12cba54b0ec9d18770a15d347d115f12d5.png?imageMogr2/format/webp",
                    "600001809",
                    "2022575626",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV15 音乐",
                    "CCTV15",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/2ceee92188ef684efe0d8b90839c4f3ad450d179dc64d59beff417059453af47.png?imageMogr2/format/webp",
                    "600001815",
                    "2022575503",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV15 音乐 HDR",
                    "CCTV15",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/2ceee92188ef684efe0d8b90839c4f3ad450d179dc64d59beff417059453af47.png?imageMogr2/format/webp",
                    "600001815",
                    "2022575526",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV16 奥林匹克",
                    "CCTV16-HD",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/53793fa7bacd3a93ff6dc5d2758418985e1f952a316c335d663b572d8bdcd74d.png?imageMogr2/format/webp",
                    "600098637",
                    "2022575403",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV16 奥林匹克 HDR",
                    "CCTV16-HD",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/53793fa7bacd3a93ff6dc5d2758418985e1f952a316c335d663b572d8bdcd74d.png?imageMogr2/format/webp",
                    "600098637",
                    "2022575426",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV17 农业农村",
                    "CCTV17",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/ddef563072f8bad2bea5b9e52674cb7b4ed50efb20c26e61994dfbdf05c1e3c0.png?imageMogr2/format/webp",
                    "600001810",
                    "2022575303",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),

                TV(
                    0,
                    "CCTV17 农业农村 HDR",
                    "CCTV17",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/ddef563072f8bad2bea5b9e52674cb7b4ed50efb20c26e61994dfbdf05c1e3c0.png?imageMogr2/format/webp",
                    "600001810",
                    "2022575326",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),

                TV(
                    0,
                    "CCTV4K 1080P",
                    "CCTV4K",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/3e9d06fd7244d950df5838750f1c6ac3456e172b51caca2c16d2282125b111e8.png?imageMogr2/format/webp",
                    "600002264",
                    "2022575203",
                    ProgramType.Y_PROTO,
                    true,
                    mustToken = false
                ),

                TV(
                    0,
                    "CCTV4K 菁彩",
                    "CCTV4K",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/3e9d06fd7244d950df5838750f1c6ac3456e172b51caca2c16d2282125b111e8.png?imageMogr2/format/webp",
                    "600002264",
                    "2022575205",
                    ProgramType.Y_JCE,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV4K 菁彩 HDR",
                    "CCTV4K",
                    listOf(),
                    "央视",
                    "https://resources.yangshipin.cn/assets/oms/image/202306/3e9d06fd7244d950df5838750f1c6ac3456e172b51caca2c16d2282125b111e8.png?imageMogr2/format/webp",
                    "600002264",
                    "2022575261",
                    ProgramType.F,
                    true,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV8K 1080P",
                    "CCTV8K",
                    listOf(),
                    "央视",
                    R.drawable.cctv8k,
                    "600156816",
                    "2020603421",
                    ProgramType.Y_JCE,
                    false,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV8K 菁彩",
                    "CCTV8K",
                    listOf(),
                    "央视",
                    R.drawable.cctv8k,
                    "600156816",
                    "2020603405",
                    ProgramType.Y_JCE,
                    false,
                    mustToken = false
                ),
                TV(
                    0,
                    "CCTV8K 菁彩HDR",
                    "CCTV8K",
                    listOf(),
                    "央视",
                    R.drawable.cctv8k,
                    "600156816",
                    "2020603465",
                    ProgramType.Y_JCE,
                    false,
                    mustToken = false
                ),

**Comment by ashsteins** [comment]
支持，有的台也就不到720p，有的台蛮清晰的。

**Comment by lizongying** [comment]
暫時先不加入清晰度選擇。
