### ISSUE TITLE
在最大维护稳定的情况下，能否增加专门滚动播放电影的频道，直播有时太单调[FR] 

### ISSUE THREAD

**Issue by laoyidianyu** [lizongying/my-tv#702]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

增加多元化，尽量符合大众化，比如原来的CHC这类型

### 额外信息

作者已经做得很好了，在空闲是考虑一下增加电影频道

**Comment by ScarletDor** [comment]
我建议不要加，加了死的更快，看电影用tvbox吧

**Comment by javadodobird** [comment]
chc电影,轮播电影请用其他软件看吧，
作者能维护稳定央,卫,cgtn就已经很好了。

**Comment by lizongying** [comment]
#893
