### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Xuenews** [lizongying/my-tv#704]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

专用版

### Bug 描述

除了凤凰三个频道，其余频道全部加载不出来，黑屏

### 预期行为

除了凤凰三个频道，其余频道全部加载不出来，黑屏

### 实际行为

除了凤凰三个频道，其余频道全部加载不出来，黑屏

### 复现步骤

除了凤凰三个频道，其余频道全部加载不出来，黑屏

### UI / OS

小米

### Android 版本

10

### 额外信息

除了凤凰三个频道，其余频道全部加载不出来，黑屏

**Comment by laoyidianyu** [comment]
确实，刚才用手机播放只要凤凰台可以，感觉随时都会.......

**Comment by vttkt** [comment]
我这里也不能用了。
