### ISSUE TITLE
[BUG] 乐视电视 在观看10s以上的时间后 按音量/上下换台键/其他 都会弹出设置菜单

### ISSUE THREAD

**Issue by xxlxmd** [lizongying/my-tv#705]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

乐视电视 在观看10s以上的时间后 按音量/上下换台键/其他 都会弹出设置菜单 从1.75~1.82都会复现

### 预期行为

可能是某些适配bug吧 连续换台或者调整音量不会出现

### 实际行为

正常响应按键

### 复现步骤

1、乐视电视
2、观看一个频道10秒以上
3、遥控器按 音量 or 上下更换频道 等任何按键 都会弹出设置菜单(就是有二维码那个界面)
4、遥控器按键也会同时响应,比如你按音量,电视的音量菜单也会和设置菜单同时弹出

### UI / OS

乐视

### Android 版本

10?

**Comment by lizongying** [comment]
給我個郵箱，我單獨給你個app，看看能不能解決。
這應該是樂視的問題，你可以試試用手機遙控，是不是有同樣的問題。

**Comment by lizongying** [comment]
最新版本應該已經解決了，可以嘗試下
