### ISSUE TITLE
[FR] 希望myTV增加自动更新功能

### ISSUE THREAD

**Issue by johnnyeecker** [lizongying/my-tv#706]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

作者你好,首先先点个赞啊,这个APP非常好,也伴随着你的每一次更新一直在更新我家各个设备,和各个亲戚家设备的APP.之前我提及的旧款遥控器没有菜单键的问题,也看到你增加了右键呼出菜单键的功能,真是体贴,感动.
目前电视上直接更新的功能还未成功过,我自己家都是通过电视上装了易有云进行更新的.但是对于帮助别人家老人的电视安装的这款APP,他们更新起来就有些困难了,例如1.8.0无法观看中央台的时候,电脑下载新版本1.8.2,存入U盘,再插入电视上安装的这几个步骤对于老人而言基本上属于不可能完成的任务.所以期望作者有空时,看看能不能实现让APP自动弹出更新窗口,另外显示项目地址时还是可以保留github的地址提示,但是自动更新时后台的链接地址可否改成国内不需要梯子也能比较快速的gitee,我不知道啊,是不是更新一直不成功的原因是亲戚家的网络访问不了GitHub,不过呢,我自己家里能访问GitHub也不能升级.
所以,期待自动弹窗更新功能,且能从国内无障碍访问的服务器地址下载.我不确定我说的对不对啊,说的不对请见谅.总之,希望软件一直存在且保持下去,辛苦,感谢.

### 额外信息

好软件,好作者,好棒.
记得过年还在紧急更新,赞一个.

**Comment by kiben2010** [comment]
顶你

**Comment by junyujian** [comment]
支持作者做一个自动更新功能

**Comment by xujiangang** [comment]
作者真牛！！顶一个，软件非常好用！！

**Comment by xhs52244152** [comment]
软件很好用，支持增加自动更新的功能！

**Comment by blackuuz** [comment]
我也是给家里老人用，软件非常好用，支持作者做一个自动更新功能

**Comment by boby2023zzb** [comment]
希望有自动更新功能！谢谢！祝福作者！

**Comment by TechOrange** [comment]
每次我都是远程分享码升级my TV，自动升级真是个痛点

**Comment by kiben2010** [comment]
这个软件的响应速度绝对是前无古人的，希望能自动升级，不需要再用U盘。

**Comment by loa123** [comment]
可以自动更新播放列表呀。。

**Comment by forbidde** [comment]
帮顶，求作者大大增加自动更新

**Comment by ashsteins** [comment]
支持，不然信号源出问题黑屏，家里老人就不知道怎么办

**Comment by psumycom** [comment]
已经支持自动更新了啊，你们不知道吗？

**Comment by donghai-Y** [comment]
> 已经支持自动更新了啊，你们不知道吗？

但是一直更新失败呀，从来没有成功过，还是一直通过u盘安装的，请问如何直接更新呢？

**Comment by netheril96** [comment]
> 已经支持自动更新了啊，你们不知道吗？

但是我没有成功过，我猜测得开魔法，但是电视魔法太难了

**Comment by johnnyeecker** [comment]
> > 已经支持自动更新了啊，你们不知道吗？
> 
> 但是我没有成功过，我猜测得开魔法，但是电视魔法太难了

家里软路由一直全家魔法,但是依旧不能自动升级的.

**Comment by sonichy** [comment]
希望自动更新，自己到 github 检查、下载、安装，太麻烦了。
我做的浏览器通过这个网址可以更新：https://www.gitlink.org.cn/api/sonichy/HTYBrowser/raw/app.apk?ref=master

**Comment by Kukuair** [comment]
@lizongying 我提个建议，把release的apk安装包文件放在一个release分支中，文件名可以固定，没必要加v版本号,方便更新地址固定，在提交时的message中填写版本号即可，在apk中，将更新地址利用jsdelivr cdn : https://www.jsdelivr.com/?docs=gh 加速下载更新

https://cdn.jsdelivr.net/gh/user/repo@version/file

例如：
https://fastly.jsdelivr.net/gh/lizongying/my-tv@master/CMakeLists.txt
https://cdn.jsdelivr.net/gh/lizongying/my-tv@master/CMakeLists.txt

**Comment by AppleMate60pro** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的功能请求。
> * [x]  这个建议不会背离 my-tv 的初衷。
> 
> ### 改进目的
> 作者你好,首先先点个赞啊,这个APP非常好,也伴随着你的每一次更新一直在更新我家各个设备,和各个亲戚家设备的APP.之前我提及的旧款遥控器没有菜单键的问题,也看到你增加了右键呼出菜单键的功能,真是体贴,感动. 目前电视上直接更新的功能还未成功过,我自己家都是通过电视上装了易有云进行更新的.但是对于帮助别人家老人的电视安装的这款APP,他们更新起来就有些困难了,例如1.8.0无法观看中央台的时候,电脑下载新版本1.8.2,存入U盘,再插入电视上安装的这几个步骤对于老人而言基本上属于不可能完成的任务.所以期望作者有空时,看看能不能实现让APP自动弹出更新窗口,另外显示项目地址时还是可以保留github的地址提示,但是自动更新时后台的链接地址可否改成国内不需要梯子也能比较快速的gitee,我不知道啊,是不是更新一直不成功的原因是亲戚家的网络访问不了GitHub,不过呢,我自己家里能访问GitHub也不能升级. 所以,期待自动弹窗更新功能,且能从国内无障碍访问的服务器地址下载.我不确定我说的对不对啊,说的不对请见谅.总之,希望软件一直存在且保持下去,辛苦,感谢.
> 
> ### 解决方案
> _No response_
> 
> ### 额外信息
> 好软件,好作者,好棒. 记得过年还在紧急更新,赞一个.

自动更新要服务器的，你又不赞助一服务器

**Comment by AppleMate60pro** [comment]
@JoinWorld 我希望你们赞助作者一服务器

**Comment by famousprince** [comment]
@Kukuair 国内网络环境不推荐 JsDelivr，部分地区被墙打不开，部分地区速度不佳，非常折磨

**Comment by netheril96** [comment]
直接在设置里可以填更新地址吧
大家各显神通，自己搞自己的服务器

**Comment by qingchanbaby** [comment]
> 直接在设置里可以填更新地址吧 大家各显神通，自己搞自己的服务器
大佬  我怎么没看到设置在哪里啊？电视上进去所有能看到的只有各个电视台的频道

**Comment by lizongying** [comment]
#772
