### ISSUE TITLE
强烈要求加一个翡翠台[FR] 

### ISSUE THREAD

**Issue by hdiwahdiuwhadi** [lizongying/my-tv#707]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

广东人迫切需要，拜托了

**Comment by ashsteins** [comment]
支持

**Comment by javadodobird** [comment]
翡翠台请用其他软件看吧，
这软件加翡翠台等于沒事找事自己找死。

**Comment by siul2018** [comment]
广东台转翡翠J2遇到某些节目都要河蟹掉转广告，这软件播翡翠相当于软件别做了

**Comment by lizongying** [comment]
可以嘗試使用[我的電視·〇](https://github.com/lizongying/my-tv-0)
