### ISSUE TITLE
黑屏对于故障排除反馈不太明确

### ISSUE THREAD

**Issue by bluexiaoyu** [lizongying/my-tv#708]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

希望能提示连接网络，等待缓冲，缓冲失败等等提示，不要直接黑屏，对于一些老人无法准确反馈问题给儿孙辈，就说一个黑屏，处理起来增加难度。

### 解决方案

希望能在黑屏时左上提示连接网络，等待缓冲，缓冲失败等等提示

**Comment by lfm09** [comment]
这软件换台很快，但确实每个版本都会时不时黑屏无法播放，每次都得升级版本才能解决，讲真不方便啊

**Comment by lizongying** [comment]
已經有了簡單的錯誤提示
