### ISSUE TITLE
[BUG] 小米电视S Pro，现在只有三个凤凰台可以看，央视卫视频道全部黑屏没反应，这是个别问题吗

### ISSUE THREAD

**Issue by alagants** [lizongying/my-tv#710]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

打开软件显示黑屏，频道菜单正常显示，只有三个凤凰台可以看到画面，然后切其他频道没有反应，这是个别问题吗

### 预期行为

现在只有三个凤凰台可以看，央视卫视频道全部黑屏没反应，这是个别问题吗

### 实际行为

打开软件显示黑屏，频道菜单正常显示，只有三个凤凰台可以看到画面，然后切其他频道没有反应

### UI / OS

小米S Pro 75

### Android 版本

澎湃os

**Comment by gsons** [comment]
@alagants @lizongying  我的小米电视也是这样子，全部黑屏，两天了都播放不了，给我整emo了

**Comment by wa7046** [comment]
更新到1.8.2版本可以解决

**Comment by gsons** [comment]
> 更新到1.8.2版本可以解决

一样的 就是182版本

**Comment by laoyidianyu** [comment]
1.8.2版本手机上可以正常播放了

**Comment by AlbiziaJulibrissinV** [comment]
1.8.2小米盒子也是这个问题

**Comment by myvmiao** [comment]
1.8.2在手机上也不正常，就香港3个台可看

**Comment by MrQz07** [comment]
是不是系统问题？1.8.2安卓的用着是正常的

**Comment by alagants** [comment]
更新1.8.2版本已解决，太棒了

**Comment by lizongying** [comment]
#893
