### ISSUE TITLE
[FR] 建议引入ijkplayer解码

### ISSUE THREAD

**Issue by caixxxin** [lizongying/my-tv#712]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

对于安卓4等老旧设备，exoplayer播放视频是会明显的卡顿掉帧，但是ijkplayer占用资源较少，播放会很流畅。

### 解决方案

可以在通用版中，使用ijkplayer替代exoplayer

### 额外信息

参考tvbox软件，在安卓4设备上，尽量使用ijkplayer硬解码，可以流程播放视频。

**Comment by caixxxin** [comment]
maven {url 'https://maven.aliyun.com/repository/jcenter'}

**Comment by caixxxin** [comment]
@lizongying

**Comment by drw2005** [comment]
支持，大佬在通用版上试试吧，或者单出一个IJK版本，照顾一下老旧设备用户。

**Comment by caixxxin** [comment]
https://github.com/caixxxin/my-tv/tree/v1.9.8-ijk
