### ISSUE TITLE
[FR]请教一个问题

### ISSUE THREAD

**Issue by Ahuangshang** [lizongying/my-tv#713]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

为什么新版央视频链接获取后，用播放器播放后，会发现后面的ts文件时间非常短，导致播放一直卡顿，但myTV并不会这样，请教下这个是怎么设置的？也使用了myTV同款播放器也是会这样，是哪里还需要做什么处理吗？

**Comment by lizongying** [comment]
這個播放地址是需要續期的
