### ISSUE TITLE
自动更新无法使用

### ISSUE THREAD

**Issue by ssiop789** [lizongying/my-tv#714]
自动更新点击不更新

**Comment by meiti789789** [comment]
同样的请求，每次都要重新下载 很是麻烦

**Comment by laoyidianyu** [comment]
这个确实是个恼火的问题，隔一段时间就用不起了，非得下载新版才行，自动更新功能完全不起作用。

**Comment by imnewbe** [comment]
能不能增加一个国内的更新源gitee

**Comment by gucong3000** [comment]
作者好像是遇到了github访问稳定性问题，我曾利用国内github镜像来更新软件，希望能对你有所参考：

利用镜像地址在国内访问github：
https://github.com/gucong3000/MiuiCleaner/blob/dev/src/miui_cleaner_app/direct-url/github.js#L80

利用github更新apk版本：
https://github.com/gucong3000/MiuiCleaner/blob/dev/src/miui_cleaner_app/update.js

**Comment by kongfucurry** [comment]
> 作者好像是遇到了github访问稳定性问题，我曾利用国内github镜像来更新软件，希望能对你有所参考：
> 
> 利用镜像地址在国内访问github： https://github.com/gucong3000/MiuiCleaner/blob/dev/src/miui_cleaner_app/direct-url/github.js#L80
> 
> 利用github更新apk版本： https://github.com/gucong3000/MiuiCleaner/blob/dev/src/miui_cleaner_app/update.js

其实科学上网对我们来讲没啥，主要是家里人玩不转，人又在外地上班，很难受

**Comment by lizongying** [comment]
#772
