### ISSUE TITLE
[BUG] 在乐视C1S盒子上，无法使用，提示“状态错误”

### ISSUE THREAD

**Issue by mixter007** [lizongying/my-tv#716]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

在乐视C1S盒子上，无法使用，提示“状态错误”

### 预期行为

期待更新

### 实际行为

状态错误

### UI / OS

leTV c1s

### Android 版本

4.4

**Comment by haha252** [comment]
您也是乐视c1s的用户吗？
我的乐视c1s安卓版本为4.1，请问如何升级到安卓4.4呢？
要是能加个qq就更好啦！我的qq是2052249283，谢谢！

**Comment by lizongying** [comment]
#893
