### ISSUE TITLE
[FR] 有可能支持体育频道吗？

### ISSUE THREAD

**Issue by codersky** [lizongying/my-tv#717]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

体育

**Comment by laoyidianyu** [comment]
爱看体育系列，去下载咪咕吧

**Comment by javadodobird** [comment]
其它体育，用其它软件看吧

**Comment by lizongying** [comment]
可以嘗試使用[我的電視·〇](https://github.com/lizongying/my-tv-0)
