### ISSUE TITLE
CCTV5 和 CCTV5+ 打不开？（坐标境外）

### ISSUE THREAD

**Issue by huifei0129** [lizongying/my-tv#72]
CCTV5 和 CCTV5+ 打不开？

**Comment by zanzhz1101** [comment]
这。。。。。自己中转吧

**Comment by huifei0129** [comment]
> 这。。。。。自己中转吧

请问如何中转，谢谢

**Comment by Obizuh** [comment]
要不挂个回国节点代理？试试软路由或者设备挂个系统代理。只是一个设想，没尝试过用国内服务器挂vmess节点，不知道可不可行。

**Comment by lizongying** [comment]
暂时海外看不了，后面有可能解决这个问题。敬请期待。
