### ISSUE TITLE
[FR] 期盼央视368等其他频道回归

### ISSUE THREAD

**Issue by taddyboy** [lizongying/my-tv#720]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

期盼央视368等其他频道回归，会不会成为永远不可实现的奢望啊？

**Comment by javadodobird** [comment]
我的意见：
看cctv3、6、8的时侯，用另外的软件看，
看其它cctv、卫视的时侯，用这个软件看，
两个软件互补着看，
这个软件作者已经做得很好了，
我们就不要为难作者要求cctv3,6,8了。

**Comment by taddyboy** [comment]
主要想让这个软件成为一个完美的软件啊，怀念软件初期的时候带给大家几乎完美的画质和完整的频道收看体验

**Comment by taddyboy** [comment]
我想作者也是个完美主义者，也许作者正在想法设法弥补这些缺憾，致敬软件开发者，谢谢你给大家带来这么好的一款软件！期待中！！！

**Comment by javadodobird** [comment]
如果这个软件这么完美有cctv368有cctv风云，
那些卖盒子的商人，肯定拿来做商业用途拿来赚钱，直接加速这个软件的玩完，
还有广电是肯定不会放过这个软件的(2023年电视家的被迫自杀)， 否则有线网络谁还装机？

**Comment by JundeLin** [comment]
我就喜欢破解这些网站。有本事来海外找我。

**Comment by amazonjdshop** [comment]
怕个毛。都会编程了还怕国内某机关找上门？ 作者这个是直接从官网解析网站的、有本事就叫这些机关改网站、让作者抓取不到。干的就是广电这些废物

**Comment by javadodobird** [comment]
> 怕个毛。都会编程了还怕国内某机关找上门？ 作者这个是直接从官网解析网站的、有本事就叫这些机关改网站、让作者抓取不到。干的就是广电这些废物

山外有山，人外有人，广电这么多饱读诗书的员工怎么可能都是废物，
人家是政府部门，有的是资源，有的是技术，有的是手段，有的是时间，跟我们这些没有后台的平民纠缠，平民有多少时间，多少精力陪他们玩？
平民跟政府斗，就是鸡蛋碰石头。

**Comment by vicacheung** [comment]
> 怕个毛。都会编程了还怕国内某机关找上门？ 作者这个是直接从官网解析网站的、有本事就叫这些机关改网站、让作者抓取不到。干的就是广电这些废物

你不怕你上呗？

**Comment by amazonjdshop** [comment]
> > 怕个毛。都会编程了还怕国内某机关找上门？ 作者这个是直接从官网解析网站的、有本事就叫这些机关改网站、让作者抓取不到。干的就是广电这些废物
> 
> 
> 
> 山外有山，人外有人，广电这么多饱读诗书的大学生员工，怎么可能都是废物，
> 
> 人家是政府部门，有的是人才，有的是充足的人手，有的是资源，有的是技术，有的是手段，有的是时间跟我们这些没有后台的平民纠缠，我们平民有多少人手，多少时间，多少精力陪政府玩？
> 
> 平民跟政府斗，就是鸡蛋碰石头。

我还就爱跟这些斗。就爱破解他们的。本人就是海外搞iptv的 国内频道抓取的还就是他们的源。天高皇帝远、有本事叫他们来漂亮国请我喝茶。作者要是怕的话可以联系我、我帮你传到github 保证匿名。☺️☺️![image](https://github.com/lizongying/my-tv/assets/130407448/91f70b8c-1d40-4dee-b4db-bc0a0a15aee6)

**Comment by javadodobird** [comment]
> > > 怕个毛。都会编程了还怕国内某机关找上门？ 作者这个是直接从官网解析网站的、有本事就叫这些机关改网站、让作者抓取不到。干的就是广电这些废物
> > 
> > 
> > 山外有山，人外有人，广电这么多饱读诗书的大学生员工，怎么可能都是废物，
> > 人家是政府部门，有的是人才，有的是充足的人手，有的是资源，有的是技术，有的是手段，有的是时间跟我们这些没有后台的平民纠缠，我们平民有多少人手，多少时间，多少精力陪政府玩？
> > 平民跟政府斗，就是鸡蛋碰石头。
> 
> 我还就爱跟这些斗。就爱破解他们的。本人就是海外搞iptv的 国内频道抓取的还就是他们的源。天高皇帝远、有本事叫他们来漂亮国请我喝茶。作者要是怕的话可以联系我、我帮你传到github 保证匿名。☺️☺️!

如果这个软件有长期稳定的cctv368，还是免费软件，还没有商业广告的话，
这样太好了，那么那些卖盒子的商人，肯定是百份百拿来做商业用途，把这个软件装在他们叫卖的盒子上炫耀招俫，拿来做盒子生意赚钱，
导致的后果，直接加速这个软件的玩完速度。

**Comment by amazonjdshop** [comment]
> > > > 怕个毛。都会编程了还怕国内某机关找上门？ 作者这个是直接从官网解析网站的、有本事就叫这些机关改网站、让作者抓取不到。干的就是广电这些废物
> 
> > > 
> 
> > > 
> 
> > > 山外有山，人外有人，广电这么多饱读诗书的大学生员工，怎么可能都是废物，
> 
> > > 人家是政府部门，有的是人才，有的是充足的人手，有的是资源，有的是技术，有的是手段，有的是时间跟我们这些没有后台的平民纠缠，我们平民有多少人手，多少时间，多少精力陪政府玩？
> 
> > > 平民跟政府斗，就是鸡蛋碰石头。
> 
> > 
> 
> > 我还就爱跟这些斗。就爱破解他们的。本人就是海外搞iptv的 国内频道抓取的还就是他们的源。天高皇帝远、有本事叫他们来漂亮国请我喝茶。作者要是怕的话可以联系我、我帮你传到github 保证匿名。☺️☺️!
> 
> 
> 
> 如果这个软件有长期稳定的cctv368，还是免费软件，还没有商业广告的话，
> 
> 这样太好了，那么那些卖盒子的商人，肯定是百份百拿来做商业用途，把这个软件装在他们叫卖的盒子上炫耀招俫，拿来做盒子生意赚钱，
> 
> 导致的后果，直接加速这个软件的玩完速度。

这个软件代码直接解析cctv网站的 根本没有服务器。要想他完蛋除非cctv网站布局或者播放视频方式改了。所以压根不用怕。

**Comment by javadodobird** [comment]
> > > > > 怕个毛。都会编程了还怕国内某机关找上门？ 作者这个是直接从官网解析网站的、有本事就叫这些机关改网站、让作者抓取不到。干的就是广电这些废物
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 山外有山，人外有人，广电这么多饱读诗书的大学生员工，怎么可能都是废物，
> > 
> > 
> > > > 人家是政府部门，有的是人才，有的是充足的人手，有的是资源，有的是技术，有的是手段，有的是时间跟我们这些没有后台的平民纠缠，我们平民有多少人手，多少时间，多少精力陪政府玩？
> > 
> > 
> > > > 平民跟政府斗，就是鸡蛋碰石头。
> > 
> > 
> > > 
> > 
> > 
> > > 我还就爱跟这些斗。就爱破解他们的。本人就是海外搞iptv的 国内频道抓取的还就是他们的源。天高皇帝远、有本事叫他们来漂亮国请我喝茶。作者要是怕的话可以联系我、我帮你传到github 保证匿名。☺️☺️!
> > 
> > 
> > 如果这个软件有长期稳定的cctv368，还是免费软件，还没有商业广告的话，
> > 这样太好了，那么那些卖盒子的商人，肯定是百份百拿来做商业用途，把这个软件装在他们叫卖的盒子上炫耀招俫，拿来做盒子生意赚钱，
> > 导致的后果，直接加速这个软件的玩完速度。
> 
> 这个软件代码直接解析cctv网站的 根本没有服务器。要想他完蛋除非cctv网站布局或者播放视频方式改了。所以压根不用怕。

在大清国，让什么事物完蛋就是一张纸一句话甚至一个手势一个表情的事，根本就不用改什么cctv网站布局或者播放视频方式，用非技术手段就已经可以办到了。

**Comment by kongfucurry** [comment]
> > > > > > 怕个毛。都会编程了还怕国内某机关找上门？ 作者这个是直接从官网解析网站的、有本事就叫这些机关改网站、让作者抓取不到。干的就是广电这些废物
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > 山外有山，人外有人，广电这么多饱读诗书的大学生员工，怎么可能都是废物，
> > > 
> > > 
> > > > > 人家是政府部门，有的是人才，有的是充足的人手，有的是资源，有的是技术，有的是手段，有的是时间跟我们这些没有后台的平民纠缠，我们平民有多少人手，多少时间，多少精力陪政府玩？
> > > 
> > > 
> > > > > 平民跟政府斗，就是鸡蛋碰石头。
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 我还就爱跟这些斗。就爱破解他们的。本人就是海外搞iptv的 国内频道抓取的还就是他们的源。天高皇帝远、有本事叫他们来漂亮国请我喝茶。作者要是怕的话可以联系我、我帮你传到github 保证匿名。☺️☺️!
> > > 
> > > 
> > > 如果这个软件有长期稳定的cctv368，还是免费软件，还没有商业广告的话，
> > > 这样太好了，那么那些卖盒子的商人，肯定是百份百拿来做商业用途，把这个软件装在他们叫卖的盒子上炫耀招俫，拿来做盒子生意赚钱，
> > > 导致的后果，直接加速这个软件的玩完速度。
> > 
> > 
> > 这个软件代码直接解析cctv网站的 根本没有服务器。要想他完蛋除非cctv网站布局或者播放视频方式改了。所以压根不用怕。
> 
> 在大清国，让什么事物完蛋就是一张纸一句话甚至一个手势一个表情的事，根本就不用改什么cctv网站布局或者播放视频方式，用非技术手段就已经可以办到了。

别尬黑啊，没物理服务器的话说不定还真有的搞，只是确实开源的话免不了有人拿去卖钱，但正是因为开源，软件被封直接换个马甲就行了，匿名上传源代码的话想查恐怕很难

**Comment by amazonjdshop** [comment]
> > > > > > 怕个毛。都会编程了还怕国内某机关找上门？ 作者这个是直接从官网解析网站的、有本事就叫这些机关改网站、让作者抓取不到。干的就是广电这些废物
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 山外有山，人外有人，广电这么多饱读诗书的大学生员工，怎么可能都是废物，
> 
> > > 
> 
> > > 
> 
> > > > > 人家是政府部门，有的是人才，有的是充足的人手，有的是资源，有的是技术，有的是手段，有的是时间跟我们这些没有后台的平民纠缠，我们平民有多少人手，多少时间，多少精力陪政府玩？
> 
> > > 
> 
> > > 
> 
> > > > > 平民跟政府斗，就是鸡蛋碰石头。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 我还就爱跟这些斗。就爱破解他们的。本人就是海外搞iptv的 国内频道抓取的还就是他们的源。天高皇帝远、有本事叫他们来漂亮国请我喝茶。作者要是怕的话可以联系我、我帮你传到github 保证匿名。☺️☺️!
> 
> > > 
> 
> > > 
> 
> > > 如果这个软件有长期稳定的cctv368，还是免费软件，还没有商业广告的话，
> 
> > > 这样太好了，那么那些卖盒子的商人，肯定是百份百拿来做商业用途，把这个软件装在他们叫卖的盒子上炫耀招俫，拿来做盒子生意赚钱，
> 
> > > 导致的后果，直接加速这个软件的玩完速度。
> 
> > 
> 
> > 这个软件代码直接解析cctv网站的 根本没有服务器。要想他完蛋除非cctv网站布局或者播放视频方式改了。所以压根不用怕。
> 
> 
> 
> 在大清国，让什么事物完蛋就是一张纸一句话甚至一个手势一个表情的事，根本就不用改什么cctv网站布局或者播放视频方式，用非技术手段就已经可以办到了。

非技术怎么办到？连服务器都没有这个app 怎么办到。找作者喝茶？作者只能下架app。 作者要是在海外的 直接干死这些网站。国内能做啥？ 还能来美国抓你不成。

**Comment by ScarletDor** [comment]
> > > > > > > 怕个毛。都会编程了还怕国内某机关找上门？ 作者这个是直接从官网解析网站的、有本事就叫这些机关改网站、让作者抓取不到。干的就是广电这些废物
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 山外有山，人外有人，广电这么多饱读诗书的大学生员工，怎么可能都是废物，
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 人家是政府部门，有的是人才，有的是充足的人手，有的是资源，有的是技术，有的是手段，有的是时间跟我们这些没有后台的平民纠缠，我们平民有多少人手，多少时间，多少精力陪政府玩？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 平民跟政府斗，就是鸡蛋碰石头。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 我还就爱跟这些斗。就爱破解他们的。本人就是海外搞iptv的 国内频道抓取的还就是他们的源。天高皇帝远、有本事叫他们来漂亮国请我喝茶。作者要是怕的话可以联系我、我帮你传到github 保证匿名。☺️☺️!
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 如果这个软件有长期稳定的cctv368，还是免费软件，还没有商业广告的话，
> > 
> > 
> > > > 这样太好了，那么那些卖盒子的商人，肯定是百份百拿来做商业用途，把这个软件装在他们叫卖的盒子上炫耀招俫，拿来做盒子生意赚钱，
> > 
> > 
> > > > 导致的后果，直接加速这个软件的玩完速度。
> > 
> > 
> > > 
> > 
> > 
> > > 这个软件代码直接解析cctv网站的 根本没有服务器。要想他完蛋除非cctv网站布局或者播放视频方式改了。所以压根不用怕。
> > 
> > 
> > 在大清国，让什么事物完蛋就是一张纸一句话甚至一个手势一个表情的事，根本就不用改什么cctv网站布局或者播放视频方式，用非技术手段就已经可以办到了。
> 
> 非技术怎么办到？连服务器都没有这个app 怎么办到。找作者喝茶？作者只能下架app。 作者要是在海外的 直接干死这些网站。国内能做啥？ 还能来美国抓你不成。

你这么nb也没见到你做一个app啊

**Comment by amazonjdshop** [comment]
> > > > > > > > 怕个毛。都会编程了还怕国内某机关找上门？ 作者这个是直接从官网解析网站的、有本事就叫这些机关改网站、让作者抓取不到。干的就是广电这些废物
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > 山外有山，人外有人，广电这么多饱读诗书的大学生员工，怎么可能都是废物，
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > 人家是政府部门，有的是人才，有的是充足的人手，有的是资源，有的是技术，有的是手段，有的是时间跟我们这些没有后台的平民纠缠，我们平民有多少人手，多少时间，多少精力陪政府玩？
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > 平民跟政府斗，就是鸡蛋碰石头。
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 我还就爱跟这些斗。就爱破解他们的。本人就是海外搞iptv的 国内频道抓取的还就是他们的源。天高皇帝远、有本事叫他们来漂亮国请我喝茶。作者要是怕的话可以联系我、我帮你传到github 保证匿名。☺️☺️!
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 如果这个软件有长期稳定的cctv368，还是免费软件，还没有商业广告的话，
> 
> > > 
> 
> > > 
> 
> > > > > 这样太好了，那么那些卖盒子的商人，肯定是百份百拿来做商业用途，把这个软件装在他们叫卖的盒子上炫耀招俫，拿来做盒子生意赚钱，
> 
> > > 
> 
> > > 
> 
> > > > > 导致的后果，直接加速这个软件的玩完速度。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 这个软件代码直接解析cctv网站的 根本没有服务器。要想他完蛋除非cctv网站布局或者播放视频方式改了。所以压根不用怕。
> 
> > > 
> 
> > > 
> 
> > > 在大清国，让什么事物完蛋就是一张纸一句话甚至一个手势一个表情的事，根本就不用改什么cctv网站布局或者播放视频方式，用非技术手段就已经可以办到了。
> 
> > 
> 
> > 非技术怎么办到？连服务器都没有这个app 怎么办到。找作者喝茶？作者只能下架app。 作者要是在海外的 直接干死这些网站。国内能做啥？ 还能来美国抓你不成。
> 
> 
> 
> 你这么nb也没见到你做一个app啊

哈哈哈做了也不给你用啊 付费的

**Comment by tokyo2006** [comment]
> > > > > > > > > 怕个毛。都会编程了还怕国内某机关找上门？ 作者这个是直接从官网解析网站的、有本事就叫这些机关改网站、让作者抓取不到。干的就是广电这些废物
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > 山外有山，人外有人，广电这么多饱读诗书的大学生员工，怎么可能都是废物，
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > 人家是政府部门，有的是人才，有的是充足的人手，有的是资源，有的是技术，有的是手段，有的是时间跟我们这些没有后台的平民纠缠，我们平民有多少人手，多少时间，多少精力陪政府玩？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > 平民跟政府斗，就是鸡蛋碰石头。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > 我还就爱跟这些斗。就爱破解他们的。本人就是海外搞iptv的 国内频道抓取的还就是他们的源。天高皇帝远、有本事叫他们来漂亮国请我喝茶。作者要是怕的话可以联系我、我帮你传到github 保证匿名。☺️☺️!
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 如果这个软件有长期稳定的cctv368，还是免费软件，还没有商业广告的话，
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 这样太好了，那么那些卖盒子的商人，肯定是百份百拿来做商业用途，把这个软件装在他们叫卖的盒子上炫耀招俫，拿来做盒子生意赚钱，
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 导致的后果，直接加速这个软件的玩完速度。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 这个软件代码直接解析cctv网站的 根本没有服务器。要想他完蛋除非cctv网站布局或者播放视频方式改了。所以压根不用怕。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 在大清国，让什么事物完蛋就是一张纸一句话甚至一个手势一个表情的事，根本就不用改什么cctv网站布局或者播放视频方式，用非技术手段就已经可以办到了。
> > 
> > 
> > > 
> > 
> > 
> > > 非技术怎么办到？连服务器都没有这个app 怎么办到。找作者喝茶？作者只能下架app。 作者要是在海外的 直接干死这些网站。国内能做啥？ 还能来美国抓你不成。
> > 
> > 
> > 你这么nb也没见到你做一个app啊
> 
> 哈哈哈做了也不给你用啊 付费的

所以你是卖盒子的商人吗？

**Comment by HTWMedia** [comment]
我在作者的基础上做了个app，支持Android4.4及IPv4，直播源比较稳定，大家可以试下：[HTV](https://github.com/HTWMedia/HTV)

**Comment by javadodobird** [comment]
> 我在作者的基础上做了个app，支持Android4.4及IPv4，直播源比较稳定，大家可以试下：[HTV](https://github.com/HTWMedia/HTV)

测试了你的HTV，
感觉你的这个HTVapp和这里作者的MYTVapp工作原理工作流程其实是很不一样的，
你的HTVapp工作原理工作流程是传统原理传统流程，
而这里作者的MYTVapp工作原理工作流程是比较创新和比较特别的工作原理工作流程，
所以你的app和这里作者的app不是同一个类型的app。

**Comment by lizongying** [comment]
暫時在我的電視無法提供。
有以下選擇：
使用[我的電視·〇](https://github.com/lizongying/my-tv-0) 自行配置視頻源
使用[我的電視·一](https://github.com/lizongying/my-tv-1) 這是另一種方式實現，不過，清晰度、連接速度差些，有時會限制播放
