### ISSUE TITLE
[FR] 哥你好，我出门在外，家里老人不识字也不会摆弄软件，软件版本低app就不能用了，黑屏，能不能出一个国内能自动更新的软件，谢谢哥

### ISSUE THREAD

**Issue by Ringzer369** [lizongying/my-tv#721]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

使不识字和不会摆弄软件的老人能实时更新

**Comment by qingchanbaby** [comment]
同样有此需求  每次更新都要重新安装    能否出个自动更新？

**Comment by ashsteins** [comment]
建议自动检查更新，防止源哪天出错家里人不会弄

**Comment by xlon7** [comment]
自动更新会不会连不上，电视可以装梯子吗

**Comment by ccav14** [comment]
可以的话你装个野草助手试试

**Comment by yinlubin1989** [comment]
跪求大佬优先解决黑屏问题，这个真的很致命。。。黑屏就要重新安装

**Comment by qingchanbaby** [comment]
> 建议自动检查更新，防止源哪天出错家里人不会弄

没看到自动更新的选项在哪啊

**Comment by qingchanbaby** [comment]
看到了，最新版的有自动更新了？一会儿试试> 建议自动检查更新，防止源哪天出错家里人不会弄

**Comment by leeo1125** [comment]
> 看到了，最新版的有自动更新了？一会儿试试> 建议自动检查更新，防止源哪天出错家里人不会弄

支持，确实需要这个，清明节回去帮他们安装好的，后面老版本失效了，没一点办法

**Comment by zhenyea** [comment]
强烈支持

**Comment by qingchanbaby** [comment]
右键确实自动更新

**Comment by TangDuoBuTiao** [comment]
强烈建议自动更新，大佬

**Comment by lizongying** [comment]
#772
