### ISSUE TITLE
[BUG] 1.8.6版本，索尼电视，所有频道出现认证错误

### ISSUE THREAD

**Issue by byhaoya** [lizongying/my-tv#722]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

[BUG] 1.8.6版本，索尼电视，所有频道出现认证错误

### 预期行为

[BUG] 1.8.6版本，索尼电视，所有频道出现认证错误

### 实际行为

[BUG] 1.8.6版本，索尼电视，所有频道出现认证错误

### UI / OS

索尼电视

### Android 版本

12

**Comment by byhaoya** [comment]
重新安装一遍又好了

**Comment by fang5566** [comment]
索尼电视 安卓9 1.9.2版本 所有频道认证错误 重装无效。

**Comment by javadodobird** [comment]
> ### Bug 描述
> [BUG] 1.8.6版本，索尼电视，所有频道出现认证错误
> 
> ### 预期行为
> [BUG] 1.8.6版本，索尼电视，所有频道出现认证错误
> 
> ### 实际行为
> [BUG] 1.8.6版本，索尼电视，所有频道出现认证错误
> 
> ### 复现步骤
> _No response_
> 
> ### UI / OS
> 索尼电视
> 
> ### Android 版本
> 12
> 
> ### 额外信息
> _No response_

自从1.86版本开始，
有了“增加错误显示”这个功能后，
就开始这样了，
除了3个凤凰台画声正常之外，
其余的央视，卫视，cgtn，
都是黑色屏幕，屏幕中间显示“认证请求错误”，
既没画面也没声音。

**Comment by lizongying** [comment]
#788
