### ISSUE TITLE
[BUG] 华为智慧屏装1.8.6没用呀，黑屏

### ISSUE THREAD

**Issue by Sedryr** [lizongying/my-tv#724]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

华为智慧安装1.8.6黑屏，打不开

### 预期行为

打不开

### 实际行为

黑屏

### UI / OS

HUAWEI

### Android 版本

鸿蒙

### 额外信息

能兼容鸿蒙吗

**Comment by yinlubin1989** [comment]
跪求大佬优先解决黑屏问题，这个真的很致命。。。黑屏就要重新安装

**Comment by Yuzgaf33tref6** [comment]
我个人海信电视和智慧屏都是一段时间就会有黑屏，用adb完全重启有概率恢复，，或者有时候黑屏了多等一下就突然好了

**Comment by lizongying** [comment]
請嘗試最新版
