### ISSUE TITLE
[BUG] 状态错误

### ISSUE THREAD

**Issue by 1ikun168** [lizongying/my-tv#726]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

在安卓4.4上，打开我的电视，黑屏然后出站状态错误。低版本兼容问题。如果点更新会闪退。
在安卓5.0上，tcl，出现认证请求错误

### 预期行为

修复状态错误问题，认证请求错误问题

### 实际行为

状态错误，认证请求错误
![17143553540221026302880619274670](https://github.com/lizongying/my-tv/assets/168388269/c8d2e177-e01c-4ddf-942d-cb931744475f)

### UI / OS

飞利浦

### Android 版本

4.4

**Comment by muskoais** [comment]
遇到同样问题，重新安装也没用，目前只有3 个凤凰台可以看

**Comment by Novhupo** [comment]
同样问题

**Comment by FywOoie** [comment]
同样问题

**Comment by muskoais** [comment]
我的问题解决了，过了一会再打开突然可以看了

**Comment by gavinmeng822** [comment]
我更新到最新的1.8.8版本依然出现此错误.如上面所显示的一样.认证请求错误.

**Comment by BigCleverKerryWang** [comment]
**重启**电视后可以载入

**Comment by xzji** [comment]
> 遇到同样问题，重新安装也没用。重启电视也没用。小米电视。目前只有3 个凤凰台可以看

**Comment by neuron42** [comment]
同样错误，当贝盒子

**Comment by neuron42** [comment]
只有3 个凤凰台可以看

**Comment by a342818026** [comment]
我也是这种情况，清理应用数据之后就可以正常使用了。

**Comment by neuron42** [comment]
只有3 个凤凰台可以看

**Comment by wanminny** [comment]
一样的错误！

**Comment by lizongying** [comment]
#734

**Comment by javadodobird** [comment]
自从1.86版本开始，
有了"增加错误显示"这个功能后，
就开始这样了，
有时侯除了3个凤凰，
其它的央视卫视cgtn，
都是屏幕显示"认证错误"既看不了也听不了。

**Comment by gavinmeng822** [comment]
1.8.8版本又出问题了.机顶盒打开显示认证错误.这是个BUG吗？很奇怪之前的版本都没有出现过这个问题.谢谢.
