### ISSUE TITLE
[FR] 希望可以添加amd64安装包

### ISSUE THREAD

**Issue by TailendWong** [lizongying/my-tv#727]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

我的微型主机的处理器是英特尔的， 现有安装包是arm v8， 指令集不同，运行不了

**Comment by TailendWong** [comment]
感谢你的回复和支持

**Comment by lizongying** [comment]
#896
