### ISSUE TITLE
[FR] 希望增加“湖南娱乐”频道，经常播知青剧集，老人家最爱

### ISSUE THREAD

**Issue by hawie** [lizongying/my-tv#728]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

这个app试用了非常好用，希望增加一个“湖南娱乐”频道，这个频道经常播知青剧集，经历过知青那些岁月的这一代老人家的最爱。电视看得最多的，是老人家吧。望采纳。
或者请告之，应如何添加这个频道，谢谢了。

**Comment by hawie** [comment]
> > ### 改进目的
> > 这个app试用了非常好用，希望增加一个“湖南娱乐”频道，这个频道经常播知青剧集，经历过知青那些岁月的这一代老人家的最爱。电视看得最多的，是老人家吧。望采纳。 或者请告之，应如何添加这个频道，谢谢了。
> 
> 你自己动手把你找到的“湖南娱乐频道”的网络源地址， 添加到 my-tv-0 软件，中文名字叫做 我的电视·〇 软件， 这个软件是这个作者写的另外一个软件。

那个UI没有这个漂亮呢。最好是这个的界面，加多这一个频道就可以了。

**Comment by hujie2690** [comment]
在度假中!假后回复!!胡杰

**Comment by gsons** [comment]
@javadodobird 有些直播源地址是动态解析的

**Comment by hawie** [comment]
除了这个“湖南娱乐”频道，才发现cctv3也没有。所以，还是先换回了小薇直播。以前电视家运营的时侯，界面不错，付费用户VIP高清频道也很好，可惜，至今没有找到替代。期待作者能出一个稳定的换台快又画面质量好的版本，收费也没关系。

**Comment by meteorazhuan** [comment]
> > ### 检查清单
> > 
> > * [x]   之前没有人提交过类似或相同的功能请求。
> > * [x]   这个建议不会背离 my-tv 的初衷。
> > 
> > ### 改进目的
> > 这个app试用了非常好用，希望增加一个“湖南娱乐”频道，这个频道经常播知青剧集，经历过知青那些岁月的这一代老人家的最爱。电视看得最多的，是老人家吧。望采纳。 或者请告之，应如何添加这个频道，谢谢了。
> > ### 解决方案
> > _No response_
> > ### 额外信息
> > _No response_
> 
> 你自己动手把你找到的“湖南娱乐频道”的网络源地址， 添加到 my-tv-0 软件，中文名字叫做 我的电视·〇 软件， 这个软件是这个作者写的另外一个软件。

那么，在哪里可以下载到呢？求链接

**Comment by javadodobird** [comment]
> > > ### 检查清单
> > > 
> > > * [x]    之前没有人提交过类似或相同的功能请求。
> > > * [x]    这个建议不会背离 my-tv 的初衷。
> > > 
> > > ### 改进目的
> > > 这个app试用了非常好用，希望增加一个“湖南娱乐”频道，这个频道经常播知青剧集，经历过知青那些岁月的这一代老人家的最爱。电视看得最多的，是老人家吧。望采纳。 或者请告之，应如何添加这个频道，谢谢了。
> > > ### 解决方案
> > > _No response_
> > > ### 额外信息
> > > _No response_
> > 
> > 
> > 你自己动手把你找到的“湖南娱乐频道”的网络源地址， 添加到 my-tv-0 软件，中文名字叫做 我的电视·〇 软件， 这个软件是这个作者写的另外一个软件。
> 
> 那么，在哪里可以下载到呢？求链接

我的电视·〇（my-tv-0）下载链接：
https://github.com/lizongying/my-tv-0/releases/

**Comment by lizongying** [comment]
[我的電視·一](https://github.com/lizongying/my-tv-1) 有這個頻道
