### ISSUE TITLE
[BUG] 认证错误，除了香港频道，其他都是认证错误黑屏

### ISSUE THREAD

**Issue by whtk** [lizongying/my-tv#732]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

认证错误，除了香港频道，其他都是认证错误黑屏1.8.8版本

### 预期行为

清晰显示

### 实际行为

黑屏

### UI / OS

海信电视

### Android 版本

5

**Comment by whtk** [comment]
wtf 又自己好了。。奇了怪了

**Comment by panybbib** [comment]
> wtf 又自己好了。。奇了怪了

yes

**Comment by wanminny** [comment]
不行；还是不行！刚刚安装看了3分钟后再切换后面显示认证错误！

**Comment by javadodobird** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的 bug report。
> * [x]  我正在使用本软件的最新版本。
> 
> ### my-ty 版本
> 通用版
> 
> ### Bug 描述
> 认证错误，除了香港频道，其他都是认证错误黑屏1.8.8版本
> 
> ### 预期行为
> 清晰显示
> 
> ### 实际行为
> 黑屏
> 
> ### 复现步骤
> _No response_
> 
> ### UI / OS
> 海信电视
> 
> ### Android 版本
> 5
> 
> ### 额外信息
> _No response_

自以1.86版本开始，
有了"增加错误显示"这个功能后，
就开始这样了，
有时侯除了3个凤凰，
其它的央视卫视cgtn，
都是屏幕显示"认证错误"既看不了也听不了。

**Comment by Steven-blue** [comment]
群主给更新下，跪求

**Comment by lizongying** [comment]
#734 我會關注這個問題
