### ISSUE TITLE
[BUG] tokenFH失效, 凤凰卫视清晰度下降

### ISSUE THREAD

**Issue by atlantis-l** [lizongying/my-tv#733]
### 检查清单

- [x] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

```
由于失去服务器支持, tokenFH始终为"", 无法显示FHD
```

### 预期行为

```
有全高清FHD显示
```

### 实际行为

```
清晰度为HD
```

### UI / OS

TCL

### Android 版本

12

### 额外信息

```
不清楚这个tokenFH参数是否可以在本地维护, 如果需要服务器的话就不用麻烦作者大大了，谢谢🙏
```

**Comment by lizongying** [comment]
後面可能會在一個合適的時候開放出來，方便本地配置。
本地維護的話，可能會引入一些新的問題，是否適合普通用戶？
