### ISSUE TITLE
[BUG] 除凤凰频道外，认证状态错误

### ISSUE THREAD

**Issue by icShare** [lizongying/my-tv#734]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

除凤凰频道外，显示认证状态错误，但是还能有凤凰频道的声音。

### 预期行为

正常加载

### 实际行为

认证状态错误

### UI / OS

HUAWEI

### Android 版本

鸿蒙OS2.0.0

**Comment by lizongying** [comment]
可以試試最新版。這個問題我電腦電視都無法復現，可能不太好處理。

**Comment by javadodobird** [comment]
> ### my-ty 版本
> 通用版
> 
> ### Bug 描述
> 除凤凰频道外，显示认证状态错误，但是还能有凤凰频道的声音。
> 
> ### 预期行为
> 正常加载
> 
> ### 实际行为
> 认证状态错误
> 
> ### 复现步骤
> _No response_
> 
> ### UI / OS
> HUAWEI
> 
> ### Android 版本
> 鸿蒙OS2.0.0
> 
> ### 额外信息
> _No response_

No response

自从1.86版本开始，
有了"增加错误显示"这个功能后，
就开始这样了，
有时侯除了3个凤凰，
其它的央视卫视cgtn，
都是屏幕显示"认证错误"既看不了也听不了。
