### ISSUE TITLE
5月1日，好像所有频道都看不了了，只有凤凰的三个台正常[BUG] 

### ISSUE THREAD

**Issue by lovelyelfpop** [lizongying/my-tv#735]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

专用版

### Bug 描述

所有台都黑屏，只有凤凰的三个台可以看

### 预期行为

所有台正常

### 实际行为

大陆和国外的台看不了

### UI / OS

创维盒子

### Android 版本

9

**Comment by caoxinyi1993** [comment]
bug复现了，可能是线路有问题。希望开发者尽快解决，谢谢。

**Comment by x0829** [comment]
除了凤凰系列其他频道都提示认证状态错误

**Comment by lizongying** [comment]
我這正常

**Comment by QiuYukang** [comment]
认证错误🤦‍♂️

**Comment by javadodobird** [comment]
> 
> ### my-ty 版本
> 专用版
> 
> ### Bug 描述
> 所有台都黑屏，只有凤凰的三个台可以看
> 
> ### 预期行为
> 所有台正常
> 
> ### 实际行为
> 大陆和国外的台看不了
> 
> ### 复现步骤
> _No response_
> 
> ### UI / OS
> 创维盒子
> 
> ### Android 版本
> 9
> 
> ### 额外信息
> _No response_

自从1.86版本开始，
有了“增加错误显示”这个功能后，
就开始这样了，
除了3个凤凰台画声正常之外，
其余的央视，卫视，cgtn，
都是黑色屏幕，屏幕中间显示“认证请求错误”，
既没画面也没声音。

**Comment by jie65535** [comment]
我出现了相同的问题。

**Comment by weingxing** [comment]
我也遇到了这个问题，重装了好几次，只有两次正常，其他都是 认证请求错误

**Comment by weingxing** [comment]
1.8.4版本基本正常，偶尔打开会黑屏；1.9.2版本多次出现 认证请求错误

**Comment by weingxing** [comment]
注意到一个现象，如果打开软件后右上角时间显示正常，就可以观看，如果显示的8:00，就无法观看

**Comment by javadodobird** [comment]
> 1.8.4版本基本正常，偶尔打开会黑屏；1.9.2版本多次出现 认证请求错误

自从1.86版本开始，
有了“增加错误显示”这个功能后，
就开始这样了，
除了3个凤凰台画声正常之外，
其余的央视，卫视，cgtn，
都是黑色屏幕，屏幕中间显示“认证请求错误”，
既没画面也没声音。

**Comment by lovelyelfpop** [comment]
1.9.2提示认证错误，旧版本没提示直接是黑屏。
安徽电信宽带，安徽联通宽带都这样。
江苏联通卡在安徽用数据流量下可以看

**Comment by FT521** [comment]
目前北京联通也提示认证错误

**Comment by hyeonsori** [comment]
天津联通也是提示认证错误，就凤凰三个台可以看

**Comment by xuan-surf** [comment]
同样的情况，但是是1.8.3，更新后还是显示认证错误

**Comment by RayneScofield** [comment]
湖北联通 1.9.2认证状态错误😑

**Comment by vendettar** [comment]
> 我把网络从电信切换到移动，就好了

怎么切换啊，家里的网络不就一个吗?

**Comment by jie65535** [comment]
这几天我测试了多次，正常在电视启动进入主页后，打开应用大部分情况下可以正常播放。

但是从电视里设置开机直达到APP后，开机就会出现状态错误，几秒后出现认证错误。
此时进设置退出APP重新打开有一定概率可以恢复。

建议在发生错误时，显示更多异常信息便于排故，也许可以允许手动重新加载？

**Comment by hexindent** [comment]
从1.9.2退回1.8.4仍然只有凤凰三个台，时间显示08:00。重启软件或路由未解决问题。广东电信

**Comment by javadodobird** [comment]
> 从1.9.2退回1.8.4仍然只有凤凰三个台，时间显示08:00。重启软件或路由未解决问题。广东电信

我猜应该是网络晚高峰到来，太多人同时登入，某些环节弄崩溃了，现在只能耐心等这些环节重新运作，才可以恢复正常收看

**Comment by pedayo-3344** [comment]
z

**Comment by mishiqi9** [comment]
1.8.4版本，可以看港澳台三个频道，其他的频道就是黑色，用的是极米投影仪

**Comment by showthesunli** [comment]
同样的问题，试过1.8.2 和 1.9.2两个版本

**Comment by ypcgamelife** [comment]
估计出问题了，我也遇到了。、

**Comment by einsteinzk** [comment]
从1.7.6一直用测试到1.9.6 所有版本都同样的问题，只有香港的3个能看，其他的都现实认证错误。小米盒子

**Comment by Grey1205** [comment]
我的是除了凤凰三个台有问题，其他的都没有问题。凤凰三个台只要切换到就会画面卡住，声音正常，但是切换到其他电视台就会出现黑屏了。
