### ISSUE TITLE
[BUG] 检查更新有新版本点击确认后过一会应用闪退

### ISSUE THREAD

**Issue by RyougiChan** [lizongying/my-tv#736]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

![IMG_20240502_082018](https://github.com/lizongying/my-tv/assets/13507165/37eca42a-0936-40f1-afab-7ec6a8dd2a7c)
点击确认，过一会应用闪退

### 预期行为

可以正常更新应用

### 实际行为

应用异常闪退

### UI / OS

XIAOMI

### Android 版本

11

### 额外信息

小米电视S75，电视系统版本是MI OS 2.8

**Comment by johnnyeecker** [comment]
sony电视,版本1.9.6,有同样问题,
识别有1.9.8新版本后,点击确定更新,稍后没有滚动条,稍后app就自动闪退了.

**Comment by lizongying** [comment]
#772
