### ISSUE TITLE
[BUG] 观看频道卡顿

### ISSUE THREAD

**Issue by brynhildrLong** [lizongying/my-tv#740]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

设备华为智慧屏，安装等过程无bug，但是在观看时总会卡顿，然后显示“播放错误”，稍等会又重新加载出来。
以前大概1.6的版本未出现过。
网速正常能够达到5m/s左右。

### 预期行为

预期不卡顿

### 实际行为

实际过分卡顿

### UI / OS

HUAWEI

### Android 版本

0

**Comment by laoyidianyu** [comment]
手机观看还行

**Comment by lizongying** [comment]
我這手機、電視都是正常的。
如果是5分鐘左右卡一下的問題，最新版本已解決。
如果是平時播放卡頓，可能是設備的硬件播放問題，暫不解決。
