### ISSUE TITLE
[FR] 增加重温经典频道

### ISSUE THREAD

**Issue by fxmirnet** [lizongying/my-tv#743]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

作者能否增加重温经典频道节目源呢？

**Comment by laoyidianyu** [comment]
目前做好稳定就不错了

**Comment by javadodobird** [comment]
> 加 cctv3 和 6

前些日子是有过全套cctv368cctv风云，
刚开始收看人数没那么多人，相对少人，收看还算正常，
到了后来收看人数越来越多，就开始有卡屏现象了，到了晚上晚高峰时段，连台都进不去，偶尔挤进去某一个台，还不敢轻易换台，因为一换台就又挤进不去了，
所以没办法人太多了，大家都挤成一团看不了了，就取消了cctv368cctv风云，我猜应该是这样的。

**Comment by fxmirnet** [comment]
我不需要加3 6 8 这种加密频道，重温经典频道是免费收看的不加密的

**Comment by javadodobird** [comment]
> 我不需要加3 6 8 这种加密频道，重温经典频道是免费收看的不加密的

应该是需要有官方网络的稳定源才会加

**Comment by dabao-zhao** [comment]
目前出现认证失败了……

**Comment by javadodobird** [comment]
> 目前出现认证失败了……

我猜应该是网络晚高峰到来，太多人同时登入，某些环节弄崩溃了，现在只能耐心等这些环节重新运作，才可以恢复正常收看

**Comment by meteorazhuan** [comment]
> 我不需要加3 6 8 这种加密频道，重温经典频道是免费收看的不加密的
这个要支持一下，这个频道是免费频道，可以加入

**Comment by 544572434** [comment]
368这种娱乐频道反而是直播软件中最少看的，因为网络上资源更多更全，直播还是看新闻类的更多

**Comment by lizongying** [comment]
可以嘗試使用[我的電視·〇](https://github.com/lizongying/my-tv-0)
