### ISSUE TITLE
断流的问题

### ISSUE THREAD

**Issue by Yigehaoren8848** [lizongying/my-tv#744]
我是一个爬虫技术爱好者，请教作者一个问题，已经拿到播放链接，但是发现断流严重，每次都是在五分钟多点的时候断掉，但是作者的app没问题，由于不太懂kt语言，想请问作者怎么解决这个问题，是和dtrace那个接口有关系吗

**Comment by zsl-157** [comment]
有知道的大佬朋友请解答一下

**Comment by zsl-157** [comment]
已解决，确实是dtrace的问题，需要定时任务，定时发送请求才能避免断流
