### ISSUE TITLE
显示状态错误

### ISSUE THREAD

**Issue by LYH66666** [lizongying/my-tv#745]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

打开频道显示状态错误

### 预期行为

可以正常观看频道

### 实际行为

显示状态错误，无法观看

### UI / OS

雷鸟

### Android 版本

12

**Comment by StudentWanLu** [comment]
我也显示这样了，昨天还是可以看的，香港台可以看，目前卫士台和央视台，无法显示状态错误或者认证错误

**Comment by GengDaPeng** [comment]
我刚下载了1.9.2  并通过小米电视助手升级   打开后直接显示 状态错误

**Comment by deseking** [comment]
同样的现象，有的频道显示：状态错误，有的频道显示：认证状态错误

**Comment by jiam9069** [comment]
香港凤凰卫视可以看，其他显示  认证状态错误

**Comment by ccav14** [comment]
时好时坏

**Comment by junjieliu002** [comment]
显示错误不能看了

**Comment by javadodobird** [comment]
应该是网络晚高峰到来，太多人同时登入，某些环节弄崩溃了，现在只能耐心等这些环节重新运作，才可以恢复正常收看

**Comment by byhaoya** [comment]
看不了了

**Comment by non-one** [comment]
应用内视频源能不能自动更新？如果不行，可否添加自定义播放源的功能，应该可以减少开发者修bug的工作量

**Comment by byhaoya** [comment]
香港台可以看，目前卫士台和央视台，无法显示状态错误或者认证错误， 版本 1.9.2

**Comment by javadodobird** [comment]
> 香港台可以看，目前卫士台和央视台，无法显示状态错误或者认证错误， 版本 1.9.2

我猜应该是网络晚高峰到来，太多人同时登入，某些环节弄崩溃了，现在只能耐心等这些环节重新运作，才可以恢复正常收看

**Comment by NI-Enrique** [comment]
+1

**Comment by easedicy** [comment]
+1

**Comment by huhu415** [comment]
我也一样, 状态错误了

**Comment by 3493129790** [comment]
+1

**Comment by TGFreeProgram** [comment]
![Screenshot_2024-05-04-19-39-30-881_com lizongying mytv](https://github.com/lizongying/my-tv/assets/168690838/aa459e48-3389-48e1-b5f1-b4c1db133cdb)
一样，天天更新 也不知道更新了点啥.

**Comment by byhaoya** [comment]
作者有TG群吗??

**Comment by yfr1002** [comment]
我也一样, 状态错误了

**Comment by haishengXie0712** [comment]
我也一样, 状态错误了

**Comment by fizzyob** [comment]
认证状态错误。。

**Comment by johnnyeecker** [comment]
同样的错误,看不了除凤凰之外的其他频道,版本1.9.2

**Comment by lililllllllilil** [comment]
一样 认证状态错误

**Comment by lizongying** [comment]
節後修復。

**Comment by wanminny** [comment]
+100

**Comment by kid9547** [comment]
同样的问题

**Comment by znzn007007** [comment]
同样的问题

**Comment by ohzhangluoluo** [comment]
同样的问题，昨天还能看

**Comment by AlbiziaJulibrissinV** [comment]
同样的问题，低版本能看，更新成高版本就看不了了

**Comment by alsojin0806** [comment]
> 同样的问题，低版本能看，更新成高版本就看不了了

哪个版本啊

**Comment by kennanhoo** [comment]
+1 加油

**Comment by hbyzl** [comment]
CCTV error

**Comment by lfm09** [comment]
同样只能播放3个凤凰台，同时右上角时间错误，可能跟无法获取网络时间有关？

**Comment by pc9868** [comment]
之前一直觉的这软件稳定好用，但是这一个月来我再也没有这感觉了，时不时不能用，已经无法当作老人电视的首选APP了

**Comment by AppleMate60pro** [comment]
@pc9868 欢喜直播花个几十块开个会员省心，维护要精力的，不花钱肯定要承受这些

**Comment by AppleMate60pro** [comment]
> 应用内视频源能不能自动更新？如果不行，可否添加自定义播放源的功能，应该可以减少开发者修bug的工作量
作者已经出了一个自定义源的啊

**Comment by akinLiu** [comment]
+1

**Comment by wuruosuilingyunzhi** [comment]
出现了状态错误

**Comment by hawie** [comment]
作者版本更新有点勤，才装上1.88版，又有1.92了，只是前一刻1.88还能看，换为1.92都显示认证错误看不了了。1.88检测更新有1.92但没有安装好更新，手动卸载再下载1.92安装的。sony tv，85x85k。
另外，cctv3那些能加进来吗？

**Comment by tsao8** [comment]
1.92版不能看，状态错误。

**Comment by tokyo2006** [comment]
> ![Screenshot_2024-05-04-19-39-30-881_com lizongying mytv](https://private-user-images.githubusercontent.com/168690838/327946061-aa459e48-3389-48e1-b5f1-b4c1db133cdb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4ODAxNzcsIm5iZiI6MTcxNDg3OTg3NywicGF0aCI6Ii8xNjg2OTA4MzgvMzI3OTQ2MDYxLWFhNDU5ZTQ4LTMzODktNDhlMS1iNWYxLWI0YzFkYjEzM2NkYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwMzMxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjhjNTZhM2E2OGY2ZjdkMTJlYTY3NjQ3ZTRlNzQ0YzVhYmFkMTJlMTg1ZmJkYWI2MmNlMzFlYTA0OWM2MzM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bn9zI9D_jf7uDp1F9fh6wZFwp_v4ntL9gLfS4-o0ECk) 一样，天天更新 也不知道更新了点啥.

开源给你用就不错了，要啥自行车，毕竟这个是作者自己在弄，多些理解吧。

**Comment by Ccitniubi** [comment]
> 節後修復。

要更新吗？ 还是自动更新 家里老人不好搞啊，年轻人又不在家都出去打工了

**Comment by 4yt1k** [comment]
一样，我试了多个版本，1.8.6、1.8.8、1.9.0、1.9.2，结果全部一样。
看来是直播源的问题，我建议作者出一个可以自定义的版本，只支持单源就可以，这样可以避免很多问题。
其实我最想要就是这种版本，适合老人，按一个机顶盒的开关就直接进入电视直播，如果现在的my-tv稳定的话，除了没有368频道，其它很好了，但我家老人最喜欢看却是8频道。。。
如果有支持自定义源的版本，那我只需要维护源就可以了。

**Comment by MasterblackG** [comment]
状态错误，sony电视，测试了1.8.2至1.9.2都一样

**Comment by wang322588** [comment]
是直播源出了问题，只有自定义的直播源才会稳定可用。移动的ipv6已经稳定用了半年了，但并不适合大部分用户。

**Comment by ccav14** [comment]
> 一样，我试了多个版本，1.8.6、1.8.8、1.9.0、1.9.2，结果全部一样。 看来是直播源的问题，我建议作者出一个可以自定义的版本，只支持单源就可以，这样可以避免很多问题。 其实我最想要就是这种版本，适合老人，按一个机顶盒的开关就直接进入电视直播，如果现在的my-tv稳定的话，除了没有368频道，其它很好了，但我家老人最喜欢看却是8频道。。。 如果有支持自定义源的版本，那我只需要维护源就可以了。

 my-tv-0了解一下
https://github.com/lizongying/my-tv-0

**Comment by xymyx66** [comment]
我也是状态错误或认证状态错误，不知该怎么解决，各位大神有办法吗？

**Comment by sion516516** [comment]
5月5日下午开始就不能看了，多个设备上测试均显示状态错误，不知道是怎么了。

**Comment by lizongying** [comment]
#750

**Comment by xumeitian** [comment]
除了香港台可以看，其他台都显示“状态错误”。还请解决一下

**Comment by Ccitniubi** [comment]
http://download.shanzhuan.cn/dd.html?id=206174-----------------------------------------------以上为闪赚软件的下载链接，安卓ios均可下载，获取钻石的方法非常简单，进去一看便明白，有wifi的朋友尽情下载兑换支付宝、话费吧〜___________亲，你送上15字了吗？伸手党可耻哦〜
