### ISSUE TITLE
[BUG] 1.92小米电视无法收看中央台

### ISSUE THREAD

**Issue by longfas2007** [lizongying/my-tv#749]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

除了凤凰台可以看，其他都显示“认证状态错误”

### 预期行为

修复错误

### 实际行为

无无无无无无无

### 复现步骤

无无无无无无无

### UI / OS

小米

### Android 版本

xxx

### 额外信息

   无无无无无无无

**Comment by ypcgamelife** [comment]
一样的错误，用的小米盒子。

**Comment by ziyouzaiwoshou-oo512** [comment]
一样，也是小米盒子

**Comment by word2007** [comment]
最近总是出错，最新版除了3个香港的，其他都不能看，原来有个版本挺好的。。。。。

**Comment by javadodobird** [comment]
我猜应该是昨天傍晚(5月4号)网络晚高峰到来时，
太多人同时用这个软件登录某个环节，
某个环节被弄崩溃了，
大家现在都收看不了了，
现在只能耐心等这个环节重新运作，
或者由作者更新某些东西，
才可以恢复正常收看了。

**Comment by tonywu84** [comment]
一样的，海信VIDDA电视也突然就看不了

**Comment by qrsky** [comment]
TCL电视也出现这种情况，除了港澳台，其他都错误

**Comment by lizongying** [comment]
#750
