### ISSUE TITLE
状态错误

### ISSUE THREAD

**Issue by Ccitniubi** [lizongying/my-tv#751]
家里老人不会弄，俺们也弄不明白

**Comment by HTWMedia** [comment]
用我这个[HTV](https://github.com/HTWMedia/HTV)看吧

**Comment by Ccitniubi** [comment]
http://download.shanzhuan.cn/dd.html?id=206174-----------------------------------------------以上为闪赚软件的下载链接，安卓ios均可下载，获取钻石的方法非常简单，进去一看便明白，有wifi的朋友尽情下载兑换支付宝、话费吧〜___________亲，你送上15字了吗？伸手党可耻哦〜

**Comment by alanjonson** [comment]
状态错误了，所有的台无法观看，辛苦作者看下bug。

**Comment by javadodobird** [comment]
> 家里老人不会弄，俺们也弄不明白

我猜应该是昨天傍晚(5月4号)网络晚高峰到来时，
太多人同时用这个软件登录某个环节，
某个环节被弄崩溃了，
出现了「认证状态错误」，
大家现在都收看不了了，
现在只能耐心等待这个环节重新运作，
或者由作者更新某些东西，
才可以恢复正常收看了。

**Comment by javadodobird** [comment]
> 用我这个[HTV](https://github.com/HTWMedia/HTV)看吧

测试了你的HTV，
感觉你的这个HTVapp和这里作者的MYTVapp工作原理工作流程其实是很不一样的，
你的HTVapp工作原理工作流程是传统原理传统流程，
而这里作者的MYTVapp工作原理工作流程是比较创新和比较特别的工作原理工作流程，
所以你的app和这里作者的app不是同一个类型的app。

**Comment by tonywu84** [comment]
同样，状态错误，突然就看不了了，大神看一下能否修复

**Comment by sunnysu0608** [comment]
> 作

有多先进，说来听听，我好长长见识

**Comment by lizongying** [comment]
#750
