### ISSUE TITLE
[FR] 能搞个在线升级功能么

### ISSUE THREAD

**Issue by githubcxg** [lizongying/my-tv#753]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

每次下载安装挺麻烦

### 解决方案

在线升级模块

### 额外信息

这个app速度不错，就是不够持久啊，过一段时间老人家就说看不了，还好有替补软件。

**Comment by MrLQi** [comment]
求替代软件

**Comment by githubcxg** [comment]
山上论坛里有，https://www.right.com.cn/forum/thread-8340850-1-1.html

**Comment by hzhuanxu** [comment]
> 山上论坛里有，速度没有my-tv快。https://www.right.com.cn/forum/thread-8340850-1-1.html
试了下，我这好像就一个星火能播放。谢谢

**Comment by hzhuanxu** [comment]
> 山上论坛里有，速度没有my-tv快。https://www.right.com.cn/forum/thread-8340850-1-1.html

难受。星火能放，但是家里小米电视不让安装

**Comment by githubcxg** [comment]
> > 山上论坛里有，速度没有my-tv快。https://www.right.com.cn/forum/thread-8340850-1-1.html
> 
> **试了下，我这好像就一个星火能播放。谢谢**
萝卜头，星火，小薇都可以啊

**Comment by tonywu84** [comment]
有还线升级这个功能，只是每次点更新的时候都报错。

**Comment by AppleMate60pro** [comment]
> 求替代软件

小薇直播足道纯净版

**Comment by cooiky** [comment]
> > 求替代软件
> 
> 小薇直播足道纯净版

官网下载的安装后打开就一直卡在 logo 界面不动，不知道为啥

**Comment by githubcxg** [comment]
> > > 求替代软件
> > 
> > 
> > 小薇直播足道纯净版
> 
> 官网下载的安装后打开就一直卡在 logo 界面不动，不知道为啥

这个不行再换个，总有可用的～

**Comment by AppleMate60pro** [comment]
> > > 求替代软件
> > 
> > 
> > 小薇直播足道纯净版
> 
> 官网下载的安装后打开就一直卡在 logo 界面不动，不知道为啥

极悦

**Comment by vrichv** [comment]
> > 山上论坛里有，速度没有my-tv快。https://www.right.com.cn/forum/thread-8340850-1-1.html
> 
> 难受。星火能放，但是家里小米电视不让安装

用星火需要小心点，某些港台频道是偷别人的源，试过几次突然变成AV，在全家面前社死就不好了 :-(

**Comment by lizongying** [comment]
最新版已支持
