### ISSUE TITLE
增加每个频道的配置项[FR] 

### ISSUE THREAD

**Issue by jiatongwu** [lizongying/my-tv#756]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

用户可以自己配置每个频道的m3u8或rtsp地址
用户可以自己增加频道

### 解决方案

帮助测试

### 额外信息

加油

**Comment by MartinMa-SH** [comment]
人家已经开发了，你自己就不能动动小手嘛
https://github.com/lizongying/my-tv-0

**Comment by gsons** [comment]
> 人家已经开发了，你自己就不能动动小手嘛 https://github.com/lizongying/my-tv-0

这不支持动态刷新token header这些 没啥用

**Comment by lizongying** [comment]
> > 人家已经开发了，你自己就不能动动小手嘛 https://github.com/lizongying/my-tv-0
> 
> 这不支持动态刷新token header这些 没啥用

不太明白。我的電視·〇應該會很快加上自定義header。
不知道你說的動態，是怎麼操作？
