### ISSUE TITLE
感谢大佬分享

### ISSUE THREAD

**Issue by lizm0712** [lizongying/my-tv#76]
特意登录 git 感谢下大佬的分享。

**Comment by zbby1987** [comment]
没事儿少跑这儿发垃圾信息占用空间！
人人都像你这样发，问题反馈区还有法看么！？？
真有心感谢，就打开软件，点菜单键，扫码捐助点money

**Comment by lizm0712** [comment]
> 没事儿少跑这儿发垃圾信息占用空间！ 人人都像你这样发，问题反馈区还有法看么?? 真有心感谢，就打开软件，点菜单键，扫码捐助点money

别人连个说话的权利都没了，你是个什么东西。

**Comment by ShanshanHY** [comment]
> > 没事儿少跑这儿发垃圾信息占用空间！ 人人都像你这样发，问题反馈区还有法看么?? 真有心感谢，就打开软件，点菜单键，扫码捐助点money
> 
> 别人连个说话的权利都没了，你是个什么东西。

issue是用来提出/反馈软件问题的，跑issue下感谢确实是扰乱环境
