### ISSUE TITLE
昨晚莫名其妙可以播放了。。。结果现在又 G 了，额 又好了。

### ISSUE THREAD

**Issue by 743859910** [lizongying/my-tv#760]

**Comment by ydywy** [comment]
时间显示也正确了

**Comment by javadodobird** [comment]
> _No description provided._

我猜应该是5月4号傍晚网络晚高峰到来时，
太多人同时用这个软件登录某个环节，
某个环节被弄崩溃了，
出现了「认证状态错误」，
大家现在都收看不了了，
现在只能耐心等待这个环节重新运作，
或者由作者更新某些东西，
才可以恢复正常收看了。

**Comment by lfm09** [comment]
应该就是跟获取的网络时间有关

**Comment by kissonfire** [comment]
大佬休假结束回来改代码了

**Comment by zxhans** [comment]
应该是改了中继服务了
