### ISSUE TITLE
[FR] 直播源文件在哪里，怎么从项目文件中找不到了？

### ISSUE THREAD

**Issue by 889098** [lizongying/my-tv#761]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

直播源文件在哪里，怎么从项目文件中找不到了？

### 解决方案

直播源文件在哪里，怎么从项目文件中找不到了？

### 额外信息

直播源文件在哪里，怎么从项目文件中找不到了？

**Comment by AppleMate60pro** [comment]
找到了你也用不了多久啊，源是关键，你要是会爬你就可以玩作者的代码，自己爬源配个服务器自用那就可以用到死

**Comment by lizongying** [comment]
没有
