### ISSUE TITLE
1.9.4版本  还是出现认证状态错误[FR] 

### ISSUE THREAD

**Issue by youlang2000** [lizongying/my-tv#763]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

希望可以尽快解决  家里的老人好几天没电视可以看了

**Comment by javadodobird** [comment]
> ### 检查清单
> 
> ### 改进目的
> 希望可以尽快解决 家里的老人好几天没电视可以看了
> 
> ### 解决方案
> _No response_
> 
> ### 额外信息
> _No response_


试试退出软件，再开启软件看看有没有正常。

或者，试试退出软件，不要立刻再开启软件，而是过了几分钟，再去开启软件看看有没有正常。

**Comment by youlang2000** [comment]
又正常了，

**Comment by lizongying** [comment]
系統時間需要正確，默認啟動的時候會請求時間進行修正，如果系統時間不對，而請求也失敗的話，後續請求就會失敗。
在1.9.6 加了3次重試，可能會緩解。
如果網絡條件好、電視性能好的話，基本不會出現此現象。
好一點的電視時間也應該是正常的。

或者試試 @javadodobird 所說方法

**Comment by Favoryoung** [comment]
我也是1.9.4 只有凤凰台 时间是对的，A73处理器 3g运存
应该是网络问题，我把路由器dns改成1.1.1.1就可以了
