### ISSUE TITLE
[BUG] 换台只要一快，马上触发认证错误，100%复现

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#765]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

[BUG] 换台只要一快，马上触发认证错误，100%复现

### 预期行为

[BUG] 换台只要一快，马上触发认证错误，100%复现

### 实际行为

[BUG] 换台只要一快，马上触发认证错误，100%复现

### 复现步骤

[BUG] 换台只要一快，马上触发认证错误，100%复现

### UI / OS

Mumu模拟器

### Android 版本

12

**Comment by javadodobird** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的 bug report。
> * [x]  我正在使用本软件的最新版本。
> 
> ### my-ty 版本
> 通用版
> 
> ### Bug 描述
> [BUG] 换台只要一快，马上触发认证错误，100%复现
> 
> ### 预期行为
> [BUG] 换台只要一快，马上触发认证错误，100%复现
> 
> ### 实际行为
> [BUG] 换台只要一快，马上触发认证错误，100%复现
> 
> ### 复现步骤
> [BUG] 换台只要一快，马上触发认证错误，100%复现
> 
> ### UI / OS
> Mumu模拟器
> 
> ### Android 版本
> 12
> 
> ### 额外信息
> _No response_

要慢慢的换台，
如果1秒钟内快速换两三四个台是很容易出现「认证状态错误」的。

**Comment by waynesocool** [comment]
同触发，不过换一下台就解决了，不影响正常使用

**Comment by tonywu84** [comment]
> > ### 检查清单
> > 
> > * [x]   之前没有人提交过类似或相同的 bug report。
> > * [x]   我正在使用本软件的最新版本。
> > 
> > ### my-ty 版本
> > 通用版
> > ### Bug 描述
> > [BUG] 换台只要一快，马上触发认证错误，100%复现
> > ### 预期行为
> > [BUG] 换台只要一快，马上触发认证错误，100%复现
> > ### 实际行为
> > [BUG] 换台只要一快，马上触发认证错误，100%复现
> > ### 复现步骤
> > [BUG] 换台只要一快，马上触发认证错误，100%复现
> > ### UI / OS
> > Mumu模拟器
> > ### Android 版本
> > 12
> > ### 额外信息
> > _No response_
> 
> 要慢慢的换台， 如果1秒钟内快速换两三四个台是很容易出现「认证状态错误」的。

是作者的小号吗？作者几乎不怎么回复都是你在回复。

**Comment by javadodobird** [comment]
> > > ### 检查清单
> > > 
> > > * [x]    之前没有人提交过类似或相同的 bug report。
> > > * [x]    我正在使用本软件的最新版本。
> > > 
> > > ### my-ty 版本
> > > 通用版
> > > ### Bug 描述
> > > [BUG] 换台只要一快，马上触发认证错误，100%复现
> > > ### 预期行为
> > > [BUG] 换台只要一快，马上触发认证错误，100%复现
> > > ### 实际行为
> > > [BUG] 换台只要一快，马上触发认证错误，100%复现
> > > ### 复现步骤
> > > [BUG] 换台只要一快，马上触发认证错误，100%复现
> > > ### UI / OS
> > > Mumu模拟器
> > > ### Android 版本
> > > 12
> > > ### 额外信息
> > > _No response_
> > 
> > 
> > 要慢慢的换台， 如果1秒钟内快速换两三四个台是很容易出现「认证状态错误」的。
> 
> 是作者的小号吗？作者几乎不怎么回复都是你在回复。

我不是作者，也不是作者的小号。

**Comment by WFANG12719** [comment]
![image](https://github.com/lizongying/my-tv/assets/87627119/11e31827-dca8-4017-a843-16476154b712)

**Comment by WFANG12719** [comment]
![image](https://github.com/lizongying/my-tv/assets/87627119/966f0cba-36fd-4816-9fe2-ec63e7e50498)

**Comment by ashsteins** [comment]
顶上去

**Comment by rex2032** [comment]
确实是这样，我刚升级了1.9.8版，刚开始可看，快速换了几个台就不行了，刚开始换一下台就行，后来再快速换台后，就怎么也恢复不了。提示认证状态错误。凤凰3个台可以看，其他都不行。而且卸载重装也不行，目前彻底不能用。

**Comment by WFANG12719** [comment]
我每回遇到这种情况直接把盒子或电视机彻底重启一下，多数时候可以恢复，也有不行的。这就是系统运维常用的重启大法。系统的稳定运行要靠不断重启来实现啊！

**Comment by javadodobird** [comment]
> 确实是这样，我刚升级了1.9.8版，刚开始可看，快速换了几个台就不行了，刚开始换一下台就行，后来再快速换台后，就怎么也恢复不了。提示认证状态错误。凤凰3个台可以看，其他都不行。而且卸载重装也不行，目前彻底不能用。

如果黑屏显示「认证状态错误」的信息，
不至于以后彻底不能用了，
是需要等待很长很久的时间，可能是10分钟15分钟20分钟，我也不确定时间是多久，
再重新启动软件，电视台的画面声音又恢復正常了。

**Comment by lizongying** [comment]
不建議太快
