### ISSUE TITLE
[FR] 希望可以有自动更新功能

### ISSUE THREAD

**Issue by 01415925** [lizongying/my-tv#766]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

家里老人不会用手机，总点到广告，找不到台。这个软件没有广告，操作也很简单，奶奶很喜欢。但隔三岔五失效，我不在身边，也不能帮她更新。即使收费也好，希望能出一个后台自动更新功能。

### 解决方案

不知道

### 额外信息

无

**Comment by cnaron** [comment]
我也是这种情况，给在老家的爸爸用，这次出了bug我还特意教了怎么下载然后投屏到电视去更新，但是操作太复杂了，我爸没记住。现在也是急切希望能有自动更新的功能，付费也愿意。

**Comment by lijiaoyang** [comment]
现在内置了自动更新但是没成功过，而且我发现一旦有更新的版本出现，老版本就不能用了

**Comment by githubcxg** [comment]
我是盒子上安装远程控制软件，直接帮老人远程更新～

**Comment by HTWMedia** [comment]
可以用下这个：[HTV](https://github.com/HTWMedia/HTV)，不用更新app，没广告。虽然刚进入和切换台的时候可能有点卡，但中央台和卫视台很全。

**Comment by AppleMate60pro** [comment]
> 可以用下这个：[HTV](https://github.com/HTWMedia/HTV)，不用更新app，没广告。虽然刚进入和切换台的时候可能有点卡，但中央台和卫视台很全。

这是什么垃圾app

**Comment by meteorazhuan** [comment]
> 我是盒子上安装远程控制软件，直接帮老人远程更新～

什么软件可以介绍一下吗？同理应该能用到电视上吧？

**Comment by lizongying** [comment]
可以試下最新版的更新功能
