### ISSUE TITLE
[FR] 创建一个插件商店的一个功能

### ISSUE THREAD

**Issue by gonjudaren** [lizongying/my-tv#767]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

1:个性化定制
2:皮肤定制
3:由不同的程序员开发插件去上传插件或皮肤
4:扩展功能：可以获取更多的实用工具和功能插件，满足多样化的需求

### 解决方案

可以参考浏览器crx扩展
可以参考kodi扩展
可以参考tvbox

**Comment by lizongying** [comment]
[我的電視·〇](https://github.com/lizongying/my-tv-0) 後期會考慮加入
