### ISSUE TITLE
索尼电视认证错误

### ISSUE THREAD

**Issue by lvcnbc** [lizongying/my-tv#769]
前几天中午安装的时候是认证错误，就没用。昨晚偶尔打开发现可以正常使用，今天中午打开又是认证错误。

**Comment by lizongying** [comment]
你看下時間，是否正常？

**Comment by lvcnbc** [comment]
设备时间？正常> 你看下時間，是否正常？

**Comment by lvcnbc** [comment]
电视系统时间正常，软件内显示时间正常

**Comment by lvcnbc** [comment]
呃，看完系统时间再打开居然又好了😂

**Comment by byhaoya** [comment]
又认证错误·········索尼电视

**Comment by lizongying** [comment]
這個時間是個問題。
目前是啟動的時候會更新一次，就怕更新完之後，電視自己又同步了時間。
還有一種方式是每隔一段時間就更新一下，或者每次換台的時候更新一下。
麻煩。

**Comment by lvcnbc** [comment]
每隔一段时间更新是指更新软件吗？手动吗？

**Comment by WFANG12719** [comment]
那我把时间显示关掉是不是可以避免？

**Comment by lizongying** [comment]
> 那我把时间显示关掉是不是可以避免？

請求視頻是需要正確時間的，和是否顯示無關。

**Comment by icekale** [comment]
我也是Sony电视，也是认真错误。

**Comment by oldiy** [comment]
电视盒子 也是认证错误 时间没有问题

**Comment by angelance** [comment]
> > 那我把时间显示关掉是不是可以避免？
> 
> 請求視頻是需要正確時間的，和是否顯示無關。

还是认证错误，第一次可以看，换台之后再换回来就不行了。另外香港的三个台是可以看的，其他都是认证状态错误

**Comment by javadodobird** [comment]
如果黑屏显示「认证状态错误」的信息，
不至于以后彻底不能用了，
是需要等待很长很久的时间，可能是10分钟15分钟20分钟，我也不确定时间是多久，
再重新启动my-tv软件，电视台的画面声音又恢復正常了。

**Comment by WFANG12719** [comment]
![image](https://github.com/lizongying/my-tv/assets/87627119/df818c05-1d6b-4a59-8c3d-3e3cb25f9f6a)
![image](https://github.com/lizongying/my-tv/assets/87627119/bcad2762-1c4a-43ec-83f1-b28f81507506)
把机器重启通常可以恢复，不得不用重启大法

**Comment by WFANG12719** [comment]
或者调至凤凰那三个台选一个，又有了。

**Comment by angelance** [comment]
看时间，放一段时间好像可以改善，但是后面偶尔还是会出现，就是目前没有测试出原因。不过我这里不是sony的

**Comment by githubcxg** [comment]
https://www.123pan.com/s/DYn1jv-k2Ryh.html，这里面收藏的一些直播还可以。

**Comment by lizongying** [comment]
#788
