### ISSUE TITLE
[FR] 可否把频道号码4到17号，对应央台的频道号码？

### ISSUE THREAD

**Issue by javadodobird** [lizongying/my-tv#771]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

电视机(安卓系统)，
机顶盒(安卓系统)，
电视盒子(安卓系统)，
投影仪(安卓系统)，
以上设备的遥控器如有实体0至9数字按键，cctv几是什么数字就按遥控器上的什么数字，使用起来方便，不用特别记忆cctv几是my-tv软件的什么数字，老人使用也方便。

### 解决方案

可否把频道号码4到17号，对应央台的频道号码？

现在的号码排列：
3(cctv4)
4(cctv5)
5(cctv7)
6(cctv9)
7(cctv10)
8(cctv11)
9(cctv12)
10(cctv13)
11(cctv14)
12(cctv15)
13(cctv16)
14(cctv17)

对应的号码排列：
4(cctv4)
5(cctv5)
7(cctv7)
9(cctv9)
10(cctv10)
11(cctv11)
12(cctv12)
13(cctv13)
14(cctv14)
15(cctv15)
16(cctv16)
17(cctv17)

电视机(安卓系统)，
机顶盒(安卓系统)，
电视盒子(安卓系统)，
投影仪(安卓系统)，
以上设备的遥控器如有实体0至9数字按键，cctv几是什么数字就按遥控器上的什么数字，使用起来方便，不用特别记忆cctv几是my-tv软件的什么数字，老人使用也方便。

### 额外信息

谢谢作者。

**Comment by taddyboy** [comment]
是个好建议，大神修改应该也不难，也方便更多观众收视习惯

**Comment by ashurajo** [comment]
这个建议好

**Comment by AppleMate60pro** [comment]
这个不要想了，368台没有

**Comment by lizongying** [comment]
之前是這樣的，只是暫時少了些頻道。等我有時間補上就好了。
