### ISSUE TITLE
[FR] 关于不升级不能用的问题

### ISSUE THREAD

**Issue by z1782158860** [lizongying/my-tv#772]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

解决老年人使用问题

### 解决方案

APP检测更新 或者 配置自动更新

### 额外信息

给家里老年人装在电视盒子用的，但是我没办法经常在家，所以每次更新版本后都没法及时升级，老版本就不能用了，老人不会自己下载安装，所以请求能加入检测更新弹窗或者后台自动更新配置。

**Comment by jsaon-L** [comment]
对的,完全同意

**Comment by gmdig** [comment]
附议

**Comment by justn-gpt** [comment]
这个建议非常好。如果能够后台自动强制升级更新，就更好了。后果顶多就是更新时退出一下，老人重新打开就可以了。

**Comment by lizongying** [comment]
> 这个建议非常好。如果能够后台自动强制升级更新，就更好了。后果顶多就是更新时退出一下，老人重新打开就可以了。

高版本是需要安裝權限的，自動更新可能無法實現。

現在的升級功能在測試中。
