### ISSUE TITLE
我按遥控器的上，对应的台数是下降的，不符合直觉[BUG] 

### ISSUE THREAD

**Issue by meihus** [lizongying/my-tv#775]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

我按遥控器的上，对应的台数是下降的，不符合直觉

### 预期行为

按遥控器的上，对应的台数是上升

### 实际行为

按遥控器的上，对应的台数是下降

### UI / OS

TCL

### Android 版本

9

### 额外信息

1

**Comment by 13037639065** [comment]
菜单里可以调，频道反向
