### ISSUE TITLE
认证请求错误[BUG] 

### ISSUE THREAD

**Issue by heyufeng1951** [lizongying/my-tv#776]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

显示认证请求错误，无法观看直播

### 预期行为

显示认证请求错误，无法观看直播

### 实际行为

显示认证请求错误，无法观看直播

### UI / OS

杂牌

### Android 版本

4.4.2

**Comment by javadodobird** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的 bug report。
> * [x]  我正在使用本软件的最新版本。
> 
> ### my-ty 版本
> 通用版
> 
> ### Bug 描述
> 显示认证请求错误，无法观看直播
> 
> ### 预期行为
> 显示认证请求错误，无法观看直播
> 
> ### 实际行为
> 显示认证请求错误，无法观看直播
> 
> ### UI / OS
> 杂牌
> 
> ### Android 版本
> 4.4.2
> 

如果显示「认证请求错误」，
我的经验和办法是：
停止操作my-tv软件，接着退出my-tv软件，

等待大约30分钟（半个小时）时间后，

再次开启my-tv软件，

应该会是各个电视频道画面声音又恢復正常播放了。

**Comment by lizongying** [comment]
本人的手機和電視都是正常的。
你的設備無法獲知原因。
建議使用最新版本，完全清理緩存試試。
