### ISSUE TITLE
[BUG] 平板上网格样式点击空白处不能返回

### ISSUE THREAD

**Issue by Link-ee** [lizongying/my-tv#777]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

网格样式点击频道尾部空白处不能返回播放界面，只能点击例如央视和地方台之间的分隔空白处才能返回播放页面。

### 预期行为

点击任何空白的地方都能返回播放界面

### 实际行为

重复性点击空白处，寻找可以退出频道列表的触摸区域

### UI / OS

XIAOMI

### Android 版本

14

**Comment by lizongying** [comment]
2.0.0 已修復
