### ISSUE TITLE
[FR]  android studio打开项目提示有错误。不知什么原因？请说一下如何导入项目学习

### ISSUE THREAD

**Issue by mikedeng888** [lizongying/my-tv#779]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

[CXX1429] error when building with cmake using D:\googleplayproject\my-tv-1.9.8\app\CMakeLists.txt: -- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/AndroidSDK/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/AndroidSDK/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done

**Comment by winkyz** [comment]
我这里提示 缺少 native.c  不知道如何解决
CMake Error at CMakeLists.txt:17 (add_library):
  Cannot find source file:

    src/main/cpp/native.c

**Comment by lizongying** [comment]
幾種種解決方法：
1. 自己補充native.c 
2. 去掉相關方法，不用native
3. ./gradlew assembleRelease -PIS_SO_BUILD=false 編譯成功，但由於沒有方法實現，請求的時候會失敗。建議使用此種方式，同時可以直接修改視頻地址，以供測試。
