### ISSUE TITLE
logo.png是512x512像素正四方形图片，用windows小画家画了一下「我的电视」这四个字的位置

### ISSUE THREAD

**Issue by javadodobird** [lizongying/my-tv#781]
logo.png是512x512像素正四方形图片，用windows小画家画了一下「我的电视」这四个字的位置，

logo原图片：
![logo](https://github.com/lizongying/my-tv/assets/167096036/8a0f6745-7c3a-42b6-9c4f-03126cd7f6ed)

四区域概念草稿图片：
![fourarealogo](https://github.com/lizongying/my-tv/assets/167096036/82c248cb-920c-4f67-b76d-733b5755f910)

利用这个安卓logo图片是正四方形的特点，而「我的电视」刚好是四个字，这四个字分布在logo图片上左(我)，上右(的)，下左(电)，下右(视)这四片区域。

**Comment by johnnyeecker** [comment]
图二没有居中吧...?

**Comment by lizongying** [comment]
兩行的話，不夠直觀。另外，有些電視圖標是橫幅。

**Comment by javadodobird** [comment]
> 图二没有居中吧...?

是的没有居中，草图大概有个模样看一看。

**Comment by javadodobird** [comment]
> 兩行的話，不夠直觀。另外，有些電視圖標是橫幅。

原来是这样。

**Comment by Lanmon94** [comment]
我觉得这个图标就是直接TV俩字，简单挺好
