### ISSUE TITLE
今天下午开始中央台和地方台没看15分钟左右就会卡顿画面停止声音停止，过10秒后会继续播放

### ISSUE THREAD

**Issue by runing25mins** [lizongying/my-tv#782]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

今天下午开始中央台和地方台没看15分钟左右就会卡顿画面停止声音停止，过10秒后会继续播放

### 预期行为

don't know

### 实际行为

don't know

### UI / OS

小米电视

### Android 版本

14

**Comment by keeplz** [comment]
+1

**Comment by Dachongzi8** [comment]
+1

**Comment by akinaedison** [comment]
+1

**Comment by alagants** [comment]
确实如此，朝闻天下伊卡伊卡

**Comment by NI-Enrique** [comment]
+1

**Comment by lizongying** [comment]
2.0.0 已修復
