### ISSUE TITLE
【芝杜 Zidoo Z9X】认证请求错误[BUG] 

### ISSUE THREAD

**Issue by myzhuyue** [lizongying/my-tv#783]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

设备：芝杜 Zidoo Z9X
芝杜软件版本：v6.4.42
Android 版本：9
从U盘安装好 My- TV 1.9.8版本之后，打开软件显示“认证请求错误”；

### 预期行为

正常浏览各频道

### 实际行为

页面黑色底色，有错误提示：“认证请求错误”。

### 复现步骤

打开My-TV就会显示

### UI / OS

芝杜 Zidoo Z9X v6.4.42

### Android 版本

9

### 额外信息

辛苦大佬看一下这个问题，我全力配合测试。

**Comment by javadodobird** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的 bug report。
> * [x]  我正在使用本软件的最新版本。
> 
> ### my-ty 版本
> 通用版
> 
> ### Bug 描述
> 设备：芝杜 Zidoo Z9X 芝杜软件版本：v6.4.42 Android 版本：9 从U盘安装好 My- TV 1.9.8版本之后，打开软件显示“认证请求错误”；
> 
> ### 预期行为
> 正常浏览各频道
> 
> ### 实际行为
> 页面黑色底色，有错误提示：“认证请求错误”。
> 
> ### 复现步骤
> 打开My-TV就会显示
> 
> ### UI / OS
> 芝杜 Zidoo Z9X v6.4.42
> 
> ### Android 版本
> 9
> 
> ### 额外信息
> 辛苦大佬看一下这个问题，我全力配合测试。

黑屏画面上显示「认证请求错误」或者「认证狀态错误」信息后，

我不是作者，我的经验和4个办法是以下：

（1）停止操作my-tv软件，

（2）退出my-tv软件，

（3）不需要停止操作my-tv软件，

（4）不需要退出my-tv软件，

上述4个办法都可以，

反正总之就是大约30分钟（半个小时）时间后，

再次重用，或者重启my-tv软件，

应该会是各个电视频道画面声音又恢復正常播放了。

**Comment by myzhuyue** [comment]
我试试

**Comment by myzhuyue** [comment]
Tested and resolved. Appreciated!
