### ISSUE TITLE
[FR] 考虑支持回看电视节目？

### ISSUE THREAD

**Issue by melin** [lizongying/my-tv#786]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

错过时间点，方便回看电视节目，

**Comment by winkyz** [comment]
支持回看就别想了， 弄个节目清单时刻表， 倒还是可行的

**Comment by lizongying** [comment]
這個功能可能在[我的電視·〇](https://github.com/lizongying/my-tv-0)上實現，我的電視暫無計劃。
