### ISSUE TITLE
点检查更新没反应，而且画面会卡住

### ISSUE THREAD

**Issue by ZGsyw** [lizongying/my-tv#787]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

点检查更新没反应，画面卡死，需要重新切换频道！

### 预期行为

无

### 实际行为

无

### 复现步骤

点检查更新！

### UI / OS

华为

### Android 版本

鸿蒙

**Comment by kiben2010** [comment]
同样 这个发布新版 测试1.9.8的自动更新功能无法正常更新

**Comment by kiben2010** [comment]
我这里检查更新会检查出来2.0.0版本 但是点了更新就没反应。

**Comment by akinaedison** [comment]
+1

**Comment by gc89925** [comment]
不管哪个版本，我的自动更新从来没成功过，盒子用的神盾TV和当贝盒子MAX1，家里网络都是配置好自动过墙的，这个问题解决了，就不用每次远程给家里老人升级了

**Comment by dongbao66** [comment]
> 不管哪个版本，我的自动更新从来没成功过，盒子用的神盾TV和当贝盒子MAX1，家里网络都是配置好自动过墙的，这个问题解决了，就不用每次远程给家里老人升级了

怎么远程升级 求教

**Comment by ZGsyw** [comment]
我用的斐讯N1盒子，在线升级也没成功过！这app存在的问题蛮多的，不是很稳定，用一段时间就会出现这样.那样的问题，希望开发者能尽可能的修复bus!

dongbao66 ***@***.***> 于 2024年5月19日周日 10:36写道：
