### ISSUE TITLE
兄弟,认证状态错误 怎么解决

### ISSUE THREAD

**Issue by StevenCoober** [lizongying/my-tv#788]

**Comment by javadodobird** [comment]
> _No description provided._

黑屏画面上显示「认证请求错误」或者「认证狀态错误」信息后，

我的经验和4个方法是以下：

（•）无需停止操作my-tv软件；

（•）无需退出my-tv软件；

（•）停止操作my-tv软件；

（•）退出my-tv软件；

上述4个方法都可以，

反正总之就是大约30分钟（半个小时）时间后，

再次重用，或者是重启my-tv软件，

应该会是各个电视频道画面声音又恢復正常播放了。

**Comment by lizongying** [comment]
我這是正常的，你可以試試清理下緩存一類試試。盡量使用最新版本。還不行就沒辦法了。不能確定原因。
