### ISSUE TITLE
[FR] 可以提供上海频道么？五星体育？

### ISSUE THREAD

**Issue by akinaedison** [lizongying/my-tv#789]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

看F1

**Comment by javadodobird** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的功能请求。
> * [x]  这个建议不会背离 my-tv 的初衷。
> 
> ### 改进目的
> 看F1
> 
> ### 解决方案
> _No response_
> 
> ### 额外信息
> _No response_

我猜「上海五星体育」要有"稳定的官方源"作者才会考虑提供。

**Comment by lizongying** [comment]
#893
