### ISSUE TITLE
有计划优化界面做成类似iptv吗？

### ISSUE THREAD

**Issue by eaudouce** [lizongying/my-tv#79]
频道越来越多了，现在选台，经常是滑动一会儿菜单就自动隐藏，还要重新再来。请问有计划优化界面做成类似iptv的吗？这样选台方便些。

![11356677662594](https://github.com/lizongying/my-tv/assets/8295487/d806de4c-7127-41ce-ad16-60c41916c279)

**Comment by liqiangsky** [comment]
> 频道越来越多了，现在选台，经常是滑动一会儿菜单就自动隐藏，还要重新再来。请问有计划优化界面做成类似iptv的吗？这样选台方便些。
> 
> ![11356677662594](https://private-user-images.githubusercontent.com/8295487/297239179-d806de4c-7127-41ce-ad16-60c41916c279.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTkxNzgsIm5iZiI6MTcwNTQ1ODg3OCwicGF0aCI6Ii84Mjk1NDg3LzI5NzIzOTE3OS1kODA2ZGU0Yy03MTI3LTQxY2UtYWQxNi02MGM0MTkxNmMyNzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTdUMDIzNDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzExM2I0NTZjMTZmYzk1ZGFiMTU2MTRlOTI0NjUxZmU3YTZiYjI2NGFjMTMxOTYxOWZlNzI5NWMxOWNjOGRhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kJwVi-4kD3zOZzFxP6vD6V0cjdOtPg8jU78YrER4RtM)

个人认为目前这个还是挺好看的，但频道多起来确实选的比较费力，看看后期大佬有没有什么优化吧

**Comment by huifei0129** [comment]
截图是哪个软件？可否分享，如果有直播源，也一并分享

**Comment by eaudouce** [comment]
> 截图是哪个软件？可否分享，如果有直播源，也一并分享

小酷直播，广告台很多，没有源。
下载地址：
https://www.magicalapk.com/appview?id=1704778888745

**Comment by lizongying** [comment]
暂无计划。
“滑动一会儿菜单就自动隐藏”可能是手机上的问题，暂时先不处理了，因为主要目标是电视，遥控器操作，是没有这个问题的。
另外，频道会增加但也不会增加太多，还不至于增加太多栏目。
目前的样式，还有优化空间。
