### ISSUE TITLE
[BUG] 魔百盒型号： ZTE ZXV10 B860AV2.1，运行 v2.0.5 ~ v2.0.8版本， 认证请求错误的问题。

### ISSUE THREAD

**Issue by winkyz** [lizongying/my-tv#791]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

安装完成后，启动app， 换台可显示正下方台标，按键有相应。 播放区显示"认证请求错误"，凤凰三台显示“请求错误"。等待右上角系统时间更新后，选择凤凰三台可正常观看， 切换至大陆各台，闪退。重启保持闪退或黑屏

### 预期行为

N/A

### 实际行为

N/A

### 复现步骤

N/A

### UI / OS

ZTE ZXV10 B860AV2.1

### Android 版本

N/A

**Comment by winkyz** [comment]
> 我记得 中兴的机顶盒 特别难打开 adb，你该不会是刷了第三方固件的吧？

刷了当贝桌面

**Comment by 1457384613gh** [comment]
第三方固件一般都有 root 权限的。
你该不会为了自启权限而推送到 系统分区里了吧？
推送到系统分区里一般是闪退的。

**Comment by lizongying** [comment]
#896
