### ISSUE TITLE
最新版，部分频道还是显示其他错误！

### ISSUE THREAD

**Issue by ZGsyw** [lizongying/my-tv#795]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

切换频道，部分频道还是显示其他错误！

### 预期行为

无

### 实际行为

无

### UI / OS

华为

### Android 版本

鸿蒙

**Comment by lizongying** [comment]
最好說下哪個頻道，我看都是正常的
