### ISSUE TITLE
[FR] 慈济大爱 

### ISSUE THREAD

**Issue by AiryXu** [lizongying/my-tv#796]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

慈济大爱1,https://pulltv1.wanfudaluye.com/live/tv1.m3u8
慈济大爱2,https://pulltv2.wanfudaluye.com/live/tv2.m3u8

**Comment by lizongying** [comment]
可以使用我的電視·〇
