### ISSUE TITLE
服了，至今都没有一个可以稳定使用的版本，不懂为什么在网上被称为神器？

### ISSUE THREAD

**Issue by 4yt1k** [lizongying/my-tv#797]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

错误。..................

### 预期行为

没有预期了

### 实际行为

错误。.................

### 复现步骤

打开就出现

### UI / OS

xiaomi

### Android 版本

xiaomi unknow

### 额外信息

可以功能简单，可以频道不全，但至少得可以正常播放吧？
这几个月发布了怕超过20个版本了吧？最好的情况就是能用几天，有的干脆刚发布就不能用！！
不懂这样的APP，何以让人吹成神器的？？？

向各位推荐极悦直播、太阳直播，干净、稳定无广告，而且频道齐全。
My-TV我是彻底受不了啦

**Comment by jintao16** [comment]
又没收你的钱，咋这么激动。 我觉得挺好，不能看是广电的封杀，又不是开发者故意搞坏的，发火发错地方了。

**Comment by mangwei** [comment]
> 又没收你的钱，咋这么激动。 我觉得挺好，不能看是广电的封杀，又不是开发者故意搞坏的，发火发错地方了。

在线更新功能你们能用吗？

**Comment by tangqiu0205** [comment]
> > 又没收你的钱，咋这么激动。 我觉得挺好，不能看是广电的封杀，又不是开发者故意搞坏的，发火发错地方了。
> 
> 在线更新功能你们能用吗？

一直不能

**Comment by luweitu** [comment]
是这样的，说神器的都是下载安装使用不超过两个小时的年轻人，试用觉得很满意就不负责任的到处推荐，然后自己可能一个星期都不会打开一次看电视。
但凡真的是给家里老人用的，早就放弃这个app项目了，宁可有广告台，宁可不是高清源，只要能稳定播放使用，“电视家”就是最好的例子。
谢谢 @4yt1k 推荐的app，其实还有很多优秀的直播app，稍微动手找找会发现更好的，毕竟这个项目是个人开发的，属于“个人爱好”类的项目，用爱发电也不容易，就看能坚持多久。
其实我也早就想BB两句，但是看看issues里的活跃度和bug反馈，越来越不忍心吐槽，不能稳定使用的再多附加功能都是白搭。

**Comment by ashsteins** [comment]
是这样的，说神器的都是下载安装使用不超过两个小时的年轻人，试用觉得很满意就不负责任的到处推荐，然后自己可能一个星期都不会打开一次看电视。
但凡真的是给家里老人用的，早就放弃这个app项目了，宁可有广告台，宁可不是高清源，只要能稳定播放使用，“电视家”就是最好的例子。.
