### ISSUE TITLE
[FR]给长辈使用，推荐使用 jsdelivr的cdn加速github。希望拥有后台自动更新视频源的功能，即使长辈不会升级app也不至于不能用。

### ISSUE THREAD

**Issue by DLGum** [lizongying/my-tv#799]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

希望本人不在家，长辈也可以无缝省心使用。

### 解决方案

普通用户不懂技术。
如果使用的是m3u8的iptv源，希望可以后台自动更新视频源。这样长辈不会升级app也不至于用不了。推荐使用jsdelivr的cdn加速github。

如果能自动更新稳定版app就更好了。使用自己搞的加速的话可能被炸。推荐使用gitee复制本项目/只提供下载，或者使用jsdelivr的cdn加速github。

**Comment by lizongying** [comment]
有我的電視·〇
