### ISSUE TITLE
[FR] 向各位推荐极悦直播，给长辈用，这个隔几天就需要手动更新实在无法给家里人用了

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#800]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

[FR] 向各位推荐极悦直播，给长辈用，这个隔几天就需要手动更新实在无法给家里人用了

**Comment by gufunhua** [comment]
这个清晰度还可以，是否可以考虑搞个自动热更新的方案
