### ISSUE TITLE
可否把CHC动作电影和CHC家庭影院这2个频道也增添上？[FR

### ISSUE THREAD

**Issue by Adjang** [lizongying/my-tv#801]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

手机上不仅能看电视，也能看一下电影频道的电影

### 解决方案

N/A

### 额外信息

N/A

**Comment by javadodobird** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的功能请求。
> * [x]  这个建议不会背离 my-tv 的初衷。
> 
> ### 改进目的
> 手机上不仅能看电视，也能看一下电影频道的电影
> 
> ### 解决方案
> N/A
> 
> ### 额外信息
> N/A

CHC动作电影和CHC家庭影院，
这2个频道有没有「官方源」？
如果有，请提供，我猜作者会考虑，
如果没有，我猜作者是不可能增添的。

**Comment by Adjang** [comment]
这只是个人的一个期望而已，希望能够实现！
但是我个人没有官方源啊，用作者的tv有一段时间了，也不断地在更新tv的版本。
希望作者能有官方源吧，没有也确实没有办法啦！

**Comment by Adjang** [comment]
另外，我看作者的更新日志TODO里面描述了”CHC高清三个电影频道“，是不是作者本身也有这个计划？

**Comment by laoyidianyu** [comment]
这个问题提过好几次了，应该是无法添加。

**Comment by lizongying** [comment]
可以嘗試使用[我的電視·〇](https://github.com/lizongying/my-tv-0)
