### ISSUE TITLE
假如能够增加一个汕头综合频道给老人家，my-tv一定是这个世界上最伟大的项目[FR] 

### ISSUE THREAD

**Issue by linchw3** [lizongying/my-tv#803]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

中央台和卫视台很多iptv开源项目可以解决，但很多老人家看的都是地方台，需求和已有解决方案不match. 增加汕头综合频道，可以极大增加该项目在潮汕地区的幸福感，解决实际问题

### 解决方案

增加汕头台和其他更多的地方台的源

**Comment by javadodobird** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的功能请求。
> * [x]  这个建议不会背离 my-tv 的初衷。
> 
> ### 改进目的
> 中央台和卫视台很多iptv开源项目可以解决，但很多老人家看的都是地方台，需求和已有解决方案不match. 增加汕头综合频道，可以极大增加该项目在潮汕地区的幸福感，解决实际问题
> 
> ### 解决方案
> 增加汕头台和其他更多的地方台的源
> 
> ### 额外信息
> _No response_

我不是作者，但请提供「汕头综合频道」的「官方源」，才会有增加的可能。

**Comment by ccav14** [comment]
https://github.com/lizongying/my-tv-0
https://github.com/lizongying/my-tv-1

地方频道自己弄
