### ISSUE TITLE
希望增加一个阶段性长期稳定的版本 不然的话你一直更新旧的版本就无法使用[BUG] 

### ISSUE THREAD

**Issue by itming001** [lizongying/my-tv#805]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

希望增加一个阶段性长期稳定的版本 不然的话你一直更新就得版本就无法使用

### 预期行为

新版本升级不会影响老版本的使用

### 实际行为

新版本升级 影响老版本不能使用

### UI / OS

OS

### Android 版本

12

**Comment by ashsteins** [comment]
主要是信号源经常失效，可以参考下灵犀直播它们咋弄的

**Comment by grasscase** [comment]
宝盒tv很多，非常多台，只是打开慢一点。

**Comment by lmk123568** [comment]
免费白嫖，我觉得很满意了，无非就是手动更新一下app，问题真多个个跟大爷一样

**Comment by ipodgoog** [comment]
觉得人多就失效

**Comment by mmabluesky** [comment]
能免费用，就bb了 ，作者用爱发电，能用就已经很满足了

**Comment by lmk123568** [comment]
> 免费白嫖，我觉得很满意了，无非就是手动更新一下app，问题真多个个跟大爷一样

喷我的，先给作者支持10块钱，再来bb，比我钱多在说话

**Comment by shengmenghui** [comment]
为什么不能把自动更新的地址换成gitee呢？

**Comment by lizongying** [comment]
舊版本無法使用和新版本無關

**Comment by ixxxix** [comment]
> 免费白嫖，我觉得很满意了，无非就是手动更新一下app，问题真多个个跟大爷一样

热更新也不是什么高难度技术，有意见当然要提，这样搞何尝不是作者白嫖大家的测试时间
