### ISSUE TITLE
[本地频道] 

### ISSUE THREAD

**Issue by mengzeyu666** [lizongying/my-tv#806]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

小而精确实言之在理，但是相信每个地区的使用者除了这几个主要的频道，最关心的就是自己所在地区的频道。这也是一代人的习惯吧，也是是他们的关注焦点

**Comment by lizongying** [comment]
我的電視暫時停止更新，有相關需求可以嘗試下 [我的電視·〇](https://github.com/lizongying/my-tv-0)
