### ISSUE TITLE
不明白为什么要做成选频道的 3 秒时长，很不合理啊。有改进的打算吗？

### ISSUE THREAD

**Issue by zqdalianchina** [lizongying/my-tv#81]

**Comment by lizongying** [comment]
现在是4秒。在电视上操作感觉还可以。

**Comment by zanzhz1101** [comment]
my-tv/app/src/main/java/com/lizongying/mytv/MainActivity.kt private 把val delay: Long = 4000改小就行

**Comment by zanzhz1101** [comment]
> _No description provided._

my-tv/app/src/main/java/com/lizongying/mytv/MainActivity.kt private 把val delay: Long = 4000改小就行
