### ISSUE TITLE
增加个人添加节目源接口[FR] 

### ISSUE THREAD

**Issue by 18690819111** [lizongying/my-tv#812]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

丰富个人可玩性，可看性，

### 解决方案

增加个人添加节目源接口

### 额外信息

我自己抓了本地的iptv的源，单播转了组播。（奈何本地带宽有限，只能个人使用），如果增加了添加个人节目源的接口就大大的怎个加了可玩性，可看性。

**Comment by liqiangsky** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的功能请求。
> * [x]  这个建议不会背离 my-tv 的初衷。
> 
> ### 改进目的
> 丰富个人可玩性，可看性，
> 
> ### 解决方案
> 增加个人添加节目源接口
> 
> ### 额外信息
> 我自己抓了本地的iptv的源，单播转了组播。（奈何本地带宽有限，只能个人使用），如果增加了添加个人节目源的接口就大大的怎个加了可玩性，可看性。

可以看看作者的我的电视•O，和我的电视•一这两个项目

**Comment by lizongying** [comment]
我的電視暫時停止更新，有相關需求可以嘗試下 [我的電視·〇](https://github.com/lizongying/my-tv-0)
