### ISSUE TITLE
这个网站的直播源好多， 不知道能否转成m3u8 [FR] 

### ISSUE THREAD

**Issue by cguo2013** [lizongying/my-tv#814]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

如题， 目前my tv 软件内置直播源有很多遗漏。丰富直播源方能让软件更加大众化
123iptv.tv

**Comment by 743859910** [comment]
这个也是 IPTV 直播源: https://www.cnblogs.com/xxy002/p/17858312.html

**Comment by zhascg** [comment]
别来这打广告，恶心

**Comment by lizongying** [comment]
#893
