### ISSUE TITLE
[FR] 能否把CCTV3,CCTV6,CCTV8加入我的电视源中

### ISSUE THREAD

**Issue by wuwei888** [lizongying/my-tv#815]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

我的电视中CCTV不全，希望能加入CCTV3,CCTV6,CCTV8这三个频道

### 解决方案

不知道这三个电视源地址能否置入到我的电视中
CCTV3:https://tv.cctv.com/live/cctv3/?spm=C28340.PTEkg7XmjUgN.ExidtyEJcS5K.3
CCTV6:https://tv.cctv.com/live/cctv6/?spm=C28340.PKIUk5AmVMT8.ExidtyEJcS5K.18
CCTV8:https://tv.cctv.com/live/cctv8/?spm=C28340.PKIUk5AmVMT8.ExidtyEJcS5K.20

**Comment by jrffrj** [comment]
CCTV网站的视频流加密了的，需要播放器解码

**Comment by genshinash** [comment]
368建议引入灵犀直播的源，目前他们家解密

**Comment by lizongying** [comment]
#893
