### ISSUE TITLE
加密 

### ISSUE THREAD

**Issue by TrueloveSomeGIRl** [lizongying/my-tv#82]
大佬请问下 代码里面涉及到的加密 如何脱离so 就纯用java 代码加密 是该 用什么加密方式呀 想把这个源写到我的电视app里面 请赐教

**Comment by lizongying** [comment]
如果了解了加密方法，改起来不难。但不好完全放出来，传播这个还是有点风险的。如果不太熟悉这方面，建议还是用其他源。
