### ISSUE TITLE
[BUG] 除了凤凰台其台都显示“认证状态错误”无法观看

### ISSUE THREAD

**Issue by runing25mins** [lizongying/my-tv#821]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

除了凤凰台其台都显示“认证状态错误”无法观看

### 预期行为

N/A

### 实际行为

N/A

### UI / OS

小米电视

### Android 版本

14

**Comment by WFANG12719** [comment]
![image](https://github.com/lizongying/my-tv/assets/87627119/ddee9a2a-1ac3-4304-b80d-1eda635db8e5)
![image](https://github.com/lizongying/my-tv/assets/87627119/aa55bb80-be53-495e-b191-5008b190fac9)
![image](https://github.com/lizongying/my-tv/assets/87627119/6f24d8f2-490f-4220-9aac-19635d7510b1)
![image](https://github.com/lizongying/my-tv/assets/87627119/bd8ddf78-46ea-45d7-aa77-4734d97b4cdb)
![image](https://github.com/lizongying/my-tv/assets/87627119/b5031a7e-7697-4238-bc6f-b0d5687022a5)
这回重启也不管用了。

**Comment by javadodobird** [comment]
> ![image](https://private-user-images.githubusercontent.com/87627119/335410113-ddee9a2a-1ac3-4304-b80d-1eda635db8e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMTY1MTgsIm5iZiI6MTcxNzExNjIxOCwicGF0aCI6Ii84NzYyNzExOS8zMzU0MTAxMTMtZGRlZTlhMmEtMWFjMy00MzA0LWI4MGQtMWVkYTYzNWRiOGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAwNDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNWFmOGYxZTk0MTc5NjE0NzY3NTA5MzcxMTAyYjYxYmVjNDgzMmQ0NGQ4OTRiMzc3MGJiZTQ2ZmI5MTYxYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p08SknWTnRgmdf3OtrFRFZTlAoya2iUVCHtxEzgdoBk) ![image](https://private-user-images.githubusercontent.com/87627119/335410128-aa55bb80-be53-495e-b191-5008b190fac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMTY1MTgsIm5iZiI6MTcxNzExNjIxOCwicGF0aCI6Ii84NzYyNzExOS8zMzU0MTAxMjgtYWE1NWJiODAtYmU1My00OTVlLWIxOTEtNTAwOGIxOTBmYWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAwNDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MmQ3NTA5M2ZmYTJhNTUwYzFjNTc2NDk0YjI0YmRhYTNhNTZmYWVmZTg1MWNiYWI0OWJkMThlZmEwMDFlNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Na5q5kzwAZrbi3_jXFY1GhUVJ3iqB9b802-1e4BFQ2w) ![image](https://private-user-images.githubusercontent.com/87627119/335410139-6f24d8f2-490f-4220-9aac-19635d7510b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMTY1MTgsIm5iZiI6MTcxNzExNjIxOCwicGF0aCI6Ii84NzYyNzExOS8zMzU0MTAxMzktNmYyNGQ4ZjItNDkwZi00MjIwLTlhYWMtMTk2MzVkNzUxMGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAwNDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxOWJiZmE1YWRhZTM0NWU1ZDZkMjg5ZjlhMWU3Mjg0NWI0MDZkNDRlNTE2ZDQxMTQ0YTQ1NmMyNGM1YmU2ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NxkN78d3G52VL8Qg7SMls9u044XN3kM-qN1e9h6DqF0) ![image](https://private-user-images.githubusercontent.com/87627119/335410154-bd8ddf78-46ea-45d7-aa77-4734d97b4cdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMTY1MTgsIm5iZiI6MTcxNzExNjIxOCwicGF0aCI6Ii84NzYyNzExOS8zMzU0MTAxNTQtYmQ4ZGRmNzgtNDZlYS00NWQ3LWFhNzctNDczNGQ5N2I0Y2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAwNDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NjAyOWIzN2Q1NTc0YThlNmRmZGUyYTdiZDYyODMwNWFmMjQxYWU3Nzg5ZmE2ZGYzNTVmM2E4MTRmOGIzMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.emqtOgY7dvt8VHMit_e1ZWFIJhh8f7r7Ko4OeUfm0sU) ![image](https://private-user-images.githubusercontent.com/87627119/335410172-b5031a7e-7697-4238-bc6f-b0d5687022a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMTY1MTgsIm5iZiI6MTcxNzExNjIxOCwicGF0aCI6Ii84NzYyNzExOS8zMzU0MTAxNzItYjUwMzFhN2UtNzY5Ny00MjM4LWJjNmYtYjBkNTY4NzAyMmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAwNDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZGNmZGU1MTY2NDE3ZGU5ZDY0ZmY3ZDFmZDU3Y2M1YzJiM2JlYWNhMTFhNDQwNjM4ZTFhMDA2MTYwMDc5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CCAKSYmAUK-5N1_b07GME46hmfEt0wZkm__bp9r_SVE) 这回重启也不管用了。




可能是某个环节又崩溃了，

或者可能是又被某机构反制了，

现在只能等待了。

**Comment by taddyboy** [comment]
大神快点修复

**Comment by akinaedison** [comment]
➕1

**Comment by godfox2012** [comment]
+1

**Comment by Ahuage98** [comment]
**+1**

**Comment by liusl104** [comment]
+1

**Comment by soberGou** [comment]
+1

**Comment by cgj8534** [comment]
+1

**Comment by WFANG12719** [comment]
吃饭前来看看，果然发版了。这响应，杠杠滴。

**Comment by Mas0n1** [comment]
笑死了 你们也太快了👍🏻

**Comment by liusl104** [comment]
现在又不行了

**Comment by xinpenghan** [comment]
还是无法使用

**Comment by lizongying** [comment]
#834
