### ISSUE TITLE
[FR] 自动更新地址能否手动配置github或gitee，默认github部分地区网络访问不到

### ISSUE THREAD

**Issue by soberGou** [lizongying/my-tv#822]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

便于更多人可以使用自动更新功能

**Comment by taddyboy** [comment]
是啊，在电视上更新功能根本没法更新

**Comment by love19791126** [comment]
就自动更新过一次 后来怎么点都没有反应

**Comment by a347808713** [comment]
+1 挂代理不方便

**Comment by sypiao97** [comment]
附议，父母不会挂代理，能否给一个切换到gitee的选项

**Comment by Sakurainy** [comment]
我有挂代理，但是在线更新也没起效果

**Comment by sobergou** [comment]
> 我有挂代理，但是在线更新也没起效果

我计划写个安卓应用就做自动更新的事情

**Comment by DMB-codegang** [comment]
主要问题就是年轻人现在都不看电视，都是在父母要求下给父母搭建的，使用github更新对于父母辈来说不是很方便。希望作者可以优化一下

**Comment by Marblog** [comment]
+1

**Comment by sobergou** [comment]
https://github.com/lizongying/my-tv/pull/842    提交了patch

**Comment by sobergou** [comment]
> 我有挂代理，但是在线更新也没起效果

看了代码，不是网络问题，是权限获取问题，做了优化patch #842
