### ISSUE TITLE
[BUG] 2.1.1在电视上面能打开，在机顶盒上面闪退

### ISSUE THREAD

**Issue by psumycom** [lizongying/my-tv#824]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

2.1.0在电视上面能打开，在机顶盒上面打不开，点击后没有任何反映也不弹出任何画面

### 预期行为

希望能解决这个问题

### 实际行为

希望能解决这个问题

### UI / OS

网络机顶盒

### Android 版本

9

**Comment by zyorai** [comment]
直接闪退

**Comment by psumycom** [comment]
2.1.1在机顶盒上面打开还是闪退

**Comment by psumycom** [comment]
老大可以研究一下为什么在机顶盒上面闪退吗？家里的电视安装不了软件只能安装在机顶盒上面看，愁人

**Comment by psumycom** [comment]
耐心等待老大修复中。。。

**Comment by psumycom** [comment]
一直没解决，不等了
