### ISSUE TITLE
[BUG] “状态错误”

### ISSUE THREAD

**Issue by xqpeter** [lizongying/my-tv#825]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

除了凤凰卫视，其它台都报“状态错误”，无法观看

### 预期行为

显示频道内容

### 实际行为

显示“状态错误”

### UI / OS

TCL

### Android 版本

12

**Comment by love19791126** [comment]
同样错误

**Comment by sjditadmin** [comment]
手机上安装，同样的"状态错误"

**Comment by 3493129790** [comment]
+1

**Comment by AndyXu3000** [comment]
+1

**Comment by deseking** [comment]
同样错误，2.1版本

**Comment by Dachongzi8** [comment]
新版挂的太快了

**Comment by baoder** [comment]
同样的问题

**Comment by lizongying** [comment]
#834
