### ISSUE TITLE
显示状态错误

### ISSUE THREAD

**Issue by yishan2019** [lizongying/my-tv#828]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

显示状态错误

### 预期行为

显示状态错误

### 实际行为

显示状态错误

### 复现步骤

显示状态错误

### UI / OS

MAX96

### Android 版本

12

**Comment by adamzyg** [comment]
我也是这个问题，Hisense电视

**Comment by a1266143** [comment]
我也是这个问题，小米手机

**Comment by Zizhi-Huang** [comment]
荣耀智慧屏，小米电视也一样

**Comment by yfr1002** [comment]
chromcast也一样

**Comment by gavinmeng822** [comment]
刚更新到最新版本.依然显示错误播放不了.

**Comment by gavinmeng822** [comment]
这个My Tv很干净.没什么乱七八糟功能.界面也清爽舒服.我也在用别的APP直播备用.但是没有一个像这个这样更新这么频繁而且崩的这么快。。。。为什么一个月更新无数次？是基于什么考虑吗？别的APP一两个月没更新也能正常看啊.继续支持

**Comment by Eessme** [comment]
sony也是显示错误

**Comment by wxupjack** [comment]
vivo手机 originos4 显示错误

**Comment by econwang** [comment]
> 这个My Tv很干净.没什么乱七八糟功能.界面也清爽舒服.我也在用别的APP直播备用.但是没有一个像这个这样更新这么频繁而且崩的这么快。。。。为什么一个月更新无数次？是基于什么考虑吗？别的APP一两个月没更新也能正常看啊.继续支持

用的源不同，没发现这个app能用的时候播放从没卡顿问题吗？作者的这个思路很牛，就是经常要应对反爬

**Comment by wendaoshu** [comment]
> 这个My Tv很干净.没什么乱七八糟功能.界面也清爽舒服.我也在用别的APP直播备用.但是没有一个像这个这样更新这么频繁而且崩的这么快。。。。为什么一个月更新无数次？是基于什么考虑吗？别的APP一两个月没更新也能正常看啊.继续支持

有啥备用的推荐的吗

**Comment by akinLiu** [comment]
+1

**Comment by AppleMate60pro** [comment]
> 这个My Tv很干净.没什么乱七八糟功能.界面也清爽舒服.我也在用别的APP直播备用.但是没有一个像这个这样更新这么频繁而且崩的这么快。。。。为什么一个月更新无数次？是基于什么考虑吗？别的APP一两个月没更新也能正常看啊.继续支持
别抱怨这些，人家本来就是写来玩玩，源又不是作者自己的，人家也不是专门搞这个，白嫖的东西还叽叽哇哇的，真把人家当黑奴隶

**Comment by AppleMate60pro** [comment]
> > 这个My Tv很干净.没什么乱七八糟功能.界面也清爽舒服.我也在用别的APP直播备用.但是没有一个像这个这样更新这么频繁而且崩的这么快。。。。为什么一个月更新无数次？是基于什么考虑吗？别的APP一两个月没更新也能正常看啊.继续支持
> 
> 有啥备用的推荐的吗

小薇纯净版

**Comment by AppleMate60pro** [comment]
> > 这个My Tv很干净.没什么乱七八糟功能.界面也清爽舒服.我也在用别的APP直播备用.但是没有一个像这个这样更新这么频繁而且崩的这么快。。。。为什么一个月更新无数次？是基于什么考虑吗？别的APP一两个月没更新也能正常看啊.继续支持
> 
> 用的源不同，没发现这个app能用的时候播放从没卡顿问题吗？作者的这个思路很牛，就是经常要应对反爬

是要经常去爬源，央视频加密又升级

**Comment by sobergou** [comment]
+1

**Comment by snowie2000** [comment]
> > 这个My Tv很干净.没什么乱七八糟功能.界面也清爽舒服.我也在用别的APP直播备用.但是没有一个像这个这样更新这么频繁而且崩的这么快。。。。为什么一个月更新无数次？是基于什么考虑吗？别的APP一两个月没更新也能正常看啊.继续支持
> 
> 用的源不同，没发现这个app能用的时候播放从没卡顿问题吗？作者的这个思路很牛，就是经常要应对反爬

作者并没有任何反爬，因为作者本身没有提供任何源。整个软件都是逆向了央视频的加密而创造的，一旦央视频的加密修改了，这个软件就会失效。最近央视频一直在改加密，所以这个软件就会不停的失效，必须跟进加密才行

**Comment by lizongying** [comment]
#834

**Comment by AppleMate60pro** [comment]
> > > 这个My Tv很干净.没什么乱七八糟功能.界面也清爽舒服.我也在用别的APP直播备用.但是没有一个像这个这样更新这么频繁而且崩的这么快。。。。为什么一个月更新无数次？是基于什么考虑吗？别的APP一两个月没更新也能正常看啊.继续支持
> > 
> > 
> > 用的源不同，没发现这个app能用的时候播放从没卡顿问题吗？作者的这个思路很牛，就是经常要应对反爬
> 
> 作者并没有任何反爬，因为作者本身没有提供任何源。整个软件都是逆向了央视频的加密而创造的，一旦央视频的加密修改了，这个软件就会失效。最近央视频一直在改加密，所以这个软件就会不停的失效，必须跟进加密才行

没得办法的事，就是不想你们安稳看电视
