### ISSUE TITLE
[FR] 没事能不能别更新了

### ISSUE THREAD

**Issue by ixxxix** [lizongying/my-tv#829]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

看得好好的隔几天又更新，还得手动更新，更新频率比win10还频繁，到底有什么功能是更新之后旧版不能继续的用，能不能让人好好看电视，更新时间比看电视时间还多

**Comment by jrffrj** [comment]
你如果可以让央视频网站不要更新，这软件就能一直用。最近央视频网站更新太频繁了，一天两更

**Comment by javadodobird** [comment]
应该是my-tv现在越来越出名了，越来越多人在使用了，

从而导致某平台每天进进出出的网络流量超级多超极巨大超极负荷超极拥挤了，

my-tv应该是早早就被某机构盯上了，所以现在某平台是越来越加強反制力度了。

**Comment by tasty007** [comment]
你不用 就不会更新,
给你免费使用了,
还JJYY?
