### ISSUE TITLE
1.4.4 数字切台bug反馈

### ISSUE THREAD

**Issue by Rekoe** [lizongying/my-tv#83]
在中兴862 晨星安卓9 最新版本1.4.4 数字切台 右上角显示数字 台没有切换

**Comment by lizongying** [comment]
如果频道号不存在，是没反应的。切换失败也有可能。嗯，我加上不存在的提示吧。另外必须输入两位数。

**Comment by youngdrak** [comment]
建议输入1个数字的时候自动补齐两位数

**Comment by Rekoe** [comment]
> 如果频道号不存在，是没反应的。切换失败也有可能。嗯，我加上不存在的提示吧。另外必须输入两位数。

建议把1/01 对应上相应的频道 比如cctv1(01/1) 这个更符合用户习惯

**Comment by lizongying** [comment]
新版本已解决
