### ISSUE TITLE
[BUG] 2.1的版本华为电视安装后无法播放

### ISSUE THREAD

**Issue by zhangke199011** [lizongying/my-tv#830]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

2.1的版本华为电视安装后无法播放

### 预期行为

解决
谢谢

### 实际行为

重启也没法播放

### UI / OS

华为鸿蒙电视

### Android 版本

11

**Comment by lizongying** [comment]
#834
