### ISSUE TITLE
[BUG] 2.1.0 on Onn androidTV box 所有国内台都报“状态错误”error

### ISSUE THREAD

**Issue by gaoty133** [lizongying/my-tv#832]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

2.1.0 on Onn androidTV box 所有国内台都报“状态错误”error

### 预期行为

国内电视台可以观看

### 实际行为

所有国内台都报“状态错误”error

### UI / OS

AndroidTV

### Android 版本

12

**Comment by gyzenger** [comment]
是的，2024年5月31日开始，TCL 55Q9K国内电视台均显示“状态错误”，但凤凰三个台可以正常播放，升级到2.1.0版本不能解决问题。

**Comment by jrffrj** [comment]
5月30号，yangshipin开启了wasm加密，要破解aes加密

**Comment by zhaoyue123ABC** [comment]
是的 除了凤凰台其他台都是状态错误

**Comment by a13988866058** [comment]
这啥世道，看个电视都这么难

**Comment by windmoonwind** [comment]
> 5月30号，yangshipin开启了wasm加密，要破解aes加密

歹毒，誓要与人民群众斗争到底啊...

**Comment by zhenghan10011** [comment]
好狠

**Comment by liullyss** [comment]
国内电视解析错误

**Comment by williamzzcn123** [comment]
所有台都显示状态错误，估计是这个mytv已经小有名气，被针对了，希望李宗英大大能解决

**Comment by cwbqiuyu** [comment]
看来不止我一个出现这问题

**Comment by javadodobird** [comment]
应该是my-tv现在出名了，太多人在用了，

导致某平台每天的进进出出网络流量超级多超极巨大超极负荷，

my-tv应该早就被某机构盯上了，所以某平台现在加強反制力度了。

**Comment by pic5566** [comment]
famingming的IPV6一样的播放不了，不只是mytv。。。。服了

**Comment by jrffrj** [comment]
这次增加的wasm加密有点low，两种方案解决，一种通过nodejs加载asfs.js就能加密，另一种方法，直接做好字典，秒加密。

**Comment by woshichenghaibo** [comment]
> 这次增加的wasm加密有点low，两种方案解决，一种通过nodejs加载asfs.js就能加密，另一种方法，直接做好字典，秒加密。

是本地解决还是需要客户端升级？

**Comment by jrffrj** [comment]
> > 这次增加的wasm加密有点low，两种方案解决，一种通过nodejs加载asfs.js就能加密，另一种方法，直接做好字典，秒加密。
> 
> 是本地解决还是需要客户端升级？

我是php写的加密过程，直接把央视频转成可直接播放的m3u8地址。mytv软件得等大佬更新加密才能用

**Comment by zzglym** [comment]
除了凤凰，其他都“状态错误”，

**Comment by zhascg** [comment]
看个电视真难

**Comment by AppleMate60pro** [comment]
十块钱的IPTV真的有这么贵？

**Comment by gaoty133** [comment]
> 十块钱的IPTV真的有这么贵？

有什么推荐吗？

**Comment by lizongying** [comment]
週末陪孩子了，週一再解決了

**Comment by zzglym** [comment]
> 十块钱的IPTV真的有这么贵？

10块钱不贵，这个软件让大家有更多的选择，还免费无广！运营商的IPTV也有免费的，不过大多是有条件减免，达不到条件就是每月2、30，甚至60多，各地不同。

**Comment by ssjdm** [comment]
> 十块钱的IPTV真的有这么贵？

有IPTV，纯粹是不想用两个遥控器，还有那个机顶盒，明明可以集成到电视里的，太傻逼了

**Comment by wendaoshu** [comment]
倒真不是10元钱的问题，手机套餐里电视都是送的，我们根本没有看电视的需求。主要是家里老人要看电视，但是老人的房间没有IPTV接口，只能从客厅拉明线过去，装IPTV的人自己都放弃了。。。。
之前给老年人用电视家买个会员，老人看着很爽，自从和谐了以后就找到了zongying大神了，感恩看了几个月了

**Comment by ypcgamelife** [comment]
希望早点解决。大家都盼望着

**Comment by maopashui** [comment]
> > > 这次增加的wasm加密有点low，两种方案解决，一种通过nodejs加载asfs.js就能加密，另一种方法，直接做好字典，秒加密。
> > 
> > 是本地解决还是需要客户端升级？
> 
> 我是php写的加密过程，直接把央视频转成可直接播放的m3u8地址。mytv软件得等大佬更新加密才能用
> 

大佬能分享下加密算法吗 之前都是看作者的 这次周末他没弄😂

**Comment by jrffrj** [comment]
function encrypt_aes($org){
$word = '0:8b0e1a4de35d011d1a4ed584f02cd2ddd66df28bbb114f64ffaaf4a4ccf7476c83d53e52960896aa984bf458a7eb1134e96343c221ee591c7571e093
1:8a0f1b4ce25c001c1b4fd485f12dd3dcd76cf38aba104e65feabf5a5cdf6466d82d43f53970997ab994af559a6ea1035e86242c320ef581d7470e192
2:890c184fe15f031f184cd786f22ed0dfd46ff089b9134d66fda8f6a6cef5456e81d73c50940a94a89a49f65aa5e91336eb6141c023ec5b1e7773e291
3:880d194ee05e021e194dd687f32fd1ded56ef188b8124c67fca9f7a7cff4446f80d63d51950b95a99b48f75ba4e81237ea6040c122ed5a1f7672e390
4:8f0a1e49e75905191e4ad180f428d6d9d269f68fbf154b60fbaef0a0c8f3436887d13a56920c92ae9c4ff05ca3ef1530ed6747c625ea5d187175e497
5:8e0b1f48e65804181f4bd081f529d7d8d368f78ebe144a61faaff1a1c9f2426986d03b57930d93af9d4ef15da2ee1431ec6646c724eb5c197074e596
6:8d081c4be55b071b1c48d382f62ad4dbd06bf48dbd174962f9acf2a2caf1416a85d33854900e90ac9e4df25ea1ed1732ef6545c427e85f1a7377e695
7:8c091d4ae45a061a1d49d283f72bd5dad16af58cbc164863f8adf3a3cbf0406b84d23955910f91ad9f4cf35fa0ec1633ee6444c526e95e1b7276e794
8:83061245eb5509151246dd8cf824dad5de65fa83b319476cf7a2fcacc4ff4f648bdd365a9e009ea29043fc50afe3193ce16b4bca29e651147d79e89b
9:82071344ea5408141347dc8df925dbd4df64fb82b218466df6a3fdadc5fe4e658adc375b9f019fa39142fd51aee2183de06a4acb28e750157c78e99a
a:da5f4b1cb20c504c4b1f84d5a17d838c873ca3daea401e35aefba5f59da6163dd2846f03c759c7fbc91aa509f6ba4065b832129370bf084d2420b1c2
b:d95c481fb10f534f481c87d6a27e808f843fa0d9e9431d36adf8a6f69ea5153ed1876c00c45ac4f8ca19a60af5b94366bb31119073bc0b4e2723b2c1
c:d85d491eb00e524e491d86d7a37f818e853ea1d8e8421c37acf9a7f79fa4143fd0866d01c55bc5f9cb18a70bf4b84267ba30109172bd0a4f2622b3c0
d:df5a4e19b70955494e1a81d0a47886898239a6dfef451b30abfea0f098a31338d7816a06c25cc2fecc1fa00cf3bf4560bd37179675ba0d482125b4c7
e:de5b4f18b60854484f1b80d1a57987888338a7deee441a31aaffa1f199a21239d6806b07c35dc3ffcd1ea10df2be4461bc36169774bb0c492024b5c6
f:dd584c1bb50b574b4c1883d2a67a848b803ba4dded471932a9fca2f29aa1113ad5836804c05ec0fcce1da20ef1bd4762bf35159477b80f4a2327b6c5
g:dc594d1ab40a564a4d1982d3a77b858a813aa5dcec461833a8fda3f39ba0103bd4826905c15fc1fdcf1ca30ff0bc4663be34149576b90e4b2226b7c4
h:d3564215bb05594542168ddca8748a858e35aad3e349173ca7f2acfc94af1f34db8d660ace50cef2c013ac00ffb3496cb13b1b9a79b601442d29b8cb
i:d2574314ba04584443178cdda9758b848f34abd2e248163da6f3adfd95ae1e35da8c670bcf51cff3c112ad01feb2486db03a1a9b78b700452c28b9ca
j:d1544017b9075b4740148fdeaa7688878c37a8d1e14b153ea5f0aefe96ad1d36d98f6408cc52ccf0c211ae02fdb14b6eb33919987bb403462f2bbac9
k:d0554116b8065a4641158edfab7789868d36a9d0e04a143fa4f1afff97ac1c37d88e6509cd53cdf1c310af03fcb04a6fb23818997ab502472e2abbc8
l:d7524611bf015d41461289d8ac708e818a31aed7e74d1338a3f6a8f890ab1b30df89620eca54caf6c417a804fbb74d68b53f1f9e7db20540292dbccf
m:d6534710be005c40471388d9ad718f808b30afd6e64c1239a2f7a9f991aa1a31de88630fcb55cbf7c516a905fab64c69b43e1e9f7cb30441282cbdce
n:d5504413bd035f4344108bdaae728c838833acd5e54f113aa1f4aafa92a91932dd8b600cc856c8f4c615aa06f9b54f6ab73d1d9c7fb007422b2fbecd
o:d4514512bc025e4245118adbaf738d828932add4e44e103ba0f5abfb93a81833dc8a610dc957c9f5c714ab07f8b44e6bb63c1c9d7eb106432a2ebfcc
p:cb4e5a0da31d415d5a0e95c4b06c929d962db2cbfb510f24bfeab4e48cb7072cc3957e12d648d6ead80bb418e7ab5174a923038261ae195c3531a0d3
q:ca4f5b0ca21c405c5b0f94c5b16d939c972cb3cafa500e25beebb5e58db6062dc2947f13d749d7ebd90ab519e6aa5075a822028360af185d3430a1d2
r:c94c580fa11f435f580c97c6b26e909f942fb0c9f9530d26bde8b6e68eb5052ec1977c10d44ad4e8da09b61ae5a95376ab21018063ac1b5e3733a2d1
s:c84d590ea01e425e590d96c7b36f919e952eb1c8f8520c27bce9b7e78fb4042fc0967d11d54bd5e9db08b71be4a85277aa20008162ad1a5f3632a3d0
t:cf4a5e09a71945595e0a91c0b46896999229b6cfff550b20bbeeb0e088b30328c7917a16d24cd2eedc0fb01ce3af5570ad27078665aa1d583135a4d7
u:ce4b5f08a61844585f0b90c1b56997989328b7cefe540a21baefb1e189b20229c6907b17d34dd3efdd0eb11de2ae5471ac26068764ab1c593034a5d6
v:cd485c0ba51b475b5c0893c2b66a949b902bb4cdfd570922b9ecb2e28ab1012ac5937814d04ed0ecde0db21ee1ad5772af25058467a81f5a3337a6d5
w:cc495d0aa41a465a5d0992c3b76b959a912ab5ccfc560823b8edb3e38bb0002bc4927915d14fd1eddf0cb31fe0ac5673ae24048566a91e5b3236a7d4
x:c3465205ab15495552069dccb8649a959e25bac3f359072cb7e2bcec84bf0f24cb9d761ade40dee2d003bc10efa3597ca12b0b8a69a611543d39a8db
y:c2475304aa14485453079ccdb9659b949f24bbc2f258062db6e3bded85be0e25ca9c771bdf41dfe3d102bd11eea2587da02a0a8b68a710553c38a9da
z:c1445007a9174b5750049fceba6698979c27b8c1f15b052eb5e0beee86bd0d26c99f7418dc42dce0d201be12eda15b7ea32909886ba413563f3baad9
&:9d180c5bf54b170b0c58c392e63ac4cbc07be49dad075972e9bce2b2dae1517a95c32844801e80bc8e5de24eb1fd0722ff7555d437f84f0a6367f685
_:e46175228c326e727521baeb9f43bdb2b9029de4d47e200b90c59bcba3982803ecba513df967f9c5f7249b37c8847e5b860c2cad4e8136731a1e8ffc';
$word_array = explode("\n",$word);
$p=array();
foreach ($word_array as $k => $v) {
    $w_array = explode(":",$v);
    $p[$w_array[0]]=str_split($w_array[1],2);
}
$result = "";
foreach(str_split($org) as $k => $v){
    $result.=$p[$v][$k];
}
return $result;
}
看看作者会不会采用我的方案

**Comment by jrffrj** [comment]
function encrypt_aes($org){
$word = '0:8b0e1a4de35d011d1a4ed584f02cd2ddd66df28bbb114f64ffaaf4a4ccf7476c83d53e52960896aa984bf458a7eb1134e96343c221ee591c7571e093
1:8a0f1b4ce25c001c1b4fd485f12dd3dcd76cf38aba104e65feabf5a5cdf6466d82d43f53970997ab994af559a6ea1035e86242c320ef581d7470e192
2:890c184fe15f031f184cd786f22ed0dfd46ff089b9134d66fda8f6a6cef5456e81d73c50940a94a89a49f65aa5e91336eb6141c023ec5b1e7773e291
3:880d194ee05e021e194dd687f32fd1ded56ef188b8124c67fca9f7a7cff4446f80d63d51950b95a99b48f75ba4e81237ea6040c122ed5a1f7672e390
4:8f0a1e49e75905191e4ad180f428d6d9d269f68fbf154b60fbaef0a0c8f3436887d13a56920c92ae9c4ff05ca3ef1530ed6747c625ea5d187175e497
5:8e0b1f48e65804181f4bd081f529d7d8d368f78ebe144a61faaff1a1c9f2426986d03b57930d93af9d4ef15da2ee1431ec6646c724eb5c197074e596
6:8d081c4be55b071b1c48d382f62ad4dbd06bf48dbd174962f9acf2a2caf1416a85d33854900e90ac9e4df25ea1ed1732ef6545c427e85f1a7377e695
7:8c091d4ae45a061a1d49d283f72bd5dad16af58cbc164863f8adf3a3cbf0406b84d23955910f91ad9f4cf35fa0ec1633ee6444c526e95e1b7276e794
8:83061245eb5509151246dd8cf824dad5de65fa83b319476cf7a2fcacc4ff4f648bdd365a9e009ea29043fc50afe3193ce16b4bca29e651147d79e89b
9:82071344ea5408141347dc8df925dbd4df64fb82b218466df6a3fdadc5fe4e658adc375b9f019fa39142fd51aee2183de06a4acb28e750157c78e99a
a:da5f4b1cb20c504c4b1f84d5a17d838c873ca3daea401e35aefba5f59da6163dd2846f03c759c7fbc91aa509f6ba4065b832129370bf084d2420b1c2
b:d95c481fb10f534f481c87d6a27e808f843fa0d9e9431d36adf8a6f69ea5153ed1876c00c45ac4f8ca19a60af5b94366bb31119073bc0b4e2723b2c1
c:d85d491eb00e524e491d86d7a37f818e853ea1d8e8421c37acf9a7f79fa4143fd0866d01c55bc5f9cb18a70bf4b84267ba30109172bd0a4f2622b3c0
d:df5a4e19b70955494e1a81d0a47886898239a6dfef451b30abfea0f098a31338d7816a06c25cc2fecc1fa00cf3bf4560bd37179675ba0d482125b4c7
e:de5b4f18b60854484f1b80d1a57987888338a7deee441a31aaffa1f199a21239d6806b07c35dc3ffcd1ea10df2be4461bc36169774bb0c492024b5c6
f:dd584c1bb50b574b4c1883d2a67a848b803ba4dded471932a9fca2f29aa1113ad5836804c05ec0fcce1da20ef1bd4762bf35159477b80f4a2327b6c5
g:dc594d1ab40a564a4d1982d3a77b858a813aa5dcec461833a8fda3f39ba0103bd4826905c15fc1fdcf1ca30ff0bc4663be34149576b90e4b2226b7c4
h:d3564215bb05594542168ddca8748a858e35aad3e349173ca7f2acfc94af1f34db8d660ace50cef2c013ac00ffb3496cb13b1b9a79b601442d29b8cb
i:d2574314ba04584443178cdda9758b848f34abd2e248163da6f3adfd95ae1e35da8c670bcf51cff3c112ad01feb2486db03a1a9b78b700452c28b9ca
j:d1544017b9075b4740148fdeaa7688878c37a8d1e14b153ea5f0aefe96ad1d36d98f6408cc52ccf0c211ae02fdb14b6eb33919987bb403462f2bbac9
k:d0554116b8065a4641158edfab7789868d36a9d0e04a143fa4f1afff97ac1c37d88e6509cd53cdf1c310af03fcb04a6fb23818997ab502472e2abbc8
l:d7524611bf015d41461289d8ac708e818a31aed7e74d1338a3f6a8f890ab1b30df89620eca54caf6c417a804fbb74d68b53f1f9e7db20540292dbccf
m:d6534710be005c40471388d9ad718f808b30afd6e64c1239a2f7a9f991aa1a31de88630fcb55cbf7c516a905fab64c69b43e1e9f7cb30441282cbdce
n:d5504413bd035f4344108bdaae728c838833acd5e54f113aa1f4aafa92a91932dd8b600cc856c8f4c615aa06f9b54f6ab73d1d9c7fb007422b2fbecd
o:d4514512bc025e4245118adbaf738d828932add4e44e103ba0f5abfb93a81833dc8a610dc957c9f5c714ab07f8b44e6bb63c1c9d7eb106432a2ebfcc
p:cb4e5a0da31d415d5a0e95c4b06c929d962db2cbfb510f24bfeab4e48cb7072cc3957e12d648d6ead80bb418e7ab5174a923038261ae195c3531a0d3
q:ca4f5b0ca21c405c5b0f94c5b16d939c972cb3cafa500e25beebb5e58db6062dc2947f13d749d7ebd90ab519e6aa5075a822028360af185d3430a1d2
r:c94c580fa11f435f580c97c6b26e909f942fb0c9f9530d26bde8b6e68eb5052ec1977c10d44ad4e8da09b61ae5a95376ab21018063ac1b5e3733a2d1
s:c84d590ea01e425e590d96c7b36f919e952eb1c8f8520c27bce9b7e78fb4042fc0967d11d54bd5e9db08b71be4a85277aa20008162ad1a5f3632a3d0
t:cf4a5e09a71945595e0a91c0b46896999229b6cfff550b20bbeeb0e088b30328c7917a16d24cd2eedc0fb01ce3af5570ad27078665aa1d583135a4d7
u:ce4b5f08a61844585f0b90c1b56997989328b7cefe540a21baefb1e189b20229c6907b17d34dd3efdd0eb11de2ae5471ac26068764ab1c593034a5d6
v:cd485c0ba51b475b5c0893c2b66a949b902bb4cdfd570922b9ecb2e28ab1012ac5937814d04ed0ecde0db21ee1ad5772af25058467a81f5a3337a6d5
w:cc495d0aa41a465a5d0992c3b76b959a912ab5ccfc560823b8edb3e38bb0002bc4927915d14fd1eddf0cb31fe0ac5673ae24048566a91e5b3236a7d4
x:c3465205ab15495552069dccb8649a959e25bac3f359072cb7e2bcec84bf0f24cb9d761ade40dee2d003bc10efa3597ca12b0b8a69a611543d39a8db
y:c2475304aa14485453079ccdb9659b949f24bbc2f258062db6e3bded85be0e25ca9c771bdf41dfe3d102bd11eea2587da02a0a8b68a710553c38a9da
z:c1445007a9174b5750049fceba6698979c27b8c1f15b052eb5e0beee86bd0d26c99f7418dc42dce0d201be12eda15b7ea32909886ba413563f3baad9
&:9d180c5bf54b170b0c58c392e63ac4cbc07be49dad075972e9bce2b2dae1517a95c32844801e80bc8e5de24eb1fd0722ff7555d437f84f0a6367f685
_:e46175228c326e727521baeb9f43bdb2b9029de4d47e200b90c59bcba3982803ecba513df967f9c5f7249b37c8847e5b860c2cad4e8136731a1e8ffc';
$word_array = explode("\n",$word);
$p=array();
foreach ($word_array as $k => $v) {
    $w_array = explode(":",$v);
    $p[$w_array[0]]=str_split($w_array[1],2);
}
$result = "";
foreach(str_split($org) as $k => $v){
    $result.=$p[$v][$k];
}
return $result;
}
看看作者会不会采用我的方案

**Comment by jrffrj** [comment]
暂时没有找到key和iv，只能用这种方案了

**Comment by jink2018** [comment]
> function encrypt_aes($org){ $word = '0:8b0e1a4de35d011d1a4ed584f02cd2ddd66df28bbb114f64ffaaf4a4ccf7476c83d53e52960896aa984bf458a7eb1134e96343c221ee591c7571e093 1:8a0f1b4ce25c001c1b4fd485f12dd3dcd76cf38aba104e65feabf5a5cdf6466d82d43f53970997ab994af559a6ea1035e86242c320ef581d7470e192 2:890c184fe15f031f184cd786f22ed0dfd46ff089b9134d66fda8f6a6cef5456e81d73c50940a94a89a49f65aa5e91336eb6141c023ec5b1e7773e291 3:880d194ee05e021e194dd687f32fd1ded56ef188b8124c67fca9f7a7cff4446f80d63d51950b95a99b48f75ba4e81237ea6040c122ed5a1f7672e390 4:8f0a1e49e75905191e4ad180f428d6d9d269f68fbf154b60fbaef0a0c8f3436887d13a56920c92ae9c4ff05ca3ef1530ed6747c625ea5d187175e497 5:8e0b1f48e65804181f4bd081f529d7d8d368f78ebe144a61faaff1a1c9f2426986d03b57930d93af9d4ef15da2ee1431ec6646c724eb5c197074e596 6:8d081c4be55b071b1c48d382f62ad4dbd06bf48dbd174962f9acf2a2caf1416a85d33854900e90ac9e4df25ea1ed1732ef6545c427e85f1a7377e695 7:8c091d4ae45a061a1d49d283f72bd5dad16af58cbc164863f8adf3a3cbf0406b84d23955910f91ad9f4cf35fa0ec1633ee6444c526e95e1b7276e794 8:83061245eb5509151246dd8cf824dad5de65fa83b319476cf7a2fcacc4ff4f648bdd365a9e009ea29043fc50afe3193ce16b4bca29e651147d79e89b 9:82071344ea5408141347dc8df925dbd4df64fb82b218466df6a3fdadc5fe4e658adc375b9f019fa39142fd51aee2183de06a4acb28e750157c78e99a a:da5f4b1cb20c504c4b1f84d5a17d838c873ca3daea401e35aefba5f59da6163dd2846f03c759c7fbc91aa509f6ba4065b832129370bf084d2420b1c2 b:d95c481fb10f534f481c87d6a27e808f843fa0d9e9431d36adf8a6f69ea5153ed1876c00c45ac4f8ca19a60af5b94366bb31119073bc0b4e2723b2c1 c:d85d491eb00e524e491d86d7a37f818e853ea1d8e8421c37acf9a7f79fa4143fd0866d01c55bc5f9cb18a70bf4b84267ba30109172bd0a4f2622b3c0 d:df5a4e19b70955494e1a81d0a47886898239a6dfef451b30abfea0f098a31338d7816a06c25cc2fecc1fa00cf3bf4560bd37179675ba0d482125b4c7 e:de5b4f18b60854484f1b80d1a57987888338a7deee441a31aaffa1f199a21239d6806b07c35dc3ffcd1ea10df2be4461bc36169774bb0c492024b5c6 f:dd584c1bb50b574b4c1883d2a67a848b803ba4dded471932a9fca2f29aa1113ad5836804c05ec0fcce1da20ef1bd4762bf35159477b80f4a2327b6c5 g:dc594d1ab40a564a4d1982d3a77b858a813aa5dcec461833a8fda3f39ba0103bd4826905c15fc1fdcf1ca30ff0bc4663be34149576b90e4b2226b7c4 h:d3564215bb05594542168ddca8748a858e35aad3e349173ca7f2acfc94af1f34db8d660ace50cef2c013ac00ffb3496cb13b1b9a79b601442d29b8cb i:d2574314ba04584443178cdda9758b848f34abd2e248163da6f3adfd95ae1e35da8c670bcf51cff3c112ad01feb2486db03a1a9b78b700452c28b9ca j:d1544017b9075b4740148fdeaa7688878c37a8d1e14b153ea5f0aefe96ad1d36d98f6408cc52ccf0c211ae02fdb14b6eb33919987bb403462f2bbac9 k:d0554116b8065a4641158edfab7789868d36a9d0e04a143fa4f1afff97ac1c37d88e6509cd53cdf1c310af03fcb04a6fb23818997ab502472e2abbc8 l:d7524611bf015d41461289d8ac708e818a31aed7e74d1338a3f6a8f890ab1b30df89620eca54caf6c417a804fbb74d68b53f1f9e7db20540292dbccf m:d6534710be005c40471388d9ad718f808b30afd6e64c1239a2f7a9f991aa1a31de88630fcb55cbf7c516a905fab64c69b43e1e9f7cb30441282cbdce n:d5504413bd035f4344108bdaae728c838833acd5e54f113aa1f4aafa92a91932dd8b600cc856c8f4c615aa06f9b54f6ab73d1d9c7fb007422b2fbecd o:d4514512bc025e4245118adbaf738d828932add4e44e103ba0f5abfb93a81833dc8a610dc957c9f5c714ab07f8b44e6bb63c1c9d7eb106432a2ebfcc p:cb4e5a0da31d415d5a0e95c4b06c929d962db2cbfb510f24bfeab4e48cb7072cc3957e12d648d6ead80bb418e7ab5174a923038261ae195c3531a0d3 q:ca4f5b0ca21c405c5b0f94c5b16d939c972cb3cafa500e25beebb5e58db6062dc2947f13d749d7ebd90ab519e6aa5075a822028360af185d3430a1d2 r:c94c580fa11f435f580c97c6b26e909f942fb0c9f9530d26bde8b6e68eb5052ec1977c10d44ad4e8da09b61ae5a95376ab21018063ac1b5e3733a2d1 s:c84d590ea01e425e590d96c7b36f919e952eb1c8f8520c27bce9b7e78fb4042fc0967d11d54bd5e9db08b71be4a85277aa20008162ad1a5f3632a3d0 t:cf4a5e09a71945595e0a91c0b46896999229b6cfff550b20bbeeb0e088b30328c7917a16d24cd2eedc0fb01ce3af5570ad27078665aa1d583135a4d7 u:ce4b5f08a61844585f0b90c1b56997989328b7cefe540a21baefb1e189b20229c6907b17d34dd3efdd0eb11de2ae5471ac26068764ab1c593034a5d6 v:cd485c0ba51b475b5c0893c2b66a949b902bb4cdfd570922b9ecb2e28ab1012ac5937814d04ed0ecde0db21ee1ad5772af25058467a81f5a3337a6d5 w:cc495d0aa41a465a5d0992c3b76b959a912ab5ccfc560823b8edb3e38bb0002bc4927915d14fd1eddf0cb31fe0ac5673ae24048566a91e5b3236a7d4 x:c3465205ab15495552069dccb8649a959e25bac3f359072cb7e2bcec84bf0f24cb9d761ade40dee2d003bc10efa3597ca12b0b8a69a611543d39a8db y:c2475304aa14485453079ccdb9659b949f24bbc2f258062db6e3bded85be0e25ca9c771bdf41dfe3d102bd11eea2587da02a0a8b68a710553c38a9da z:c1445007a9174b5750049fceba6698979c27b8c1f15b052eb5e0beee86bd0d26c99f7418dc42dce0d201be12eda15b7ea32909886ba413563f3baad9 &:9d180c5bf54b170b0c58c392e63ac4cbc07be49dad075972e9bce2b2dae1517a95c32844801e80bc8e5de24eb1fd0722ff7555d437f84f0a6367f685 _:e46175228c326e727521baeb9f43bdb2b9029de4d47e200b90c59bcba3982803ecba513df967f9c5f7249b37c8847e5b860c2cad4e8136731a1e8ffc'; $word_array = explode("\n",$word); $p=array(); foreach ($word_array as $k => $v) { $w_array = explode(":",$v); $p[$w_array[0]]=str_split($w_array[1],2); } $result = ""; foreach(str_split($org) as $k => $v){ $result.=$p[$v][$k]; } return $result; } 看看作者会不会采用我的方案

这个不是aes加密吧，只是通过字典转换字符串

**Comment by sese649** [comment]
> 倒真不是10元钱的问题，手机套餐里电视都是送的，我们根本没有看电视的需求。主要是家里老人要看电视，但是老人的房间没有IPTV接口，只能从客厅拉明线过去，装IPTV的人自己都放弃了。。。。 之前给老年人用电视家买个会员，老人看着很爽，自从和谐了以后就找到了zongying大神了，感恩看了几个月了

可以用电力猫。一头接机顶盒itv口，一头接电视端插座接出网线。。百兆的电力猫就够了

**Comment by guoyan1983** [comment]
> > 倒真不是10元钱的问题，手机套餐里电视都是送的，我们根本没有看电视的需求。主要是家里老人要看电视，但是老人的房间没有IPTV接口，只能从客厅拉明线过去，装IPTV的人自己都放弃了。。。。 之前给老年人用电视家买个会员，老人看着很爽，自从和谐了以后就找到了zongying大神了，感恩看了几个月了
> 
> 可以用电力猫。一头接机顶盒itv口，一头接电视端插座接出网线。。百兆的电力猫就够了

这个如何实现？两个电力猫？一个接 iptv？可以连接多个电视机么

**Comment by sese649** [comment]
要接多个就要一配多了，因为我只接了一台电视，没试过能否两台电视同时看



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月02日 20:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lizongying/my-tv] [BUG] 2.1.0 on Onn androidTV box 所有国内台都报“状态错误”error (Issue #832) |

倒真不是10元钱的问题，手机套餐里电视都是送的，我们根本没有看电视的需求。主要是家里老人要看电视，但是老人的房间没有IPTV接口，只能从客厅拉明线过去，装IPTV的人自己都放弃了。。。。 之前给老年人用电视家买个会员，老人看着很爽，自从和谐了以后就找到了zongying大神了，感恩看了几个月了

可以用电力猫。一头接机顶盒itv口，一头接电视端插座接出网线。。百兆的电力猫就够了

这个如何实现？两个电力猫？一个接 iptv？可以连接多个电视机么

**Comment by hongsongshu** [comment]
看了下其他app 基于ipv4地址的国内也是看不了,除了cctv 4k台,其他台中央1-13...使用基于ipv6地址的可以看

**Comment by AppleMate60pro** [comment]
> > 十块钱的IPTV真的有这么贵？
> 
> 有IPTV，纯粹是不想用两个遥控器，还有那个机顶盒，明明可以集成到电视里的，太傻逼了

作者不是还有一个my tv 1项目，类似电视浏览器，可以看画质切台可能慢一点，重在不用频繁黑屏看不了

**Comment by a857898089** [comment]
免费的app大家就没必要强求太多，随意等吧。

**Comment by lizongying** [comment]
#834

**Comment by jrffrj** [comment]
看来作者还是采用了我的字典方案
  ht = create_table();
  insert(ht,'0',&DAT_000a587a);
  insert(ht,'1',&DAT_000b1d8d);
  insert(ht,'2',&DAT_000ab1f4);
  insert(ht,'3',&DAT_000ab231);
  insert(ht,'4',&DAT_0009a144);
  insert(ht,'5',&DAT_00095347);
  insert(ht,'6',&DAT_000a32fa);
  insert(ht,'7',&DAT_00091813);
  insert(ht,'8',&DAT_000b1dca);
  insert(ht,'9',&DAT_0009b4c2);
  insert(ht,'a',&DAT_0008de95);
  insert(ht,'b',&DAT_000b1e07);
  insert(ht,'c',&DAT_000a3337);
  insert(ht,'d',&DAT_0009fd59);
  insert(ht,'e',&DAT_000ab26e);
  insert(ht,'f',&DAT_000a8b63);
  insert(ht,'g',&DAT_000ab2ab);
  insert(ht,'h',&DAT_000b1e44);
  insert(ht,'i',&DAT_000b1e81);
  insert(ht,'j',&DAT_000a8ba0);
  insert(ht,'k',&DAT_0008f1f6);
  insert(ht,'l',&DAT_00095384);
  insert(ht,'m',&DAT_000b1ebe);
  insert(ht,'n',&DAT_000a2095);
  insert(ht,'o',&DAT_00091850);
  insert(ht,'p',&DAT_0009a181);
  insert(ht,'q',&DAT_0009fd96);
  insert(ht,'r',&DAT_00093eba);
  insert(ht,'s',&DAT_000b1efb);
  insert(ht,'t',&DAT_000a7b4e);
  insert(ht,'u',&DAT_000a8bdd);
  insert(ht,'v',&DAT_000a9e72);
  insert(ht,'w',&DAT_000b1f38);
  insert(ht,'x',&DAT_0009a1be);
  insert(ht,'y',&DAT_000a460c);
  insert(ht,'z',&DAT_0008ded2);
  insert(ht,'&',&DAT_0009c7bc);
  insert(ht,'_',&DAT_0009188d);
  pHVar1 = ht;
  insert(ht,'-',&DAT_000b1f75);
