### ISSUE TITLE
[BUG] UNT413A 21版本闪退

### ISSUE THREAD

**Issue by ihumbert** [lizongying/my-tv#833]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

20.5提示认证状态错误。升级mytv21安装后闪退，

### 预期行为

mytv21安装后希望正常使用

### 实际行为

mytv21安装后闪退

### UI / OS

UNT413A-U2

### Android 版本

9

**Comment by lizongying** [comment]
#896
