### ISSUE TITLE
新版本无法播放

### ISSUE THREAD

**Issue by Yahiuu** [lizongying/my-tv#834]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

显示认证问题，无法播放，抓紧更新哦

### 预期行为

无法播放

### 实际行为

无法播放

### UI / OS

手机

### Android 版本

14

**Comment by shengmenghui** [comment]
今天更新了以下，发现也是无法播放

**Comment by aepub** [comment]
2.1.0版本，无法播放，显示状态错误！

**Comment by javadodobird** [comment]
应该是my-tv现在越来越出名了，越来越多人在使用了，

从而导致某平台每天进进出出的网络流量超级多超极巨大超极负荷超极拥挤了，

my-tv应该是早早就被某机构盯上了，所以现在某平台是越来越加強反制力度了。

**Comment by knightgrq** [comment]
> 应该是my-tv现在越来越出名了，越来越多人在使用了，
> 
> 从而导致某平台每天进进出出的网络流量超级多超极巨大超极负荷超极拥挤了，
> 
> my-tv应该是早早就被某机构盯上了，所以现在某平台是越来越加強反制力度了。

确实，被ban的速度几乎是同步的。

**Comment by bilibili2077** [comment]
一样显示错误

**Comment by akinaedison** [comment]
是再也无法恢复了么，一天半过去了

**Comment by laotumsn** [comment]
作者加油吧，上一个版本就看了一天，就没然后了

**Comment by Fliny** [comment]
同，显示“状态错误”

**Comment by abc99991** [comment]
每次都是关键时刻掉链子。

**Comment by Eessme** [comment]
没有办法，网上都是推荐my-tv的，太出名了，基本一出就扑街，难受啊

**Comment by yzb5158** [comment]
2.1.0最新版本 闪退

**Comment by dust2k** [comment]
现在这种每个版本绑死的播放地址的模式肯定不行了。。。唉。。。

**Comment by yanquan2020** [comment]
源壳分离，变源。。。

**Comment by holenbase** [comment]
用的人太多了，被盯死了吧

**Comment by ypcgamelife** [comment]
都是报错，希望能解决，这个速度是最快的了。

**Comment by cliff19721108** [comment]
只有香港卫视依然坚挺

**Comment by sunyt50** [comment]
两台电视都显示状态错误

**Comment by githubcxg** [comment]
据说5月30号，央视频开启了wasm加密，要破解aes加密。

**Comment by lixianghui40** [comment]
新版本也无法播放，看来有很多的问题要解决。

**Comment by lizongying** [comment]
[v2.1.1](https://github.com/lizongying/my-tv/releases/tag/v2.1.1)

**Comment by lixianghui40** [comment]
你好，我已经收到您的来信。

**Comment by pic5566** [comment]
> [v2.1.1](https://github.com/lizongying/my-tv/releases/tag/v2.1.1)

已恢复正常，感激不尽！
