### ISSUE TITLE
[FR] 项目开发调试教程，更多人参与维护

### ISSUE THREAD

**Issue by sobergou** [lizongying/my-tv#835]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

项目开发调试教程，更多人参与维护

**Comment by sobergou** [comment]
lizongying / my-tv github项目研究维护：https://www.zeppos.tech/t/topic/2821?u=sober

**Comment by whenyooyoo** [comment]
v2.1.0显示状态错误，无法使用哦。而且只要有新版本发布，旧的版本就无法使用。而且，在tv上也搜索不到更新。总要重新安装是不是很不方便？

**Comment by 743859910** [comment]
> lizongying / my-tv github项目研究维护：https://www.zeppos.tech/t/topic/2821?u=sober

打开就直接让注册登录，看都不让看是什么东西？

**Comment by meiti789789** [comment]
更新bug 同样感受 我一个车载/一个投影仪/一个电视盒 每次更新都要做三次重新下载去安装 很是麻烦 劳烦作者能解决更新的问题 这样哪怕出不能播放问题 也不至于大动干戈去更新

**Comment by sobergou** [comment]
> > lizongying / my-tv github项目研究维护：https://www.zeppos.tech/t/topic/2821?u=sober
> 
> 打开就直接让注册登录，看都不让看是什么东西？

实在抱歉，因匿名用户给技术论坛造成了名誉损害，暂时关闭了匿名访问通道

**Comment by sobergou** [comment]
开发环境搭建初步完成
![image](https://github.com/lizongying/my-tv/assets/50661423/ce722aa4-4c3e-4e42-8d73-fd8cbdafdb78)

**Comment by sobergou** [comment]
@lizongying 大佬，能否在JELLY_BEAN_MR1分支上传x86、x86_64平台的libnative.so，便于模拟器的仿真调试，让更多人参与维护

![image](https://github.com/lizongying/my-tv/assets/50661423/d0992f2c-a842-4e82-84c4-001892eee83f)

**Comment by shuohao** [comment]
> @lizongying 大佬，能否在JELLY_BEAN_MR1分支上传x86、x86_64平台的libnative.so，便于模拟器的仿真调试，让更多人参与维护
> 
> ![image](https://private-user-images.githubusercontent.com/50661423/336274908-d0992f2c-a842-4e82-84c4-001892eee83f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODIwNzksIm5iZiI6MTcxNzQ4MTc3OSwicGF0aCI6Ii81MDY2MTQyMy8zMzYyNzQ5MDgtZDA5OTJmMmMtYTg0Mi00ZTgyLTg0YzQtMDAxODkyZWVlODNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA2MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMWU5N2NhOWMwZDUzYTA4Mjk5Yzg1ZTNiNDliMDk1ZWNmZTk3NDNlMTQyNmM5NGJkOTE2ZWEyY2U1NDEwZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ud70Ci6aUMTpfD6V3s_2KJmuNipGg_YY09ICVecYSt4)

我下载源码后 Android studio build  cmake报错  是不是缺少你说的相关文件啊

**Comment by sobergou** [comment]
> > @lizongying 大佬，能否在JELLY_BEAN_MR1分支上传x86、x86_64平台的libnative.so，便于模拟器的仿真调试，让更多人参与维护
> > ![image](https://private-user-images.githubusercontent.com/50661423/336274908-d0992f2c-a842-4e82-84c4-001892eee83f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODIwNzksIm5iZiI6MTcxNzQ4MTc3OSwicGF0aCI6Ii81MDY2MTQyMy8zMzYyNzQ5MDgtZDA5OTJmMmMtYTg0Mi00ZTgyLTg0YzQtMDAxODkyZWVlODNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA2MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMWU5N2NhOWMwZDUzYTA4Mjk5Yzg1ZTNiNDliMDk1ZWNmZTk3NDNlMTQyNmM5NGJkOTE2ZWEyY2U1NDEwZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ud70Ci6aUMTpfD6V3s_2KJmuNipGg_YY09ICVecYSt4)
> 
> 我下载源码后 Android studio build cmake报错 是不是缺少你说的相关文件啊

你在论坛贴一下你的错误信息图片

**Comment by sobergou** [comment]
模拟器、真机可调试开发
![image](https://github.com/lizongying/my-tv/assets/50661423/00fd3b75-c41f-47be-8112-174d48db1a90)
