### ISSUE TITLE
[BUG] 软件很好就是三天两头的看不了

### ISSUE THREAD

**Issue by silentchild** [lizongying/my-tv#836]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

看不了的原因是啥呀，是否是本地配置失效了，能把直播配置直接通过接口返回做成动态返回，省的三天两头发版，现在太不稳定了！

### 预期行为

能稳定观看

### 实际行为

三天两头无法播放

### UI / OS

TCL

### Android 版本

12

**Comment by lizongying** [comment]
做不到
