### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yqwlsc3** [lizongying/my-tv#837]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本
2.1.1

通用版

### Bug 描述

乐视4.3rom闪退

### 预期行为

安装正常，闪退

### 实际行为

闪退

### 复现步骤

2

### UI / OS

乐视

### Android 版本

4.3

**Comment by sunnysu0608** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的 bug report。
> * [x]  我正在使用本软件的最新版本。
> 
> ### my-ty 版本
> 2.1.1
> 
> 通用版
> 
> ### Bug 描述
> 乐视4.3rom闪退
> 
> ### 预期行为
> 安装正常，闪退
> 
> ### 实际行为
> 闪退
> 
> ### 复现步骤
> 2
> 
> ### UI / OS
> 乐视
> 
> ### Android 版本
> 4.3
> 
> ### 额外信息
> _No response_

https://share.weiyun.com/psHu2tOK
这个版本永远有效

**Comment by lizongying** [comment]
#896
