### ISSUE TITLE
[BUG] 2.10 2.11都是闪退

### ISSUE THREAD

**Issue by ghfangzong** [lizongying/my-tv#838]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

先是2.05认证错误只有凤凰台可以看
再从2.10开始闪退 最新的2.11也是闪退

### 预期行为

能正常使用

### 实际行为

  闪退

### UI / OS

魔百盒m311-1a 当贝桌面

### Android 版本

9

**Comment by xyschen** [comment]
2.11 我这完美， 谢谢更新！

**Comment by chuiyg** [comment]
同样问题，210，211都更新了。谢谢！

**Comment by oiin** [comment]
使用my TV差不多两个月，版本205及以前的没有闪退情况，平时如果突然出现认证状态错误，更新一下新版本就可以，但是最近三个版本209、210、211未进画面就闪退，电视盒子是天猫魔盒，但app安装在手机上都是正常观看的。

**Comment by winkyz** [comment]
我的 ZXV10 B860AV2.1 当贝桌面也是这个问题，从2.05~2.11 也都是凤凰三台可以看，内地台闪退。天天在等更新修复， 请问作者有没有修复的计划，我可以提供调试信息，帮助定位问题。

**Comment by ssiop789** [comment]
同样问题，cm311-1a，android 9,软件版本v.955.05,从2.1.0开始，2.1.1也闪退，根本进不去。

**Comment by lizongying** [comment]
#896
