### ISSUE TITLE
能不能让老版本正常使用

### ISSUE THREAD

**Issue by word2007** [lizongying/my-tv#839]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

如果没有新功能或者增加频道，能不能让老版本正常使用，有些人就想踏踏实实的看个电视。新版本可以慢慢研究慢慢升级。看大家需要的会重新安装的。[FR] 

### 解决方案

什么都不做

**Comment by econwang** [comment]
不能

**Comment by snowie2000** [comment]
这个软件的工作原理导致并不是人家想出新版本让旧版本不能用，而是旧版本用不了了所以才出了新版本……

**Comment by WenTuanYao** [comment]
节目单是写在程序里的，要更新只能安装新版本，要想老版本能一直使用就要把节目单独立出来，为了照顾国内用户要用到国内的服务，还要备案，很容易被有关部门请去喝茶，而且还要多一笔费用。

**Comment by snowie2000** [comment]
> 节目单是写在程序里的，要更新只能安装新版本，要想老版本能一直使用就要把节目单独立出来，为了照顾国内用户要用到国内的服务，还要备案，很容易被有关部门请去喝茶，而且还要多一笔费用。

你错了，mytv中根本没有节目单，不像一般的内置源的播放软件。
mytv是直接请求的yangshipin.cn中的内容，所以央视频修复了可以免费看vip的bug后，mytv也看不了了。
而央视频一直都修改他们的加密手段，人家是个网页可以随便改，不需要发布，但mytv是个客户端软件，无法热更新其中的代码，自然就播放不了了

**Comment by everstu** [comment]
> > 节目单是写在程序里的，要更新只能安装新版本，要想老版本能一直使用就要把节目单独立出来，为了照顾国内用户要用到国内的服务，还要备案，很容易被有关部门请去喝茶，而且还要多一笔费用。
> 
> 你错了，mytv中根本没有节目单，不像一般的内置源的播放软件。 mytv是直接请求的yangshipin.cn中的内容，所以央视频修复了可以免费看vip的bug后，mytv也看不了了。 而央视频一直都修改他们的加密手段，人家是个网页可以随便改，不需要发布，但mytv是个客户端软件，无法热更新其中的代码，自然就播放不了了


可是这样老人用的真的好不方便啊，我感觉能否加个自定义节目单功能？我自己在家里nas上更新解密服务就可以了。

**Comment by snowie2000** [comment]
> > > 节目单是写在程序里的，要更新只能安装新版本，要想老版本能一直使用就要把节目单独立出来，为了照顾国内用户要用到国内的服务，还要备案，很容易被有关部门请去喝茶，而且还要多一笔费用。
> > 
> > 
> > 你错了，mytv中根本没有节目单，不像一般的内置源的播放软件。 mytv是直接请求的yangshipin.cn中的内容，所以央视频修复了可以免费看vip的bug后，mytv也看不了了。 而央视频一直都修改他们的加密手段，人家是个网页可以随便改，不需要发布，但mytv是个客户端软件，无法热更新其中的代码，自然就播放不了了
> 
> 可是这样老人用的真的好不方便啊，我感觉能否加个自定义节目单功能？我自己在家里nas上更新解密服务就可以了。

人家不是做了么：
https://github.com/lizongying/my-tv-0
https://github.com/lizongying/my-tv-server
不过不提供央视频协议解密服务，只是个简单的发布源的功能，你可以收集网上共享出来的解密php等然后把地址放进去

**Comment by everstu** [comment]
> > > > 节目单是写在程序里的，要更新只能安装新版本，要想老版本能一直使用就要把节目单独立出来，为了照顾国内用户要用到国内的服务，还要备案，很容易被有关部门请去喝茶，而且还要多一笔费用。
> > > 
> > > 
> > > 你错了，mytv中根本没有节目单，不像一般的内置源的播放软件。 mytv是直接请求的yangshipin.cn中的内容，所以央视频修复了可以免费看vip的bug后，mytv也看不了了。 而央视频一直都修改他们的加密手段，人家是个网页可以随便改，不需要发布，但mytv是个客户端软件，无法热更新其中的代码，自然就播放不了了
> > 
> > 
> > 可是这样老人用的真的好不方便啊，我感觉能否加个自定义节目单功能？我自己在家里nas上更新解密服务就可以了。
> 
> 人家不是做了么： https://github.com/lizongying/my-tv-0 https://github.com/lizongying/my-tv-server 不过不提供央视频协议解密服务，只是个简单的发布源的功能，你可以收集网上共享出来的解密php等然后把地址放进去

哦哦，挺好的，我去研究研究，谢谢啦，这样老人用起来就好多了，我家人老是问我为什么又不能用。

**Comment by billliou** [comment]
可是你有源的话，我的电视不就成了一个空壳了的功能么？，这样的壳还不有的是？TVBox本身就可以。还可以点播，那个多好？

**Comment by everstu** [comment]
> 可是你有源的话，我的电视不就成了一个空壳了的功能么？，这样的壳还不有的是？TVBox本身就可以。还可以点播，那个多好？

是滴，老人用只需要一个简单的壳。对于我们来说当然无所谓怎么样都可以，老人只需要点开，换台两个操作。

**Comment by snowie2000** [comment]
你可以用diyp或者派大星，那些都比mytv体验好，这个0手感很难受

**Comment by everstu** [comment]
> diyp

好的，谢谢，我去看看。

**Comment by jrffrj** [comment]
> 你可以用diyp或者派大星，那些都比mytv体验好，这个0手感很难受

有没有类似diyp或者派大星 开源的IPTV壳子？

**Comment by snowie2000** [comment]
都是不开源的，只有最初的老版本tvbox是开源的。
不放心代码的话，你也可以用tivimate，人家是商业软件，而且是外国人做的，不存在偷你源的情况

**Comment by jrffrj** [comment]
https://github.com/CatVodTVOfficial/TVBoxOSC
这个是派大星？就是tvbox的IPTV精简版

**Comment by snowie2000** [comment]
这个就是tvbox原始版。但现在市面流行的都是改版的，只有apk没有源代码，包括派大星也是闭源的

**Comment by javadodobird** [comment]
> 如果没有新功能或者增加频道，能不能让老版本正常使用，有些人就想踏踏实实的看个电视。新版本可以慢慢研究慢慢升级。看大家需要的会重新安装的。[FR]
> ### 解决方案
> 什么都不做



不能，

做不到，

因为大众的直播apk和这里作者自己写的my-tv直播apk，

工作原理工作流程其实是很不一样的，

大众的直播apk工作原理工作流程，是传统原理和传统流程，

而这里作者自己写的my-tv直播apk工作原理工作流程，是比较新颖和比较特别的原理和流程，

所以不能，

所以做不到。

**Comment by snowie2000** [comment]
听君一席话，如听一席话

**Comment by jrffrj** [comment]
https://yangshipin.cn/tv/home?pid=600001800

**Comment by jrffrj** [comment]
央视频看来又在改版 官网都挂了

**Comment by grasscase** [comment]
对啊，他自己都搞不懂了。

请求数据错误，请确认操作是否正确
点击重试  lol

**Comment by grasscase** [comment]
> 央视频看来又在改版 官网都挂了
对啊，他自己都搞不懂了

请求数据错误，请确认操作是否正确
点击重试

**Comment by grasscase** [comment]
这个软件和其他软件比，厉害之处就是快，几乎没有缓冲。

**Comment by jrffrj** [comment]
老版本已恢复正常使用

**Comment by AppleMate60pro** [comment]
> > > 节目单是写在程序里的，要更新只能安装新版本，要想老版本能一直使用就要把节目单独立出来，为了照顾国内用户要用到国内的服务，还要备案，很容易被有关部门请去喝茶，而且还要多一笔费用。
> > 
> > 
> > 你错了，mytv中根本没有节目单，不像一般的内置源的播放软件。 mytv是直接请求的yangshipin.cn中的内容，所以央视频修复了可以免费看vip的bug后，mytv也看不了了。 而央视频一直都修改他们的加密手段，人家是个网页可以随便改，不需要发布，但mytv是个客户端软件，无法热更新其中的代码，自然就播放不了了
> 
> 可是这样老人用的真的好不方便啊，我感觉能否加个自定义节目单功能？我自己在家里nas上更新解密服务就可以了。

你要是赞助一个服务器是可以不用经常更新才能看滴

**Comment by qaxc** [comment]
> 老版本已恢复正常使用

哪个版本能用

**Comment by Mashirl** [comment]
用的是央视频的源，央视那边一动当然就看不了了，看不了了那就要更新。

想要绝对稳定，那就只有买运营商的IPTV，10块钱一个月，肯定稳定。

**Comment by snowie2000** [comment]
其实是可以做到让老版本也能正常使用的，就做成像tvbox那样动态下载jar就可以了，但这样一来就必须把所有解密代码都写成java的，很明显作者并不想这么做，他有部分加密是有意写成so的

**Comment by Mashirl** [comment]
> 其实是可以做到让老版本也能正常使用的，就做成像tvbox那样动态下载jar就可以了，但这样一来就必须把所有解密代码都写成java的，很明显作者并不想这么做，他有部分加密是有意写成so的

话是这么说，但其实动态下载能实现，直接更新apk点两下安装也能实现，但问题是下载源要放在哪，放Github的话国内很多地区还是没法下载。

**Comment by snowie2000** [comment]
不是有很多github的镜像嘛，在国内速度也是可以保障的

**Comment by Mashirl** [comment]
> 不是有很多github的镜像嘛，在国内速度也是可以保障的

确实是，其实只要把这个github的更新地址换掉，换成镜像站之类的体验就会好很多。

就是不知道作者意见如何 @lizongying

**Comment by snowie2000** [comment]
直接更新不好做的，很多国内的盒子不允许apk自我更新，或者黑名单了
