### ISSUE TITLE
[BUG] 你好，没有native 和native.c 的文件，能提供一下吗？

### ISSUE THREAD

**Issue by chenguo123456** [lizongying/my-tv#840]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

clang: error: no such file or directory: 'D:/AndroidDev/my-tv-main/my-tv-main/app/src/main/cpp/native.c'

### 预期行为

想要运行起来

### 实际行为

clang: error: no such file or directory: 'D:/AndroidDev/my-tv-main/my-tv-main/app/src/main/cpp/native.c'

### 复现步骤

clang: error: no such file or directory: 'D:/AndroidDev/my-tv-main/my-tv-main/app/src/main/cpp/native.c'

### UI / OS

极米

### Android 版本

10

### 额外信息

clang: error: no such file or directory: 'D:/AndroidDev/my-tv-main/my-tv-main/app/src/main/cpp/native.c'

**Comment by sobergou** [comment]
源码作者估计不会提供，构建项目改下配置就可以了

**Comment by chenguo123456** [comment]
修改后是不是就不能用.jni下的方法了？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月4日(周二) 晚上6:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lizongying/my-tv] [BUG] 你好，没有native 和native.c 的文件，能提供一下吗？ (Issue #840)




 
源码作者估计不会提供，构建项目改下配置就可以了
 
&mdash;

**Comment by sobergou** [comment]
不清楚你具体问题，默认构建源码，有个宏定义，不知道在哪里配置，强制改一下，可以构建动态库

**Comment by chenguo123456** [comment]
要不咱们加一下微信？😂


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月4日(周二) 晚上6:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lizongying/my-tv] [BUG] 你好，没有native 和native.c 的文件，能提供一下吗？ (Issue #840)




 
不清楚你具体问题，默认构建源码，有个宏定义，不知道在哪里配置，强制改一下，可以构建动态库
 
&mdash;

**Comment by winkyz** [comment]
我也想自己编写一份native.c 但是我不知道里面写了哪些内容， 请问作者是否可以给个模板。我的盒子跑不起来，也等不到更新， 我想自己尝试解决一下问题

**Comment by sobergou** [comment]
> 要不咱们加一下微信？😂
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年6月4日(周二) 晚上6:21 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [lizongying/my-tv] [BUG] 你好，没有native 和native.c 的文件，能提供一下吗？ (Issue #840) 不清楚你具体问题，默认构建源码，有个宏定义，不知道在哪里配置，强制改一下，可以构建动态库 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

https://www.zeppos.tech/t/topic/2821/15?u=sober   正在研究这个项目

**Comment by sobergou** [comment]
> 我也想自己编写一份native.c 但是我不知道里面写了哪些内容， 请问作者是否可以给个模板。我的盒子跑不起来，也等不到更新， 我想自己尝试解决一下问题

![image](https://github.com/lizongying/my-tv/assets/50661423/cbff69b7-61ff-42c5-b85e-2357c8f414d5)

这个是不是可以用

**Comment by jrffrj** [comment]
libnative.so自己实现很容易
Java_com_lizongying_mytv_api_Encryptor_encrypt
AES-128-CBC加密  对应key:48e5918a74ae21c972b90cce8af6c8be iv:9a7e7d23610266b1d9fbf98581384d92
Java_com_lizongying_mytv_api_Encryptor_encrypt2
新增加的wasm加密，对应字典查询
Java_com_lizongying_mytv_api_Encryptor_hash
Java_com_lizongying_mytv_api_Encryptor_hash2
看着就是MD5加密

**Comment by sobergou** [comment]
> libnative.so自己实现很容易 Java_com_lizongying_mytv_api_Encryptor_encrypt AES-128-CBC加密 对应key:48e5918a74ae21c972b90cce8af6c8be iv:9a7e7d23610266b1d9fbf98581384d92 Java_com_lizongying_mytv_api_Encryptor_encrypt2 新增加的wasm加密，对应字典查询 Java_com_lizongying_mytv_api_Encryptor_hash Java_com_lizongying_mytv_api_Encryptor_hash2 看着就是MD5加密

可以认证成功不

**Comment by sobergou** [comment]
> libnative.so自己实现很容易 Java_com_lizongying_mytv_api_Encryptor_encrypt AES-128-CBC加密 对应key:48e5918a74ae21c972b90cce8af6c8be iv:9a7e7d23610266b1d9fbf98581384d92 Java_com_lizongying_mytv_api_Encryptor_encrypt2 新增加的wasm加密，对应字典查询 Java_com_lizongying_mytv_api_Encryptor_hash Java_com_lizongying_mytv_api_Encryptor_hash2 看着就是MD5加密

目前判断作者在视频流认证模块加了apk打包key，一般人打包的apk，视频流认证模块是不正常工作的
![image](https://github.com/lizongying/my-tv/assets/50661423/73ee456c-99ad-453c-b264-87cf4014ece1)

![image](https://github.com/lizongying/my-tv/assets/50661423/acf99e7f-a088-47af-8057-8656e6a2cdb1)

**Comment by sobergou** [comment]
> 我也想自己编写一份native.c 但是我不知道里面写了哪些内容， 请问作者是否可以给个模板。我的盒子跑不起来，也等不到更新， 我想自己尝试解决一下问题

有高手实现了
![image](https://github.com/lizongying/my-tv/assets/50661423/fc957aa8-f684-4008-961a-af8fa71db1d2)

**Comment by winkyz** [comment]
> > 我也想自己编写一份native.c 但是我不知道里面写了哪些内容， 请问作者是否可以给个模板。我的盒子跑不起来，也等不到更新， 我想自己尝试解决一下问题
> 
> 有高手实现了 ![image](https://private-user-images.githubusercontent.com/50661423/336666430-fc957aa8-f684-4008-961a-af8fa71db1d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NTU0NjYsIm5iZiI6MTcxNzU1NTE2NiwicGF0aCI6Ii81MDY2MTQyMy8zMzY2NjY0MzAtZmM5NTdhYTgtZjY4NC00MDA4LTk2MWEtYWY4ZmE3MWRiMWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDAyMzkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZjU5MGZkOTE0YzcxMjY4MjZjYzg4YmYxOWIwMjUyMjJhODY3ZWM5MzljZjJkZDI0NjVhNjMzOWI5YzczMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PEHwCWFrZYR7WJ2sgUWMod5E4g4QcS71Ov2j6YMCpKg)

你的图我看不到

**Comment by sobergou** [comment]
> > > 我也想自己编写一份native.c 但是我不知道里面写了哪些内容， 请问作者是否可以给个模板。我的盒子跑不起来，也等不到更新， 我想自己尝试解决一下问题
> > 
> > 
> > 有高手实现了 ![image](https://private-user-images.githubusercontent.com/50661423/336666430-fc957aa8-f684-4008-961a-af8fa71db1d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NTU0NjYsIm5iZiI6MTcxNzU1NTE2NiwicGF0aCI6Ii81MDY2MTQyMy8zMzY2NjY0MzAtZmM5NTdhYTgtZjY4NC00MDA4LTk2MWEtYWY4ZmE3MWRiMWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDAyMzkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZjU5MGZkOTE0YzcxMjY4MjZjYzg4YmYxOWIwMjUyMjJhODY3ZWM5MzljZjJkZDI0NjVhNjMzOWI5YzczMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PEHwCWFrZYR7WJ2sgUWMod5E4g4QcS71Ov2j6YMCpKg)
> 
> 你的图我看不到

你是工程师的话，     https://www.zeppos.tech/t/topic/2821?u=sober，     有调试方法，可以自己适配下安卓设备，论坛有写这个的高手，可以咨询下

**Comment by winkyz** [comment]
我的想法很简单 就是能编译跑起来，然后去找我盒子崩溃的问题， 其他部分不打算研究。 谁能帮我编译跑起来就好了。 主要就是内地台要进入播放状态时会崩溃，如果认证错误啥的不播放， 他也不会崩溃的

**Comment by sobergou** [comment]
> 我的想法很简单 就是能编译跑起来，然后去找我盒子崩溃的问题， 其他部分不打算研究。 谁能帮我编译跑起来就好了。 主要就是内地台要进入播放状态时会崩溃，如果认证错误啥的不播放， 他也不会崩溃的

你在论坛发下你安卓设备的信息，可以尝试帮你解决下

**Comment by lizongying** [comment]
也是為了大家能多用幾天，加密不複雜，全放出來也不太合適。
加個參數，應該能跑起來，只是無法播放。
./gradlew assembleRelease -PIS_SO_BUILD=false

**Comment by mianyunjianshi** [comment]
> libnative.so自己实现很容易 Java_com_lizongying_mytv_api_Encryptor_encrypt AES-128-CBC加密 对应key:48e5918a74ae21c972b90cce8af6c8be iv:9a7e7d23610266b1d9fbf98581384d92 Java_com_lizongying_mytv_api_Encryptor_encrypt2 新增加的wasm加密，对应字典查询 Java_com_lizongying_mytv_api_Encryptor_hash Java_com_lizongying_mytv_api_Encryptor_hash2 看着就是MD5加密

能直接给示例不

**Comment by mianyunjianshi** [comment]
> https://www.zeppos.tech/t/topic/2821/15?u=sober 正在研究这个项目

 这个项目地址zeppos登陆不了，有直接下载的链接吗
