### ISSUE TITLE
魔白盒401a闪退[BUG] 

### ISSUE THREAD

**Issue by denchuan1969** [lizongying/my-tv#841]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

这个版本211还有201，魔白盒401a(安卓9)点不进去，一点就退。手机(安卓11)。

### 预期行为

运行正常

### 实际行为

点击闪退。

### UI / OS

魔白盒401a

### Android 版本

9

**Comment by NekoEffect** [comment]
a311-1sa也会闪退

**Comment by yoholo** [comment]
CM311-1A 也闪退

**Comment by Kawasaki2024** [comment]
除了手机不闪退，盒子都闪退，中兴B863

**Comment by Rekoe** [comment]
晶晨L3 L3B 安卓9系列都闪退

**Comment by hzw102** [comment]
我用的是奇异果盒子，点到那个外国频道就机顶盒重启了……

**Comment by sunnysu0608** [comment]
> 我用的是奇异果盒子，点到那个外国频道就机顶盒重启了……

https://share.weiyun.com/psHu2tOK
这个版本永远有效

**Comment by lizongying** [comment]
可以提供下錯誤信息，方便排查
