### ISSUE TITLE
2.1.1 版本又 G 了。。。

### ISSUE THREAD

**Issue by 743859910** [lizongying/my-tv#843]

**Comment by taddyboy** [comment]
今天早上又不能用了

**Comment by 743859910** [comment]
> 今天早上又不能用了

昨天下午6点多还正常，但今天凌晨2点多打开时，又显示认证状态错误

**Comment by Licolas** [comment]
昨天下午下载的，装上就是认证状态错误

**Comment by 743859910** [comment]
> 昨天下午下载的，装上就是认证状态错误

我昨天从中午12点看到下午六点,今天凌晨两点打开就显示认证状态错误
