### ISSUE TITLE
[FR]  认证状态错误，开发维护教程，更多的人一起维护起来，目前主要在libnative.so的认证处理上经常出问题

### ISSUE THREAD

**Issue by sobergou** [lizongying/my-tv#844]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

使用稳定性

**Comment by sobergou** [comment]
开发维护教程：https://www.zeppos.tech/t/topic/2821?u=sober

![image](https://github.com/lizongying/my-tv/assets/50661423/46c55700-df0d-405c-91ac-f7ad12995538)

**Comment by PandaRyshan** [comment]
好事啊，如果有能力修复的话，可以提个PR等合并呗，或者Fork完了自己Release也行啊，都挺好的

**Comment by sobergou** [comment]
> 好事啊，如果有能力修复的话，可以提个PR等合并呗，或者Fork完了自己Release也行啊，都挺好的

不是过年为了看春晚，都不知道现在看个电视挺难的

**Comment by PandaRyshan** [comment]
> 不是过年为了看春晚，都不知道现在看个电视挺难的

是的，我也是为了看春晚发现这个的。现在基本上家里人一周也就看一次电视，装了好几个app换着来，不是经常看的话的确不太值得从运营商那装了。

**Comment by sobergou** [comment]
> > 不是过年为了看春晚，都不知道现在看个电视挺难的
> 
> 是的，我也是为了看春晚发现这个的。现在基本上家里人一周也就看一次电视，装了好几个app换着来，不是经常看的话的确不太值得从运营商那装了。

我用的投影仪，电视家不能用后，官方有个app可以看电视直播，关键问题是不是高清源收费，是只要看就收费

**Comment by sypiao97** [comment]
> > > 不是过年为了看春晚，都不知道现在看个电视挺难的
> > 
> > 
> > 是的，我也是为了看春晚发现这个的。现在基本上家里人一周也就看一次电视，装了好几个app换着来，不是经常看的话的确不太值得从运营商那装了。
> 
> 我用的投影仪，电视家不能用后，官方有个app可以看电视直播，关键问题是不是高清源收费，是只要看就收费

请问什么电视app可以付费看电视直播？三天两头被封对父母来说比较难受，我想要不付点钱也行。

**Comment by raincao123** [comment]
> > > > 不是过年为了看春晚，都不知道现在看个电视挺难的
> > > 
> > > 
> > > 是的，我也是为了看春晚发现这个的。现在基本上家里人一周也就看一次电视，装了好几个app换着来，不是经常看的话的确不太值得从运营商那装了。
> > 
> > 
> > 我用的投影仪，电视家不能用后，官方有个app可以看电视直播，关键问题是不是高清源收费，是只要看就收费
> 
> 请问什么电视app可以付费看电视直播？三天两头被封对父母来说比较难受，我想要不付点钱也行。

运营商送的IPTV盒子不就能免费看嘛，还有华为电视自带广电的高清电视节目，每年199

**Comment by ipodgoog** [comment]
> > > > 不是过年为了看春晚，都不知道现在看个电视挺难的
> 
> > > 
> 
> > > 
> 
> > > 是的，我也是为了看春晚发现这个的。现在基本上家里人一周也就看一次电视，装了好几个app换着来，不是经常看的话的确不太值得从运营商那装了。
> 
> > 
> 
> > 我用的投影仪，电视家不能用后，官方有个app可以看电视直播，关键问题是不是高清源收费，是只要看就收费
> 
> 
> 
> 请问什么电视app可以付费看电视直播？三天两头被封对父母来说比较难受，我想要不付点钱也行。

不行 买个中九卫星看得了 买设备300元左右 免费看
