### ISSUE TITLE
[FR] 什么破软件，看两天就看不了，快回家吧

### ISSUE THREAD

**Issue by wflmy** [lizongying/my-tv#846]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

什么破软件，看两天就看不了，快回家吧

### 解决方案

什么破软件，看两天就看不了，快回家吧

### 额外信息

什么破软件，看两天就看不了，快回家吧

**Comment by dangxingzhi** [comment]
不至于 人家也是辛苦开发的

**Comment by shadowcf** [comment]
脑子有屎，人家为爱发电 不收费免费给你看。你逼逼什么

**Comment by pic5566** [comment]
你他么的赶紧卸载！开源社区不欢迎你这种缺德玩意儿！MDZZ

**Comment by javadodobird** [comment]
你太野蛮了，太不讲道理了，

第一，这apk免费的，别说1毛钱，就是1分钱都没收过你这个野蛮人的，爱用就用，不爱用就滚蛋，别在这里胡搅蛮缠，吱吱歪歪的，

第二，又不是作者故意去搞到不能看的，是被某平台和某机构用技术手段反制了，分明就是这apk现在有名了，太多人在使用了，很早就已经进入了某平台和某机构的黑名单，这apk现在已经被某平台和某机构盯得紧紧的了，请问这关作者什么事呢？

真是世界这么大，什么鸟人野蛮人都有。

**Comment by CamellyaElaina** [comment]
弱智别出来丢人现眼了^^

**Comment by OriginalEW** [comment]
找喷呢，你有什么资格说这种话，巨婴^-^

**Comment by cikichen** [comment]
有病吧，爱用不用，什么巨婴？

**Comment by he11oboy** [comment]
you can you up，no can no bb

**Comment by uzjihc** [comment]
该给你用啊，说这话，你快回家找妈妈吧

**Comment by AlbiziaJulibrissinV** [comment]
因为太巨婴感觉像是钓鱼的

**Comment by anmidii** [comment]
煞笔玩意儿.让踏马你用了?

**Comment by kimwang1978** [comment]
围观大家是怎么dis楼主的

**Comment by avoyoo** [comment]
垃圾玩意，纯属智障

**Comment by Mashirl** [comment]
推荐阅读：https://mashirl.com/2024/06/03/from-psp-to-the-psychology-of-some-netizens/

**Comment by ghost** [comment]
傻逼

**Comment by 1stSamurai** [comment]
你他妈这种傻卵只配看新闻联播和学习强国

**Comment by jameswang17** [comment]
爱用就用，不爱用就滚蛋

**Comment by sirlioniva** [comment]
能有这种言论正是说明这软件出圈才被盯上了, 什么阿猫阿狗都在用, 所以自然经常被封

**Comment by maoma946** [comment]
作者不用管这个弱质，别在意他说的屁话

**Comment by gbcp** [comment]
老鼠屎

**Comment by Timerunning** [comment]
垃圾玩意，纯属智障

**Comment by zhascg** [comment]
这煞笔哪儿来的，赶紧滚，别给你父母丢脸。

**Comment by qdpatriotcn** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的功能请求。
> * [x]  这个建议不会背离 my-tv 的初衷。
> 
> ### 改进目的
> 什么破软件，看两天就看不了，快回家吧
> 
> ### 解决方案
> 什么破软件，看两天就看不了，快回家吧
> 
> ### 额外信息
> 什么破软件，看两天就看不了，快回家吧

煞笔玩意，草拟麻痹的。有人生没人养的初生。si全家的玩意。祝你全家过不过今晚。你马勒戈壁的，怎么有你这种沙茶。草拟麻痹的。

**Comment by Cvliug9006** [comment]
你这种贱种从哪来的勇气，伸手要还骂人的，贱狗，想体验好花钱买广电的去啊，充VIP啊，别人免费给你用还让你骂？操你妈。

**Comment by woshichenghaibo** [comment]
傻叉？不要钱不放广告，怎么得罪你了？

**Comment by cq10086123** [comment]
最恶心的就是这种人，喜欢白嫖，白嫖得还理直气壮。太忒么恶心了啊。要是GitHub出个黑名单，这种必须拉黑

**Comment by MaxYANDev** [comment]
傻逼

**Comment by ghost** [comment]
> 你他妈这种傻卵只配看新闻联播和学习强国

笑到你爸了，龟孙这就破防了

**Comment by Neil-2322** [comment]
你行你上啊，光骂算什么本事

**Comment by Yahiuu** [comment]
你为什么不去装个有线电视？你个巨婴，脑子有病吧你？

**Comment by zhudashi** [comment]
你tm可真是个畜生啊，这种逼话都说得出来，畜生

**Comment by nichousha123** [comment]
百度搜不到你，搜狗一定能搜到

**Comment by Ning1111** [comment]
傻逼

**Comment by KloppWH** [comment]
你妈凉了

**Comment by ForLovelj** [comment]
白嫖狗这么理直气壮？有娘生没娘教的玩意儿。

**Comment by chjshi** [comment]
看到这么多人喷我就放心了。

**Comment by 0975mingfeng** [comment]
傻逼玩意，你来做一个试试。

**Comment by JoeNik** [comment]
看完评论、舒服了
