### ISSUE TITLE
[BUG]2.1.6机顶盒上面闪退

### ISSUE THREAD

**Issue by psumycom** [lizongying/my-tv#847]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

打開就是一閃而過，完全看不到任何介面就消失不見了，什麼都看不見相當於閃退的意思吧，從2.1.0--2.1.1--2.1.2這幾個版本都是一樣的閃退。

### 预期行为

打開就是一閃而過，完全看不到任何介面就消失不見了，什麼都看不見相當於閃退的意思吧，從2.1.0--2.1.1--2.1.2這幾個版本都是一樣的閃退。

### 实际行为

打開就是一閃而過，完全看不到任何介面就消失不見了，什麼都看不見相當於閃退的意思吧，從2.1.0--2.1.1--2.1.2這幾個版本都是一樣的閃退。

### UI / OS

魔百盒M401

### Android 版本

9

**Comment by sobergou** [comment]
我帮你出个版本你试试

**Comment by psumycom** [comment]
> 我帮你出个版本你试试

怎麼試？

**Comment by sobergou** [comment]
> > 我帮你出个版本你试试
> 
> 怎麼試？

试一下临时包2.1.2-debug，看会不会闪退，https://www.zeppos.tech/t/topic/2821?u=sober

**Comment by soberGou** [comment]
> > > 我帮你出个版本你试试
> > 
> > 
> > 怎麼試？
> 
> ![image](https://private-user-images.githubusercontent.com/50661423/337545465-defb0b0e-ddd0-4461-9bca-53450f5e4ebd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDExNDksIm5iZiI6MTcxNzc0MDg0OSwicGF0aCI6Ii81MDY2MTQyMy8zMzc1NDU0NjUtZGVmYjBiMGUtZGRkMC00NDYxLTliY2EtNTM0NTBmNWU0ZWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA2MTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNDIwMjJmYTZhZDI4YzlmZjdlMGQ5NWQ4ZDU2ZjQyMmRhYmYyNzA4NTFiZjEyMzI1MWQ0OTMyNmUwYjBiOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M_Y-dm3mRrfafuhRyFN_EBxO0_xMu9t9O6XZWO4XwIc)
> 
> 安卓9上确实有问题，我尝试帮你适配个，关注下https://www.zeppos.tech/t/topic/2821?u=sober

**Comment by psumycom** [comment]
老大发布的2.1.4试了还是闪退

**Comment by psumycom** [comment]
> > > 我帮你出一个版本你试试
> > 
> > 
> > 怎么试？
> 
> 试一下临时包2.1.2-debug，看会不会闪退，https://www.zeppos.tech/t/topic/2821?u=sober

一样会闪退

**Comment by Ba1ker** [comment]
> > > 我帮你出个版本你试试
> > 
> > 
> > 怎麼試？
> 
> 试一下临时包2.1.2-debug，看会不会闪退，https://www.zeppos.tech/t/topic/2821?u=sober

你提供的这个版本也闪退，我也是安卓9，可能是系统版本原因

**Comment by sobergou** [comment]
> > > > 我帮你出个版本你试试
> > > 
> > > 
> > > 怎麼試？
> > 
> > 
> > 试一下临时包2.1.2-debug，看会不会闪退，https://www.zeppos.tech/t/topic/2821?u=sober
> 
> 你提供的这个版本也闪退，我也是安卓9，可能是系统版本原因

你的设备完整型号，系统参数的页面发个照片，抽时间研究下

**Comment by sobergou** [comment]
> > > > 我帮你出个版本你试试
> > > 
> > > 
> > > 怎麼試？
> > 
> > 
> > 试一下临时包2.1.2-debug，看会不会闪退，https://www.zeppos.tech/t/topic/2821?u=sober
> 
> 你提供的这个版本也闪退，我也是安卓9，可能是系统版本原因

你的设备完整型号，系统参数的页面发个照片，抽时间研究下

**Comment by yzb5158** [comment]
我的也是同样问题，之前版本不闪退。现在打开就闪退，安卓9

**Comment by psumycom** [comment]
> > > > > 我帮你出个版本你试试
> > > > 
> > > > 
> > > > 怎麼試？
> > > 
> > > 
> > > 试一下临时包2.1.2-debug，看会不会闪退，https://www.zeppos.tech/t/topic/2821?u=sober
> > 
> > 
> > 你提供的这个版本也闪退，我也是安卓9，可能是系统版本原因
> 
> 你的设备完整型号，系统参数的页面发个照片，抽时间研究下

所有的网络机顶盒都闪退，打不开软件界面

**Comment by Ba1ker** [comment]
> > > > > 我帮你出个版本你试试
> > > > 
> > > > 
> > > > 怎麼試？
> > > 
> > > 
> > > 试一下临时包2.1.2-debug，看会不会闪退，https://www.zeppos.tech/t/topic/2821?u=sober
> > 
> > 
> > 你提供的这个版本也闪退，我也是安卓9，可能是系统版本原因
> 
> 你的设备完整型号，系统参数的页面发个照片，抽时间研究下

![Uploading P20240608-105019.jpg…]()

**Comment by Ba1ker** [comment]
> > > > > 我帮你出个版本你试试
> > > > 
> > > > 
> > > > 怎麼試？
> > > 
> > > 
> > > 试一下临时包2.1.2-debug，看会不会闪退，https://www.zeppos.tech/t/topic/2821?u=sober
> > 
> > 
> > 你提供的这个版本也闪退，我也是安卓9，可能是系统版本原因
> 
> 你的设备完整型号，系统参数的页面发个照片，抽时间研究下
![c2635eb91510c3f97d19f0bb50d1b24](https://github.com/lizongying/my-tv/assets/145630915/ad9e2197-0e5d-4435-a6bc-67eb8806d8fd)

**Comment by psumycom** [comment]
看來老大最近沒有時間處理閃退的問題了，重心應該放在解決無法播放的問題上了

**Comment by psumycom** [comment]
2.16依然閃退，還在耐心等待中

**Comment by sunnysu0608** [comment]
> > 我帮你出个版本你试试
> 
> 怎麼試？

https://share.weiyun.com/psHu2tOK
这个版本永远有效

**Comment by yzb5158** [comment]
> > > 我帮你出个版本你试试
> > 
> > 
> > 怎麼試？
> 
> https://share.weiyun.com/psHu2tOK 这个版本永远有效

很多台都失效了 打不开

**Comment by psumycom** [comment]
> > > > 我帮你出个版本你试试
> > > 
> > > 
> > > 怎麼試？
> > 
> > 
> > https://share.weiyun.com/psHu2tOK 这个版本永远有效
> 
> 很多台都失效了 打不开

央視和衛視要IPV6都能看，意義不大

**Comment by sunnysu0608** [comment]
> > > > > 我帮你出个版本你试试
> > > > 
> > > > 
> > > > 怎麼試？
> > > 
> > > 
> > > https://share.weiyun.com/psHu2tOK 这个版本永远有效
> > 
> > 
> > 很多台都失效了 打不开
> 
> 央視和衛視要IPV6都能看，意義不大

这年代还没ipv6？？？

**Comment by psumycom** [comment]
> > > > > > 我帮你出个版本你试试
> > > > > 
> > > > > 
> > > > > 怎麼試？
> > > > 
> > > > 
> > > > https://share.weiyun.com/psHu2tOK 这个版本永远有效
> > > 
> > > 
> > > 很多台都失效了 打不开
> > 
> > 
> > 央視和衛視要IPV6都能看，意義不大
> 
> 这年代还没ipv6？？？

還真沒有，估計有ipv6的占少數吧

**Comment by 80608989** [comment]
2.1.6  版本卡死了，一直播放错误。

**Comment by lizongying** [comment]
可以提供下錯誤信息，方便排查
