### ISSUE TITLE
[BUG] 从2.1.0和2.1.1和2.1.2打开都闪退，我的系统是安卓9.0的

### ISSUE THREAD

**Issue by psuitxdx** [lizongying/my-tv#848]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

[BUG] 从2.1.0和2.1.1和2.1.2打开都闪退，我的系统是安卓9.0的

### 预期行为

[BUG] 从2.1.0和2.1.1和2.1.2打开都闪退，我的系统是安卓9.0的

### 实际行为

[BUG] 从2.1.0和2.1.1和2.1.2打开都闪退，我的系统是安卓9.0的

### 复现步骤

[BUG] 从2.1.0和2.1.1和2.1.2打开都闪退，我的系统是安卓9.0的

### UI / OS

魔百和

### Android 版本

9

### 额外信息

[BUG] 从2.1.0和2.1.1和2.1.2打开都闪退，我的系统是安卓9.0的

**Comment by sobergou** [comment]
#847

**Comment by sunnysu0608** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的 bug report。
> * [x]  我正在使用本软件的最新版本。
> 
> ### my-ty 版本
> 通用版
> 
> ### Bug 描述
> [BUG] 从2.1.0和2.1.1和2.1.2打开都闪退，我的系统是安卓9.0的
> 
> ### 预期行为
> [BUG] 从2.1.0和2.1.1和2.1.2打开都闪退，我的系统是安卓9.0的
> 
> ### 实际行为
> [BUG] 从2.1.0和2.1.1和2.1.2打开都闪退，我的系统是安卓9.0的
> 
> ### 复现步骤
> [BUG] 从2.1.0和2.1.1和2.1.2打开都闪退，我的系统是安卓9.0的
> 
> ### UI / OS
> 魔百和
> 
> ### Android 版本
> 9
> 
> ### 额外信息
> [BUG] 从2.1.0和2.1.1和2.1.2打开都闪退，我的系统是安卓9.0的

https://share.weiyun.com/psHu2tOK
这个版本永远有效

**Comment by lrf6997** [comment]
我也是，电脑模拟器上可以安装，机顶盒9.0版本安装上去闪退

**Comment by sunnysu0608** [comment]
> 我也是，电脑模拟器上可以安装，机顶盒9.0版本安装上去闪退

https://share.weiyun.com/psHu2tOK
这个版本永远有效

**Comment by tasty007** [comment]
> > 我也是，电脑模拟器上可以安装，机顶盒9.0版本安装上去闪退
> 
> https://share.weiyun.com/psHu2tOK 这个版本永远有效

可以分享个阿里或者夸克网盘吗...链接点开是空的

**Comment by lizongying** [comment]
#896
