### ISSUE TITLE
[BUG] 2.1.4 认证状态错误

### ISSUE THREAD

**Issue by haser72** [lizongying/my-tv#849]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

2.1.4 认证状态错误

### 预期行为

2.1.4 认证状态错误

### 实际行为

2.1.4 认证状态错误

### UI / OS

XIAOMI

### Android 版本

12

### 额外信息

2.1.4 认证状态错误

**Comment by ahjdzx** [comment]
+1

**Comment by zkun1970** [comment]
+1

**Comment by zhmstar0310** [comment]
+1
现在出现这个问题的频率越来越高了

**Comment by QiTianQingShui** [comment]
+1

**Comment by NI-Enrique** [comment]
+1

**Comment by ericlian319** [comment]
+1

**Comment by xiaoxiaoadmin** [comment]
不行，那个debug版也不行。一直认证错误。其实应该是因为直播源失效吧，好像直播源地址一直变

**Comment by jrffrj** [comment]
央视频今天第二次更新。这节奏看来这个项目要黄了

**Comment by sunnysu0608** [comment]
> 央视频今天第二次更新。这节奏看来这个项目要黄了

是不是央视的技术人员跟作者杠上了？？？？真的是神仙打架，我们吃亏

**Comment by chuan511** [comment]
+1   我是个文盲，通过自己服务器做一个跳转会不会好点，大家共同维护，失效了自动切换。

**Comment by he11oboy** [comment]
我估计这个项目已经被盯上了，甚至这个帖子也在被广电局的人盯梢，如果看到我的回复的话，我真想对盯梢的人说一句，fuck off！

**Comment by gyzenger** [comment]
+1

**Comment by lizongying** [comment]
這有個問題，我做什麼，實際都是透明的，好比我明牌和人家打。沒辦法了，大家可以考慮其他軟件了，也可以用[我的電視·〇](https://github.com/lizongying/my-tv-0)，現在iptv每個省都是單獨的，技術參差不齊，不至於這麼被動，相比可能更穩定。

**Comment by jrffrj** [comment]
> 這有個問題，我做什麼，實際都是透明的，好比我明牌和人家打。沒辦法了，大家可以考慮其他軟件了，也可以用[我的電視·〇](https://github.com/lizongying/my-tv-0)，現在iptv每個省都是單獨的，技術參差不齊，不至於這麼被動，相比可能更穩定。

已经搞定了，你的软件不更新 我看看这次能用多久
一个星期已经改了4次了，换第三个wasm了

**Comment by sunnysu0608** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的 bug report。
> * [x]  我正在使用本软件的最新版本。
> 
> ### my-ty 版本
> 通用版
> 
> ### Bug 描述
> 2.1.4 认证状态错误
> 
> ### 预期行为
> 2.1.4 认证状态错误
> 
> ### 实际行为
> 2.1.4 认证状态错误
> 
> ### 复现步骤
> _No response_
> 
> ### UI / OS
> XIAOMI
> 
> ### Android 版本
> 12
> 
> ### 额外信息
> 2.1.4 认证状态错误

https://share.weiyun.com/psHu2tOK
这个版本永远有效
