### ISSUE TITLE
增加频道建议

### ISSUE THREAD

**Issue by FunctFan** [lizongying/my-tv#85]
您好，给软件设计和使用便捷性点赞，之前自己也开发过相应app，奈何界面设计太丑，不忍直视，请问能否多增加点电视频道，目前地方卫视频道较少，还有CHC高清频道等，感谢！

**Comment by twn1993** [comment]
是的，在这个issue下建议添加天津卫视，感谢作者维护的源，很棒！

**Comment by Ruige65730** [comment]
感谢大佬的分享，用过很多网上找的app不是卡就是延迟很高，只有大佬的所有频道都能稳定播放，就像看有线电视一样，界面方便整洁。同时希望增加北京地方频道。

**Comment by redscarful** [comment]
大佬也不知道用的啥方法，直播源是v6的，居然能在v4网下播放，求教

**Comment by ashsteins** [comment]
大佬也不知道用的啥方法，直播源是v6的，居然能在v4网下播放，求教

**Comment by ashsteins** [comment]
CHC高清三个电影频道 和 CETV教育频道 4个台建议增加

**Comment by lizongying** [comment]
@twn1993 天津已加
