### ISSUE TITLE
[FR] gitee release 无 apk

### ISSUE THREAD

**Issue by sobergou** [lizongying/my-tv#851]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

gitee release 无 apk

![image](https://github.com/lizongying/my-tv/assets/50661423/78b1f3fe-9d3f-48b3-871c-eef211a3fd31)

**Comment by lizongying** [comment]
已處理
