### ISSUE TITLE
认证错误[BUG] 

### ISSUE THREAD

**Issue by changfutao** [lizongying/my-tv#852]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

一进来认证错误

### 预期行为

一进来认证错误

### 实际行为

一进来认证错误

### 复现步骤

1

### UI / OS

小米

### Android 版本

6

### 额外信息

q

**Comment by rwwang50** [comment]
认证状态错误 +1
v2.1.4
N1盒子

**Comment by xiaoyuan1996** [comment]
认证状态错误 +1
v2.1.4
当贝盒子

**Comment by echo-layker** [comment]
认证状态错误 +1
v2.1.4 和  v2.1.2
小米电视

**Comment by ZCCalmond** [comment]
认证错误+1
v2.1.4
索尼电视

**Comment by Baiang** [comment]
认证状态错误 +1
v2.1.4 和 v2.1.2
小米电视a70

**Comment by sunburst89757** [comment]
v2.1.4 认证错误
雷鸟鹏6a55  andriod11

**Comment by maoma946** [comment]
我也是，突然这两天认证错误

**Comment by meiti789789** [comment]
作者能不能把自动升级先修复一下，哪怕天天更新软件也不怕了，现在每次都是重装，3台设备 都需要装一遍，作者看到的话，麻烦能修复一下升级

**Comment by feristar** [comment]
认证错误

**Comment by CodeOceany** [comment]
认证错误，TCL

**Comment by c901008** [comment]
看了一天电视，就认证错误

**Comment by jiandanaiken** [comment]
现在所有版本都是认证错误，只有凤凰卫视能看，飞利浦电视

**Comment by bipheny** [comment]
认证错误+1，小米电视

**Comment by 80608989** [comment]
我也是 海信  mytv2.1.4版本

**Comment by jiandanaiken** [comment]
刚装了最新版本2.1.5 版本，安装完就无法打开了，一打开立马程序崩溃闪退，电视机自带安卓4.4版本

**Comment by smithfox** [comment]
从编程角度看，认证的源头唯一性信息可能有时间，IP，机器唯一码等。
需要逐一排查。
从现象看，我大胆猜测一下，很多的网络IP都是动态的，这会导致IP每天都会变化。

**Comment by kjellywang** [comment]
感谢作者这么棒的app. 我刚安装2.1.6， 绝大多数台都没问题， 但cctv-5 动态错误

**Comment by liurobin76** [comment]
作者相当勤奋啊，感谢

**Comment by lizongying** [comment]
> 作者能不能把自动升级先修复一下，哪怕天天更新软件也不怕了，现在每次都是重装，3台设备 都需要装一遍，作者看到的话，麻烦能修复一下升级

应该可以自动升级了
