### ISSUE TITLE
[BUG] 2.1.5版闪退

### ISSUE THREAD

**Issue by liangawei** [lizongying/my-tv#853]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

TCL q-mini电视
闪退

### 预期行为

TCL q-mini电视
闪退

### 实际行为

TCL q-mini电视
闪退

### 复现步骤

TCL q-mini电视
闪退

### UI / OS

TCL电视

### Android 版本

12

### 额外信息

TCL q-mini电视
闪退

**Comment by jiandanaiken** [comment]
是这样，我的飞利浦自带安卓4.4，刚升级2.1.5也是闪退，连凤凰卫视都没得看了

**Comment by tomcatzh** [comment]
小米电视4同样故障，是APP自动更新的

**Comment by lizongying** [comment]
216
