### ISSUE TITLE
2.1.5闪退2.1.5闪退2.1.5闪退[BUG] 

### ISSUE THREAD

**Issue by geyanan001** [lizongying/my-tv#854]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

专用版

### Bug 描述

2.1.5闪退2.1.5闪退2.1.5闪退

### 预期行为

修复2.1.5闪退

### 实际行为

2.1.5闪退2.1.5闪退2.1.5闪退

### 复现步骤

直接打开2.1.5闪退2.1.5闪退2.1.5闪退

### UI / OS

模拟器

### Android 版本

9

### 额外信息

修复一下2.1.5闪退2.1.5闪退

**Comment by gonggaohan** [comment]
+1

**Comment by lizongying** [comment]
216  我測試更新應該可用的
