### ISSUE TITLE
这到底在更新啥，也不搞更新日志

### ISSUE THREAD

**Issue by 743859910** [lizongying/my-tv#855]
昨天三更今天两更，我刚准备下载 215，现在216又出来

**Comment by kongxu633** [comment]
可以不用， 别催更。
作者免费用爱发电 珍惜一下。

**Comment by Huy1ngJuN** [comment]
2.1.6更新了闪退bug和认证错误bug 免费作者用爱发电 请珍惜

**Comment by 743859910** [comment]
> 可以不用， 别催更。
> 作者免费用爱发电 珍惜一下。
> 
> 

我这是催更吗？你也是搞笑吧

**Comment by psumycom** [comment]
> > 可以不用， 别催更。
> > 作者免费用爱发电 珍惜一下。
> 
> 我这是催更吗？你也是搞笑吧

作者給大家免費用，希望每一位使用者能尊重作者的勞動成果，能肯定作者的無私精神，除非你交錢了。

**Comment by 743859910** [comment]
> > > 可以不用， 别催更。
> > > 作者免费用爱发电 珍惜一下。
> > 
> > 我这是催更吗？你也是搞笑吧
> 
> 作者給大家免費用，希望每一位使用者能尊重作者的勞動成果，能肯定作者的無私精神，除非你交錢了。

我也不知道你们从哪里看到我是催更

**Comment by ItXiaoYuNeverGiveUp** [comment]
> > > > 可以不用， 别催更。
> > > > 作者免费用爱发电 珍惜一下。
> > > 
> > > 
> > > 我这是催更吗？你也是搞笑吧
> > 
> > 
> > 作者給大家免費用，希望每一位使用者能尊重作者的勞動成果，能肯定作者的無私精神，除非你交錢了。
> 
> 我也不知道你们从哪里看到我是催更

那个隔着唧唧歪歪干什么。不行就自己搞一个，开头说那话显着你啥了？嗯？

**Comment by ItXiaoYuNeverGiveUp** [comment]
> > > > 可以不用， 别催更。
> > > > 作者免费用爱发电 珍惜一下。
> > > 
> > > 
> > > 我这是催更吗？你也是搞笑吧
> > 
> > 
> > 作者給大家免費用，希望每一位使用者能尊重作者的勞動成果，能肯定作者的無私精神，除非你交錢了。
> 
> 我也不知道你们从哪里看到我是催更

那你隔着唧唧歪歪干什么。不行就自己搞一个，在这说话显着你啥了？嗯？

**Comment by 743859910** [comment]
> > > > > 可以不用， 别催更。
> > > > > 作者免费用爱发电 珍惜一下。
> > > > 
> > > > 
> > > > 我这是催更吗？你也是搞笑吧
> > > 
> > > 
> > > 作者給大家免費用，希望每一位使用者能尊重作者的勞動成果，能肯定作者的無私精神，除非你交錢了。
> > 
> > 我也不知道你们从哪里看到我是催更
> 
> 那你隔着唧唧歪歪干什么。不行就自己搞一个，在这说话显着你啥了？嗯？

我发现你们真跟一群狗一样的怎么

**Comment by 743859910** [comment]
> > > > > 可以不用， 别催更。
> > > > > 作者免费用爱发电 珍惜一下。
> > > > 
> > > > 
> > > > 我这是催更吗？你也是搞笑吧
> > > 
> > > 
> > > 作者給大家免費用，希望每一位使用者能尊重作者的勞動成果，能肯定作者的無私精神，除非你交錢了。
> > 
> > 我也不知道你们从哪里看到我是催更
> 
> 那你隔着唧唧歪歪干什么。不行就自己搞一个，在这说话显着你啥了？嗯？

我就说怎么连续更，连续更，你们就说这是催更？

**Comment by psumycom** [comment]
> > > > 可以不用， 别催更。
> > > > 作者免费用爱发电 珍惜一下。
> > > 
> > > 
> > > 我这是催更吗？你也是搞笑吧
> > 
> > 
> > 作者給大家免費用，希望每一位使用者能尊重作者的勞動成果，能肯定作者的無私精神，除非你交錢了。
> 
> 我也不知道你们从哪里看到我是催更

請問您是從哪句話看到我說你催更了呢？

**Comment by 743859910** [comment]
一群狗一样追着咬，我就说怎么连续更新，昨天更三次，今天又更两次。我刚准备下215，现在又更新216。你们居然说我这是催更，看不懂理解不了就不要说话
