### ISSUE TITLE
 [BUG] 小米电视，2.1.1版本开始一打开就是黑屏提示认证状态错误

### ISSUE THREAD

**Issue by RobinCZW** [lizongying/my-tv#858]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

打开app就是黑屏

### 预期行为

正常播放电视频道

### 实际行为

黑屏，提示一行字  认证状态错误

### UI / OS

小米电视4

### Android 版本

12

**Comment by liangjunliang** [comment]
2.1.6可以了

**Comment by Sword20140414** [comment]
> 2.1.6可以了

我的还是认证状态错误，小米电视

**Comment by ryan1051** [comment]
同认证状态错误，Sony电视

**Comment by sobergou** [comment]
#872

**Comment by lizongying** [comment]
#893
