### ISSUE TITLE
[BUG] 2.10开始全部打都打不开闪退，天天是更新了啥玩意？？

### ISSUE THREAD

**Issue by 15559006263** [lizongying/my-tv#859]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

2.1一直全正常，2.10开始全部打都打不开闪退，天天是更新了啥玩意？？就不能修复一下跟1.9的一样吗？

### 预期行为

2.1一直全正常，2.10开始全部打都打不开闪退，天天是更新了啥玩意？？就不能修复一下跟1.9的一样吗？

### 实际行为

2.1一直全正常，2.10开始全部打都打不开闪退，天天是更新了啥玩意？？就不能修复一下跟1.9的一样吗？

### 复现步骤

2.1一直全正常，2.10开始全部打都打不开闪退，天天是更新了啥玩意？？就不能修复一下跟1.9的一样吗？

### UI / OS

s905l3a

### Android 版本

9.0

### 额外信息

2.1一直全正常，2.10开始全部打都打不开闪退，天天是更新了啥玩意？？就不能修复一下跟1.9的一样吗？

**Comment by 15559006263** [comment]
2.0之前全正常，2.10开始全部打都打不开闪退，天天是更新了啥玩意？？就不能修复一下跟1.9的一样吗？

**Comment by kimwang1978** [comment]
楼主给作者打赏了多少银子伸手就要。

**Comment by 15559006263** [comment]
> 楼主给作者打赏了多少银子伸手就要。

跟你要了吗？

**Comment by psumycom** [comment]
我的天啊！怎麼可以這樣？說話不摸著自己的良心嗎？

**Comment by kddzl** [comment]
逼你用了？要饭还嫌馊？白给你用嫌这嫌那的，你怎么不自己做个软件去？

**Comment by kimwang1978** [comment]
> 我的天啊！怎麼可以這樣？說話不摸著自己的良心嗎？

巨婴都是这种思考方式

**Comment by aigezhe95** [comment]
你能懂？我专门注册了个账号回复你。就在昨晚，整整一晚上作者一直在跟广电搞事情，一晚上更了好几个版本，几乎两小时一个版本，刚发上来用了一会就被封。我为啥知道，因为我新电视回来闲得无聊在教家里人用电视，挑了半天直播时灵时不灵的，每次状态错误一上这个站就有新的版本发出来，用一会就有被封。作者几乎是用爱发电，如果你觉得这个好用，就多打赏点，鼓励一下作者比在这里批评他有用的多

**Comment by 15559006263** [comment]
这反馈的是闪退问题，关你封不封什么事情？一个个瞎几把回复

**Comment by 15559006263** [comment]
> > 我的天啊！怎麼可以這樣？說話不摸著自己的良心嗎？
> 
> 巨婴都是这种思考方式

这反馈的是闪退问题，看不惯说话一边呆着去？一个个吃饱撑着，

**Comment by 15559006263** [comment]
> > 我的天啊！怎麼可以這樣？說話不摸著自己的良心嗎？
> 
> 巨婴都是这种思考方式

这反馈的是闪退问题，看不惯说话一边呆着去？一个个吃饱撑着，

**Comment by 15559006263** [comment]
> 这反馈的是闪退问题，看不惯说话一边呆着去？一个个吃饱撑着

这反馈的是闪退问题，看不惯说话一边呆着去？一个个吃饱撑着。

**Comment by jink2018** [comment]
> > 楼主给作者打赏了多少银子伸手就要。
> 
> 跟你要了吗？

求你用了？

**Comment by 80608989** [comment]
2.1.6  版本卡死了，一直播放错误。

**Comment by lizongying** [comment]
可以提供下錯誤信息，方便排查
