### ISSUE TITLE
数字选台

### ISSUE THREAD

**Issue by 3504886962** [lizongying/my-tv#86]
大佬好，1.4.4新增加的数字选台换1台要输入01，可不可以改成输入1后等待1.5秒就可以换台

**Comment by 3504886962** [comment]
右上角的选台数字可以加个黑色阴影吗，有时候背景颜色是白的就看不见换台

**Comment by lizongying** [comment]
优先级靠后些

**Comment by lizongying** [comment]
@3504886962 最新版本已解决。阴影会考虑
