### ISSUE TITLE
[FR] 建议增加设备绑定

### ISSUE THREAD

**Issue by aigezhe95** [lizongying/my-tv#860]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

建议增加国内设备绑定，引入付费验证使用环节，将大大减少傻白甜的装机数据，个人表示支持这个软件的付费开发

**Comment by iuroc** [comment]
开源软件就别搞这个了吧，想支持作者，你可以多捐赠一点。

**Comment by aigezhe95** [comment]
> 开源软件就别搞这个了，想支持作者，你可以多捐赠一点。

有捐赠啊，就是一晚上看作者和广电打的有来有回觉得麻烦的，树大招风😂

**Comment by lizongying** [comment]
沒收費打算。
真要是商用的話，直接用iptv的源更好，還簡單。
