### ISSUE TITLE
[FR] 自动更新无法正常使用，提交了patch，能否参考优化下

### ISSUE THREAD

**Issue by sobergou** [lizongying/my-tv#861]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

自动更新无法正常使用，提交了patch，能否参考优化下

**Comment by sobergou** [comment]
#842

**Comment by meiti789789** [comment]
强烈支持

**Comment by genshinash** [comment]
强烈支持.

**Comment by windmoonwind** [comment]
有没有可能...没有墙是可以正常更新的？

**Comment by sobergou** [comment]
> 有没有可能...没有墙是可以正常更新的？

目前除了网络，主要是权限申请的处理，动态申请不成功，如果判断权限不达标，不会进入更新流程

**Comment by Michael-he1980** [comment]
创维电视也不能在线更新，没有翻墙。强烈要求修正优化这个问题。能在线更新的话，这能提高使用体验。

**Comment by Michael-he1980** [comment]
创维电视也不能在线更新，没有翻墙。强烈要求修正优化这个问题。能在线更新的话，这能提高使用体验。
