### ISSUE TITLE
[BUG] 在機頂盒上面閃退的問題什麼時候可以解決呢？

### ISSUE THREAD

**Issue by psumycom** [lizongying/my-tv#862]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

現在每天都要打開10幾遍網頁刷新好多次看看有沒有出新版本，隨時都在關注著留言動態看看有沒有解決閃退的問題，2.0.9以後的版本都閃退，看看是不是哪裡改動的原因呢？

### 预期行为

希望在機頂盒上面不閃退，能正常使用

### 实际行为

所有的網絡機頂盒上面都閃退

### UI / OS

魔百盒M401

### Android 版本

9

**Comment by Kawasaki2024** [comment]
熬着吧，作者也挺辛苦的，但愿作者手里有安卓9的盒子吧，做好测试一下再发布，先用另一个作者的mytv

**Comment by psumycom** [comment]
> 熬着吧，作者也挺辛苦的，但愿作者手里有安卓9的盒子吧，做好测试一下再发布，先用另一个作者的mytv

另一個不會搭建，可以教一下嗎？

**Comment by yzb5158** [comment]
我的也是闪退，安卓9
