### ISSUE TITLE
2.1.6认证状态错误[BUG] 

### ISSUE THREAD

**Issue by gonggaohan** [lizongying/my-tv#863]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

2.1.6 
6.8号安装后可用，6.10开始认证状态错误

### 预期行为

2.1.6

### 实际行为

2.1.6

### UI / OS

sony

### Android 版本

12

**Comment by SunYong0821** [comment]
我也是一样的认证错误

**Comment by Su-YunLong** [comment]
2.1.6没有认证错误，卸载重装吧。

**Comment by AlbiziaJulibrissinV** [comment]
同样认证错误了

**Comment by Su-YunLong** [comment]
Thank you for you Email.I will reply to you as soon as possible.( *^_^* )您的邮件我已收到，会尽快给您回复。谢谢!!

**Comment by gonggaohan** [comment]
> 2.1.6没有认证错误，卸载重装吧。

用了两天没问题，今天不行了，重装了也一样认证错误。

**Comment by gonggaohan** [comment]
reopen

**Comment by dyw618** [comment]
我用着还是好的

**Comment by gonggaohan** [comment]
电视关了再开又可以了
