### ISSUE TITLE
[BUG] v2.0.5 ~ v2.1.6 凤凰三台可正常观看， 内地台始终闪退

### ISSUE THREAD

**Issue by winkyz** [lizongying/my-tv#865]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

凤凰三台可正常观看，切换到内地台， 播放前必闪退。 TTL 报错如下
![20240611-185440](https://github.com/lizongying/my-tv/assets/37137714/91d49f5e-5af9-455d-8949-1c09950de8f6)

getprop ro.build.version.release 命令显示版本为
4.4.2

### 预期行为

正常播放不崩溃

### 实际行为

同步好时间，播放前直接崩溃， 但凤凰三台不会崩溃。

### UI / OS

ZTE ZXV10 B860AV2.1

### Android 版本

4.4.2

**Comment by soberGou** [comment]
测试下my-tv-2.1.6-1-debug.apk，提供下adb信息，https://www.zeppos.tech/t/topic/2821?u=sober

**Comment by lizongying** [comment]
#893
