### ISSUE TITLE
[BUG] 当贝盒子H3，启动软件显示认证状态错误

### ISSUE THREAD

**Issue by acejiyu** [lizongying/my-tv#866]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

当贝盒子H3，系统为最新版本，安装MyTV，启动显示【认证状态错误】信息，无法正常显示画面

### 预期行为

正常显示电视画面

### 实际行为

显示【认证状态错误】信息

### UI / OS

当贝

### Android 版本

11

**Comment by sobergou** [comment]
#872

**Comment by lizongying** [comment]
#893
