### ISSUE TITLE
[BUG] 2.1.0--2.1.6在機頂盒上面打開全部閃退無法使用，耐心等待老大解決

### ISSUE THREAD

**Issue by psumycom** [lizongying/my-tv#867]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

移動魔百盒、CM311、M401等全部都不行，打開就閃退沒有任何畫面

### 预期行为

希望下一個版本能解決閃退的問題

### 实际行为

網絡機頂盒上面打不開沒有任何提示，屬於閃退的一種

### UI / OS

魔百盒M401

### Android 版本

9

**Comment by hezhongfeng** [comment]
我这也是闪退
