### ISSUE TITLE
[FR] 闪退问题，大家留下详细设备型号，系统信息，协助测试验证，尝试帮大家解决

### ISSUE THREAD

**Issue by sobergou** [lizongying/my-tv#869]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

设备兼容性

**Comment by sobergou** [comment]
闪退设备信息收集，https://www.zeppos.tech/t/topic/2821?u=sober

**Comment by soberGou** [comment]
设备信息收集，https://www.zeppos.tech/t/topic/2821?u=sober

**Comment by winkyz** [comment]
盒子型号: ZTE ZXV10 B860AV2.1     安卓: 4.4.2     从 2.0.5 到 2.1.6 都是内地台会闪退， 我可以帮忙提供测试信息， 麻烦快点解决呀。 等了很久了

**Comment by soberGou** [comment]
> 2.1.6
