### ISSUE TITLE
在github上获取静态url，写了这样的代码，不知道是否起到参考作用。（不太会写kt/java代码）

### ISSUE THREAD

**Issue by SingerLan** [lizongying/my-tv#87]
private fun readTxt(urlString: String): String
    {
        var reader: BufferedReader? = null
        var inputStream: InputStream? = null
        var connection: HttpURLConnection? = null
            try
        {
            val url = URL(urlString)
            connection = url.openConnection() as HttpURLConnection
            inputStream = connection.inputStream
            reader = BufferedReader(InputStreamReader(inputStream))

            val stringBuilder = StringBuilder()
            var line: String?
            while (reader.readLine().also { line = it } != null) {
                stringBuilder.append(line).append("\n")
            }

            println("Content of the file:\n$stringBuilder")
            return stringBuilder.toString()
        }
        catch (e: java.lang.Exception)
        {
            e.printStackTrace()
        }
        finally
        {
            reader?.close();
            inputStream?.close();
            connection?.disconnect();
        }
        return ""
    }
![image](https://github.com/lizongying/my-tv/assets/44799711/4438f05a-7b7e-413b-8293-e63a329da690)
![image](https://github.com/lizongying/my-tv/assets/44799711/806f9693-8429-4b57-9f93-6dfcfb499f5f)

**Comment by Yvonne0827** [comment]
借楼问一下，我在本地编译时提示C/C++:   Cannot find source file: src/main/cpp/native.c，时确实少提交了这个文件吗？

**Comment by SingerLan** [comment]
https://github.com/lizongying/my-tv/issues/82

**Comment by lizongying** [comment]
本项目使用的非静态地址

**Comment by liuxinlink** [comment]
> 借楼问一下，我在本地编译时提示C/C++: Cannot find source file: src/main/cpp/native.c，时确实少提交了这个文件吗？

最后有解决吗，我也是遇到这个问题
