### ISSUE TITLE
[BUG] 希望能有一个稳定的版本，提升视频清晰度，除了央视8k，其他都不太清晰

### ISSUE THREAD

**Issue by vipliucheng** [lizongying/my-tv#870]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

希望大佬有空了，可以搞搞稳定版本，或者能在线升级app，也可以找几个大佬一起维护。后续出付费版本，我愿意支持！

### 预期行为

更稳定，更好用

### 实际行为

大佬加油

### UI / OS

海信

### Android 版本

忘了啥版本

**Comment by zhascg** [comment]
清晰度还真不是作者能决定的

**Comment by sobergou** [comment]
目前是720p，1080p源端就是vip付费的，一月30元

**Comment by Tsubamei** [comment]
没有对应清晰度的免费源

**Comment by sobergou** [comment]
> 没有对应清晰度的免费源

看你看什么内容，现在看的内容只有中央电视台有版权，高清的免费源，现在看的内容应该没有，可以找找

**Comment by sobergou** [comment]
#875

**Comment by blackshow** [comment]
你以为作者不想稳定吗🤣

**Comment by AppleMate60pro** [comment]
没有稳定版，永远也不会有。除非你提供服务器

**Comment by lizongying** [comment]
#896
