### ISSUE TITLE
2.16版本闪退[BUG] 

### ISSUE THREAD

**Issue by marcoz0214** [lizongying/my-tv#878]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

刚下载还能用，两天后就闪退了。卸载吧，太烦了，隔两天就要更新，就不能自动切换直播源吗，付费我也可以接受。垃圾啊

### 预期行为

闪退

### 实际行为

闪退

### UI / OS

vivo

### Android 版本

14

**Comment by runing25mins** [comment]
强行换到其他台也是显示“状态错误”

**Comment by adamzyg** [comment]
一言难尽啊

**Comment by runing25mins** [comment]
2.1.6版本坚持了一个星期左右就崩溃了

**Comment by LabmenNo001** [comment]
同闪退

**Comment by sobergou** [comment]
2.1.6-13-nolog-debug.apk修复闪退问题 #877

**Comment by feristar** [comment]
闪退

**Comment by yxhy1010** [comment]
又挂了

**Comment by yxhy1010** [comment]
挂了

**Comment by pan985** [comment]
昨晚还能看的，今晚就挂了

**Comment by haser72** [comment]
同闪退

**Comment by wangyeming** [comment]
大哥，为啥crash不能自动上报，还非要用户手动去系统目录下面找文件发给你，电视机哪有文件管理器啊...虽然很感谢，但咱们这个apk做的属实是太糙了

**Comment by zhascg** [comment]
免费看电视就是这样，因为广电不允许。既然收费你也愿意，那你怎么不去开通有线电视呢，多安逸啊，何必受这罪呢。

**Comment by Cui-Kexin** [comment]
安卓tv安装后，点击去出现CCTV1,就会闪退；手机安装只能观看凤凰卫视，其他的还是看不了，点击去黑屏状态。
大佬加加油

**Comment by 15936349035** [comment]
华为鸿蒙4，apk安装后没几天就状态错误无法播放，，，有没稳定点的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月19日 09:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [lizongying/my-tv] 2.16版本闪退[BUG]  (Issue #878) |

安卓tv安装后，点击去出现CCTV1,就会闪退；手机安装只能观看凤凰卫视，其他的还是看不了，点击去黑屏状态。
大佬加加油

**Comment by psumycom** [comment]
我的机顶盒是M401A，芯片是S905L3A的，一直闪退看不了，用了@soberGou老大的也是闪退

**Comment by sobergou** [comment]
> 我的机顶盒是M401A，芯片是S905L3A的，一直闪退看不了，用了@soberGou老大的也是闪退

试一下2.1.6-13-nolog-debug.apk，针对兼容性有所调整，不一定能解决你的问题，我只是在作者正式版本发布前，给大家一个可以用的临时版本，期待作者的回归

**Comment by sooxal** [comment]
这真的算是bug么，还是什么特殊技术手段，很好奇怎么做到让应用本身闪退的

**Comment by sobergou** [comment]
> 这真的算是bug么，还是什么特殊技术手段，很好奇怎么做到让应用本身闪退的

目前发现代码中有个bug，是闪退的因素之一，已经修复

**Comment by pigyn1988** [comment]
> 昨晚还能看的，今晚就挂了

我也是，昨天下午还能看的，今天早晨就彻底挂了……赶紧上网站上来看一眼，嗯果然大佬还没来得及更新呢。不管咋说得谢谢大佬，人家没赚钱天天免费给咱们更新软件，不容易。

**Comment by sobergou** [comment]
> > 昨晚还能看的，今晚就挂了
> 
> 我也是，昨天下午还能看的，今天早晨就彻底挂了……赶紧上网站上来看一眼，嗯果然大佬还没来得及更新呢。不管咋说得谢谢大佬，人家没赚钱天天免费给咱们更新软件，不容易。

2.1.6-13-nolog-debug.apk修复闪退问题 #877  可以临时用

**Comment by pigyn1988** [comment]
> > > 昨晚还能看的，今晚就挂了
> > 
> > 
> > 我也是，昨天下午还能看的，今天早晨就彻底挂了……赶紧上网站上来看一眼，嗯果然大佬还没来得及更新呢。不管咋说得谢谢大佬，人家没赚钱天天免费给咱们更新软件，不容易。
> 
> 2.1.6-13-nolog-debug.apk修复闪退问题 #877 可以临时用

非常感谢，确实好了。

**Comment by AndyXu3000** [comment]
三星手机和Sony电视同闪退

**Comment by psumycom** [comment]
> > 我的机顶盒是M401A，芯片是S905L3A的，一直闪退看不了，用了@soberGou老大的也是闪退
> 
> 试一下2.1.6-13-nolog-debug.apk，针对兼容性有所调整，不一定能解决你的问题，我只是在作者正式版本发布前，给大家一个可以用的临时版本，期待作者的回归

试了这个版本也闪退，打不开界面就消失不见了

**Comment by sobergou** [comment]
> > > 我的机顶盒是M401A，芯片是S905L3A的，一直闪退看不了，用了@soberGou老大的也是闪退
> > 
> > 
> > 试一下2.1.6-13-nolog-debug.apk，针对兼容性有所调整，不一定能解决你的问题，我只是在作者正式版本发布前，给大家一个可以用的临时版本，期待作者的回归
> 
> 试了这个版本也闪退，打不开界面就消失不见了

我想想其它方案

**Comment by Cvliug9006** [comment]
还“付费我也可以接受”，你能接受个屁，联通移动的IPTV每个月就10块钱，有的套餐还直接送IPTV，这么便宜你都不舍得花钱，还付费！！！！！！！！！

**Comment by marcoz0214** [comment]
> 还“付费我也可以接受”，你能接受个屁，联通移动的IPTV每个月就10块钱，有的套餐还直接送IPTV，这么便宜你都不舍得花钱，还付费！！！！！！！！！

你可闭嘴吧，哪里都能杠。老子想用手机看，你给老子开个10块的。

**Comment by wangyeming** [comment]
> 免费看电视就是这样，因为广电不允许。既然收费你也愿意，那你怎么不去开通有线电视呢，多安逸啊，何必受这罪呢。

app里面加个crash错误上报很难吗？连so都搞得定人，告诉我初级Android开发都能做的日志上报做不了？实在不行集成一个sdk不行吗？一点实话都不让讲？

**Comment by zhascg** [comment]
> > 免费看电视就是这样，因为广电不允许。既然收费你也愿意，那你怎么不去开通有线电视呢，多安逸啊，何必受这罪呢。
> 
> app里面加个crash错误上报很难吗？连so都搞得定人，告诉我初级Android开发都能做的日志上报做不了？实在不行集成一个sdk不行吗？一点实话都不让讲？

没人不让你讲实话，提建议可以，但是说人家垃圾之类的就不合适了。作者可没收费。

**Comment by hohhoo** [comment]
> > 免费看电视就是这样，因为广电不允许。既然收费你也愿意，那你怎么不去开通有线电视呢，多安逸啊，何必受这罪呢。
> 
> app里面加个crash错误上报很难吗？连so都搞得定人，告诉我初级Android开发都能做的日志上报做不了？实在不行集成一个sdk不行吗？一点实话都不让讲？

那你可以提交PR

**Comment by sobergou** [comment]
> 大哥，为啥crash不能自动上报，还非要用户手动去系统目录下面找文件发给你，电视机哪有文件管理器啊...虽然很感谢，但咱们这个apk做的属实是太糙了

也是刚开始抽时间维护，目前集中在通用问题视频认证失败，部分设备闪退还没顾得上，自动上报功能正在规划

**Comment by sobergou** [comment]
> > 免费看电视就是这样，因为广电不允许。既然收费你也愿意，那你怎么不去开通有线电视呢，多安逸啊，何必受这罪呢。
> 
> app里面加个crash错误上报很难吗？连so都搞得定人，告诉我初级Android开发都能做的日志上报做不了？实在不行集成一个sdk不行吗？一点实话都不让讲？

2.1.6-14-crash-debug  集成了crash上报功能

**Comment by psumycom** [comment]
> > > 免费看电视就是这样，因为广电不允许。既然收费你也愿意，那你怎么不去开通有线电视呢，多安逸啊，何必受这罪呢。
> > 
> > 
> > app里面加个crash错误上报很难吗？连so都搞得定人，告诉我初级Android开发都能做的日志上报做不了？实在不行集成一个sdk不行吗？一点实话都不让讲？
> 
> 2.1.6-14-crash-debug 集成了crash上报功能

我用14这个版本不需要收集本地log了吗？我的是M401A晶辰S905L3A芯片的机顶盒闪退的

**Comment by sobergou** [comment]
> > > > 免费看电视就是这样，因为广电不允许。既然收费你也愿意，那你怎么不去开通有线电视呢，多安逸啊，何必受这罪呢。
> > > 
> > > 
> > > app里面加个crash错误上报很难吗？连so都搞得定人，告诉我初级Android开发都能做的日志上报做不了？实在不行集成一个sdk不行吗？一点实话都不让讲？
> > 
> > 
> > 2.1.6-14-crash-debug 集成了crash上报功能
> 
> 我用14这个版本不需要收集本地log了吗？我的是M401A晶辰S905L3A芯片的机顶盒闪退的

不用

**Comment by leonardo110** [comment]
作者没收费，还骂人家做的垃圾的狗东西。你能滚多远就滚多远，不行你来维护？显得你了？

**Comment by lizongying** [comment]
#893
