### ISSUE TITLE
[BUG] 状态错误

### ISSUE THREAD

**Issue by jarodise** [lizongying/my-tv#879]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

昨天刚刚装了2.1.6的debug版，昨天能正常观看，今天所有频道都显示状态错误，无法观看。

### 预期行为

正常观看

### 实际行为

状态错误

### UI / OS

Vidda Z75

### Android 版本

12

**Comment by sobergou** [comment]
试下 #877 应该可以了

**Comment by zxf258** [comment]
刚刚装的最新版的，打开还是“状态错误”

**Comment by jarodise** [comment]
> 试下 #877 应该可以了

卸载了重装了debug带log带版本，还是状态错误，没法看。

**Comment by sobergou** [comment]
> > 试下 #877 应该可以了
> 
> 卸载了重装了debug带log带版本，还是状态错误，没法看。

2.1.6-13-nolog-debug.apk这个版本吗

**Comment by darnell7-7** [comment]
我也是状态错误诶

**Comment by wa7046** [comment]
应该是寄了，等大佬更新吧

**Comment by gavinmeng822** [comment]
12版本昨天可以看.现在显示状态错误.刚安装13版本完全没问题。全部丝滑播放.满血复活.感谢大佬.赞

**Comment by 999code** [comment]
me too

**Comment by jarodise** [comment]
> > > 试下 #877 应该可以了
> > 
> > 
> > 卸载了重装了debug带log带版本，还是状态错误，没法看。
> 
> 2.1.6-13-nolog-debug.apk这个版本吗

这个版本和带log那个版本都分别装了，都一样，“状态错误”

**Comment by Stephen-liangz** [comment]
同样问题，尝试了debug版，也是状态错误，是视频源出问题了吗？![IMG_20240619_215251.jpg](https://github.com/lizongying/my-tv/assets/13581271/12c60030-c9b4-4574-bbdf-cb70a79c770d)

**Comment by githubcxg** [comment]
https://github.com/githubcxg/TV-LBT/releases/tag/1.0

**Comment by sobergou** [comment]
> 同样问题，尝试了debug版，也是状态错误，是视频源出问题了吗？![IMG_20240619_215251.jpg](https://private-user-images.githubusercontent.com/13581271/341101053-12c60030-c9b4-4574-bbdf-cb70a79c770d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDY2MzAsIm5iZiI6MTcxODgwNjMzMCwicGF0aCI6Ii8xMzU4MTI3MS8zNDExMDEwNTMtMTJjNjAwMzAtYzliNC00NTc0LWJiZGYtY2I3MGE3OWM3NzBkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE0MTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NzZmYWVlYjk0MjJhMzFlNzFhOTkwZDEwNGVmZjFkYTAzZGQ4OTc3M2Q0MTRlYjEwZjE5N2IyNmI4ZGRmYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QSHXzh2t8hpg1qLAuxeOeiE8jhN8g-_6IC1px4s6Koc)

按一下菜单看一下，版本

![image](https://github.com/lizongying/my-tv/assets/50661423/88760563-2ca1-4ea4-9318-ae9b06ea3da1)

**Comment by Stephen-liangz** [comment]
我之前装成debug -10了。重新装了debug-14，顺利播放

**Comment by Stephen-liangz** [comment]
> > 同样问题，尝试了debug版，也是状态错误，是视频源出问题了吗？![IMG_20240619_215251.jpg](https://private-user-images.githubusercontent.com/13581271/341101053-12c60030-c9b4-4574-bbdf-cb70a79c770d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDY2MzAsIm5iZiI6MTcxODgwNjMzMCwicGF0aCI6Ii8xMzU4MTI3MS8zNDExMDEwNTMtMTJjNjAwMzAtYzliNC00NTc0LWJiZGYtY2I3MGE3OWM3NzBkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE0MTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NzZmYWVlYjk0MjJhMzFlNzFhOTkwZDEwNGVmZjFkYTAzZGQ4OTc3M2Q0MTRlYjEwZjE5N2IyNmI4ZGRmYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QSHXzh2t8hpg1qLAuxeOeiE8jhN8g-_6IC1px4s6Koc)
> 
> 按一下菜单看一下，版本
> 
> ![image](https://github.com/lizongying/my-tv/assets/50661423/88760563-2ca1-4ea4-9318-ae9b06ea3da1)
> 

我之前装成debug -10了。重新装了debug-14，顺利播放

**Comment by curlHA0ne** [comment]
android14 手机端 my-tv 2.1.6 每次更新完过几天就会提示状态错误，但是凤凰三个台一直都正常，有和我一样的吗？

**Comment by sobergou** [comment]
> android14 手机端 my-tv 2.1.6 每次更新完过几天就会提示状态错误，但是凤凰三个台一直都正常，有和我一样的吗？

试一下2.1.6-13-nolog-debug版本

**Comment by jarodise** [comment]
更新到2.1.8版可以正常观看了，感谢作者
