### ISSUE TITLE
建议for 安卓4和安卓5的，用不同的版本号

### ISSUE THREAD

**Issue by billliou** [lizongying/my-tv#88]
建议for 安卓4和安卓5的，用不同的版本号，比方安卓4的用0.4.4，安卓5的用1.4.5加以区分。

**Comment by zbby1987** [comment]
应该是用同一个版本号，加不同的后缀名，
包名也区分开

**Comment by drw2005** [comment]
支持这个建议，4.4的直接加个标识就行了，比如：my-tv-4x-v1.47.apk

**Comment by postxx** [comment]
支持，4.4的只求cctv的稳定就行了，不需要增加功能了。

**Comment by lizongying** [comment]
@billliou 应该是这样的，也最合理。但是

1.  一开始没分开。
2.  版本号区别太大，容易让大家分不清先后。
3. 待稳定后，是应该合并的。

加标识也可以。暂时轮换着升级。

实际上这个问题没多大意义，也没有多大用户规模，怎么都可以，不必纠结。
