### ISSUE TITLE
[FR] 看不了电视的朋友，请进来，我给出一个终极方案

### ISSUE THREAD

**Issue by sunnysu0608** [lizongying/my-tv#880]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

下载一个空壳子，加载这个直播源，全部齐活了
https://gitee.com/sangni2024/mingge/raw/master/1949.txt

### 解决方案

试试就知道

### 额外信息

ipv6为主

**Comment by peijs** [comment]
下载一个空壳子，加载这个直播源，全部齐活了
https://gitee.com/sangni2024/mingge/raw/master/1949.txt 这个源会不会也有被禁用的风险

**Comment by billliou** [comment]
> 下载一个空壳子，加载这个直播源，全部齐活了 https://gitee.com/sangni2024/mingge/raw/master/1949.txt 这个源会不会也有被禁用的风险

会的，这里边的央视大部分已经看不了啦。

**Comment by jimmyuncle** [comment]
非常感谢，可以了，我下载了diyp空壳，然后导入直播源！

**Comment by peijs** [comment]
空壳，在那里下载

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月20日 12:02 |
| 收件人 | lizongying/my-tv ***@***.***> |
| 抄送人 | peijs ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [lizongying/my-tv] [FR] 看不了电视的朋友，请进来，我给出一个终极方案 (Issue #880) |

非常感谢，可以了，我下载了diyp空壳，然后导入直播源！

**Comment by sunnysu0608** [comment]
> > 下载一个空壳子，加载这个直播源，全部齐活了 https://gitee.com/sangni2024/mingge/raw/master/1949.txt 这个源会不会也有被禁用的风险
> 
> 会的，这里边的央视大部分已经看不了啦。

你开通ipv6就可以

**Comment by 50lovelace** [comment]
空壳，在那里下载，下载哪个？

**Comment by sunnysu0608** [comment]
> 空壳，在那里下载，下载哪个？

进群

**Comment by sunnysu0608** [comment]
> 下载一个空壳子，加载这个直播源，全部齐活了 https://gitee.com/sangni2024/mingge/raw/master/1949.txt 这个源会不会也有被禁用的风险

不会，有人维护，

**Comment by sunnysu0608** [comment]
> > 下载一个空壳子，加载这个直播源，全部齐活了 https://gitee.com/sangni2024/mingge/raw/master/1949.txt 这个源会不会也有被禁用的风险
> 
> 会的，这里边的央视大部分已经看不了啦。

你如果是ipv6。不可能看不了

**Comment by zhascg** [comment]
空壳子是一个播放软件？

**Comment by tianxia9990** [comment]
@

**Comment by sunnysu0608** [comment]
> 空壳子是一个播放软件？
你浏览器打开那个网址，底部有qq群号

**Comment by sunnysu0608** [comment]
> 空壳子是一个播放软件？

网址底部有qq群号

**Comment by jimmyuncle** [comment]
下载DIYP空壳软件

**Comment by AppleMate60pro** [comment]
大伙安装Pn播放器https://www.pyhezi.com/pnbfp.html

**Comment by sunnysu0608** [comment]
顶一下

**Comment by kilvn** [comment]
不用折腾了，刚搜了下，有人写了个同名的，非常好用

https://github.com/yaoxieyoulei/mytv-android

**Comment by peppers26** [comment]
> 不用折腾了，刚搜了下，有人写了个同名的，非常好用
> 
> https://github.com/yaoxieyoulei/mytv-android

谢谢，好用

**Comment by lizongying** [comment]
#893

**Comment by sunnysu0608** [comment]
> #893

能不能开发安卓4，好多家庭电视升级很麻烦
