### ISSUE TITLE
惨惨惨！华为智慧屏装最新版也闪退，家里的老人已经1周没看电视了，大佬快点更新吧[BUG] 

### ISSUE THREAD

**Issue by xlon7** [lizongying/my-tv#881]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

华为智慧屏打开app闪退；

### 预期行为

华为智慧屏打开app闪退；

### 实际行为

华为智慧屏打开app闪退；

### UI / OS

华为智慧屏

### Android 版本

鸿蒙

**Comment by sobergou** [comment]
2.1.6-13-nolog-debug.apk：https://www.zeppos.tech/t/topic/2821?u=sober   试一下这个临时版本

**Comment by AppleMate60pro** [comment]
安装Pn播放器https://www.pyhezi.com/pnbfp.html

**Comment by lizongying** [comment]
#893
