### ISSUE TITLE
2.1.8也閃退，可惜老大不再更新版本了，有沒有大佬接替這個任務繼續下去呢？[BUG] 

### ISSUE THREAD

**Issue by psumycom** [lizongying/my-tv#884]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

2.1.6-2.1.7-2.1.8都閃退，機頂盒是M401A芯片是S905L3A，打開沒有任何介面直接消失不見。

### 预期行为

2.1.6-2.1.7-2.1.8都閃退，機頂盒是M401A芯片是S905L3A，打開沒有任何介面直接消失不見。

### 实际行为

2.1.6-2.1.7-2.1.8都閃退，機頂盒是M401A芯片是S905L3A，打開沒有任何介面直接消失不見。

### UI / OS

魔百盒M401

### Android 版本

9

**Comment by sobergou** [comment]
2.1.7-1-update.apk   用这个版本多运行几次，这边看能拿到你的异常信息不

**Comment by psumycom** [comment]
運行5次了看看有數據嗎？都是閃退沒有任何畫面

**Comment by sobergou** [comment]
> 運行5次了看看有數據嗎？都是閃退沒有任何畫面

晚点看看，目前测试这个数据上来同步到web时间比较慢，2.1.7-1-update.apk版本，设备正常联网

**Comment by adamzyg** [comment]
西夏直播
宝全直播
下载这两个软件，亲测都能看大部分电视。
https://www.youtube.com/watch?v=E7xWUfld1I4

**Comment by turbolam** [comment]
弄个tvbox吧，自己添加直播源能长期用，这个每次出新版本后老的就看不了还得重新安装，而且更新频率太高，一个月就得重装几次，天天折腾真没意思

**Comment by BanboLee** [comment]
@turbolam 哪里有可用的直播源啊，我之前的都用不了了

**Comment by sunnysu0608** [comment]
> @turbolam 哪里有可用的直播源啊，我之前的都用不了了

https://gitee.com/sangni2024/mingge/raw/master/1949.txt

**Comment by lrf6997** [comment]
我CM311-1A也是打不开
