### ISSUE TITLE
华为荣耀盒子中的218版目前一切正常。

### ISSUE THREAD

**Issue by ammondu** [lizongying/my-tv#886]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

华为荣耀盒子中的218版目前一切正常。

### 预期行为

不定期什么时候就没信号了。或者出现认证失败！

### 实际行为

等待大佬更新版本。

### UI / OS

华为荣耀盒子

### Android 版本

12

**Comment by lizongying** [comment]
#893
