### ISSUE TITLE
请问有计划支持 Apple TV 吗？

### ISSUE THREAD

**Issue by ssnhd** [lizongying/my-tv#889]
### 检查清单

- [ ] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

安卓上体验很好，希望增加 Apple TV 版

**Comment by javadodobird** [comment]
不可能的。

**Comment by psumycom** [comment]
老大都不準備更新版本了，也不準備繼續維護了，用別的軟件吧！

**Comment by YuchuZhang** [comment]
> 老大都不準備更新版本了，也不準備繼續維護了，用別的軟件吧！

有推荐的么

**Comment by hegan001** [comment]
接力维护my-tv项目，2.1.8-9-release版本支持cctv 3、6、8 
2.1.8-9-release，https://www.zeppos.tech/t/topic/2821/112?u=sober
注册进入西安华米论坛，可以下载my-tv最新版本。


gitee链接

https://gitee.com/sobergou/my-tv-apk

**Comment by lizongying** [comment]
#896
