### ISSUE TITLE
能否添加开机自启选项

### ISSUE THREAD

**Issue by baibaiwow** [lizongying/my-tv#89]

**Comment by baibaiwow** [comment]
照着别人的magisk模块改了一个，有需要的朋友可以试试，作用是开机自启，https://drive.google.com/file/d/1X5NQEo-y5Kk3BZZxJExuG9fL5Jo_SAHc/view?usp=sharing

**Comment by Mluocheng** [comment]
> 照着别人的magisk模块改了一个，有需要的朋友可以试试，作用是开机自启，https://drive.google.com/file/d/1X5NQEo-y5Kk3BZZxJExuG9fL5Jo_SAHc/view?usp=sharing

咋用啊

**Comment by swh3zZ** [comment]
求大佬添加开机自启功能，家里老人开机后不会调

**Comment by baibaiwow** [comment]
> > 照着别人的magisk模块改了一个，有需要的朋友可以试试，作用是开机自启，https://drive.google.com/file/d/1X5NQEo-y5Kk3BZZxJExuG9fL5Jo_SAHc/view?usp=sharing
> 
> 咋用啊，自己打包吗？ 不懂c

安卓9.0电视刷magisk，然后直接刷我这个模块就可以啦

**Comment by Luo-Ye** [comment]
太感谢大佬了，见过最流畅的直播APP.要是能添加开机自启，方便家里长辈用，就完美了

**Comment by lizongying** [comment]
最新新版本雖然加了此功能，自測是不生效的，估計大多數設備還是不支持的。

**Comment by wxjdsj** [comment]
> 最新新版本雖然加了此功能，自測是不生效的，估計大多數設備還是不支持的。

国产电视魔改的太严重了，实现起来很费劲
