### ISSUE TITLE
认证状态错误[BUG] 

### ISSUE THREAD

**Issue by Hanwu-pku** [lizongying/my-tv#891]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

打开软件后，展示认证状态错误，无法观看任何节目6月23日打开就好好的，24日打开后，就无法观看
![IMG_20240625_094931](https://github.com/lizongying/my-tv/assets/52122318/76ab2b3f-bbf9-4e81-ba0e-5fd529b3ac89)

### 预期行为

认证出了问题

### 实际行为

同上

### 复现步骤

打开软件

### UI / OS

夏普

### Android 版本

12

**Comment by sobergou** [comment]
问题已经修复，#890，使用2.1.8-7-release版本（论坛中下载）

github的项目作者上次回复已经停止维护，持续关注论坛alpha版本，部分设备闪退问题会持续尽力解决，目前在线异常问题采集系统已经上线，对采集的异常问题在逐步处理，https://www.zeppos.tech/t/topic/2821/106?u=sober

沟通平台
项目发版、问题反馈使用论坛平台而非github平台，主要受限于网络访问，部分地区普通非vpn网络无法访问github，论坛做了全球DCDN加速，全球大部分地区普通网络可以访问到

**Comment by JQJoe** [comment]
认证错误又出现了

**Comment by tsuimanlung** [comment]
一样的错误2.1.8版本

**Comment by elives0810** [comment]
同带图片的表现一样 而且2.1.6 6月21号开始 今天下了2.1.8（6月25）还是出现同样的问题

**Comment by 80608989** [comment]
![IMG_0200](https://github.com/lizongying/my-tv/assets/46585088/16c79f47-493f-44e3-917d-4cbfcfc52727)
2.1.8

**Comment by Zee-hash** [comment]
我也下载的v2.1.8，打开出现同样问题”认证状态错误“

**Comment by dongpengfei123** [comment]
2.1.8 目前还是不行报错 认证状态错误

**Comment by Zee-hash** [comment]
> 我也下载的v2.1.8，打开出现同样问题”认证状态错误“

我在这个issue的下面那个issue里找到了另一个版本 v2.1.8-8-alpha，可用，有兴趣的也可以去翻翻

**Comment by dongpengfei123** [comment]
> > 我也下载的v2.1.8，打开出现同样问题”认证状态错误“
> 
> 我在这个issue的下面那个issue里找到了另一个版本 v2.1.8-8-alpha，可用，有兴趣的也可以去翻翻

get it 亲测可用 感谢

**Comment by qcyangyang** [comment]
> > > 我也下载的v2.1.8，打开出现同样问题”认证状态错误“
> > 
> > 
> > 我在这个issue的下面那个issue里找到了另一个版本 v2.1.8-8-alpha，可用，有兴趣的也可以去翻翻
> 
> get it 亲测可用 感谢

无法安装

**Comment by gavinmeng822** [comment]
2.1.8-8-alpha.apk.最新安装这个.没问题.小米盒子.安装过程顺利.播放非常丝滑稳定。谢谢大佬们.赞赞赞.

**Comment by QiKeO** [comment]
> 2.1.8-8-alpha.apk.最新安装这个.没问题.小米盒子.安装过程顺利.播放非常丝滑稳定。谢谢大佬们.赞赞赞.

你是如何安装到小米电视盒子的，是通过手机app“小米电视助手”还是U盘安装呢？

**Comment by Nadal3** [comment]
> 问题已经修复，#890，使用2.1.8-7-release版本（论坛中下载）
> 
> github的项目作者上次回复已经停止维护，持续关注论坛alpha版本，部分设备闪退问题会持续尽力解决，目前在线异常问题采集系统已经上线，对采集的异常问题在逐步处理，https://www.zeppos.tech/t/topic/2821/106?u=sober
> 
> 沟通平台 项目发版、问题反馈使用论坛平台而非github平台，主要受限于网络访问，部分地区普通非vpn网络无法访问github，论坛做了全球DCDN加速，全球大部分地区普通网络可以访问到

雷电模拟器安装2.1.8-8使用正常，感谢。

**Comment by WM2023** [comment]
好像是 lyrics.run 网站证书过期，导致软件里相关HTTPS无法连接以获取yangshipin的特殊码

**Comment by futianhang** [comment]
> 问题已经修复，#890，使用2.1.8-7-release版本（论坛中下载）
> 
> github的项目作者上次回复已经停止维护，持续关注论坛alpha版本，部分设备闪退问题会持续尽力解决，目前在线异常问题采集系统已经上线，对采集的异常问题在逐步处理，https://www.zeppos.tech/t/topic/2821/106?u=sober
> 
> 沟通平台 项目发版、问题反馈使用论坛平台而非github平台，主要受限于网络访问，部分地区普通非vpn网络无法访问github，论坛做了全球DCDN加速，全球大部分地区普通网络可以访问到

用哪个平台发布不是主要问题，最重要的实现app内更新（最好是能自动更新），这个软件最主要的用户是老年人，尤其是给异地的老年人更新真是人世间最痛苦的事也莫过于此了233333（现解决方案是：微信视频加米家远程遥控器）

**Comment by sobergou** [comment]
> > 问题已经修复，#890，使用2.1.8-7-release版本（论坛中下载）
> > github的项目作者上次回复已经停止维护，持续关注论坛alpha版本，部分设备闪退问题会持续尽力解决，目前在线异常问题采集系统已经上线，对采集的异常问题在逐步处理，https://www.zeppos.tech/t/topic/2821/106?u=sober
> > 沟通平台 项目发版、问题反馈使用论坛平台而非github平台，主要受限于网络访问，部分地区普通非vpn网络无法访问github，论坛做了全球DCDN加速，全球大部分地区普通网络可以访问到
> 
> 用哪个平台发布不是主要问题，最重要的实现app内更新（最好是能自动更新），这个软件最主要的用户是老年人，尤其是给异地的老年人更新真是人世间最痛苦的事也莫过于此了233333（现解决方案是：微信视频加米家远程遥控器）

自动更新功能大部分设备可正常使用，部分设备因兼容性问题，无法正常使用

**Comment by alex13by** [comment]
刚更新安装还是有认证问题，把原版本卸载后再安装2.1.8-7就没问题了

**Comment by javadodobird** [comment]
各种不正常迹象来看，
这个apk已经是非常肯定进了黑名单，
被专门人员盯哨了。

**Comment by xaqingfeng** [comment]
不再修复了吗？

**Comment by billliou** [comment]
> 不再修复了吗？

2.1.8和2.1.7没有问题啊，还修复什么？

**Comment by adamzyg** [comment]
[秒看电视TV(电视直播软件)v9.2.15免费纯净版](https://www.423down.com/14385.html)

**Comment by AppleMate60pro** [comment]
> 问题已经修复，#890，使用2.1.8-7-release版本（论坛中下载）
> 
> github的项目作者上次回复已经停止维护，持续关注论坛alpha版本，部分设备闪退问题会持续尽力解决，目前在线异常问题采集系统已经上线，对采集的异常问题在逐步处理，https://www.zeppos.tech/t/topic/2821/106?u=sober
> 
> 沟通平台 项目发版、问题反馈使用论坛平台而非github平台，主要受限于网络访问，部分地区普通非vpn网络无法访问github，论坛做了全球DCDN加速，全球大部分地区普通网络可以访问到

2.1.8-9在小米电视上部分台看不了，黑屏提示播放错误

**Comment by hegan001** [comment]
接力维护my-tv项目，2.1.8-9-release版本支持cctv 3、6、8 
2.1.8-9-release，https://www.zeppos.tech/t/topic/2821/112?u=sober
注册进入西安华米论坛，可以下载my-tv最新版本。


gitee链接

https://gitee.com/sobergou/my-tv-apk

**Comment by AppleMate60pro** [comment]
脑子有坑也不看其他issues，就这还看什么电视，去画地图得了

**Comment by lizongying** [comment]
#893
