### ISSUE TITLE
[BUG] 闪退闪退 还是闪退 

### ISSUE THREAD

**Issue by yzb5158** [lizongying/my-tv#892]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

用了论坛里评论里的所有版本，都闪退。安卓9

### 预期行为

闪退

### 实际行为

闪退  

### UI / OS

移动cm311-1a 魔百和

### Android 版本

9

**Comment by sobergou** [comment]
github的项目作者上次回复已经停止维护，持续关注论坛alpha版本，部分设备闪退问题会持续尽力解决，目前在线异常问题采集系统已经上线，对采集的异常问题在逐步处理，https://www.zeppos.tech/t/topic/2821/106?u=sober

沟通平台
项目发版、问题反馈使用论坛平台而非github平台，主要受限于网络访问，部分地区普通非vpn网络无法访问github，论坛做了全球DCDN加速，全球大部分地区普通网络可以访问到

**Comment by billliou** [comment]
非常感谢@soberGou的延续开发。目前alpha版本运行稳定，在线更新因为还没有新版本所以还没测试。希望作者能够再接再励，持续进步。

**Comment by genshinash** [comment]
感谢sobergou，能加368等台么

**Comment by sobergou** [comment]
> 感谢sobergou，能加368等台么

368源端是收费观看的

**Comment by hbzmt** [comment]
> > 感谢sobergou，能加368等台么
> 
> 368源端是收费观看的

那列表里能把这几个台删掉不？

**Comment by sobergou** [comment]
代码中吗，现在应该交互界面上看不到这几个台

**Comment by genshinash** [comment]
建议参考灵犀直播 星火直播等的368台和军事科技等央视台

**Comment by sobergou** [comment]
> 建议参考灵犀直播 星火直播等的368台和军事科技等央视台

使用的是三方源，需要中继服务器一直检测更新可用源，有费用支出，其它应用都植入广告，有广告营收，这个项目没有任何营收，目前涉及费用支出，都是自费的

技术方案不一样，类似这种源，很快就失效了，连接也不稳定

![image](https://github.com/lizongying/my-tv/assets/50661423/314a4f8f-6de5-488b-ad2e-601d7efc01a5)

**Comment by soberGou** [comment]
> > 建议参考灵犀直播 星火直播等的368台和军事科技等央视台
> 
> 使用的是三方源，需要中继服务器一直检测更新可用源，有费用支出，其它应用都植入广告，有广告营收，这个项目没有任何营收，目前涉及费用支出，都是自费的

**Comment by feristar** [comment]
太容易失效了，事实证明不可行，项目可以终止了

**Comment by yyyaohhh** [comment]
刚试了alpha版本 只能看初始的中央一台，调其他台会bug。节目始终是中央一台，但左上角显示其他频道的图标。
版本：海外google tv

**Comment by javadodobird** [comment]
mytv的节目频道和操作方式，
太类似于gd有线电视和dx，lt，ydIPTV的节目频道和操作方式，
而gd有线电视和dx，lt，ydIPTV是要收取用户月租费才可以收看央视卫视直播频道的。

**Comment by lizongying** [comment]
#893
