### ISSUE TITLE
缺少频道：山西卫视

### ISSUE THREAD

**Issue by eregg** [lizongying/my-tv#893]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

父母需要看山西卫视

**Comment by javadodobird** [comment]
由于前端没有山西卫视信号，

所以my-tv不会有山西卫视，

要看山西卫视就要用其它的apk去看。

**Comment by lizongying** [comment]
我的電視暫時停止更新，有相關需求可以嘗試下 [我的電視·〇](https://github.com/lizongying/my-tv-0)
