### ISSUE TITLE
 少了cctv6, 湖南台没用 

### ISSUE THREAD

**Issue by gitzyj** [lizongying/my-tv#894]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

 少了cctv6, 湖南台没用 

### 解决方案

增加cctv6 修复地方台播放错误

### 额外信息

无

**Comment by sobergou** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的功能请求。
> * [x]  这个建议不会背离 my-tv 的初衷。
> 
> ### 改进目的
> 少了cctv6, 湖南台没用
> 
> ### 解决方案
> 增加cctv6 修复地方台播放错误
> 
> ### 额外信息
> 无

2.1.8-9-release版本支持cctv6、湖南卫视

**Comment by exurie** [comment]
现在都挂了，好想已经停止维护了

**Comment by lizongying** [comment]
#893
