### ISSUE TITLE
[BUG] 江苏徐州，移动宽带。从1.98版本到2.18版本，都显示认证状态错误

### ISSUE THREAD

**Issue by Ytv1** [lizongying/my-tv#896]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

江苏徐州，移动宽带。从1.98版本到2.18版本，都显示认证状态错误

### 预期行为

请问是什么问题，怎么解决啊

### 实际行为

江苏徐州，移动宽带。从1.98版本到2.18版本，都显示认证状态错误

### 复现步骤

江苏徐州，移动宽带。从1.98版本到2.18版本，都显示认证状态错误

### UI / OS

海信 Vidda  电视

### Android 版本

9

**Comment by adsslmy** [comment]
我也是

**Comment by JefreeCN** [comment]
一样的问题

**Comment by 325622220** [comment]
山东联通也是

**Comment by sobergou** [comment]
> 一样的问题

作者已经不维护了，看 #895，可能会解决你的问题

**Comment by xinjing-cloud** [comment]
上海移动一样的问题，可能是停止使用了吧

**Comment by yaoxin1588** [comment]
电视上认证状态错误，但是手机上是可以正常播放的

**Comment by yzb5158** [comment]
闪退，根本打不开

**Comment by exurie** [comment]
全是认证错误

**Comment by hegan001** [comment]
接力维护my-tv项目，2.1.8-9-release版本支持cctv 3、6、8 
2.1.8-9-release，https://www.zeppos.tech/t/topic/2821/112?u=sober
注册进入西安华米论坛，可以下载my-tv最新版本。


gitee链接

https://gitee.com/sobergou/my-tv-apk

**Comment by ipodgoog** [comment]
手机Wi-Fi分享看。正常

**Comment by lizongying** [comment]
我的電視暫時停止更新，有相關需求可以嘗試下 [我的電視·〇](https://github.com/lizongying/my-tv-0)
