### ISSUE TITLE
快更新

### ISSUE THREAD

**Issue by 398907877** [lizongying/my-tv#897]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

快更新

### 预期行为

快更新

### 实际行为

快更新

### 复现步骤

快更新

### UI / OS

快更新

### Android 版本

快更新

**Comment by javadodobird** [comment]
> 快更新

由于前端频繁反制，
作者已经停止更新。

**Comment by ghjx** [comment]
> > 快更新
> 
> 由于前端频繁反制，
> 作者已经停止更新。

什么是前端反制？

**Comment by javadodobird** [comment]
> > > 快更新
> > 
> > 
> > 由于前端频繁反制，
> > 作者已经停止更新。
> 
> 什么是前端反制？

被大清广电局使用技术手段，
在前端信号源头频繁改变信号方式加密，
使得后端my-tv失效认证状态错误。

**Comment by hegan001** [comment]
接力维护my-tv项目，2.1.8-9-release版本支持cctv 3、6、8 
2.1.8-9-release，https://www.zeppos.tech/t/topic/2821/112?u=sober
注册进入西安华米论坛，可以下载my-tv最新版本。


gitee链接

https://gitee.com/sobergou/my-tv-apk

**Comment by sunnysu0608** [comment]
安卓5？？？？？？？？？？那沒意義

**Comment by lizongying** [comment]
我的電視暫時停止更新，有相關需求可以嘗試下 [我的電視·〇](https://github.com/lizongying/my-tv-0)

**Comment by sunnysu0608** [comment]
> 我的電視暫時停止更新，有相關需求可以嘗試下 [我的電視·〇](https://github.com/lizongying/my-tv-0)

能不能开发安卓4，好多家庭电视没办法升级
