### ISSUE TITLE
[BUG] 认证状态错误

### ISSUE THREAD

**Issue by nanfeng** [lizongying/my-tv#898]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

进入app后 黑屏
显示 “认证状态错误”

### 预期行为

正常播放

### 实际行为

黑屏

### 复现步骤

必现

### UI / OS

乐视X43S

### Android 版本

电视系统版本8.0

### 额外信息

用的是最新版
my-tv-v2.1.8.apk

**Comment by golango-cn** [comment]
![Screenshot_20240706_115757_com.lizongying.mytv.jpg](https://github.com/lizongying/my-tv/assets/10085466/d81e7f5f-6cb9-47d3-9c01-cfbb4d7dd605)

大部分频道有此问题

**Comment by zhihonwa** [comment]
刚刚在电视机上安装了，也是这个认证错误。

**Comment by ybjbox** [comment]
废了这个项目。作者没精力维护，还是自己找直播源吧

**Comment by qulihai** [comment]
是的，出现雷同现象，希望尽快解决。

**Comment by javadodobird** [comment]
> 用的是最新版 my-tv-v2.1.8.apk

由于my-tv apk前端频繁反制，
作者已经暂停修复my-tv apk。

**Comment by qrsky** [comment]
TCL电视 小米12spro同样问题

**Comment by lizongying** [comment]
#893
