### ISSUE TITLE
其实这个软件可以就弄个壳，又保持个性，又方便维护！

### ISSUE THREAD

**Issue by tcguangda** [lizongying/my-tv#907]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

用了一段时间mytv之后感觉界面不错，挺简洁，直爽，经常看到这个版本更新，很多是更新节目源，其实这个是很累，节目源大部分都是不断变化的，再多精力也不够，不如像其他的一些软件一样，可以自己加载节目源，这样最好了，保持软件的独特个性！又方便维护以及大家需求！

### 预期行为

!

### 实际行为

!

### UI / OS

android

### Android 版本

9,12

**Comment by zhascg** [comment]
这个已经不更新了吗？

**Comment by AppleMate60pro** [comment]
你是不看作者主页吗？人家作者不是有写了一个壳

**Comment by psumycom** [comment]
> 你是不看作者主页吗？人家作者不是有写了一个壳

那个你用了吗？

**Comment by AppleMate60pro** [comment]
@psumycom 在用，起码不会经常看不了，虽然没有my-tv体验好，旨在持续可用

**Comment by zhascg** [comment]
> @psumycom 在用，起码不会经常看不了，虽然没有my-tv体验好，旨在持续可用

隔壁有个壳DIYP，用了半个月了；还有个MYTV-ANDROID也不错。

**Comment by javadodobird** [comment]
> 用了一段时间mytv之后感觉界面不错，挺简洁，直爽



my-tv的「网格界面」是挺创新的，
挺方便看台选台的，
还能看到当前各个台在播什么节目，
还挺美观挺好看的。

**Comment by yes-github** [comment]
亲测可用：
https://github.com/yaoxieyoulei/mytv-android/releases

**Comment by zhascg** [comment]
@yes-github 悄咪咪的用，搞大了又没得看了。哈哈哈

**Comment by danshn** [comment]
> 亲测可用：
> https://github.com/yaoxieyoulei/mytv-android/releases

一样也是几个台可以看

**Comment by cyxnzb** [comment]
那同质化太严重了，能看直播的软件也挺多的，何必专注于这个呢，其实归根到底还是源的问题，有个好的源能做到秒开秒看就可以了

**Comment by iseku** [comment]
> > 亲测可用：
> > https://github.com/yaoxieyoulei/mytv-android/releases
> 
> 一样也是几个台可以看
自带的节目源大部分是ipv6的，不支持的话就只有少数v4的可以看

**Comment by sunnysu0608** [comment]
> > > 亲测可用：
> > > https://github.com/yaoxieyoulei/mytv-android/releases
> > 
> > 
> > 一样也是几个台可以看
> > 自带的节目源大部分是ipv6的，不支持的话就只有少数v4的可以看

弄一个v4v6双栈节点就可以

**Comment by andandroidor** [comment]
亲测可用 https://github.com/andandroidor/ourtv/releases

**Comment by thisharp** [comment]
> 亲测可用 https://github.com/andandroidor/ourtv/releases

感谢，真心感谢，维护源是一个辛苦的事。

**Comment by lizongying** [comment]
可以試試 [我的電視·〇](https://github.com/lizongying/my-tv-0)

**Comment by fifaplayer88** [comment]
> > 亲测可用 https://github.com/andandroidor/ourtv/releases
> 
> 感谢，真心感谢，维护源是一个辛苦的事。

w

> 亲测可用 https://github.com/andandroidor/ourtv/releases

问下兄弟这个OurTV还可以正常使用吗？我的电视机原本用这个软件一直都挺好用，刚刚昨天用了以后发现播放的时候一顿顿 比较卡，更新到最新版本也是这样，麻烦问下兄弟你那边的情况如何？ 是否有更好的直接软件推荐一下 感谢

**Comment by cyxnzb** [comment]
> > > 亲测可用 https://github.com/andandroidor/ourtv/releases
> > 
> > 
> > 感谢，真心感谢，维护源是一个辛苦的事。
> 
> w
> 
> > 亲测可用 https://github.com/andandroidor/ourtv/releases
> 
> 问下兄弟这个OurTV还可以正常使用吗？我的电视机原本用这个软件一直都挺好用，刚刚昨天用了以后发现播放的时候一顿顿 比较卡，更新到最新版本也是这样，麻烦问下兄弟你那边的情况如何？ 是否有更好的直接软件推荐一下 感谢

可以去http://www.wmsio.cn/ 下载自己想要的

**Comment by fifaplayer88** [comment]
> > > > 亲测可用 https://github.com/andandroidor/ourtv/releases
> > > 
> > > 
> > > 感谢，真心感谢，维护源是一个辛苦的事。
> > 
> > 
> > w
> > > 亲测可用 https://github.com/andandroidor/ourtv/releases
> > 
> > 
> > 问下兄弟这个OurTV还可以正常使用吗？我的电视机原本用这个软件一直都挺好用，刚刚昨天用了以后发现播放的时候一顿顿 比较卡，更新到最新版本也是这样，麻烦问下兄弟你那边的情况如何？ 是否有更好的直接软件推荐一下 感谢
> 
> 可以去http://www.wmsio.cn/ 下载自己想要的

感谢兄弟回复，另外问下兄弟这个网站哪个程序比较好用和稳定，主要用于看CCTV和卫视的直播电视
