### ISSUE TITLE
[FR] 列表太宽了遮挡界面

### ISSUE THREAD

**Issue by icowme** [lizongying/my-tv#912]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

建议这里可以自适应文字长度变窄
<img width="341" alt="微信图片_20240726113145" src="https://github.com/user-attachments/assets/89be5121-ab50-49b3-a164-d412fb0674a6">

**Comment by icowme** [comment]
![微信截图_20240726114029](https://github.com/user-attachments/assets/02440da7-8c25-4d55-bb07-70c3656576da)

**Comment by yxhy1010** [comment]
按一下右键，可以小点凑合用吧。
![1](https://github.com/user-attachments/assets/6300e361-2a23-426a-9616-839fd955124d)
