### ISSUE TITLE
我的电视还要不要做了。

### ISSUE THREAD

**Issue by zhangwc1030** [lizongying/my-tv#914]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 my-tv 的初衷。

### 改进目的

我的电视还要不要做了。几天就不能看了。我是已经放弃了。
建议使用电视大全，TVBox直播，电视家等。

**Comment by fangker** [comment]
嗐

**Comment by HiSoftrock** [comment]
今天试了，反正是打不开了。。。状态错误。。。这是要放弃了吗？

**Comment by taddyboy** [comment]
有人接着维护了，不过目前好似陷入困境，毕竟维护需要很多的精力和极高的专业水平

**Comment by javadodobird** [comment]
出名了，
被盯哨了，
而且源端换加密了，
已经做不了了。

**Comment by Azhe-c** [comment]
> ### 检查清单
> * [x]  之前没有人提交过类似或相同的功能请求。
> * [x]  这个建议不会背离 my-tv 的初衷。
> 
> ### 改进目的
> 我的电视还要不要做了。几天就不能看了。我是已经放弃了。 建议使用电视大全，TVBox直播，电视家等。
> 
> ### 解决方案
> _No response_
> 
> ### 额外信息
> _No response_

提到的那几个在哪下载啊？电视家不是第一个被封的吗

**Comment by oylm1234** [comment]
我用tvbox源稳定一年了

**Comment by Azhe-c** [comment]
> 我用tvbox源稳定一年了

哪个源呀，这边不支持ipv6，天v和小7都不太好用

**Comment by oylm1234** [comment]
> > 我用tvbox源稳定一年了
> 
> 哪个源呀，这边不支持ipv6，天v和小7都不太好用
yuechan ipv6的源

**Comment by lizongying** [comment]
#916
