### ISSUE TITLE
小米手机、电视、米家投影投影机青春版2，可以说整个米系都看不了，除了港澳台可以看，其他国内的频道都看不了，报状态错误，目前安装的是2.1.8最新版本。

### ISSUE THREAD

**Issue by dingshidingmaoshimao** [lizongying/my-tv#916]
小米手机、电视、米家投影投影机青春版2，可以说整个米系都看不了，除了港澳台可以看，其他国内的频道都看不了，报状态错误 。目前安装的是2.1.8最新版本。

**Comment by Yanwei0914** [comment]
我也是小米电视用不了

**Comment by majianheng** [comment]
我的TCL的也一样

**Comment by git123perry** [comment]
小米电视看不了：状态错误

**Comment by git123perry** [comment]
哪个版本可以在小米电视上使用的？

**Comment by javadodobird** [comment]
今年6月底的时候2.1.8就已经看不了了(除了3个凤凰卫视台之外)。

**Comment by gh19880625** [comment]
后期接受手的开发者，应为有人恶意攻击，停止发布公开版本了！

**Comment by nibazshab** [comment]
tcl 加一，什么都看不了

**Comment by Azhe-c** [comment]
> 后期接受手的开发者，应为有人恶意攻击，停止发布公开版本了！

这边会员版也不行了，不知道赞助的还能不能用

**Comment by lizongying** [comment]
目前我的電視已經看不了了，可以考慮 [我的電視·〇](https://github.com/lizongying/my-tv-0) 等軟件替代。
