### ISSUE TITLE
已赞赏，感谢开发出这么方便的软件，希望完善各省卫视、增加屏蔽电视台、增加节目时刻表和版本更新提醒功能

### ISSUE THREAD

**Issue by wqinf** [lizongying/my-tv#92]
已赞赏，感谢开发出这么方便的软件，找了很久，就这个最好用，希望增加：
1、各省卫视目前还有缺少，希望能够补全，比如陕西卫视、山西卫视、吉林卫视、新疆卫视等，以及以前经常看的金鹰卡通、炫动卡通、卡酷少儿、优漫卡通。
2、屏蔽电视台功能，因为某些电视台基本不会看，比如中央电视台外语频道等。
3、电视台节目时刻表，可以看该电视台当天都有什么节目。
4、版本更新提醒功能，如果不方便做一键更新的话，建议后续版本增加有新版本发布的提醒功能 ，比如每天第一次启动的时候弹一个提醒之类的。

最后，再次感谢！！！

**Comment by redscarful** [comment]
我也一直想问大佬怎么搞的，看了直播源才知道不是v4的源，是v6，怪不得这么快，不知都大佬怎么搞的把v6转的v4,能不能分享下

**Comment by ashsteins** [comment]
> 这app的直播切换速度非常快，是使用了什么秘诀吗？我使用过很多款类似的TVBOX的直播，切换速度都没有作者这款app速度快，如果能加入广东珠江台和大湾区卫视就更好了，这两个电视台老人必看，没办法，还是只能使用影视仓。后来我试图重新编译，看看能不能自己加入直播源，编译过程发现缺少"native.c" 文件，弄不了。。所以强烈建议作者增加自定义直播源的入口的，这样我就可以自己添加广东珠江台和大湾区卫视的直播源了。我知道很多tvbox的app可以自行添加直播源，但是我很想要你这款app的切换速度！！！其他的app没有这样的切换速度！！！非常感谢作者的辛苦奉献！

湾区卫视没找到高清的源，你是用的ipv6源么，求推荐

**Comment by lizongying** [comment]
#431
