### ISSUE TITLE
提示状态错误，不能使用

### ISSUE THREAD

**Issue by new985211** [lizongying/my-tv#920]
之前安装的时候是正常可以看的，现在点击打开提示状态错误，使用不了啦，是什么原因呀？

**Comment by werner-balonius** [comment]
+1

**Comment by jy123go** [comment]
+1

**Comment by WheelChen** [comment]
+1

**Comment by AppleMate60pro** [comment]
这个项目作者应该不更新了，建议看看别的

**Comment by SoonerMinde** [comment]
作者已停止对这个项目的更新

**Comment by ebaogogo** [comment]
1、目前这个MY-TV项目，作者已经不更新了，
2、作者新的项目和最新版本是在这里：https://github.com/lizongying/my-tv-0
3、也可以参考基于作者基础改良的一个版本：https://github.com/andandroidor/ourtv/releases

**Comment by lizongying** [comment]
#893
