### ISSUE TITLE
我宣布这个APP彻底挂了

### ISSUE THREAD

**Issue by jswcph** [lizongying/my-tv#921]
根本打不开了现在  也不更新了

**Comment by ebaogogo** [comment]
1、目前这个MY-TV项目，作者已经不更新了，
2、作者新的项目和最新版本是在这里：https://github.com/lizongying/my-tv-0
3、也可以参考基于作者基础改良的一个版本：https://github.com/andandroidor/ourtv/releases

**Comment by javadodobird** [comment]
> 根本打不开了现在 也不更新了

还有凤凰卫视3个台可以打开，用来看凤凰卫视。

**Comment by sosleakey** [comment]
1.3.7.13 家里移动宽带无法看 三个版本都试了  只有 手机使用移动网络 移动版本的可以看

**Comment by ebaogogo** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases
或者
https://github.com/andandroidor/ourtv/releases

这两个都是基于lizongying 之后再修改的版本，目前都可以看，你可以试试；

**Comment by lizongying** [comment]
#893
