### ISSUE TITLE
[BUG] 加载失败 java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no scheme was found for /stora...

### ISSUE THREAD

**Issue by Robertoyang-droid** [lizongying/my-tv#924]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

我在手机和电视上推送文件播放源，按照二维码的地址进行推送成功了，但是设置后，在加载播放源后，出现
加载失败
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https'
but no scheme was found for /stora...

### 预期行为

希望能有解决办法，多谢！

### 实际行为

推送不成功

### UI / OS

华为mate50

### Android 版本

鸿蒙14

### 额外信息

我还在一个电视盒试用，出现了同样的问题。海信电视推送播放文件成功

**Comment by lizongying** [comment]
請移步到 [我的電視·〇](https://github.com/lizongying/my-tv-0/issues)
