### ISSUE TITLE
建议频道竖排导航

### ISSUE THREAD

**Issue by StrollStars** [lizongying/my-tv#93]
感觉竖排的方式能够容下更多的频道，频道切换效率更高。
PS：可否实现嵌套频道，比如中央电视台二级有中央电视台相关的频道，目的也是为了提高切换效率。

**Comment by why0818** [comment]
+1

**Comment by aiddroid** [comment]
另外， 导航列表， 当前是哪个台，不是台明显，建议高亮

**Comment by zbby1987** [comment]
竖排无图模式+1
图片必要性不大
中央和地方，两个一级菜单。具体的台分到对应的二级菜单里

**Comment by fengjiuge1** [comment]
+1

**Comment by myvmiao** [comment]
我感觉横屏+图标挺好的，可以加个平铺模式，所有频道都平铺到屏幕上，直接选吗

**Comment by lizongying** [comment]
不排除，但目前非必要，暂不考虑。
