### ISSUE TITLE
APP提示状态错误

### ISSUE THREAD

**Issue by YuanZiFuShengRuoMeng** [lizongying/my-tv#932]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

APP提示状态错误，无法正常播放
![Screenshot_2024-12-02-13-13-44-389_com lizongying mytv](https://github.com/user-attachments/assets/efddfc59-43f8-4a55-b627-db0b1735f926)

### 预期行为

正常播放

### 实际行为

![Screenshot_2024-12-02-13-13-44-389_com lizongying mytv](https://github.com/user-attachments/assets/b7ddd75f-4453-46d5-9436-e4dc188690d8)

### 复现步骤

打开应用程序，便走这个提示。

### UI / OS

小米和PC模拟器

### Android 版本

14

**Comment by 743859910** [comment]
已经停更了

**Comment by dinjufen** [comment]
我也是，这个app没用了吗？

**Comment by 743859910** [comment]
> 我也是，这个app没用了吗？

停更快半年了

**Comment by kangzr** [comment]
有没有类似替代的软件吗

**Comment by lizongying** [comment]
[我的電視·〇](https://github.com/lizongying/my-tv-0)
