### ISSUE TITLE
[BUG] 切换频道过程可能会卡死；

### ISSUE THREAD

**Issue by ebaogogo** [lizongying/my-tv#933]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

版本：mytv-android-tv-2.2.6-all-sdk21-media3-1.4.0  
设备：华为智慧屏

状况：
1、正播放节目时候，当直接往上下切换频道比较快的时候，会容易出现卡死，需要重新退出再进去才可以继续播放；
2、如果先OK键，唤出菜单，然后再上下切换频道的时候，不容易出现以上情况；

### 预期行为

频道切换不应该引起卡死，应该是一个BUG

### 实际行为

正播放节目时候，比如播放CCTV-4，当直接往上下切换频道（切换到CCTV-3或CCTV-5）比较快的时候，会容易出现卡死，需要重新退出再进去才可以继续播放；

### UI / OS

华为智慧屏

### Android 版本

鸿蒙 2.0

**Comment by faintout** [comment]
同问题
