### ISSUE TITLE
大佬 请问是否考虑可自行添加源的功能？

### ISSUE THREAD

**Issue by 137943103** [lizongying/my-tv#94]
感谢大佬提供这么流畅的app，

由于各个地方台三四线县市台比较小众，没办法都内置到app里作为主流用户的需求，

所以能否增加自建频道呢？
方便各个用户的不同需求去自行diy添加源

**Comment by redscarful** [comment]
大佬的直播源我看了，是v6的，不是v4的,可能是做了转换

**Comment by lizongying** [comment]
后面可能新开项目，使用自定义源。
