### ISSUE TITLE
后续版本可不可以增加添加直播源地址的地方

### ISSUE THREAD

**Issue by redscarful** [lizongying/my-tv#96]
如果可以的自由添加直播源就可以了，还有个问题就是，你用的直播源是v6，是怎么做到换成v4的,因为在播放器放不了

**Comment by lizongying** [comment]
暂时不考虑加源，或者新开一个可以自由加源的项目

**Comment by Obizuh** [comment]
已经有好多自定义源的项目了，没必要再做这个功能了
