### ISSUE TITLE
感谢作者，目前换台最快，建议有显示清晰度分辨率的选项，目前cctv6有点糊。

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv#98]
如果需要些源参考的话，目前感觉 灵犀直播 用的源不错，台很全，建议作者参考。

**Comment by ashsteins** [comment]
如果作者担心有些源的版权问题，可以增加用户自定义导入m3u8功能，我就可以自己导点其他台进去

**Comment by 3504886962** [comment]
作者可以参考DIYP这个软件的自定义导入的功能吗，您这个软件换台贼快，DIYP完全比不了，要是能加一个自定义功能，或者发布一个不内置源的空壳版就更好了

**Comment by zbby1987** [comment]
> 如果作者担心有些源的版权问题，可以增加用户自定义导入m3u8功能，我就可以自己导点其他台进去

想找直播壳，就去微信公众号里搜派大星直播，目前更到1.0.6版了

**Comment by lizongying** [comment]
cctv6新版本已解决

**Comment by lingyust** [comment]
> 如果作者担心有些源的版权问题，可以增加用户自定义导入m3u8功能，我就可以自己导点其他台进去
直播源太杂了，网上找的，很快就失效了，自己抓源倒是没问题，可问题是，自己抓源了，那就没啥必要用这个软件了
