### ISSUE TITLE
大佬,建议可选择竖排横排导航选项

### ISSUE THREAD

**Issue by nel-x** [lizongying/my-tv#99]
大佬,非常感谢您的作品,让家里人看到了电视🤤
提几个使用上的建议:
1.可否有竖排横排的导航选项,很多人喜欢竖排, 竖排不需要图标,看电视一目了然,界面清爽友善

2.可否自主删减频道,特别是对于家里父母,频道太多,会有一定的难度

3.可否显示分辨率

4.可否自行添加接口或本地直播文件

5.现在的app图标似乎有点简陋,这个问题不大

希望大佬的作品越来越完善,感谢🙏

**Comment by zbby1987** [comment]
去掉图标，用文字竖排，确实省地方。
建议做一个竖排无图的开关！

**Comment by lizongying** [comment]
可以关注下这个新项目，会支持自定义源 #532
